### ISSUE TITLE
 Error: Server terminated early with status 127

### ISSUE THREAD

**Issue by Whuhxh** [wechaty/wechaty#102]
@zixia [@s1183.bx.sys.d /opt/www.d/wechat/src]# node kzge.js
INFO Wechaty v0.6.25 initializing...
WARN PuppetWebBrowserDriver valid() getSession() rejected: Server terminated early with status 127
(node:21896) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server terminated early with status 127

what's the problem to me? my node version is 6.9.1, npm version is 3.10.8 
package.json:
"dependencies": {
    "body-parser": "~1.8.1",
    "chromedriver": "^2.25.1",
    "cookie-parser": "~1.3.3",
    "debug": "~2.0.0",
    "ejs": "^2.5.2",
    "express": "~4.9.0",
    "mongodb": "^2.2.11",
    "mongoose": "^4.6.6",
    "morgan": "~1.3.0",
    "node-schedule": "^1.2.0",
    "qrcode-terminal": "^0.11.0",
    "seedrandom": "^2.4.2",
    "selenium-webdriver": "^3.0.0",
    "serve-favicon": "~2.1.3",
    "wechaty": "^0.6.22"
  }
could you tell what's wrong？

**Comment by zixia** [comment]
In order to help others find the problem out, you need to follow the ISSUE Template, answer all the question, and provide the steps to reproduce your problem.

I'll close this issue. Please re-submit a new issue to provide the information that needed.
