### ISSUE TITLE
[EVENT INVITATION] Welcome to join Beijing Node Party 18: Wechaty & ChatBot on 11th Dec.

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#107]
![nodeparty](https://cloud.githubusercontent.com/assets/1361891/20657650/7c14c972-b572-11e6-880c-6bddd6b3a5e3.jpg)

What is Node Party?
每月组织JavaScript/Node开发者聚会，关注热门的前端、后端框架，开发工具和方法。

* 学习新东西
* 认识新朋友
* 聚餐

我们会为你准备： 
咖啡，甜点，爆米花和动听的音乐，一起度过一个愉快的下午。
时间：12月11日 星期日 下午13:00 ～ 18:00
地点：科技寺创业空间(北新桥店)
地址: 东城区 东四北大街107号科林大厦B座107室(近北新桥地铁站)
报名地址：<http://www.bagevent.com/event/291037>
内容：

13:00 ~ 13:30 入场

**13:30 - 14:30 如何用6行JavaScript写出微信聊天机器人**
 
![zixia_lijiarui](https://cloud.githubusercontent.com/assets/1361891/20657673/a7193efa-b572-11e6-88f6-2894b2c04042.jpg)

- 李卓桓，李佳芮 - 
 
    李卓桓，PreAngel合伙人，zixia BBS、叽歪网创始人。曾任优酷网首席科学家，ChinaRen系统工程师，水木清华BBS站长。清华大学本科，中欧国际工商学院EMBA。15年互联网创业经验，20年编程经验。著有《Linux网络编程》(2000年)、《反垃圾邮件完全手册》(2006年)等技术作品。热爱极限运动，喜欢和勇敢、富有激情、愿意接受新鲜事物并不断挑战突破自己的人做朋友。生活中喜爱跑步、滑雪、SALSA、MMA、跑酷、滑翔伞等极限运动。

   李佳芮，桔子互动创始人/CEO，北京邮电大学计算机系硕士；2014年创立婚庆O2O平台“艾娘子”，同年获得500万天使投资；历任北京的邮电大学IDEA精英汇会长、学生会公关部副部长；曾获得第二届腾讯全国互联网创新创业大赛银奖、第三届京津冀营销创业大赛亚军。桔子互动是一家社区运营服务解决方案提供商，如基于微信的定制开发和运营推广服务。曾服务过亚马逊、腾讯、京东等多家上市公司。 爵士舞爱好者，业余时间创立舞蹈视频教学自媒体“舞哩”，搭建舞蹈社群。半年内原创视频全网播放近千万。多次被美拍、腾讯视频、B站、优酷评为热门精选。

演讲内容介绍

1.	Why Wechaty
2.	Wechaty from Scratch
3.	Why Browser
4.	Selenium WebDriver
5.	Wechat Browser Insight
6.	Why TypeScript
7.	Stacks
8.	DevOps
9.	What is Wechaty.IO
10.	Vision
11.	Demo
12.	Q/A

**15:00 - 16:00 Chatbot的场景化应用**
 
![ein](https://cloud.githubusercontent.com/assets/1361891/20657725/1e2cbbfc-b573-11e6-9434-6a7c9069e528.jpg)

- 王守崑 - 
   王守崑@Ein，个性化推荐系统和相关技术在中国的早期实践者。毕业于清华大学自动化系，豆瓣早期初创团队成员之一，曾长期担任豆瓣网首席科学家兼副总裁，负责豆瓣个性化推荐系统搭建。目前创业中，担任爱因互动（Ein）创始人、CEO，专注于自然语言处理和对话服务，向企业和个人用户提供专业、高质量的对话机器人产品。

演讲内容介绍
1.	Chatbot兴起的两大基础
2.	Chatbot历史、技术和现状
3.	Chatbot的适用场景
4.	展望

 16:20 - 17:20 Barcamp
 简单介绍，公司，工作，兴趣，擅长的技术栈

结束后
晚上有空的，在附近一起吃饭。

往期回顾
领袖硅谷 / Geek Lab / 科技寺 北新桥 / 36kr 氪空间 / 三里屯科技寺 / 渡鸦科技 / 零壹时光 / 世贸天阶 / Coffee Maker / 科技寺 三里屯 / NodeJS Live Beijing 2016 / 望京科技寺 ／ 三里屯科技寺
照片，PPT，Slides https://git.oschina.net/ubiware/node-party

主办
Rockq社区

![海报](https://cloud.githubusercontent.com/assets/1361891/20657707/ee4d8588-b572-11e6-84bb-1443d6d33f4b.jpg)

**Comment by JasLin** [comment]
woo! cool:)

**Comment by zixia** [comment]
Hi @JasLin , I'd like inviting you to join this event because you are the earliest adaptor of Wechaty. If you could come to Beijing, this event is a great opportunity for us to meet. :octocat:

**Comment by JasLin** [comment]
@zixia  hi,Brother, I'd love to go and meet you at the event, but I'm going to attend a two-week meditation in December. it's not a good time for me, but if you need, maybe I can provide you a story about using wechaty(usecase).

**Comment by zixia** [comment]
It's a pity that you can not join this event, maybe next time. 

And it will be awesome if you could share your use case! I would like to put it in my slides, looking forward for it. :)

**Comment by zixia** [comment]
https://blog.wechaty.io/event/2016/12/07/beijing-nodejs-meetup-party.html

**Comment by Samurais** [comment]
Nice Sharing.
![image](https://cloud.githubusercontent.com/assets/3538629/21167236/0236a7d0-c1e6-11e6-862a-df45798476cb.png)

More photos are available tomorrow.
