### ISSUE TITLE
Run Wechaty in Chrome Browser Directly Through Chatie Service.

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1153]
Today when I'm thinking about the Hostie service of Chatie, the following idea comes into my head:

```ts
import { PuppetHostie } from 'wechaty-puppet-hostie'
import { Wechaty } from 'wechaty'

const puppet = new PuppetHostie('hostie-token-secret')
const wechaty = Wechaty.instance({
  puppet,
})

wechaty.start()
```

Which the `HostiePuppet` class will accept a `token` in its constructor, and use this `token` to connect with the `api.chatie.io/v0/hostie/${token}` service.

Where can we get the `token` of the `Hostie`? We can make it on `app.chatie.io` in the future. (WIP)

The above code should be able to be compiled by WebPack and run right inside the browser. (and certainly, we can run it right inside plnkr.co / jsbin.com etc too)

Please let me know what you think if you are interested, thanks.

**Comment by padlocal** [comment]
@huan A little confused about how to integrate with puppet provider service. What is the token format should be? And  how to connect token with `api.chatie.io/v0/hostie/${token}` service in detail ? How the service can be auto discovered ?

**Comment by lijiarui** [comment]
I think the token format should be `puppet_padplocal_XXXX`

**Comment by huan** [comment]
@padlocal Hi, there is an valuable discussion about the puppet service token registering at https://github.com/wechaty/wechaty-puppet-hostie/issues/98 , there are many very valuable discussions about rock which is also useful for PadLocal.

The token format should follow the suggestion from @lijiarui .

You can register the token to our api so that the api can discover your service ip and port which has many discussion in the issue that I mentioned.

Please feel free to let me know if you have any questions, and I'm looking forward to seeing your token online soon!
