### ISSUE TITLE
New Puppet: Win32 Hook

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1191]
I know there's many developers are working on the 易语言 version of a Wechaty Hook based on a DLL injection solution.

Any discussion and contribution is welcome, please feel free to leave comments under this issue.

Thanks!

### See Also

* [关于对微信PC版Hook的一点研究分享 by @h4dex](https://blog.chatie.io/wechat-pc-impactor/)
* https://github.com/Chatie/wechaty/wiki/Puppet

**Comment by golezi** [comment]
Is there a plan for this?

**Comment by zixia** [comment]
It will not be very hard to implement a prototype for this puppet.

However, it is not in our priority right now. It will be very welcome if you want to contribute any.

Or please be patient and stay tuned.

**Comment by huan** [comment]
We have XP now: https://github.com/wechaty/wechaty-puppet-xp
