### ISSUE TITLE
请问可以获取联系人或群成员的性别、所属地域、头像吗？

### ISSUE THREAD

**Issue by wuhaoworld** [wechaty/wechaty#121]
看文档 Contact Class 中并没有提供性别和所属地域以及头像的支持，在 web 页面中可以获得用户的地域和性别属性，刚好一个小项目中需要用到，希望未来能支持，感谢！

**Comment by udbmnm** [comment]
@wuhaoworld 在web上有的就是可以获取的

**Comment by wuhaoworld** [comment]
@udbmnm 文档中并未提供相关 API

**Comment by zixia** [comment]
@wuhaoworld 

We are planing to add `Contact.sex()` & `Contact.province()` & `Contact.city()` in the future. Before that, you can use `Contact.get('sex')` & `Contact.get('province')` & `Contact.get('city')` to get them.

For more details about the user contact information which is not exposed by API, you can try to `console.log(contact.obj)` & `console.log(contact.rawObj)`, and any new API suggestion is welcome.

The harder part is to get the contact avatar. I do not know if you could get the avatar picture by URL directly, as the server might check the cookies. Please let me know if the url works for you, if not, I can add a new method to Contact for you, to get the avatar file.

Thanks.

**Comment by wuhaoworld** [comment]
@zixia thank you very much. 获取头像时，微信确实会检查 Cookie，未登录状态下头像地址无效。
API 可以设计成下载头像文件到指定目录，这个需求倒是比较小众了。

性别接口建议使用 gender 这个词。

**Comment by zixia** [comment]
Ok. 

And how do you think about the `province()` and `city()` method name? I'm wondering if we should combine them to one method?

**Comment by zixia** [comment]
@wuhaoworld 

Some new methods that you required just added. 

Could you please test them and let me know if they work as expected?

Thanks.

```diff
+  /**
+   * Contact gender
+   * @return Gender.Male(2) | Gender.Femail(1) | Gender.Unknown(0)
+   */
+  public gender()   { return this.obj ? this.obj.sex : Gender.Unknown }
+  public province() { return this.obj && this.obj.province }
+  public city()     { return this.obj && this.obj.city }
+
+  /**
+   * Get avatar picture file stream
+   */
+  public async avatar(): Promise<NodeJS.ReadableStream> {
```

**Comment by nolanlee** [comment]
@zixia 
`gender()`, `province()`, `city()` 可以正常工作, 但是我在执行 `avatar()` 的时候失败了，异常如下：

```
WARN Contact avatar() exception: Error: protocol unknown: null
    at Function.urlStream (/xxx/node_modules/wechaty/dist/src/util-lib.js:94:19)
    at Contact.<anonymous> (/xxx/node_modules/wechaty/dist/src/contact.js:90:43)
    at next (native)
    at fulfilled (/xxx/node_modules/wechaty/dist/src/contact.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:25907) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: protocol unknown: null
```
我在调试的时候发现 `rawObj.HeadImgUrl` 是一个 `pathname` (形如: `/cgi-bin/mmwebwx-bin/webwxgeticon?seq=xxx&username=xxx&skey=xxx`), 并没有 `protocol` 和 `host`，这样导致 `const protocol = u.protocol` 赋值后  `protocol`为 `null`

**Comment by zixia** [comment]
@nolanlee Thanks for your great feed back, then we have to add a new method like `serverHost()` to get the current wechat web server name, like `wx.qq.com` or `wx2.qq.com`/`wx8.qq.com`, and add it to the url.

I'll check it later.

**Comment by zixia** [comment]
@nolanlee `avatar()` should work now, I test it without any problem.

Please let me know if it works for you. Thanks.

**Comment by nolanlee** [comment]
@zixia `avatar()` 可以正常工作，棒🖐

**Comment by zixia** [comment]
@nolanlee Great! :+1:

**Comment by LuKing4DB** [comment]
现在又获取不到头像了，相关的项目也是如此
