### ISSUE TITLE
ERR Message ready() exception: Error: Contact.load(): id not found

### ISSUE THREAD

**Issue by Samurais** [wechaty/wechaty#123]
# Description
Get the latest codes, https://github.com/wechaty/wechaty/commit/eb8d79fac64ac46c6709dace79e388756d8ba170.

```
cd wechaty
npm install
npm start
```

### Expected behavior
No error messages.

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/3538629/20996810/4df63618-bd3b-11e6-8f28-67c497a7917b.png)

[Log trace](https://gist.github.com/Samurais/2387cb25965617f55bd33ebe46e2466c)

But the app is launched and service well. The incoming message is printed, not sure if the message has further impact.

### Environment
OS: macOS Sierra
NodeJS: 6.9.1

**Comment by Samurais** [comment]
# Id is undefined at this point

```
ERR Message ready() exception: Error: Contact.load(): id not found
    at Function.load (/Users/hain/ai/wechaty/src/contact.ts:337:13)
    at Message.<anonymous> (/Users/hain/ai/wechaty/src/message.ts:415:29)
    at next (native)
    at /Users/hain/ai/wechaty/dist/src/message.js:7:65
    at __awaiter (/Users/hain/ai/wechaty/dist/src/message.js:3:12)
    at Message.ready (/Users/hain/ai/wechaty/dist/src/message.js:195:16)
    at PuppetWeb.<anonymous> (/Users/hain/ai/wechaty/src/puppet-web/event.ts:295:13)
    at next (native)
    at /Users/hain/ai/wechaty/dist/src/puppet-web/event.js:7:65
```

But I can not reproduce this error.

**Comment by zixia** [comment]
I had seen this bug now and then. will check it later.

**Comment by zixia** [comment]
@Samurais this exception is caused by calling `this.say()` before bot login. fixed.
