### ISSUE TITLE
send message to filehelper

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#13]
bot send message to filehelper for more test

**Comment by zixia** [comment]
it's quite easy to do this as the following example code:

```javascript
const m = new Message()

m.set('to', 'filehelper')
m.set('content', 'hello helper')

wechaty.send(m)
```

**Comment by lijiarui** [comment]
cool ！
thank you！

**Comment by zixia** [comment]
now it's recommend to use `wechaty.say(content)` to send `content` to `filehelper` for a shortcut.
