### ISSUE TITLE
`tsc` compiling error: Cannot find namespace 'webdriver'

### ISSUE THREAD

**Issue by imWildCat** [wechaty/wechaty#136]
Hello zixia,

I was trying to use `wechaty` in TypeScript. While compiling, there were errors:
```bash
node_modules/wechaty/dist/src/puppet-web/browser-driver.d.ts(18,13): error TS2503: Cannot find namespace 'webdriver'.
node_modules/wechaty/dist/src/puppet-web/server.d.ts(2,1): error TS2688: Cannot find type definition file for 'socket.io'
.
node_modules/wechaty/dist/src/puppet-web/server.d.ts(11,19): error TS2503: Cannot find namespace 'SocketIO'.
node_modules/wechaty/dist/src/puppet-web/server.d.ts(12,19): error TS2503: Cannot find namespace 'SocketIO'.
node_modules/wechaty/dist/src/puppet-web/server.d.ts(27,39): error TS2503: Cannot find namespace 'SocketIO'.
```

Only by adding these typings dependencies in my project (`yarn add -D  yarn add @types/selenium-webdriver @types/socket.io`) can solve this problem. **Is there any better way?** I do not tend to add these dependencies in the `package.json` of my project.

**Comment by zixia** [comment]
I just move them from devDependence to dependence, they should be installed by wechaty by default now. I guess this could help you to solve this issue. 

Please let me if it works.

**Comment by imWildCat** [comment]
@zixia Problem solved. Many thanks for your work! Good night!

**Comment by imWildCat** [comment]
By the way, could you please publish the latest version to `npm`? Because the latest version installed directly from Github doesn't contain the `dist` directory.

**Comment by zixia** [comment]
It's already published, Wechaty uses CI/CD to publish NPM. :)

Run `npm install wechaty@next` you will get the latest Wechaty :)

**Comment by chenzhutian** [comment]
this bug happens again in v0.8.107

**Comment by zixia** [comment]
@chenzhutian Could you post a code snip that could reproduce your problem?

**Comment by chenzhutian** [comment]
@zixia 
This is for reproduction: https://github.com/chenzhutian/wechaty-tsc-warning
My OS is win 10 and node version is `6.10.3`. Typescript version is `2.3.4`. Wechaty version is `0.8.107`. 
After cloning this repo, please run `npm install && npm run build`.
Actually this is a bug related to type definition files. 

Some logs:
```
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(2,1): error TS2688: Cannot find type definition file for 'socket.io'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(3,1): error TS2688: Cannot find type definition file for 'express'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(4,24): error TS2307: Cannot find module 'https'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(6,30): error TS2307: Cannot find module 'events'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(11,19): error TS2503: Cannot find namespace 'SocketIO'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(12,19): error TS2503: Cannot find namespace 'SocketIO'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet-web/server.d.ts(27,39): error TS2503: Cannot find namespace 'SocketIO'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/puppet.d.ts(20,30): error TS2307: Cannot find module 'events'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/room.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/room.d.ts(20,30): error TS2307: Cannot find module 'events'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/util-lib.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/util-lib.d.ts(21,61): error TS2503: Cannot find namespace 'NodeJS'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/util-lib.d.ts(35,24): error TS2304: Cannot find name 'Buffer'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/wechaty.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/_wechaty@0.8.107@wechaty/dist/src/wechaty.d.ts(20,30): error TS2307: Cannot find module 'events'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wechaty-tsc-bug@1.0.0 build: `tsc -p .`
npm ERR! Exit status 2
```

**Comment by zixia** [comment]
Thanks for your reproduce repo, it's very clear and straight forward.

After studied from your repo, I figured out that it's not a Wechaty bug, it's because you did not configure the @types.

To run `npm run build`, you need to install all the typings files needed as the following:

```shell
$ npm i @types/node @types/express @types/socket.io
```

At last, this is a good question and I believe it should put into the FAQ in Wiki.

Would you like to add a new Q/A entry in [FAQ](https://github.com/Chatie/wechaty/wiki/FAQ) about this? I will appreciate if you would like to.

Thanks!

**Comment by chenzhutian** [comment]
Thank you very much! 
I also support to put those dependencies into package.json.

**Comment by zixia** [comment]
@chenzhutian It should work for you on Wechaty version 0.8.110 or above.

**Comment by chenzhutian** [comment]
yes it works. Thanks very much
