### ISSUE TITLE
保存头像为空

### ISSUE THREAD

**Issue by jerryge** [wechaty/wechaty#138]
m.from().avatar().then(stream => {
			console.log(stream)
            stream.pipe(fileStream)
            .on('close', () => {
            	console.log('finish readyStream()')
            })
        })
        .catch(e => console.log('stream error:' + e))

保存头像时，文件为空。'content-type': 'text/html; charset=gbk', 不是Content-Type:image/jpeg。Status Code = 200，似乎是cookie问题。

**Comment by zixia** [comment]
Duplicate with #121 

The code should work ok, please see my last commit, with `example/contact-bot.ts` can demo you how to save avatar to file.
