### ISSUE TITLE
[Feature Request] Add friend(Contact) to a group(Room)

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#14]
after agree friend request, i hope wechaty can add this friend to a certain group

thank you

**Comment by zixia** [comment]
This interface is not implement yet.

however, it should look like this:

```javascript
const friend = message.get('from')
const room = Room.find('Group Name')
if (room) {
  room.add(friend)
}
```

**Comment by zixia** [comment]
close this issue for splited to #32 #33 #34
