### ISSUE TITLE
how to use padchat in docker(win32) ?

### ISSUE THREAD

**Issue by Zhou-Bill** [wechaty/wechaty#1480]
i have install [WECHATY-GETTING-STARTED](https://github.com/Chatie/wechaty-getting-started), and just do `docker run -t -i  -e WECHATY_PUPPET="padchat" -e WECHATY_PUPPET_PADCHAT_TOKEN="${MYTOKEN}"  --volume="E:\project\wechaty-getting-started":/bot --name=wechaty zixia/wechaty:latest examples/contact-bot.js`, it something error by IO, it can't create a profile.memory.json

**Comment by Zhou-Bill** [comment]
![image](https://user-images.githubusercontent.com/13554001/42720944-e169e6da-8763-11e8-94ce-4d702a5eb7bb.png)

**Comment by zixia** [comment]
It seems that you might run into https://github.com/Chatie/wechaty/issues/66#issuecomment-374086724

Please check your SELinux settings first, and feel free to let me know the result.

**Comment by Zhou-Bill** [comment]
but i am using in windows !

**Comment by zixia** [comment]
Could you please post your log message as plain text so that we can analyze it easier?

We are not using Windows but it should work.

Do you know is there a Max length limitation of the file name in Windows?

**Comment by zixia** [comment]
> Correct for NTFS, not correct for Windows, according to the link you provided: "In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters". The total path is, for all practical purposes, limited to 259 characters (allowing for the null-terminator). – Lawrence Dol Mar 14 '12 at 6:49

See https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista#comment12323381_265782

What's your file system, and what's the length of your total file payee name?

**Comment by Zhou-Bill** [comment]
NTFS,  and the path is "E:\project\wechaty-getting-started", the string length is 32 ,is too shorter than 259

**Comment by zixia** [comment]
Seems related with:

* https://github.com/Level/levelup/issues/222
* https://github.com/google/leveldb/issues/281

But I have no idea what's wrong with your environment.

I'd like to suggest you ask in the Wechaty Developers' Home Wechat Room, hope there's someone who is using Wechaty under Windows can share some success experiences for you.

**Comment by Zhou-Bill** [comment]
This seems to be a mistake in leveldb when windows shares files in docker.

**Comment by zixia** [comment]
Could you please try the latest wechaty@0.20 to see if it will fix your problem?

v0.20 had switch the storage backend from `nosql-leveldb` to `level-down`, so it might be difference.
