### ISSUE TITLE
Will you implement the function of Extracting the Contact Card from the Message for PuppetPadchat

### ISSUE THREAD

**Issue by biching** [wechaty/wechaty#1499]
According to the code below, the function that Extract the Contact Card from the Message is to be implemented. I deeply need that in my project. Do you have a plan to implement that in project of the PuppetPadchat ?
https://github.com/Chatie/wechaty/blob/0c941388e29910890ab1c3d619faa0ab7c59ca48/src/user/message.ts#L811-L823

**Comment by iching-long** [comment]
Or could you show me a temp way for alternative?

**Comment by lijiarui** [comment]
Yes, this function is for padchat. 

Have you tried padchat yet? Can the function now satisfy you or you find some bug?

**Comment by iching-long** [comment]
I have used padchat， but can't find the way to use this function.  It seems to be implemented anyway else. Could you tell me how to use it with the padchat?

**Comment by lijiarui** [comment]
Yes, we need to implement this but do not have time these days, pr is welcome ：）

**Comment by iching-long** [comment]
I have checked the toString function of message with share card, which has  enough information for creating a new contact. I still can't find a way to do it. I am a newbie for JS, but I will dig it.

**Comment by lijiarui** [comment]
If you can get contact id in `toString()`, then you can try 
```ts
const contact = Contact.load(id)
```
see more in [Contact.id](https://qhduan.github.io/wechaty-doc/#/api/contact) and [Contact.load(id)](https://qhduan.github.io/wechaty-doc/#/api/contact?id=contactload)

**Comment by zixia** [comment]
@lijiarui I got a `404 File not found` error when visiting your links.

**Comment by lijiarui** [comment]
@zixia sorry, this is because we just move https://github.com/qhduan/wechaty-doc to https://github.com/botorange/wechaty-doc 

And I change the link then.
