### ISSUE TITLE
Get "userAvatar" data when bot onScan

### ISSUE THREAD

**Issue by wuying8** [wechaty/wechaty#1508]
![image](https://user-images.githubusercontent.com/16256704/43308172-3b15a77e-91b3-11e8-8ad8-b75bc8d390f4.png)
Whether the bot can get back the userAvatar when scanning the QR？I think that UE will be better

**Comment by lijiarui** [comment]
You can add code to get userAvatar when user login as following code show. But framework won't support this. see more in the [doc](https://botorange.github.io/wechaty-doc/#/api/contact?id=contactavatar)

```ts
bot.
on('login', user => {
   console.log(user.avatar())
})
```
