### ISSUE TITLE
How can I send emotion instead of picture?

### ISSUE THREAD

**Issue by Flyphy** [wechaty/wechaty#1513]
Emotion is a important form of communication in wechat, but I can't find sending emotion API.

**Comment by lijiarui** [comment]
This function hasn't been implemented yet, pr is welcome :)

Btw, some emotion has the code, maybe will easy to use.

**Comment by Flyphy** [comment]
我指的是发送表情包（用户收到的消息类型是：MessageType.Emoticon），用户可直接长按保存至自定义表情中。

> Btw, some emotion has the code, maybe will easy to use.
这里说的是 emoji ？

**Comment by lijiarui** [comment]
Both emoji and Emotion hasn't been implemented yet.

But we would like to enhance this in the future. If you would like to join, maybe this will be faster.

**Comment by lijiarui** [comment]
You can keep track here: https://github.com/lijiarui/wechaty-puppet-padchat/issues/101

**Comment by zixia** [comment]
@lijiarui They are different problems.

This issue is for sending emotion, and the other is receiving files.

**Comment by wj-Mcat** [comment]
It's 2020 year now, can wechaty send emotion?

**Comment by huan** [comment]
I hope we can support sending emotion in 2020.

PR will be very welcome!

**Comment by w2227669390** [comment]
> 你好，@Flyphy！我是 Dosu，我正在帮助微信团队管理他们的积压订单。我想让您知道我们已将此问题标记为过时。
> 
> 据我了解，您是在寻求如何在微信中发送情感而不是图片的指导。lijiarui提到该功能尚未实现，并建议您可以通过提交拉取请求来做出贡献。你澄清说你想发送表情符号，李嘉瑞确认表情符号和情感都还没有实现，但他们计划在未来加强这一点。wj-Mcat还询问2020年微信是否可以发送情感，huan表示希望2020年得到支持，并欢迎pull requests。
> 
> 如果该问题与最新版本的wechaty仓库仍然相关，请通过评论该问题告知我们。否则，请自行关闭问题，否则该问题将在 7 天后自动关闭。
> 
> 感谢您对微信社区的理解和贡献！

您解决这个问题了吗
