### ISSUE TITLE
new contact information not sync after contact being add via friendship event

### ISSUE THREAD

**Issue by kis87988** [wechaty/wechaty#1521]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
U.S.
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
own machine

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
docker run in container

### Expected behavior
```typescript
bot.on('friendship', async friendship =>
{
    let logMsg
    try
    {
        logMsg = 'received `friend` event from ' + friendship.contact().name()
        console.log(logMsg)
        switch (friendship.type())
        {
            case Friendship.Type.Receive:
                logMsg = 'accepted automatically'
                await delay(10000)
                await friendship.accept()      
                break
            case Friendship.Type.Confirm:
                logMsg = 'friend ship confirmed with ' + friendship.contact().name()
                await delay(10000)
                await friendship.contact().sync()
                let fs = await friendship.contact().friend()
                console.log(fs) //////////////// false, but it should be true
                break
        }
    } catch (e)
    {
      logMsg = e.message
    }
    console.log(logMsg)
})
```
### Actual behavior
console.log(fs) / return false, but it should be true

### Steps to reproduce the behavior (and fixes, if any)
After friend being add wechaty should refrash contact cache and change the friendship between with bot and new_contact (means new contact cache should fetch again because all information change after add new friend).

this may be same issue as #1517 

### Full Output Logs
None available for this time
```shell
$ docker create -t -i --name=$docker_name \
--mount type=bind,source="${dir}",target=/bot \
-e WECHATY_LOG=silly \
-e TZ="America/Los_Angeles" \
zixia/wechaty:latest mybot.ts
$ docker start -a $docker_name 
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment]
Good catch!

And it would be terrific if you can fix this problem by sending a PR, would you like to do that?

**Comment by kis87988** [comment]
I would try:)

**Comment by zixia** [comment]
@kis87988 Did you get any progress about the PR to fix this issue? 

Would love to hear back from you!

**Comment by kis87988** [comment]
@zixia 
Not really, no luck. 
I tried to do sync() in the accept() function, but that doesn't work 😢

**Comment by zixia** [comment]
Do you think we have to set the `contact.payload.friend = true` directly for a workaround?
