### ISSUE TITLE
[feature request] fire `room-join` when someone joins from a QR Code

### ISSUE THREAD

**Issue by dcsan** [wechaty/wechaty#155]
I was trying to create a welcome message when someone joins from scanning a QR Code but I don't think that [room-join](https://github.com/wechaty/wechaty/wiki/API#7-event-room-join) event is fired.

Instead all I see is the message (in english mode)

```
$username joined the group chat via the QR Code shared by $invitee
```

So I think the current API only works if you use [+] to add someone to a room.

It would be nice to have a common interface for dealing with room-join events but perhaps an extra param for `source=invite|qrcode` ?

Perhaps the event does get sent the *first time* someone joins a room. I am quitting and re-joining the group and have run out of devices to test, so not 100% sure...

**Comment by zixia** [comment]
Yes, the join event is fired by matching the join message.

Could you please help me to post both English and Chinese version of that string? So I could write unite test for it. :)

**Comment by dcsan** [comment]
haha, I was just adding a TODO that I need the Chinese versions too :)

I was writing my own kind of test harness to add to these messages since I didn't have time to dive into the Wechaty test suite yet. I'll share that repo with you as it has the basic tests and messages.

**Comment by zixia** [comment]
Great! :)

Also have a look at  https://github.com/wechaty/wechaty/blob/master/src/puppet-web/firer.spec.ts , I'll add to this file

**Comment by dcsan** [comment]
I made a gist here with some basic regex tests for the english messages
https://gist.github.com/dcsan/6975c84389ceac19d6677389d910506d.js

also in this repo (shared with you)
https://github.com/dcsan/ta-bot/blob/master/kbot/test/JoinRoomRegex-test.ts

I could try and merge this into Wechaty's own test suite next week sometime but I'm not sure where the other regex matches are
https://github.com/wechaty/wechaty/blob/master/test/room.spec.ts


Another thing to note is that WeChat added the "restricted rooms" recently, so they may have other messages. It seems so fragile to build this on top of regex messages rather than some type of data structures... it won't work in other languages for a start.

**Comment by dcsan** [comment]
actually I made a much simpler check now to just get the person who Joined the room not the invitee. So the checks are a lot simpler

```
  regexCheckJoinMessage: (input) => {
    let checks = [
      { regex: /.* invited "(.*)" to .*/i },  // You've | $inviter
      { regex: /.* invited (.*) to .*/i },  // without quotes
      { regex: /"(.*)" joined the group chat .*/i },
      //// dont need these
      // { regex: /"(.*)" joined the group chat via the QR Code shared by "(.*)"/i },
      // { regex: /"(.*)" joined the group chat via your .*/i }
    ]
    let match
    for (let elem of checks) {
      match = input.match(elem.regex)
      if (match) {
        // debug('found join match', match)
        break
      } else {
        // debug("NO match\n", input, "\n", elem.regex)
      }
    }
    return match
  },
```

checking against these messages

```
let msgs = [
  '"$invitee😀" joined the group chat via the QR Code shared by "$invitee😀"',
  '"😀inviter" invited "$invitee😀" to the group chat',
  '"😀inviter" invited "$invitee😀, $invitee2, $invitee3" to the group chat',
  'You\'ve invited "$invitee😀" to the group chat  Revoke',
  'You\'ve invited "Quoted name, Person name two" to join the group chat',
  'You\'ve invited Person Name one, Person name two to join the group chat',
]
```

**Comment by lijiarui** [comment]
Chinese version of QR info String：

`"$invitee"通过扫描"$inviter"分享的二维码加入群聊`

**Comment by zixia** [comment]
Support to fire `room-join` when someone joins from a QR Code is not hard to do, so I'd like to leave this issue for _Welcome Pull Request_ for a week. :)

**Comment by dcsan** [comment]
with version 7.5 which includes @lijiarui pull request I don't get a room join event fired...

#### Wechaty Doctor

1. Wechaty version: #git[df619ab Merge pull request #177 from wechaty/greenkeeper/@types/sinon-1.16.34]
2. Darwin x64 version 16.3.0 memory 160/8192 MB
3. Docker: false
4. Node version: v6.9.1



```
  bot:Kbot RECV: "DC-helper" joined the group chat via your shared QR Code. +21s
[TestBotGroup]<TestBotGroup>:{SYS}"DC-helper" joined the group chat via your shared QR Code.
  bot:Kbot roomName TestBotGroup +2ms
  bot:KBrain getItemData - no item for "dc-helper" joined the group chat via your shared qr code. +1ms
  bot:KBrain lookup TestBotGroup "DC-helper" joined the group chat via your shared QR Code. +0ms
  bot:KBrain examples TestBotGroup "DC-helper" joined the group chat via your shared QR Code. +0ms
check.res= undefined

```

**Comment by dcsan** [comment]
also noting the messages are all a bit different

> "DC-helper" joined the group chat via your shared QR Code.

the joining person themselves sees:
> You've joined the group chat via QR Code. Group chat members: (list of names)

others who did NOT send the QR code would see another message
>  "$invitee😀" joined the group chat via the QR Code shared by "$invitee😀"

**Comment by lijiarui** [comment]
@dcsan  it seems you are not running the correct version...   

@zixia didn't merge my pr, so maybe you should clone the [repo](https://github.com/lijiarui/wechaty) I forked to check whether it works...

**Comment by dcsan** [comment]
(oops I thought I saw some release notes for a 7.5 version that had already had this merged in)

OK great I confirmed this works using your fork @lijiarui 
tested with users from a QR code and from a direct [+] add

Thanks!

**Comment by zixia** [comment]
PR merged. Please let me know if there's any other problem with this issue.

Thank @dcsan @lijiarui for the contribution!
