### ISSUE TITLE
ContactType of ‘微信团队’ and ‘腾讯新闻’  are not consistent between puppet padchat & puppeteer

### ISSUE THREAD

**Issue by xwxtwd** [wechaty/wechaty#1551]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China) chaina
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using? Qcloud

when  ‘微信团队’ or ‘腾讯新闻’ sent message to me
message.form().type() is Contact.Type.Personal 
and 
message.form().friend() is true

so.  I can't distinguish between my friend or any special.

**Comment by zixia** [comment]
Which puppet did you use?
What's version did you use?

Please follow our issue template, thanks.

**Comment by TbhT** [comment]
try   `message.from().contact() === '微信团队' ` to diff

**Comment by zixia** [comment]
It is like that the `微信团队 ` and `腾讯新闻` is not the Official Account.

In the web API, there's another kind of contact named _Special_.

Maybe we should consider adding a third type of the Contact? I'm not sure.

Before we can fix it, it seems that the suggestion from @TbhT is a good workaround.

**Comment by xwxtwd** [comment]
ok👌，i get it（now Wechaty  v0.18.5 && padchat）

ps. a few months ago, i use Contact.special() whit wechatyV0.13.57

**Comment by zixia** [comment]
@xwxtwd Thanks for reporting that, good catch!

It should be consistent among all puppet implementations, will look into it later.
