### ISSUE TITLE
[feature] check nodejs version

### ISSUE THREAD

**Issue by kis87988** [wechaty/wechaty#1584]
Since Wechaty require node v10 or above, but on the nodejs.org the LTS version is node v8.
Therefore, Wechaty may need to support check node version.
If the node version is not v10, should come out ERR warning.

**Comment by zixia** [comment]
We have two options:

1. Wait the node v10 become LTS this Oct, or
1. Add a `postinstall` script to do that.

Which one do you prefer?

**Comment by kis87988** [comment]
@zixia I think we should still check version in ```postinstall`` script because node version may be different in the future such as node v11 come out or so on
