### ISSUE TITLE
Feature request: room/contact say delay time by character count 

### ISSUE THREAD

**Issue by kis87988** [wechaty/wechaty#1608]
purpose: 
Since bot should similar more to human. 
I think room.say(content,mention) or any contact.say(content) should delay say to send out some message?
it should be count the ```content length * 0.5 + some random int (1~5s)```
However, if the message is ```more than certain length(maybe length > 50), we can consider that is forward message. Then, we can do no delay.```

idea 1: add one Boolean optional parameter with delay or not, default is not, and use the formula above to calculate. 
idea 2:add one Number optional parameter with delay ms, default is 0 (more flexible)
idea 3: no add parameter, just do above calculation to delay.

Feel free to discuses this because just my personal opinions

**Comment by zixia** [comment]
This is a good direction that we should follow, and there's a discussion based on this topic at wiki: <https://github.com/Chatie/wechaty/wiki/Throttled-Rate-for-WeChat-Web-API>

However, instead to add this feature to `say()`, it should be better to add another layer to control this kind of delay for a better design and be easy to use.

Not only the `say()` should be throttled, but also all the write operation like `add()`, `accept()` that all should follow this rule.
