### ISSUE TITLE
How to use it without opening a chrome window?

### ISSUE THREAD

**Issue by wuhaoworld** [wechaty/wechaty#163]
I want to develop a client with Electron, and want to show the QR image in the Electron window, how to do it without opening a chrome window?

thanks!

**Comment by zixia** [comment]
@wuhaoworld  To develop a client with electron is a awesome idea!

Unfortunately, we can not hide chrome window easy with electron, you need to consider using the phantomjs head.

The good news is we can hide the window by using phantomjs, you need to set `WECHATY_HEAD=phantomjs` environment variable before start Wechaty.

However the bad news is phantomjs head is not work as stable as chrome, sometimes it even not work as expected. More details you can have a look at #60.

Please feel free to have a try with phantomjs, and let me know it works for you.

**Comment by wuhaoworld** [comment]
thank you very much

**Comment by zixia** [comment]
@wuhaoworld How about the phantomjs, did you make it?

**Comment by udbmnm** [comment]
How about the [spectron]( https://electron.atom.io/spectron/)?

**Comment by zixia** [comment]
@udbmnm I believe the Spectron is an alternate to the WebDriver solution.

However I think it is not related to this topic, please feel free to submit a new Issue to discuss about it.
