### ISSUE TITLE
Room.find() and Room.findAll() are always returning error

### ISSUE THREAD

**Issue by k5dash** [wechaty/wechaty#1635]
Hi, Huan:

I noticed this afternoon, Room.find() and Room.findAll() are returning
```01:05:13 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???```
now. 

I checked even the most simple case `const rooms = bot.Room.findAll()` wouldn't work
I bet there is some change on Tencent API, can you take a look?

Thanks
-Alfred

**Comment by zixia** [comment]
We have a tracker for monitor Tencent changes at <https://github.com/Chatie/webwx-app-tracker/commits/master>

Please let me know if you can find anything.
