### ISSUE TITLE
[Discussion] Possibility of macOS wechat.app API/puppet?

### ISSUE THREAD

**Issue by sk9c00** [wechaty/wechaty#1645]
I'm not sure if this is the right place or if this issue has been brought up before so please forgive me if this is the case.

From my current understanding, unless you have an older WeChat account from before a certain set date, are willing to pay for an orange token (currently around couple hundred RMB a month), willing to get a dedicated iOS jailbreak device (for the pre-alpha stage ioscat), it is very hard to setup a wechaty bot especially for amateurs or freelancers.

This is in particular very frustrating not to mention how a SMS capable phone number is basically now mandatory for the creation of a personal WeChat account.
`<error><ret>1203</ret><message>For account security, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com</message></error>`

**So, I'm curious if it is possible and/or is there anyone that could slightly assist me if they do not want to do it themselves, to create a puppet based off the actual WeChat app for preferably macOS for now or even windows?** My eventual goal would be to be able to expand it to a UNIX system so that it can run off a mini dedicated server like raspberry pi.

From a cursory investigation and packet sniffing, the WeChat app doesn't actually use any proprietary protocols or the like, although it might be a slight pain to reverse engineer some of the compiled binaries like a WCDB.framework to understand how they work. I'm just personally a bit vague on application based hooking and of course it also depends on whether the app has any user friendly APIs/hooks.

Another possibility that I have yet to explore is if it's possible to adapt the current web API puppet to mimic the current WeChat client application as the communication protocols don't actually seem all that different, but I could be wrong...

**Comment by zixia** [comment]
It's great to hear from the community that there's someone want to build a puppet that fulfills themselves!

Please have a look at <https://github.com/Chatie/wechaty-puppet/wiki/Links> , it includes many useful links, like:

### PuppetWine

* [微信(WeChat)电脑端多开研究+源码](http://anhkgg.com/wechat-multi-pc/)
* [C/C++ Memory Hacking — API Call Hooking | Intercepting API calls](https://www.youtube.com/watch?v=knPMS01QbxU)
* [如何实现Hook替换Windows上的AP函数](http://blog.csdn.net/friendan/article/details/12226201)

### PuppetMac

* [两行代码组织 Mac 微信撤回消息](https://juejin.im/entry/58d8bdff570c350058e1d210)

Please let me know if you can do any prototype, and if you can make a good prototype, then I'd like to guide you how to write a puppet.

Good luck!
