### ISSUE TITLE
too many levels of symbolic links

### ISSUE THREAD

**Issue by dcsan** [wechaty/wechaty#165]
(information/ question)

maybe this is not a problem in normal usage, but I was using rsync to move some files around and it failed with "too many levels of symbolic links"

There seems to be either a *very* deep folder hierarchy or some type of recursion, perhaps Babel Typescript or some other part of the compile step is emitting nasty javascript.

```
rsync: readlink "/Users/dc/dev/rikai/ta-bot/wechaty/node_modules/.0.1.1@d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es5-ext/node_modules/es6-symbol/node_modules/d/node_modules/es5-ext/node_modules/es6-symbol/node_modules/es5-ext/node_modules/es6-symbol" failed: Too many levels of symbolic links (62)
```

its turtles all the way down!

```
 ls -la node_modules/.0.1.1@d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es6-symbol/node_modules/d/node_modules/es5-ext/node_modules 
total 16
drwxr-xr-x   4 dc  staff  136 Dec 27 08:18 .
drwxr-xr-x  26 dc  staff  884 Dec 27 08:18 ..
lrwxr-xr-x   1 dc  staff   25 Dec 27 08:18 es6-iterator -> ../../.2.0.0@es6-iterator
lrwxr-xr-x   1 dc  staff   23 Dec 27 08:18 es6-symbol -> ../../.3.1.0@es6-symbol
```

and still keeps going.

**Comment by zixia** [comment]
I don't think this is a Wechaty issue because node_modules directory is managed by npm.

In order to resolve your problem, my suggestion is:

1. to exclude node_modules directory when u setup rsync, and run `npm install` if you  updated ur dependencies.
1. use another rsync like tool which is support symbolic well.
1. use a github repo hook to trigger a git pull on your other side server.

**Comment by dcsan** [comment]
right agreed this is not wechaty related. 
I often deploy with node_modules from local to speed up deployment process in china, but now just reinstall node_modules on the server. I should maybe switch to a prebuilt docker env

**Comment by zixia** [comment]
Please be noticed that: Docker hub is also random blocked in China.
