### ISSUE TITLE
How to use Message.find() and Message.findAll()

### ISSUE THREAD

**Issue by xmsz** [wechaty/wechaty#1657]
### 1. Expected behavior

**Question: What behavior do you expect?**

Answer: Filter params with Message.find(), and get result.

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer: Can't set any params in Message.find()
I want to do in this way 

```
const record  =  await this.bot.Message.findAll({'text': /test/});
console.log(record)

```
But, it turn out with error notice me lack of 'fromId'.

Only did i use 
```
const record  =  await this.bot.Message.findAll();
console.log(record)

```
do return record. but, the record only came from one person no two.
And only have 10 records not all of them.

---
So, How to use Message.find() to filter the message record result.

### 3. Steps to reproduce your problem (and fixes, if any)

**Question: What're the reproducible steps for us to see your problem?**

Answer:
on_message.js
export default =(message)=>{
  const record  =  await this.bot.Message.findAll();
  console.log(record)
}

**Comment by huan** [comment]
Did you mean that you can not specify the filter parameter to `findAll` method?

I Will look into it when I have time.
