### ISSUE TITLE
[Feature] Send Raw Message

### ISSUE THREAD

**Issue by lhr0909** [wechaty/wechaty#1678]
Currently on Wechaty's `Message` class, the message type is pre-parsed and we are able to tell the type of the messages. As features start to grow in Wechat, there are more and more message types, notably the Mini-Program type.

`Message.text()` method can return the raw payload in XML format, and there is a way to forward the message in memory with `Message.forward()` method. However, often times we will need to persist such message payloads and forward it at a later time. I am proposing adding a low-level `sayRaw` method to send the raw payload over so we can have more flexibility to integrate into different systems.

I do see a lot of various requests for integrating ChatHistory and Mini-Program sending, I think exposing a lower level API can let developers integrate with Wechaty much quicker and have features built out much more easily.

It would be a lot of effort to pull the wires all the way down from the puppet level to the wechaty surface, but I am willing to put some time into it and make it happen.

**Comment by lijiarui** [comment]
Agree with this! 

Could you show your suggestion of what this API looks like?

**Comment by lhr0909** [comment]
It will basically just to have an extra `.sayRaw()` on the `Bot`, `Contact`, `Message` and `Room` classes, we will have them in wherever the `.say()` API is

```javascript
Bot.sayRaw(xml)
Room.sayRaw(xml)
Contact.sayRaw(xml)
Message.sayRaw(xml)
```

**Comment by lijiarui** [comment]
Related Issues:

- [Support ChatHistory messages](https://github.com/lijiarui/wechaty-puppet-padchat/issues/223)

**Comment by jijiechen** [comment]
@lhr0909  While I agree with your idea, but it's not easy to build raw messages though. This is especially true when much logic is hidden on servers when you use other puppets rather than the puppteer.
