### ISSUE TITLE
[New Puppet] PuppetWechatWork

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1684]
It has official API and should be very easy to implement.

See #1167

**Comment by lijiarui** [comment]
Really looking forward for this implement!

**Comment by huan** [comment]
It would be wonderful if anyone could volunteer to implement this puppet. ;-D

**Comment by lijiarui** [comment]
I can sponsor this project ：）

**Comment by windmemory** [comment]
`WeChatWork` feels weird to me, maybe `PuppetEnterprise` would be better :)

**Comment by huan** [comment]
We have WXWork now: https://wechaty.js.org/docs/puppet-services/wxwork
