### ISSUE TITLE
代码部署到服务器上，无法登录 ,警告异地登录

### ISSUE THREAD

**Issue by TigerBill2016** [wechaty/wechaty#1687]
### 0. Report Issue Guide

0. Please search in the issue first, and make sure your problem had not been reported before.
1. If your issue is related to _wechaty-puppet-padchat_, please report the issue at <https://github.com/lijiarui/wechaty-puppet-padchat/issues/new>
2. If your issue is related to _wechaty-puppet-puppeteer_, please report the issue at <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/new>
3. If your issue is DIRECT related to Wechaty, then please follow the below template and make sure you fill it as required in detail.

### 1. Expected behavior

本地调试是可以登录的，部署到服务器上，微信提醒 【....扫码请求在其他城市的设备登陆...】
**Question: What behavior do you expect?**

Answer:

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer:

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer:

### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by lijiarui** [comment]
Can you login by scan qrcode?

**Comment by TigerBill2016** [comment]
登录不了了
22:11:16 WARN PuppetPuppeteerBridge onDialog() page.on(dialog) type:type() {
0|app  |     return this._type;
0|app  |   } message:当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。
0|app  | (node:22502) UnhandledPromiseRejectionWarning: Error: Error: type() {
0|app  |     return this._type;
0|app  |   }(当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过Windows微信、Mac微信或者手机客户端微信登录。)
0|app  |     at PuppetPuppeteer.puppet.on.error (/www/thewave-server/node_modules/_wechaty@0.22.6@wechaty/dist/src/wechaty.js:436:44)
0|app  |     at PuppetPuppeteer.emit (events.js:182:13)
0|app  |     at PuppetPuppeteer.EventEmitter.emit (domain.js:442:20)
0|app  |     at PuppetPuppeteer.emit (/www/thewave-server/node_modules/_wechaty-puppet@0.14.1@wechaty-puppet/dist/src/puppet.js:171:22)
0|app  |     at Bridge.bridge.on.e (/www/thewave-server/node_modules/_wechaty-puppet-puppeteer@0.14.1@wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:207:47)
0|app  |     at Bridge.emit (events.js:182:13)
0|app  |     at Bridge.EventEmitter.emit (domain.js:442:20)
0|app  |     at Bridge.<anonymous> (/www/thewave-server/node_modules/_wechaty-puppet-puppeteer@0.14.1@wechaty-puppet-puppeteer/dist/src/bridge.js:118:18)
0|app  |     at Generator.next (<anonymous>)
0|app  |     at fulfilled (/www/thewave-server/node_modules/_wechaty-puppet-puppeteer@0.14.1@wechaty-puppet-puppeteer/dist/src/bridge.js:23:58)
0|app  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|app  | (node:22502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by lijiarui** [comment]
I found you are using PuppetPuppeteer which is using web wechat, web wechat has some limit, see more: https://docs.chatie.io/v/zh/#web-limit-1

**Comment by TigerBill2016** [comment]
服务器上，如何避免出现异地登录的警告, 谢谢！

**Comment by llh1187** [comment]
> I found you are using PuppetPuppeteer which is using web wechat, web wechat has some limit, see more: https://docs.chatie.io/v/zh/#web-limit-1

page not found

**Comment by llh1187** [comment]
> 服务器上，如何避免出现异地登录的警告, 谢谢！

您好，请问解决了吗

**Comment by llh1187** [comment]
> > 服务器上，如何避免出现异地登录的警告, 谢谢！
> 
> 您好，请问解决了吗

有的时候又可以登陆了，真奇怪

**Comment by Walt-like** [comment]
> 服务器上，如何避免出现异地登录的警告, 谢谢！

下载客户端登陆，手机确认就可以了吧
