### ISSUE TITLE
room.announce()报unexpected api call: WXGetChatroomAnnouncement

### ISSUE THREAD

**Issue by TigerBill2016** [wechaty/wechaty#1696]
### 0. Report Issue Guide

0. Please search in the issue first, and make sure your problem had not been reported before.
1. If your issue is related to _wechaty-puppet-padchat_, please report the issue at <https://github.com/lijiarui/wechaty-puppet-padchat/issues/new>
2. If your issue is related to _wechaty-puppet-puppeteer_, please report the issue at <https://github.com/Chatie/wechaty-puppet-puppeteer/issues/new>
3. If your issue is DIRECT related to Wechaty, then please follow the below template and make sure you fill it as required in detail.

### 1. Expected behavior

**Question: What behavior do you expect?**

Answer:

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer:
**wechaty-puppet-padchat 群聊中获取公告方法异常（room.announce）**

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer:
```js
const bot = new Wechaty()
await bot.start()
// after logged in...
const room = await bot.Room.find({topic: 'your room'})
const announce = await room.announce()
console.log(`room announce is : ${announce}`)
```
### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```
![image](https://user-images.githubusercontent.com/19324557/51544090-0e95b580-1e9a-11e9-9871-72992184bf6d.png)

</details>

**Comment by lijiarui** [comment]
wechaty-puppet-padchat hasn't implement anouncement yet, you can try [wechaty-puppet-padpro](https://github.com/botorange/wechaty-puppet-padpro)
