### ISSUE TITLE
你好,关于wechaty.say("ddd")中的信息,是经过你们的服务器再转到微信服务器吗

### ISSUE THREAD

**Issue by cuiweipeng** [wechaty/wechaty#1721]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by cuiweipeng** [comment]
我debug了 但是没找到...

**Comment by windmemory** [comment]
不同puppet有不同的实现
