### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by LiuWeiMr** [wechaty/wechaty#1722]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:0.22.6

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:padpro

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:"wechaty-puppet-padpro": "0.0.47"

- What is your node version? (run `node --version`)
Answer:v10.15.3

- What os are you using
Answer:Ubuntu

## 2. Describe the bug
bot启动四五个小时左右，bot进程自动退出。

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. 编译typescript，然后复制静态文件到编译目标目录，然后启动bot
2. 运行：tsc && rm -rf ./dist/static && cp -r ./src/static ./dist/static && node dist/index.js
3. 四五个小时后进程自动退出

## 4. Expected behavior
bot一直正常运行

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
log file:
[bot.zip](https://github.com/Chatie/wechaty/files/2986709/bot.zip)


```

</details>

## 7. Additional context

[bug]

**Comment by huan** [comment]
When you have not enough memory, this might happen. 

Please try to increase the memory in your server and try again.

**Comment by LiuWeiMr** [comment]
> When you have not enough memory, this might happen.
> 
> Please try to increase the memory in your server and try again.

![image](https://user-images.githubusercontent.com/17976666/54668528-15534880-4b2a-11e9-8914-132df0df3655.png)

**Comment by huan** [comment]
To get the detailed log output from wechaty, you can set `WECHATY_LOG=verbose` to enable the logging.

```sh
WECHATY_LOG=verbose node dist/index.js
```

Please provide the detailed log output so that we can see what's happened with your program.
