### ISSUE TITLE
How long can the Wechat Robot stay "logged in"？（微信机器人可以保持登录状态多长时间？）

### ISSUE THREAD

**Issue by Liusq-Cindy** [wechaty/wechaty#1727]
I have start a wechaty robot.

In my code, i use the sentence:"const bot = Wechaty.instance({ name: 'default' })" to create a default.memory-card.json file to store the landing information, and the robot can login automatically through this file.In this pason file, there are many expires message, is it means the login state will expires and my robot will be offline automatically at the appointed time？the minimal time is only 12 hours, but some time is 10 years
![image](https://user-images.githubusercontent.com/41781513/55147820-1156a480-5182-11e9-9d2e-21a3805946f3.png)

**Comment by huan** [comment]
This memory-card file will be updated automatically when your bot is keeping running.

**Comment by hfcheng66** [comment]
我试过用itchat的机器人，一般几天就需要重新扫码登陆了。 不知道这个限制是微信网页版的限制还是itchat有问题？ 

用wechaty的PuppetPuppeteer做的微信机器人能够长时间在线吗？

**Comment by shmilyoo** [comment]
same question.
can the bot keep online?
or is there some mechanism to restore the online state immediately whenever the bot logout.

**Comment by lijiarui** [comment]
This depends on which puppet are you using.

If you use web protocol, it may stay only for a few days depends on your wechat account.

If you use ipad protocol, it may stay for several months depends on your wechat account.
