### ISSUE TITLE
room.member() cannot find contact when contact set whose alias in the room

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#173]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
```shell
1. Wechaty version: #git[d6b69ab #155]
2. Darwin x64 version 14.5.0 memory 2398/16384 MB
3. Docker: false
4. Node version: v7.0.0
```

### Expected behavior

Use room.member() to find contact by name in a room. 

### Actual behavior

Cannot find contact by name when the contact change whose alias in the room.

### Steps to reproduce the behavior (and fixes, if any)

code as follows:

```
async function RoomTest(){
  let room = await Room.find({topic:"wetest"})
  await room.ready()
  console.log("member1: " + room.member("wuli舞哩客服"))
  console.log("member2: " + room.member("桔小秘"))
}
```
log as follows:
```
member1: wuli舞哩客服
member2: null
```
contact `"桔小秘"` has changed her alias in the room, so room.member() return null.

I found your annotation in `room.ts` says：
```
/**
   * NickName / DisplayName / RemarkName of member
   */
public member(name: string): Contact | null {
   // your function
}
```
I thought maybe you mean we can find room member by nickname、displayname or remark.

while, you use following function to find member

```
const idList = Object.keys(nickMap)
                          .filter(k => nickMap[k] === name)
```

nickMap is a map with id and displayName, log as follows:

```
SILL Room member() check nickMap: {"@bba74f144ab75df78e9cd3bbe9f79937":"李佳芮","@e40ab116adf563b28e0a8efdfb737b5bdfef69fad6dd83a02f087b827d8238b7":"哈哈","@c1d97b69778da9a480e790b15666fcbe3dfb0e185a5cbf3a07a813b21579dd68":"wuli舞哩客服"}
```

so, I thought may be you should refract nickMap to fix this bug?

Could you help me to fix it? thanks

**Comment by zixia** [comment]
Not sure about your issue, but I know there will be some issue because the Tencent had changed the way of show names in the room for many times.

You can just send a PR(with the unit test), then I'll be able to dive into it and understand which part you are going to fix.

**Comment by lijiarui** [comment]
I mean function `room.member()` cannot work well when the contact set its' remark, including in group and in contact list.

**Comment by lijiarui** [comment]
Contact's name was shown by the following order:   

remark set by bot  > remark set by itself in the group > nickName

it means:

* if the bot set remark for a contact, the group display name is the  remark set by the bot.
* if the bot doesn't set remark for a contact, the group display name is the remark set by the contact in the group
* if the contact doesn't set it's remark in the group, the group dispaly name is the contact's nickname

**Comment by lijiarui** [comment]
And I found it is caused by this commit:

[c41f3eda7c3bc1be06439127684f1901620795dc](https://github.com/wechaty/wechaty/commit/a6babc6072d62c16c3bfaddf4b110a499a8f53e1)

your comment says:
> ISSUE #104 never use remark name because sys group message will never use that

Actually， it does use remark name

**Comment by zixia** [comment]
> But I'm sorry for #104 you delete this perfect solution..

if i deleted this, that would mean  this solution absolutely is not perfect.

I believe you can start from here and get to dive deeper to the code, cheers.

**Comment by lijiarui** [comment]
At last, I got the rule of 3 kinds of name in wechat, maybe can helps in the future

### Definition
* `nickName`  Contact's wechat nickName
* `remark` When the bot set alias or remark for a contact in contact list, we call it remark.
* `displayName` When a contact set its's alias in the group,  we call it displayName, so displayName is bind to one room.


### Display order:

* `@ ` 
When someone @ a contact in  a room, wechat recognise the name order as follows:   
displayName > nickName

* `system message`
When room event happens(join, leave, changetopic), system message recognise the name order as follows:   
remark > nickName

* `on-screen Names`
the contact name showed to the wechat user in the group   
remark > displayName > nickName

**Comment by zixia** [comment]
1. All names are the same as them in the webwxApp source code; this could make them less understanding, excellent.
1.  Display order is very clear. I believe this will help us to correct the program logic of dealing with nickName/remark/displayName.

Great job, and I'm looking forward to receiving your Pull Request that implement this!

**Comment by lijiarui** [comment]
I have update my code in [fix_function_room.member_#173](https://github.com/wechaty/wechaty/pull/211)   

Could you help me to check the code?
