### ISSUE TITLE
需要一个能列出待审核好友请求的功能（而且得能对请求进行accept等操作）

### ISSUE THREAD

**Issue by harefield** [wechaty/wechaty#1733]
**Is your feature request related to a problem? Please describe.**
TX对微信账号管理愈发严格，无论是大量主动添加好友或者被动通过好友请求，都会引发封号的情况发生。

**Describe the solution you'd like**
需要能够读取待审核的好友请求，这样通过定时任务可以定时定量的审批好友请求，不至于被封号

**Describe alternatives you've considered**
在Friendship类中增加一个list方法，可以列出尚未审核的好友请求，该方法应当返回一个列表，列表中的每一项应当为好友请求实例，以便可以根据需要对好友请求实例进行操作，如通过、拒绝等

**Additional context**
该方法应当为一个静态方法

[enhancement]

**Comment by lijiarui** [comment]
Sorry, we won't enhance this in the near future.

**Comment by huan** [comment]
@harefield Thanks for the suggestion!

It's a good feature request, I'd like to add this feature if there will have someone implmentated it by submiting a PR.

**Comment by windmemory** [comment]
@huan So for this feature, seems like we could just add a `bot.Friendship.list()` function to popup all the friendship events before, with corrected type, then the problem is solved, am I right?

**Comment by huan** [comment]
Thanks for your design for that. And yes, this API design looks good to me.

I believe the `list()` function should call the underlining Puppet Implementation to get the actual List out.

**Comment by windmemory** [comment]
> I believe the list() function should call the underlining Puppet Implementation to get the actual List out.

I agree. Do you have any idea of what should the method name be for `wechaty-puppet`? Like `friendshipList`?
