### ISSUE TITLE
[document] should list only the public/stable API to users

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#174]
@lijiarui Many new APIs that you had just added to https://github.com/wechaty/wechaty/wiki/API , should not list at all.

such as:

1. dump()
1. dumpRaw()
1. rawObj
1. toString/toStringEx/xxxEx()
1. others/etc...

Because those APIs is not stable/will be changed in anytime/should be treated as private/testing methods.

**Comment by lijiarui** [comment]
done

**Comment by zixia** [comment]
great. 

Also:

1. `Message.count()` should not be an API because it is only used for debugging.
1. MsgType should use enum instead of numbers.
1. etc.

**Comment by lijiarui** [comment]
done

**Comment by zixia** [comment]
Thank you. :)
