### ISSUE TITLE
wechat warn:WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???But if i change another wechat account, it is running normally.（微信机器人报错，无法收取群消息，但换一个微信账号登录则没有这个问题）

### ISSUE THREAD

**Issue by Liusq-Cindy** [wechaty/wechaty#1740]
My wechaty version is ^0.22.6
    when I log in with my own wechatl account and didn't do anything, the robot can't show the rooms messages but only show warning as:
![image](https://user-images.githubusercontent.com/41781513/56119642-1ba8d900-5f9f-11e9-89ca-689802897520.png)
![image](https://user-images.githubusercontent.com/41781513/56120582-fb7a1980-5fa0-11e9-92f2-d8aa4f02e61e.png)

    I have read the similar issue :https://github.com/Chatie/wechaty/issues/1547，so  i changed my node version,it isn't useful.
    But when i change a wechat account to login the robot ,the room messages could be show normally.
   I guess there maybe some not suitable setting in my rooms of my account, but i don't know what it is.Could you please tell me why the diffrent account show these issues and how to solve it ?Thank you!

**Comment by sunnyboyi** [comment]
我也遇到这个问题了  要换微信号才能发消息   这个问题要这么解？

**Comment by caffreycc** [comment]
**The same problem was found on my machine.**
errTrace:
`13:10:59 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:00 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:01 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:02 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:03 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:04 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:05 WARN PuppetPuppeteer roomRawPayload() currLength(-1) <= prevLength(0) ???
13:11:06 ERR PuppetPuppeteer roomRawPayload(@765cfe6de121c1b666c1d85578e6b998a6a089253d93256ca6311591bb2c235cab) exception: no payload
(node:9061) UnhandledPromiseRejectionWarning: Error: no payload
    at PuppetPuppeteer.<anonymous> (/wechat/wechatBot/node_modules/_wechaty-puppet-puppeteer@0.14.6@wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:603:23)
    at Generator.next (<anonymous>)
    at fulfilled (/wechat/wechatBot/node_modules/_wechaty-puppet-puppeteer@0.14.6@wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:22:58)
(node:9061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

删除node_modules ， 更新wechaty到0.27.3 即可解决此问题。
update devDependencies.wechaty to ** "wechaty": "^0.27.3"**

**Comment by caffreycc** [comment]
> 我也遇到这个问题了要换微信号才能发消息这个问题要这么解？
更新wechaty到0.27.3
