### ISSUE TITLE
登陆二维码无法识别

### ISSUE THREAD

**Issue by azui007** [wechaty/wechaty#1753]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:最新的版本

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:默认的

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:最新的

- What is your node version? (run `node --version`)
Answer:v10.15.0

- What os are you using
Answer:windows 10

## 2. Describe the bug
控制台输入二维码无法识别
## 3. To Reproduce
1. wechaty-getting-started> npm start
> node examples/starter-bot.js

22:20:16 INFO Wechaty <default> start() v0.22.6 is starting...
Starter Bot Started.
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄█▀ ██  ▀█▄▀█ ▄▄▄▄▄ █
█ █   █ █▄   ▄▀▀  ▄█▀▀█ █   █ █
█ █▄▄▄█ █ ▀█▀█▄▀▀   ▀▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█ █ ▀ ▀▄▀ █▄▄▄▄▄▄▄█
█▄▄▀ █▀▄ ██ ▀█▀ ██▀█▄█▀ ▄▄▀▄▄▀█
██ ▀██▀▄▄▀▄▄██ █▀▄▄ ▄▄  ▄ ▄  ██
█ ▄▀▄▀ ▄▄██▀▀ ▄█▄█▄█  ▀▄██▄█▄▄█
█ ▀▀▄█ ▄▄ ▄ █   ▀▄▀▀▀▄ ▀██ ▄ ▄█
██▀▄█▄▀▄ ▀▀ ▄██▄█  ██▄▄▀▀█▀█▄▀█
█▄██ ▀█▄ █▄▀▀██▀█▄▀▀█▄▄▄▄▀██  █
█▄█▄▄█▄▄▄▀█▄  ▄▀█ █▄▄ ▄▄▄ █ ▀▀█
█ ▄▄▄▄▄ █▄▄▀   █▀▄▄▀█ █▄█ ▀▀ ▀█
█ █   █ █▀▄▀ █▀▄▀▄▄█▀▄▄   ▀▀▀██
█ █▄▄▄█ █▀ ▀ █▄▄█▀ █▀ ██▀▄▄▄▀▄█
█▄▄▄▄▄▄▄█▄▄▄█▄▄█▄█▄▄█▄▄█▄█▄█▄██

## 4. Expected behavior
输出正常的二维码（可以通过微信扫一扫识别）

## 5. Actual behavior
请参考上边

## 6. Full Output Logs
没看到哪里有这个设置，抱歉

**Comment by jim4node** [comment]
我今天新安装的 wechaty 也是这问题, 不知道如何解决?

**Comment by su-chang** [comment]
https://github.com/wechaty/wechaty-puppet-padplus/wiki/FAQ#2-when-the-terminal-starts-the-project-the-qr-code-is-deformed

Maybe it could help you.

**Comment by jim4node** [comment]
solution: you need to copy and paste the generation URL on your browser and scan from there

**Comment by huan** [comment]
Yes. and it's related to https://github.com/wechaty/wechaty/issues/1905?from=groupmessage&from=groupmessage#issuecomment-580560030
