### ISSUE TITLE
[Help]How to send message to a friend of wechat on Windows, called by the other C++ Exe?

### ISSUE THREAD

**Issue by opengpu** [wechaty/wechaty#1760]
[Help]How to send message to a friend of wechat on Windows, called by the other C++ Exe?

**Comment by opengpu** [comment]
???anybody?

**Comment by huan** [comment]
It's not hard to call anything in your C++ code.

For example, you could be able to build a RESTful service in Node.js and wrap Wechaty inside, then you can call REST API in your C++ code.

You can learn more from our Chatie Blog: [Interact Wechaty with Ruby on Rails from scratch](https://blog.chatie.io/interact-wechaty-with-ruby-on-rails-from-scratch/)

**Comment by opengpu** [comment]
谢谢。没有直接restful和c++的例子？
到时候是应该把我的c++程序和wechaty都先启动，然后在需要发送消息的时候，有c++调用接口发消息给wechaty？

**Comment by opengpu** [comment]
这样同时启动两个程序通信的话，效率如何，因为需要比较迅速的给好友发消息，还需要长时间登陆。
