### ISSUE TITLE
friendship回调问题

### ISSUE THREAD

**Issue by wenh7788** [wechaty/wechaty#1773]
1.用户A添加B（机器人），b通过了可以进入到friendship的回调中 这个没有问题
2.用户A删除掉B 再次添加 没有进入到回调
3.b删除用户A 然后A重新添加 没有进入 回调

**Comment by VEADoc** [comment]
2.用户A删掉B 再次添加 对B是无感的啊 没有回调不是很正常吗
3.B删掉A 然后 A重新添加(B)? 抱歉没理解这逻辑
