### ISSUE TITLE
ContactQueryFilter 里增加通过id或者weixin 查找联系人

### ISSUE THREAD

**Issue by nickwong** [wechaty/wechaty#1804]
**Is your feature request related to a problem? Please describe.**
name和alias 是可变的，可修改。想查找某个用户的时候，可能他的name被用户修改过因而没有找到该用户。

**Describe the solution you'd like**
id和weixin由微信决定不可变，希望增加通过这两个参数也可以查找联系人。

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by huan** [comment]
Duplicated with #1785

**Comment by huan** [comment]
BTW please notice that whether the id is permanent will be depended on the puppet provider you are using.

Padpro will but puppeteer will not.

**Comment by huan** [comment]
Thanks for the feature request.

To search for contact by their weixin id, we can now use `Contact.findAll({ weixin: 'xxx' })` to archive that.

Require Wechaty v0.29.52 or above.
