### ISSUE TITLE
 bot.Friendship.add 无效

### ISSUE THREAD

**Issue by JarVZhao** [wechaty/wechaty#1805]
web  0,27.36    bot.Friendship.add 无效
使用场景是从群里加好友,试了加一个几百人的群,人都能拿到但是无法添加,500个人一个也不行:
const memberList = await room.memberList()
for (let i = 0; i < memberList.length; i++) {
  await bot.Friendship.add(member, 'Nice to meet you! I am wechaty bot!')
}

**Comment by maoguijun** [comment]
我试了一晚上也是没有效果，又看不到具体报错

**Comment by lijiarui** [comment]
Please follow the issue template, thanks!
