### ISSUE TITLE
机器人会隔一段时间自动退出

### ISSUE THREAD

**Issue by wenh7788** [wechaty/wechaty#1810]
单纯的从日志上看就是跑着跑走到了机器人的loginout的回调里面了。绝对不是人为操作。因为机器人的手机只有一个人保管。日志上看不出来啥。能否帮忙看看~谢谢~~

**Comment by scholar-wei** [comment]
我这边也是这种情况，我这边大概20多个机器人，同时启动之后，都会同一个时间退出，频率是三天

**Comment by huan** [comment]
I guess you are all using the `wechaty-puppet-padpro`?

**Comment by scholar-wei** [comment]
> I guess you are all using the `wechaty-puppet-padpro`?

"wechaty-puppet-padpro": "0.3.5"

**Comment by heguofeng** [comment]
I had the same problem

**Comment by huan** [comment]
Close this issue because the wechaty-puppet-padpro has been deprecated.

User [wechaty-puppet-padplus](https://github.com/wechaty/wechaty-puppet-padplus) instead.
