### ISSUE TITLE
Would like to have receiver, serialize and deserialize functions on RoomInvitation

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty#1823]
**Is your feature request related to a problem? Please describe.**
Trying to implementing a feature that user could accept room invitation and view room invitation in web page. So I need two more functions:
* One function enables the ability to retrieve/regenerate the room invitation, and accept when the user triggered the accept action.
* The other one could return back the invitation's receiver, for invitation that is not sent by bot, it is clear that the sender and the receiver, but if the invitation is sent by myself, it is impossible currently to know whom the invitation is sent to. So I want to have this function that tells me who is the receiver.

**Describe the solution you'd like**
I would like to have two or three more functions provide by `RoomInvitation` class. 
* `to(): Promise<Contact>` to retrieve the receiver info
* `stringify(): Promise<string>` to serialize the `RoomInvitation`
* `static parse(): Promise<RoomInvitation>` to deserialize the string and generate the room invitation object again, so we can call `accept` on it to accept the invitation.

**Describe alternatives you've considered**
No alternatives yet considered.

**Comment by windmemory** [comment]
Kindly ping @huan

**Comment by huan** [comment]
Sorry for the late reply, and thanks for the reminding.

The basic concept looks good in your proposal.

Please go-ahead to submit a PR to show your code so that we could be able to discuss the design patterns for it.

**Comment by windmemory** [comment]
I've created a draft PR in `wechaty`, `wechaty-puppet` and `wechaty-puppet-padpro`. I added two class methods and two instance methods:
**Class Method**
* `serialize (invitation: RoomInvitation): Promise<string>`
* `deserialize<T extends typeof RoomInvitation> (payloadString: string): Promise<T['prototype']>`

**Instance Method**
* `to (): Promise<Contact>`
* `avatar (): Promise<FileBox>`

The class methods used to serialize the object back and forth so we can persist it in other storage, and load it, accept it anytime we want.

The instance methods used to get two more attributes for room invitation, which is the `to`, whom the invitation is sent to, and the `avatar` for the room that the invitation is for.

With the current functions, we are able to construct the invitation card with the functions on `RoomInvitation`.

But this is just a draft api, please let me know your idea about this, and any suggestion is welcome.

**Comment by huan** [comment]
Great to hear from you and see the API drafts!

I will look into it and get back to you later.

**Comment by windmemory** [comment]
Kindly ping @huan

**Comment by huan** [comment]
Got it. Cloud you please also create the PR for #1829 so that I could review all the code at once? Because that would greatly increase the efficiency and save a lot of time for me.

**Comment by windmemory** [comment]
Will do later.

**Comment by huan** [comment]
Does this feature request similar to #1890?

A PR to demonstrate the requirement and implementation will be welcome.

**Comment by windmemory** [comment]
This is similar to that, but currently active puppets do not support this feature, so we can  close this issue for now.

**Comment by huan** [comment]
Thanks for the Pull Request and the improvements for Wechaty.

This feature is quite the same as we did the `Friendship` before, and we have already had the design pattern with the merged code before.

Please follow my reviews of those PRs, and make sure we are keeping consistent with the design pattern.

We will be able to merge them once they confirmed the design pattern of the `toJSON`, `fromJSON`, and the `roomInvitationPayload()`

**Comment by su-chang** [comment]
There has one bug in RoomInvitation, if we named this method `toJSON`, when the RoomInvitation constructor, this method will be called by some one which I do not know.

Do you know who call the method `toJSON` ? 

P.S. if I change the name `toJSON` to `toJson`, everything work well.

**Comment by huan** [comment]
I believe that's because somewhere called `JSON.stringify(roomInvitation)`, which will call `toJSON` on `roomInvitation` automatically defined by the specification at <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify>

> ### toJSON() behavior
> If an object being stringified has a property named toJSON whose value is a function, then the toJSON() method customizes JSON stringification behavior: instead of the object being serialized, the value returned by the toJSON() method when called will be serialized. JSON.stringify() calls toJSON with one parameter:
> 
> - if this object is a property value, the property name
> - if it is in an array, the index in the array, as a string
> - an empty string if JSON.stringify() was directly called on this object

**Comment by su-chang** [comment]
Yes, thank you very much for point out this problem.

Code:
```js
public async toJSON (id: string): Promise<string> {
    log.verbose('RoomInvitation', `toJSON(${id})`)
    const payload = await this.puppet.roomInvitationPayload(id)
    return JSON.stringify(payload)
}
```

So we should change the method name ? Or return RoomInvitationPayload object, and let user to stringified by themselves.

**Comment by su-chang** [comment]
In this case, JSON.stringify() will worked at `RoomInvitationPayload` but not `RoomInvitation`.

It seems that `RoomInvitation` could have a method named `toJSON`, but bug happened. :(

**Comment by huan** [comment]
Does this block your work? If not, I suggest that you can feel free to ignore it because it's just a `toJSON()` call, nothing matters?

**Comment by su-chang** [comment]
Of course, if we call `JSON.stringify()` in `room-invite` event, it will block.

The type of params in `room-invite` event is RoomInvitaion.

I think this bug will be happened in `friendship` event too.

So maybe we could change all `toJSON()` to `serialize()`, and all `fromJSON()` to `deserialize()`.

**Comment by huan** [comment]
1. Why it will block? I can not understand, please explain in details.
1. Can you provide a reproduce-able description, which can demonstrate this problem?

**Comment by su-chang** [comment]
```js
bot.on('room-invite', async (roomInvitation: RoomInvitation) => {
    console.log(`room invitation : ${JSON.stringify(roomInvitation)}`)

    const roomInvitationObject = bot.RoomInvitation.load(roomInvitation.id)

    const jsonData = await roomInvitationObject.toJSON(roomInvitation.id)
    console.log(`jsonData : ${jsonData}`)
})
.start()
```
If we use JSON.stringify() here in `room-invite` event for , it will call `toJSON()` method in `RoomInvitation` class without params.

If we remove the first `console.log()`, everything ok.

**Comment by huan** [comment]
So you get to know why your `toJSON` get called, am I right? You can fix this by comment out your `console.log` line.

The reason is the `console.log` will call `JSON.stringify(roomInvitation)` which will invoke the `roomInvitation.toJSON()` method. (this behavior is defined by specification)

I have two questions about your code:

1. why are you using `bot.RoomInvitation.load(roomInvitation.id)` ? I believe you will get a `roomInvitationObject === roomInvitation` at last.
1. why you call toJSON with argument `roomInvitation.id` like this: `roomInvitationObject.toJSON(roomInvitatoini.id)` ? Instead of your way, I will prefer to use `JSON.stringify(roomnvitation)`. Does that can archive your goal? If not, why?

**Comment by su-chang** [comment]
You are right for there two questions.
Code:
```js
bot.on('room-invite', async (roomInvitation: RoomInvitation) => {
    const jsonData = await roomInvitation.toJSON()
    console.log(`jsonData : ${jsonData}`)
})
.start()
```

**Comment by huan** [comment]
Great. I hope we are good now.

Cheers!

**Comment by huan** [comment]
Please close this issue if there's no more questions, thank you very much!

**Comment by windmemory** [comment]
One more thing to discuss, shall we add an `id` to the payload, so we can distinct these payloads whether they are duplicates or not?

**Comment by huan** [comment]
Do you mean to add `id` in `RoomInvitatoinPayload`?

If so, I believe we have it already:

https://github.com/wechaty/wechaty-puppet/blob/725138b01cdf2553560912713047b842d49b8a36/src/schemas/room-invitation.ts#L2

**Comment by windmemory** [comment]
Yep, it's already there, and everything looks marvelous! Close this issue!

Thanks everyone for the help!

**Comment by windmemory** [comment]
We missed the `receiver` property on this payload.
:(

So let's open this issue and add the receiver to the payload.
Without the receiver, it is impossible for user to know whom an invitation sent by the bot itself sent to. Because the invitation sent by the bot will have the inviter as the bot, and no other information to tell who is the receiver.
