### ISSUE TITLE
Would like to have the timestamp on the room/friendship events

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty#1829]
**Is your feature request related to a problem? Please describe.**
Currently we don't have a way to get the timestamp of when the events really happened. In wechat's world, when the account is not online, the event is queued up, and once the account is online, events will be pushed. If we use the timestamp that the event is triggered, it is not accurate, sometimes, it will have few hours or even days delay. So I would like to have the timestamp value emitted together in the room/friendship events.

**Describe the solution you'd like**
In the listener function of room/friendship functions, add `timestamp` as the last parameter.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
No

[enhancement]

**Comment by huan** [comment]
It's a reasonable proposal, please go-ahead and PR will be welcome!

**Comment by windmemory** [comment]
Okay will do

**Comment by windmemory** [comment]
I've created draft changes for this feature request.

Actually I came up with two solutions:
* Add timestamp value to the event callbacks
* Convert the arguments in the event callback into one event object, then add timestamp onto that object

I took the first one, since the second one requires more code changes than the first one, and that is a big breaking change.
But for the first solution, my PR might not be the best solution. At the beginning, I thought to put the new arguments at the end of the parameters, so this change won't be a breaking change, but I found the `room-leave` event has an optional parameter, and from my understanding, the new `time` argument should always be available, so it is not optional, so I can not put it at the end of every event callback. So I put it after the `room` argument.

Let me know what do you think is the best implementation. @huan

**Comment by windmemory** [comment]
I think we can close this issue as soon as the `wechaty-puppet-puppeteer` update the code to emit the `timstamp` in room events.

**Comment by huan** [comment]
You are right. And not only the wechaty-puppet-puppeteer but also other puppet providers maintained by chatie as well, like `mock`, `wechat4u`, etc.

**Comment by windmemory** [comment]
Issues created in each puppet, I will try to squeeze some time working on some of the upgrades.

**Comment by huan** [comment]
Great, thank you very much for creating the issues and planing to fix them!

**Comment by huan** [comment]
After we had close this issue, I'd like to bump all the puppets version to a stable version number, so that all the developers would be able to use them.

Especially the puppeteer and the padpro.

**Comment by huan** [comment]
I will close this issue because I guess it has been resolved.
