### ISSUE TITLE
基于padpro协议不能发送微信小程序

### ISSUE THREAD

**Issue by CQHO** [wechaty/wechaty#1837]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:
  "wechaty": "^0.27.60",
    "wechaty-puppet-padpro": "^0.3.18"
- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:
  "wechaty": "^0.27.60",
    "wechaty-puppet-padpro": "^0.3.18"
- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:
  "wechaty": "^0.27.60",
    "wechaty-puppet-padpro": "^0.3.18"
- What is your node version? (run `node --version`)
Answer:
v10.16.1
- What os are you using
Answer:
mac osx
## 2. Describe the bug
Give a clear and concise description of what the bug is.
不能发送微信小程序
 var miniPayload = new MiniProgram ({
     username : 'gh_dc74f3309680',
     appid              : 'wxebccec0b2aff9d88',
     title              : '寻声朗读',
     pagepath           : 'pages/index/index',
     description        : '寻声校园',
     thumbnailurl       : ''
 });

 await room.say(miniPayload);
发送小程序后 不能pagepath填写什么，都会出现找不到页面。如果不填就能发出去，打开显示主页。thumbnailurl不支持，发不出封面图
## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...
参见源码
## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by zhaoic** [comment]
in miniPayload, you can try
```
pagepath : 'pages/index/index.html'
```

thumbnailurl not support yet, we can't get cdnthumbnail automatically

**Comment by CQHO** [comment]
为什么要这样？ 是bug还是以后都这样了

**Comment by zhaoic** [comment]
微信小程序cdn相关字段不开放，目前无法自动获得，还需要后面继续逐渐的完善

有一个临时解决办法是解析一个正确的小程序，把其中cdn相关字段提取出来，硬编码进generateMiniProgramXMLMessage

**Comment by limingth** [comment]
@CQHO 关于封面图的问题，在目前的PR里面没有得到很好的解决。一方面是我们的能力所限，一方面也是希望能有更多志同道合的技术高手参与到开源项目里贡献代码。 如果有兴趣对这个feature enhancement提交PR，可以加我微信 limingth，我拉你到我们的 PR 群里交流。

**Comment by huan** [comment]
Close this issue because the wechaty-puppet-padpro is deprecated.
