### ISSUE TITLE
微信退出登录后，重新登录不了ipad

### ISSUE THREAD

**Issue by lb1938** [wechaty/wechaty#1839]
扫码后出现代码如下

  at process.topLevelDomainCallback (domain.js:120:23)
(node:12696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:12696) UnhandledPromiseRejectionWarning: OpenError: EIO, IO error: lock /root/.wechaty/puppet-padpro-cache/puppet_padpro_653ef69a479d4f87/file-cache/LOCK: Resource temporarily unavailable
    at /home/wechatbot/node_modules/_levelup@2.0.0-rc3@levelup/lib/levelup.js:88:23
    at /home/wechatbot/node_modules/_abstract-leveldown@3.0.0@abstract-leveldown/abstract-leveldown.js:39:16
    at /home/wechatbot/node_modules/_deferred-leveldown@2.0.3@deferred-leveldown/deferred-leveldown.js:19:21
    at /home/wechatbot/node_modules/_abstract-leveldown@2.7.2@abstract-leveldown/abstract-leveldown.js:39:16
    at /home/wechatbot/node_modules/_abstract-nosql@3.0.0@abstract-nosql/abstract-nosql.js:594:16
    at Immediate.<anonymous> (/home/wechatbot/node_modules/_abstract-nosql@3.0.0@abstract-nosql/abstract-nosql.js:282:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
(node:12696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
然后就一直提示这个.... 微信不会显示登录
00:53:27 WARN PadproManager setContactAndRoomData() can not proceed due to no cache.

**Comment by huan** [comment]
This error message indicated that you might have another process already running.

That's why you get a `OpenError: EIO, IO error: lock file-cache/LOCK: Resource temporarily unavailable`

**Comment by lb1938** [comment]
> 错误代码如下
> 
> at process.topLevelDomainCallback (domain.js:120:23)
> (node:12696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
> (node:12696) UnhandledPromiseRejectionWarning: OpenError: EIO, IO error: lock /root/.wechaty/puppet-padpro-cache/puppet_padpro_653ef69a479d4f87/file-cache/LOCK: Resource temporarily unavailable
> at /home/wechatbot/node_modules/_levelup@2.0.0-rc3@levelup/lib/levelup.js:88:23
> at /home/wechatbot/node_modules/_abstract-leveldown@3.0.0@abstract-leveldown/abstract-leveldown.js:39:16
> at /home/wechatbot/node_modules/_deferred-leveldown@2.0.3@deferred-leveldown/deferred-leveldown.js:19:21
> at /home/wechatbot/node_modules/_abstract-leveldown@2.7.2@abstract-leveldown/abstract-leveldown.js:39:16
> at /home/wechatbot/node_modules/_abstract-nosql@3.0.0@abstract-nosql/abstract-nosql.js:594:16
> at Immediate. (/home/wechatbot/node_modules/_abstract-nosql@3.0.0@abstract-nosql/abstract-nosql.js:282:13)
> at runCallback (timers.js:705:18)
> at tryOnImmediate (timers.js:676:5)
> at processImmediate (timers.js:658:5)
> at process.topLevelDomainCallback (domain.js:120:23)
> (node:12696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)



> 错误代码如下
> 
> at process.topLevelDomainCallback (domain.js:120:23)
> (node:12696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
> (node:12696) UnhandledPromiseRejectionWarning: OpenError: EIO, IO error: lock /root/.wechaty/puppet-padpro-cache/puppet_padpro_653ef69a479d4f87/file-cache/LOCK: Resource temporarily unavailable
> at /home/wechatbot/node_modules/_levelup@2.0.0-rc3@levelup/lib/levelup.js:88:23
> at /home/wechatbot/node_modules/_abstract-leveldown@3.0.0@abstract-leveldown/abstract-leveldown.js:39:16
> at /home/wechatbot/node_modules/_deferred-leveldown@2.0.3@deferred-leveldown/deferred-leveldown.js:19:21
> at /home/wechatbot/node_modules/_abstract-leveldown@2.7.2@abstract-leveldown/abstract-leveldown.js:39:16
> at /home/wechatbot/node_modules/_abstract-nosql@3.0.0@abstract-nosql/abstract-nosql.js:594:16
> at Immediate. (/home/wechatbot/node_modules/_abstract-nosql@3.0.0@abstract-nosql/abstract-nosql.js:282:13)
> at runCallback (timers.js:705:18)
> at tryOnImmediate (timers.js:676:5)
> at processImmediate (timers.js:658:5)
> at process.topLevelDomainCallback (domain.js:120:23)
> (node:12696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)



> 此错误消息表示您可能已经运行了另一个进程。
> 
> 所以你才能得到一个`OpenError: EIO, IO error: lock file-cache/LOCK: Resource temporarily unavailable`

好的我看看

**Comment by huan** [comment]
Close this issue due to no reply for more than 6 months.
