### ISSUE TITLE
Use wechaty-puppet-mock as a template to getting started with Wechaty Puppet Provider developing.

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#1850]
wechaty is not only wechat connector, but it also contains a lot of tests, pack and deploy things.

Each time we made a new puppet, we have to reset these things.

If we could publish a wechaty-puppet-template package in the future, maybe it will make us way easier to do a new puppet.....

**Comment by huan** [comment]
We can use [wechaty-puppet-mock](https://github.com/Chatie/wechaty-puppet-mock) as the template, and it will exactly do what you want in your post.

![image](https://user-images.githubusercontent.com/1361891/64499120-4434c500-d2ea-11e9-88ae-17442e71c9b0.png)

**Comment by huan** [comment]
I believe we need to marketing more on how easy to write a wechaty puppet, like:

1. Write tech blogs to introduce the wechaty-puppet
1. Write tutorials for tech user to develop a new wechaty-puppet
1. Publish video with screen record and live coding to make new developers understand the puppet system easily.

To be planed.
