### ISSUE TITLE
PuppetManager install(wechaty-puppet-padpro@^0.3.21) please wait

### ISSUE THREAD

**Issue by njdmznkj** [wechaty/wechaty#1865]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
PuppetManager install(wechaty-puppet-padpro@^0.3.21) please wait???

**Comment by huan** [comment]
It need to install the wechaty-puppet-padpro when you run wechaty.

You can:

1. Pre-install it by running `npm install wechaty-puppet-padpro@0.3.21`, then run your code again.
1. Just wait for it to be installed. It might take a while (from dozens of seconds to more than 10 minutes, depends on your network and your environment).

**Comment by huan** [comment]
I hope my comment has answered the question.

Close this issue due to inactive in the past year.
