### ISSUE TITLE
调试开发,很麻烦, 有没有好的测试方法,每次都要扫码登录,烦琐的工作!

### ISSUE THREAD

**Issue by tangjoin** [wechaty/wechaty#1874]
记得puppeteer有一个接口,puppeteer.connect(options), 可以连接到现有的puppeteer上,
wechaty有暴露出puppeteer.connect(options)接口吗,   这样我们就可以开一个puppeteer服务,
wechaty测试开发时连接 puppeteer服务,更好的调试逻辑代码,避免每次都要扫码登录,烦琐调试工作!
        小白一个知识面小, 如有其它好调试的方法, 希望能告知一二,谢谢

**Comment by huan** [comment]
You can save your profile when creating the Wechaty instance so that you can save your session between restarts.

**Comment by iyjian** [comment]
you can implement a mock puppeteer just like [wechaty-puppet-mock](https://github.com/wechaty/wechaty-puppet-mock) ,  sending mock qr code, contacts profiles, group profiles after puppeteer started, and then make appropriate reponses to the wechaty command.

**Comment by huan** [comment]
@iyjian That's correct.

I'll treat this is an advance unit testing method for your project, and if anyone is interested in using a  `wechaty-puppet-mock` to do unit testing, please let me know!

**Comment by tangjoin** [comment]
> You can save your profile when creating the Wechaty instance so that you can save your session between restarts.

如何保存一个实例, 在文档中没有找到对应的api

**Comment by huan** [comment]
@tangjoin You can specify the `name` options in the [WechatyOptions](https://wechaty.github.io/wechaty/#WechatyOptions)

**Comment by huan** [comment]
Close this issue because it's inactive for more than 6 weeks.
