### ISSUE TITLE
msg.mentionSelf()方法不对，始终返回false

### ISSUE THREAD

**Issue by mandaren** [wechaty/wechaty#1877]
async function message(msg){   
    const isAtSelf = await msg.mentionSelf()
    console.log(isAtSelf)
}
最简单的复现

**Comment by mandaren** [comment]
这个是macpro的问题，我移到macpro去了

**Comment by zzc-tongji** [comment]
在默认情形下，好像也有这个 BUG。

``` javascript
const robot = new Wechaty();
```
