### ISSUE TITLE
bot.logonoff()报错【static puppet not found for Wechaty】

### ISSUE THREAD

**Issue by losetime** [wechaty/wechaty#1878]
## 1. Versions
- What is your wechaty version?
Answer:0.29.5，0.28.3，0.22.1

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: puppeteer

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.18.2

- What is your node version? (run `node --version`)
Answer: 10.15.1，12.13.1

- What os are you using
Answer: windows

## 2. Describe the bug
当前我想知道微信web的登录状态，所以使用bot.logonoff()这个方法，但是总是会报出【static puppet not found for Wechaty】这个错误，当前我只在这个方法中遇到错误，我试了三个版本的wechaty，依旧如此。写法也是依照issue #1217中写的，并且试了官方给的例子也是如此
![image](https://user-images.githubusercontent.com/21984991/69494546-07936580-0ef8-11ea-9036-424ef84ef27a.png)
![image](https://user-images.githubusercontent.com/21984991/69494568-46c1b680-0ef8-11ea-8efa-52f3c323fccd.png)

## 4. Expected behavior
bot.logonoff() 返回true或false

## 7. Additional context
node， koa2

**Comment by LaoHu97** [comment]
同问

**Comment by huan** [comment]
Thanks for reporting this problem!

It should be fixed with version 0.29.27 or above.
