### ISSUE TITLE
Support Moments related methods.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#1880]
**Is your feature request related to a problem? Please describe.**

Support Moments related methods could make Wechaty be better.

**Describe the solution you'd like**

The API which I design based on the WeChat underlying protocol:

```javascript
  // post text moments
  postText (moment: string): Promise<Moments>

  // post some images with text or one video moments
  postMedia (moment: MomentsMedia[], text?: string): Promise<Moments>

  // post link moments
  postUrlLink (moment: MomentsUrlLink): Promise<Moments>

  // get all or one's moments
  timeline (contact?: Contact, momentsId?: string): Promise<Moments[]>

  // get one's moments detail
  moments (momentsId: string): Promise<Moments>

  // comment or like one's moments
  comments (comments: MomentsComments): Promise<boolean>

  // revoke bot moments
  revokeMoments (momentsId: string): Promise<boolean>

  // revoke bot comments
  revokeComments (momentsId: string): Promise<boolean>

  // revoke bot like
  revokeLike (momentsId: string): Promise<boolean>
```

The model data:

```javascript
Moments {
  comment?: MomentsCommentsDetail[], // for detail
  commentCount: number,
  description: string,
  id: string,
  likeCount: number,
  like?: MomentsLikeDetail[], // for detail
  nickName: string,
  time: number,
  userName: string,
}

MomentsLikeDetail {
  createTime: number,
  nickName: string,
  userName: string,
}

MomentsCommentsDetail {
  createTime: number,
  replyId: number,
  userName: string,
  nickName: string,
  replyNickName: string,
  id: number,
  content: string,
}

MomentsUrlLink {
  contentUrl?: string,
  description?: string,
  title?: string,
}

MomentsMedia {
  thumb: string,
  url: string,
  width?: string,
  height?: string,
  totalSize?: string,
}

MomentsComments {
  toUserName: string,
  comments?: string,
  momentsId: string,
  replyId?: number,
}
```

And I have saw the related issue which @huan created.

```javascript
wechaty.on('moments', ...)
```

Could not supported by underlying protocol, because of they have no Moments stream.

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by su-chang** [comment]
@huan Could you give me some suggestions about Moments design when you are available? Thank you very much.

**Comment by su-chang** [comment]
New design's example for Moments:

- post moments

	```js
	postText (moment: string): Promise<Moments>
	postMedia (moments: MomentsMedia[], text?: string): Promise<Moments>
	postUrlLink (moment: MomentsUrlLink): Promise<Moments>
	```

- get moments time line

	```js
	/*
      For the first time to get the timeline, momentsId = '0', firstPageMd5 = '0'
      If we want to get the new timeline, we should give the momentsId as boundary. We can get firstPageMd5 from the first timeline result.
	*/
	bot.Moments.timeline(momentsId, firstPageMd5) // get all moments
	contact.timeline(momentsId, firstPageMd5) // get all moments of contact
	```

- get moments detail
	```js
	const moments = bot.Moments.moments('xxxx')
	```

- comment or like for moments
	```js
	const moments = bot.Moments.moments('xxxx')
	moments.comment('test comment') // comment this moments
	moments.like() // like this moments
	```
	
- delete moments or like
	```js
	const moments = bot.Moments.moments('xxxx')
	moments.delete()
	moments.dislike()
	```	

Waiting for your review, thank you very much for your time.

**Comment by su-chang** [comment]
Related data structure : https://github.com/wechaty/wechaty-puppet-padplus/wiki/Grpc-Moments-API

**Comment by 1057437122** [comment]
how about delete others' comments?

**Comment by su-chang** [comment]
> how about delete others' comments?

Good question, the method delete other's moments not supported now.

**Comment by su-chang** [comment]
**Question about `timeline()`**

*How to get new moments?*
> I'm not sure about do we need get new moments? or just return all moments instead.
  - add params: `timeline(page: string)`?
  - add new method: `newTimeline()`?

If anyone have good idea about this, please let me know, thank you very much.

**Comment by huan** [comment]
@su-chang It's great to see that you purpose the feature of moments!

I would love to implement the Moments for Wechaty, could you please send a PR with both the wechaty-puppet and wechaty so that I could be able to study your design through the code?

Looking forward to seeing your PR, and let's discuss the design based on the PR soon.

Thank you very much!

**Comment by huan** [comment]
Are there any updates about this project?

I'd like to suggest that we can post any questions & progress by replying to this issue.

**Comment by zavierxu** [comment]
@su-chang @huan  Are there any updates now? Is there anyone working on it now? I hope this feature can be developed ASAP

**Comment by huan** [comment]
As far as I know, currently there's nobody working on it.

Do you want to develop this new features? I believe it will not very hard and could be finished in 1 to 3 days.

**Comment by su-chang** [comment]
## Moment Design Adjust

### Moment Class

```ts
class Moment {
 
  id: string

  payload: MomentPayload

  // get or set coverage

  static coverage(): Promise<FileBox>

  static coverage(image?: FileBox): Promise<boolean>

  // get or set signature

  static signature(): Promise<string>

  static signature(sign: string): Promise<boolean>

  // post moment

  static post (moment: MomentRequestParams): Promise<Moment>

  // moment timeline and owner timeline

  static timeline(listOption: ListOption): Promise<Moment[]>

  static ownerPost(listOption: ListOption): Promise<Moment[]>

  // get moment detail

  momentPayload(): Promise<MomentPayload>

}
```


### Moment Data Structure
```ts
interface MomentRequestParams { // post moment params
  content?: string,
  urlLink?: UrlLinkPayload,
  images?: FileBox[],  
}

interface MomentPayload {
  authorId: string,
  content?: string,
  urlLink?: UrlLinkPayload,
  images?: FileBox[],
  id: string,
  createTime: number,
  updateTime: number,
}

interface ListOption {
  pageSize?: number, // need default value
  currentPage?: number,
  startAfter?: string, // get list start after this key
}
```

## Example

```ts
const moment = await bot.Moment.post(moment)

const comment = await bot.Comment.comment(moment, 'this is moment comment')
await comment.reply('this is moment comment')

await bot.Like.like(moment)
await bot.Like.cancel(moment)

await moment.momentPayload()

await moment.remove()
```

**Comment by su-chang** [comment]
Same question about `Comment` and `Like`, see: https://github.com/wechaty/wechaty/issues/2245#issuecomment-915726584

**Comment by su-chang** [comment]
After [`Post`](https://github.com/wechaty/wechaty/issues/2245) has been designed, we can use `Post` to support `Moment`.

```ts
const momentPost = bot.Post.builder()
.add('moment text')
.add(FileBox.fromUrl('imageUrl_1'))
.add(FileBox.fromUrl('imageUrl_2'))
.build()
const moment = await bot.say(momentPost)

await moment.like(true)
await moment.reply('moment content')
```

And `say()` is not the only method for `Moment`, we have to add other methods:
- set moment signature
- set moment coverage
- remove moment

What do you think about it? @huan

**Question**
WeChat support post video via `Channel` or `Moment`.

What's the difference between post `Channel` and `Moment` in `Post`?

```ts
const post = bot.Post.builder()
.add(FileBox.fromUrl('videoUrl'))
.build()
await bot.say(post)
```

**Comment by huan** [comment]
> set moment signature
  set moment coverage
  remove moment

Do you have any suggestions/draft designs? If so, please share it and we can discuss it.

I guess one of our options should be add some Puppet API interface.

> What's the difference between post Channel and Moment in Post?

Technically speaking, they are all in the same data structure,  just come from different channels.

For example, if we have a `moment` event, then the `Post` from this event, should be a moment; On the other hand, `Post`s come from `channel` event should be video post.

**Comment by su-chang** [comment]
> Do you have any suggestions/draft designs? If so, please share it and we can discuss it.

```ts
class Moment {
  setSignature(text: string)
  setCoverage(url: string)
  remove(id: string)
  
  post(sayable: SayablePayload) // call POST builder and say
}
```

> Technically speaking, they are all in the same data structure, just come from different channels.

The same data structure make puppet implementation hard to call `postMoment(data)` or `postChannel(data)`.

> For example, if we have a moment event, then the Post from this event, should be a moment; On the other hand, Posts come from channel event should be video post.

Agree for receive message from different channel.

**Comment by huan** [comment]
> The same data structure make puppet implementation hard to call postMoment(data) or postChannel(data).

Why? Could you please give some reasons that support the above option? (hard to call ...)

**Comment by su-chang** [comment]
```ts
const post = bot.Post.builder()
.add(FileBox.fromUrl('videoUrl'))
.build()
await bot.say(post)
```
From this example, we don't known it is post `moment` or `channel`.

**Comment by huan** [comment]
I think we can not say a post directly.

We need to create a moment or channel message for the post:

```ts
const serverPost = await Moment.create(post)
await contact.say(serverPost)
```

The `serverPost` will reference all the media via the `messageId` 

Above is the draft design, more details of discussions are welcome.

**Comment by su-chang** [comment]
For `Moment`, I think it's strange that use method `say()` to post moment.

We can reuse `Post.builder()` to create a param for `Moment`, and then use static method `bot.Moment.post()` to post moment.

BTW, the params of `Moment` will re-generate in `Moment.create(post)` for these three cases:

- `text` + n * `image` (0 < n <= 9)
- `video`
- `url link`

I'm learning the new design pattern of wechaty@1.x now, and after that I will create a PR for moment base above design.

**Comment by su-chang** [comment]
@huan I had create PR base on `post` branch, please see the `example/moment.ts` for detail when you are available.

**Comment by huan** [comment]
Thank you very much for starting to design the Moment WUM!

Will take a look at it and feedback to you later.

**Comment by su-chang** [comment]
I would like invite @hcfw007 to join us to discuss the Moment VUM! @hcfw007 please see more info here: [https://github.com/su-chang/wechaty/pull/23](https://github.com/su-chang/wechaty/pull/23), thank you very much.

**Comment by su-chang** [comment]
I would like invite @hcfw007 to join us to discuss the Moment VUM! @hcfw007 please see more info here: [https://github.com/su-chang/wechaty/pull/23](https://github.com/su-chang/wechaty/pull/23), thank you very much.

**Comment by su-chang** [comment]
I would like invite @hcfw007 to join us to discuss the Moment VUM! @hcfw007 please see more info here: [https://github.com/su-chang/wechaty/pull/23](https://github.com/su-chang/wechaty/pull/23), thank you very much.

**Comment by huan** [comment]
That's great!

And I'd also like to learn the `Post` data structure examples for encapsulating the 5G RCS messages, do we have any plan for that?

**Comment by hcfw007** [comment]
In my opinion, the userName, nickName and other contact-related properties could be replaced by a Contact reference.
e.g.
```
Moments {
  comment?: MomentsCommentsDetail[], // for detail
  commentCount: number,
  description: string,
  id: string,
  likeCount: number,
  like?: MomentsLikeDetail[], // for detail
  time: number,
  issuer: Contact
}
```

**Comment by su-chang** [comment]
> In my opinion, the userName, nickName and other contact-related properties could be replaced by a Contact reference.
> e.g.

Agree, we had make it in `POST` WUM, please learn the `Post` WUM first, and then here is [Draft Design PR](https://github.com/su-chang/wechaty/pull/23) for `moment`.
