### ISSUE TITLE
现在用不了了呀，网页版的api现在不能登陆了

### ISSUE THREAD

**Issue by JackSengKing** [wechaty/wechaty#1881]
![image](https://user-images.githubusercontent.com/29450408/69697355-2aeb2a00-111d-11ea-9e4d-158443c891ff.png)
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by JackSengKing** [comment]
![image](https://user-images.githubusercontent.com/29450408/69697275-02633000-111d-11ea-9dd6-e42bc36812df.png)

**Comment by laoshaw** [comment]
```
11:49:00 WARN PuppetPuppeteerBridge testBlockedMessage() error.ret=1203
11:49:00 INFO PuppetPuppeteerBridge 

        Please see: Account Login Issue <https://github.com/Chatie/wechaty/issues/872>

        
11:49:00 ERR PuppetPuppeteerBridge onLoad() exception: Error: For account security, newly registered WeChat accounts are unable to log in to WeChat for Web. To use WeChat on a computer, you can download WeChat for Windows or WeChat for Mac at http://wechat.com
(node:17154) UnhandledPromiseRejectionWarning: Error: Error: For account security, newly registered WeChat accounts are unable to log in to WeChat for Web. To use WeChat on a computer, you can download WeChat for Windows or WeChat for Mac at http://wechat.com
```

It's a shame Wechat does not support web client for newer accounts. I'm on Linux and now have to use phone to type everything?

**Comment by wangsijie** [comment]
我的老账号也不能，所以即使切换到PuppetMacpro也是用的网页版接口吗

My old account cannot login either, switch WECHATY_LOG to PuppetMacpro still doesn't work.

**Comment by fastlane0220** [comment]
Have the same issue(My account was registered before 2017)
wechaty & puppeteer version:  "dependencies": {
    "puppeteer": "^2.0.0",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^0.22.1"
  }
Run Environment: Mac OS; node version: 12.13.1
See the error msg screen-shot below:
![image](https://user-images.githubusercontent.com/15046625/70059388-a7996f00-161b-11ea-8d1d-bb13bac45995.png)

**Comment by windmemory** [comment]
Please check https://docs.chatie.io/v/zh/#web-limit-1

**Comment by lijiarui** [comment]
See https://docs.chatie.io/#web-wechat-limitations

**Comment by huan** [comment]
@lijiarui  According to https://github.com/wechaty/PMC/issues/2#issuecomment-555360870, we will close the docs.chatie.io on 31 January 2020.

**Comment by huan** [comment]
Duplicated with #872
