### ISSUE TITLE
I want wechaty puppet padpro token to create a wechat bot

### ISSUE THREAD

**Issue by acid-tech** [wechaty/wechaty#1882]
I have connected with **botorange2** on wechat. As per the suggestion I got from him, I am creating this issue to get a token with the template information as follows:

1. Introduce Yourself(who you are): developer of a startup
2. Explain the Problem You Want to Solve:(what you do): Message listening for Some companies
3. Your Email: yash@acid-tech.com
4. Your Wechat: meghal_132
5. I Had Joined the Wechaty Developers' Home Wechat Room: YES
6. I understand that the Wechaty v0.15 is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: YES

Goal: To monitor messages of wechat for my organization.

**Comment by su-chang** [comment]
We have received your email, and will have a meeting with you at 2 p.m. tomorrow. 

Please close this issue and see you tomorrow, thank you.

**Comment by acid-tech** [comment]
Sure, Can you please confirm your timezone for the meeting?
I am in India and my timezone is IST.

**Comment by su-chang** [comment]
OK, the meeting time: 06:00:00(UTC), are you free at that time?

**Comment by acid-tech** [comment]
I am confirming the timing as 6 a.m. (UTC) which will be 11:30 a.m IST. I am comfortable with this timings.
Please confirm it from your side so that I can close the issue.

**Comment by su-chang** [comment]
Confirmed! Thank you.

**Comment by acid-tech** [comment]
See you in the meeting.
Will use the meeting ID which I got after registration on Calendly.
Thanks.
