### ISSUE TITLE
主动撤回消息

### ISSUE THREAD

**Issue by SilentQianyi** [wechaty/wechaty#1885]
**Is your feature request related to a problem? Please describe.**
实现主动撤回消息功能。

**Describe the solution you'd like**
在message中增加撤销消息api

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by SilentQianyi** [comment]
在底层实现中所需参数

> {
>&nbsp;&nbsp; fromUserName: string, 
>&nbsp;&nbsp; msgId: string,
>&nbsp;&nbsp; toUserName: string
> }

因为三个参数都必须拥有，其中toUserName是接收方id，所以需要receiver参数。

**Comment by SilentQianyi** [comment]
wechaty：
    在message中实现recall方法，返回值是boolean类型。
```js 
public async recall (): Promise<boolean>
```
wechaty-puppet:
receiver: 需要撤回消息的接收方，messageId: 需要撤回的消息id
```js 
public async messageRecall (receiver: Receiver, messageId: string): Promise<boolean>
```
wechaty-puppet-padplus:
selfId: 自己的id，receiverId: 需要撤回消息的接收方，messageId: 需要撤回消息的消息id
```js
public async recallMessage (selfId: string, receiverId: string, messageId: string): Promise<boolean>
```
在该方法中需要调用底层方法，需要参数：
```js
{
  fromUserName: string, 
  msgId: string,
  toUserName: string
}
```
返回值：
```js
成功：
{
  "BaseResponse": {
    "Ret": 0,
    "ErrMsg": "已撤回"
  }
}

超时：
{
  "BaseResponse": {
    "Ret": -430,
    "ErrMsg": "该消息超过撤回时间，不能被撤回。"
  }
}
```

**Comment by huan** [comment]
This feature had been merged and will be available with Wechaty on v0.29.30 or above.

Cloud you please let us know which version of what puppet will support this new feature?

Thank you very much.

**Comment by SilentQianyi** [comment]
Wechaty: on v0.29.25 or above

**Comment by huan** [comment]
Thank you very much for the update!

Please feel free to close this issue if it has been resolved.
