### ISSUE TITLE
延期通过好友

### ISSUE THREAD

**Issue by SilentQianyi** [wechaty/wechaty#1890]
**Is your feature request related to a problem? Please describe.**
可以延期通过好友，可以存储好友请求

**Describe the solution you'd like**
在friendship中增加getPayload()方法，来获取好友请求的详细数据
在friendship中增加build()方法，通过payload数据来补充friendship数据

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by SilentQianyi** [comment]
wechaty：
在friendship中实现getPayload方法, 返回friendship的payload。
```js
public async getPayload (): Promise<FriendshipPayload>
```
在friendship中实现build方法, 传入需重新创建的payload。
```js
public async build (friendshipPayload: FriendshipPayload): Promise<void>
```

wechaty-puppet:
判断缓存中是否已经存在该payload，不存在时进行存储。
```js
public async friendshipBuild (friendshipPayload: FriendshipPayload): Promise<FriendshipPayload | void>
```
wechaty-puppet-padplus:
将传入的payload 进行存储。
```js
protected async friendshipSavePayload (friendship: FriendshipPayload): Promise<FriendshipPayload | void>
```

**Comment by SilentQianyi** [comment]
example: 
```js
const bot = new Wechaty()
bot.on('friendship', async friendship => {
  try {
    const payload = await friendship.getPayload()
    const newFriendship = bot.FriendShip.load(payload.id)
    await newFriendship.ready()
    if (!newFriendship.isReady()) {
      newFriendship.build(payload)
    }
    newFriendship.build(payload)
  } catch (e) {
    console.error(e)
  }
})
.start()
```

**Comment by windmemory** [comment]
I think we could use `fromJson` and `toJson` to accomplish this.

```ts
bot.on('friendship', async friendship => {
  const friendshipToBeSaved = friendship.toJson()
  saveFriendship(friendshipToBeSaved)
})

const friendshipFromDisk = getFriendshipFromDisk()
const friendship = bot.Friendship.fromJson(friendshipFromDisk)
await friendship.accept()
```

**Comment by SilentQianyi** [comment]
wechaty：
在friendship中实现toJson方法, 将friendship的payload转成的 Json格式 返回。
```js
public async toJson (): Promise<string>
```
在friendship中实现静态方法fromJson, 通过传入Json格式的payload 来获得Friendship。
```js
public static async fromJson (friendshipJson: string): Promise<Friendship>
```

wechaty-puppet:
调用friendshipPayloadSave, 调用成功后将payload数据存入缓存。
```js
public async friendshipSave (friendshipPayload: FriendshipPayload): Promise<FriendshipPayload | void>
```
wechaty-puppet-padplus:
将传入的payload 进行存储，并返回payload。
```js
protected async friendshipPayloadSave (payload: any)  : Promise<FriendshipPayload | void>
```

**Comment by SilentQianyi** [comment]
example : 
在接收到好友请求时，我们可以将好友请求 通过toJson 函数，获得Json格式的payload。在我们需要的时候，可以将存储在本地的Json格式payload 传入静态方法 fromPayload 来获得Friendship。之后我们就可以对Friendship 进行操作。
```js
const bot = new Wechaty()
bot.on('friendship', async friendship => {
  try {
    if (friendship.type === FriendshipType.Receive) {
      const friendshipToBeSaved = await friendship.toJson()
      saveFriendship(friendshipToBeSaved) // 存储payload
    }
  } catch (e) {
    console.error(e)
  }
})
.start()

function async acceptFriend () {
  const friendshipFromDisk = getFriendshipFromDisk()
  const newFriendship = bot.FriendShip.fromJson(friendshipFromDisk)
  await newFriendship.accept()
}
```

**Comment by windmemory** [comment]
@huan 

Any thoughts on this issue? Actually this is similar to https://github.com/wechaty/wechaty/issues/1733

Which way you prefer to solve this problem?

**Comment by SilentQianyi** [comment]
@huan 
Could you give me some advice?

**Comment by SilentQianyi** [comment]
@huan 
What do you think of this issue?
Could you give me some advice?

**Comment by huan** [comment]
Hi, @SilentQianyi @windmemory,

Thank you very much for the feature request, design, and the pull request!

The PR is good and I made some minor changes: add a `set` feature to `puppet.friendshipPayload(id, payload)` so that we can add a payload to puppet when we need to do `fromJSON`

This feature will be available with wechaty@0.29.50 or above.

**Comment by SilentQianyi** [comment]
@huan
When we accept friend, we need the cache in `padplus`. Because there are some properties that  underlying puppet needs to finish the accept friend action, like the `v1` for a contact.
When calling `fromJSON`, the current code only cache in puppet, but not underlying implementation.


Here are two solutions for this problem:

* add another abstract method in puppet. to set the cache into unlderlying puppet layer
* override `friendshipPayload` method in underlying puppet layer to set or get the payload info

Which way you think it the best practice for us to do?

**Comment by huan** [comment]
Thanks for the feedback.

I think we have a third choice: how about let's add the `v1` and `v2` property to the standard ContactPayload? Because it seems that v1 and v2 are quite common for strangers?

For now, I believe you can use choice 2: override the `friendshipPayload` method to archive your needs.

**Comment by 726425219** [comment]
@SilentQianyi  大佬，我最近在研发关于定时通过好友申请的功能，toJSON方法一切顺利，但是在fromJSON时报了异常，在Set the payload back to the puppet for future use时报的异常
