### ISSUE TITLE
room.say() 中参数类型为 TemplateStringsArray 时存在问题

### ISSUE THREAD

**Issue by SilentQianyi** [wechaty/wechaty#1893]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: 0.29.22

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: wechaty-puppet-padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.1.4

- What is your node version? (run `node --version`)
Answer: v10.17.0

- What os are you using
Answer: mac 10.12.6

## 2. Describe the bug
在群内通过 say() 方法 参数类型为 TemplateStringsArray 发送消息，当数组长度为1时报错
## 3. To Reproduce
```js
  bot.on('message', async msg => {
      const room = msg.room()
      if (room) {
        const contact = msg.from()
        const templateStringsArray = [`@${contact.name()} 123`] as any
        target.say(templateStringsArray, contact)
      }
    })
  .start()
```
## 4. Expected behavior
我希望当文本内存在@name的内容时，不会额外增加@name
```js
    // TODO(huan) 20191222 it seems the following code will not happen,
    // becasue it's equal the mentionList.length === 0 situation?
    //
    // } else if (textList.length === 1) {
    //   /**
    //    * Constructed mention string, skip inserting @ signs
    //    */
    //   return this.puppet.messageSendText(
    //     receiver,
    //     textList[0],
    //     mentionList.map(c => c.id),
    //   )
```
这段代码就是处理这种问题的

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
18:33:02 ERR Config ###########################
18:33:02 ERR Config unhandledRejection: Error: Can not say message, invalid Tagged Template. [object Promise]
18:33:02 ERR Config ###########################
18:33:02 ERR Config process.on(unhandledRejection) promise.catch(Can not say message, invalid Tagged Template.)
Config Error: Can not say message, invalid Tagged Template.
    at AnotherOriginalClass.<anonymous> (/Users/apple/Work/weChaty/wechaty/src/user/room.ts:578:15)
    at Generator.next (<anonymous>)
    at /Users/apple/Work/weChaty/wechaty/dist/src/user/room.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/Work/weChaty/wechaty/dist/src/user/room.js:4:12)
    at AnotherOriginalClass.sayTemplateStringsArray (/Users/apple/Work/weChaty/wechaty/dist/src/user/room.js:454:16)
    at AnotherOriginalClass.<anonymous> (/Users/apple/Work/weChaty/wechaty/src/user/room.ts:528:26)
    at Generator.next (<anonymous>)
    at /Users/apple/Work/weChaty/wechaty/dist/src/user/room.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/Work/weChaty/wechaty/dist/src/user/room.js:4:12)
    at AnotherOriginalClass.say (/Users/apple/Work/weChaty/wechaty/dist/src/user/room.js:388:16)
    at /Users/apple/Work/weChaty/my-wechaty-project/index.ts:47:19
    at step (/Users/apple/Work/weChaty/my-wechaty-project/index.ts:33:23)
    at Object.next (/Users/apple/Work/weChaty/my-wechaty-project/index.ts:14:53)
    at /Users/apple/Work/weChaty/my-wechaty-project/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/Work/weChaty/my-wechaty-project/index.ts:4:12)
    at Wechaty.<anonymous> (/Users/apple/Work/weChaty/my-wechaty-project/index.ts:25:27)
    at Wechaty.on.args (/Users/apple/Work/weChaty/wechaty/src/wechaty.ts:553:18)
    at Wechaty.emit (events.js:198:13)
    at Wechaty.EventEmitter.emit (domain.js:448:20)
    at Wechaty.emit (/Users/apple/Work/weChaty/wechaty/src/wechaty.ts:317:18)
    at Wechaty.<anonymous> (/Users/apple/Work/weChaty/wechaty/src/wechaty.ts:661:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/apple/Work/weChaty/wechaty/dist/src/wechaty.js:5:58)
(node:25231) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
18:33:02 SILL PadplusManager setContactAndRoomData() initialize contact and room data.
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by huan** [comment]
I feel very strange when seeing you are using:

```ts
        const templateStringsArray = [`@${contact.name()} 123`] as any
        target.say(templateStringsArray, contact)
```

I believe the template string array should be used like the following code:

```ts
        target.say`${contact} 123`
```

Can you make sure that you are understood the ES6 Template String Array?

Please read https://github.com/wechaty/wechaty/issues/1718#issuecomment-472937224 for more details about it.

**Comment by windmemory** [comment]
@huan  

Originally, we have a console on web page to send text message to wechat. We added a function to allow user input a mentioned text message. But the mention syntax might appear anywhere within the message, and it uses a frontend generated name, so we want to pass in the message with mention syntax as a whole string to wechaty, followed with the real mentioned contact to do the mention operation.

We discussed this offline in California and came up with the solution that we implemented before, and we've been using that for about 9 months.

**Comment by huan** [comment]
Oh, yes, I remembered a little about our conversation before.

However, `const templateStringsArray = [`@${contact.name()} 123`] as any` is not the right way to use our `say` method. It should be changed to following the ES6 TemplateStringsArray if it want to use the `say` method, or we need to open a new discussion later.

**Comment by windmemory** [comment]
I agree that `const templateStringsArray = [`@${contact.name()} 123`] as any` is not the right way, but that's the workaround that we came up before.

Otherwise we need to update our frontend code to parse the text that use inputs, split it with contacts, passed to server, and wechaty will parse that parsed arguments and put them together, then passed to puppet.
Like below:

User inputs:
```
text: Hi @Tom, welcome to join us.
mentionList: wxid_tom
```

Parsed arguments (processed result with frontend code):
```
text array: ['Hi', ', welcome to join us']
mentionList: wxid_tom
```

Code to call wechaty:
```
const templateStringsArray = ['Hi', ', welcome to join us'] as any // ts will complain if an array is passed in as an TemplateStringsArray, so I put as any here
const mentionList = ['wxid_tom'].map(id => bot.Contact.load(id))
await room.say(templateStringsArray, mentionList)
```

Note: I don't know how to call `` say` ` `` with a list of text and a list of contact, that's the only thing that I could pass from frontend.

**Comment by huan** [comment]
I'm very glad that you agree with me that `[] as any` is not the right way.

And as you demonstrated, it's a great solution to this problem.

Using `room.say(templateStringsArray, mentionList)` will be OK because that's how it works.

**Comment by windmemory** [comment]
@huan In that way, we parse the string, then assemble it back, and it might cause some inconsistency during the process. Besides, this is not using the tag template directly, but calling the function, which is not elegant at all. I don't think that is a good solution.

**Comment by huan** [comment]
I understand your situation, and after I think about it, there's a workaround: calling the puppet directly to fulfill your requirement.

When you need to send your message, you can do this:

```ts
wechaty.puppet.messageSendText(
  receiver,
  textList[0],
  mentionList.map(c => c.id),
)
```

In this way, you are calling the underlying puppet private API instead of the public API.

However, it should still be far better than the `[] as any`.

P.S. I have reviewed the code, and I believe as the Wechaty API, we will not consider the situation when `textList.length !== (mentionList + 1)` because if we are using the ```say`` ``` method, it will be always `false`.

**Comment by windmemory** [comment]
Why force all users to use tag template? I think my situation will happen to some other users.

**Comment by huan** [comment]
This pattern I believe is an anti-pattern so it will not be supported by the Wechaty framework.

However, if this use case is a must, please feel free to use `wechaty.puppet.messageSend(...)` to fulfill this requirement.

**Comment by huan** [comment]
BTW: Here's a workaround that helps developers to skip the Wechaty encapsulate and force checking:

See: https://github.com/wechaty/wechaty/issues/1849#issuecomment-580197920

I think it can help this case too.
