### ISSUE TITLE
启动官方学习项目报错

### ISSUE THREAD

**Issue by STDSuperman** [wechaty/wechaty#1898]
18:31:24 ERR PuppetPuppeteerBridge start() exception: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
18:31:24 ERR PuppetPuppeteer initBridge() exception: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
18:31:24 WARN PuppetPuppeteerBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
18:31:24 ERR PuppetPuppeteer start() exception: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
Error: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
    at PuppetPuppeteer.<anonymous> (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPuppeteer.emit (events.js:210:5)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:476:20)
    at PuppetPuppeteer.emit (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PuppetPuppeteer.<anonymous> (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:195:12)
    at Generator.throw (<anonymous>)
    at rejected (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
18:31:24 ERR Wechaty start() exception: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
18:31:24 ERR StarterBot Error: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com

**Comment by llh1187** [comment]
> 18:31:24 ERR PuppetPuppeteerBridge start() exception: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
> 18:31:24 ERR PuppetPuppeteer initBridge() exception: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
> 18:31:24 WARN PuppetPuppeteerBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
> 18:31:24 ERR PuppetPuppeteer start() exception: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
> Error: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
> at PuppetPuppeteer. (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:611:32)
> at PuppetPuppeteer.emit (events.js:210:5)
> at PuppetPuppeteer.EventEmitter.emit (domain.js:476:20)
> at PuppetPuppeteer.emit (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:282:18)
> at PuppetPuppeteer. (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:195:12)
> at Generator.throw ()
> at rejected (/Users/superman/Documents/Node/wechaty-getting-started/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
> 18:31:24 ERR Wechaty start() exception: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com
> 18:31:24 ERR StarterBot Error: Error: Error: Error: net::ERR_PROXY_CONNECTION_FAILED at https://wx.qq.com

你好，请问这个问题解决了吗？

**Comment by llh1187** [comment]
根据我的测试，我这边是因为用了电信的手机热点，开了vpn的pac模式之后就可以了。
