### ISSUE TITLE
在群内发消息网页版微信还是没有提供@成员的接口吗？

### ISSUE THREAD

**Issue by LofWalter** [wechaty/wechaty#190]

**Comment by zixia** [comment]
If anyone know how to @ members in a chat room, please let me know.

Duplicated with #153

**Comment by etnperlong** [comment]
I found an issue about @ members but it may not work
https://github.com/HalfdogStudio/wechat-user-bot/issues/15

**Comment by etnperlong** [comment]
may be you can see this post.
http://reverland.github.io/javascript/2016/01/15/webchat-user-bot/
in function generateReplys

**Comment by zixia** [comment]
It seems there's no this kind of API in wxwebApp for now.
