### ISSUE TITLE
为什么每天凌晨都会掉线啊？

### ISSUE THREAD

**Issue by isnl** [wechaty/wechaty#1901]
为什么每天凌晨都会掉线啊？

**Comment by su-chang** [comment]
Which puppet are you using?

If your answer is `wechaty-puppet-padplus`.

This problem is due to the update of protocal in WeChat, we are fixing this problem now. Thanks for your waiting.

**Comment by isnl** [comment]
oh ! I don't know which puppet I using。mabey it's puppetPuppeteer
![image](https://user-images.githubusercontent.com/35526117/71869329-ad1f3300-314c-11ea-8547-bf6c6b2d8569.png)

it's
![image](https://user-images.githubusercontent.com/35526117/71869209-2cf8cd80-314c-11ea-99d6-7af6f04436c5.png)

**Comment by lianqiang** [comment]
I have the same issue. Hope it could be solved soon.

**Comment by lianqiang** [comment]
FYI I am using `"wechaty-puppet": "^0.16.1"`

**Comment by pauleric** [comment]
我用的web版本第一次登陆后凌晨会自动下线，不重启程序，再扫码登陆后可以保持几天在线，版本是
"wechaty": "^0.28.3"

**Comment by huan** [comment]
I'm using [wechaty-puppet-padplus](https://github.com/wechaty/wechaty-puppet-padplus) and I can confirm that this problem has been fixed this week.

Before this week the session lost every day around 2-5 am, which means the bot logged out every day.

From this week (with the latest version of wechaty-puppet-padplus), this issue has gone.
