### ISSUE TITLE
room.announce()中当参数为空字符串时, 调用获取群公告而不是设置群公告为空

### ISSUE THREAD

**Issue by SilentQianyi** [wechaty/wechaty#1902]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: v0.29.32

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: wechaty-puppet-padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: v0.3.2

- What is your node version? (run `node --version`)
Answer: v10.17.0

- What os are you using
Answer: mac 10.12.6

## 2. Describe the bug
我想要设置群公告为空，但是当传入空字符串的时候，仅仅是获取群公告，而不是设置群公告为空

## 3. To Reproduce
1. run '...'
2. ...
3. ...

## 4. Expected behavior
我希望有个一个专门的参数类型，用来处理清空群公告。对空字符也能进行一些处理。

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by huan** [comment]
I believe this is the problem that introduced from the method `Room.annnounce()` in Wechaty, and which should be fixed in the latest commit.
