### ISSUE TITLE
Use docker to run, QR code address prompt "unrecognized QR code"

### ISSUE THREAD

**Issue by Jesn** [wechaty/wechaty#1905]
[question]

Use docker to run, QR code address prompt "unrecognized QR code"
`docker run -ti --name=mybot --rm -v="$(pwd)":/bot zixia/wechaty mybot.js`

 
![image](https://user-images.githubusercontent.com/5728274/73507409-d06b9400-4413-11ea-8cd0-cf686539e208.png)

![image](https://user-images.githubusercontent.com/5728274/73507382-bd58c400-4413-11ea-8b4c-defe4b8ec270.png)

**Comment by huan** [comment]
In order to scan the login QR Code, you should not visit the QR Code URL directly.

Instead, use the following code to show you are QR Code which value is that URL:

https://github.com/wechaty/wechaty-getting-started/blob/f6697da38d341a857646fed1a2fb8cbcd462475a/examples/starter-bot.ts#L15-L24

**Comment by Jesn** [comment]
thx!

**Comment by ashq3** [comment]
bingo! thx!
