### ISSUE TITLE
Support Encode & Decode QR Code functions from file-box@0.10

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1907]
In order to deal with the QR Code image file convenience, we start supporting the following two new methods in the FileBox v0.10:

### `FileBox.fromQRCode(qrCodeValue: string)`

Get a FileBox instance that represent a QR Code value.

```ts
const fileBox = FileBox.fromQRCode('https://github.com')
fileBox.toFile('qrcode.png')
```

### `fileBox.toQRCode(): Promise<string>`

Decode the QR Code value from the file.

```ts
const fileBox = FileBox.fromFile('qrcode.jpg')
const qrCodeValue = await fileBox.toQRCode()
console.log(`QR Code decoded value is: "${qrCodeValue}"`)
// Output: QR Code decoded value is: "https://github.com"
```

I hope you will enjoy it!

**Comment by huan** [comment]
fileBox.toQRCode(): Promise<string>

**Comment by su-chang** [comment]
It's really helpful for get room qrcode, we change the result of `room.qrcode()` from qrcode buffer to qrcode link in padplus these days, so if user want to get the image of qrcode, they should transfer it with some third-part modules. Now they could do it by `FileBox.fromQRCode(qrcodeLink)`.

Perfect!

**Comment by huan** [comment]
I'm glad to close this issue because the new FileBox seems working great!
