### ISSUE TITLE
FileBox version incompatible across wechaty wechaty-puppet and wechaty-puppet-x 

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty#1914]
Recently I was trying to link `wechaty`, `wechaty-puppet` and `wechaty-puppet-padplus` together to debug an issue, then some errors complains about `FileBox` instances are not compatible. Then I found the `FileBox` version in `wechaty` is different from the one in `wechaty-puppet` and `wechaty-puppet-padplus`. 

I would suggest that we move the `FileBox` dependency in each package to `wechaty-puppet`, and import the `FileBox` from `wechaty-puppet`, thus the dependency will have a unique version and source, and we can avoid the version incompatible issue in the future.

**Comment by huan** [comment]
Thank you very much for your great suggestion! I believe it will help us in the future, especially for the new developers.

And I also export `FileBox` from `wechaty` as well, so we should import `FileBox` from `wechaty` as the following:

```ts
import { FileBox } from 'wechaty'
```

Then the developers will be guaranteed the FileBox is good for using.
