### ISSUE TITLE
Can not create Image class.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#1922]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: 0.32.2

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.5.18

- What is your node version? (run `node --version`)
Answer: 10.16.0

- What os are you using
Answer: Mac os

## 2. Describe the bug
Give a clear and concise description of what the bug is.

Image class can not be instanciated directly!

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run receive an image message
2. call message.toImage() method

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
18:16:17 VERB Message toImage() for message id: 8076004588539345100
18:16:17 VERB Image static create(8076004588539345100)
18:16:17 SILL Accessory #7<[object Object]> constructor()
18:16:17 VERB Image constructor(8076004588539345100)
18:16:17 ERR Config ###########################
18:16:17 ERR Config unhandledRejection: Error: Image class can not be instanciated directly! See: https://github.com/wechaty/wechaty/issues/1217 [object Promise]
18:16:17 ERR Config ###########################
18:16:17 ERR Config process.on(unhandledRejection) promise.catch(Image class can not be instanciated directly! See: https://github.com/wechaty/wechaty/issues/1217)
Config Error: Image class can not be instanciated directly! See: https://github.com/wechaty/wechaty/issues/1217
    at new Image (/Users/suchang/Desktop/PROJECT/Test/testPadplus/wechaty/src/user/image.ts:27:13)
    at Function.create (/Users/suchang/Desktop/PROJECT/Test/testPadplus/wechaty/src/user/image.ts:38:19)
    at AnotherOriginalClass.toImage (/Users/suchang/Desktop/PROJECT/Test/testPadplus/wechaty/src/user/message.ts:986:31)
    at UtilFunctions.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPadplus/functions.ts:108:35)
    at Generator.next (<anonymous>)
    at /Users/suchang/Desktop/PROJECT/Test/testPadplus/functions.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/suchang/Desktop/PROJECT/Test/testPadplus/functions.ts:3:12)
    at UtilFunctions.processMessageByDifferentType (/Users/suchang/Desktop/PROJECT/Test/testPadplus/functions.ts:111:16)
    at Object.<anonymous> (/Users/suchang/Desktop/PROJECT/Test/testPadplus/index.ts:90:21)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/suchang/Desktop/PROJECT/Test/testPadplus/index.ts:4:58)
(node:10370) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
```

</details>

## 7. Additional context

[bug]

**Comment by huan** [comment]
Related to #1217

**Comment by huan** [comment]
Thank you very much to figure it out and the fix!
