### ISSUE TITLE
how to get contact avatar in room

### ISSUE THREAD

**Issue by LukeDev2K** [wechaty/wechaty#1923]
🚨 The issue tracker is not for questions 🚨

seems there is no api for this feature,

**Comment by huan** [comment]
Thanks for asking.

I just found that this method missed the jsdoc so it has not been documented before.

Please see: <https://wechaty.github.io/wechaty/#Room+avatar>

**Comment by huan** [comment]
Thanks for asking.

I just found that this method missed the jsdoc so it has not been documented before.

Please see: <https://wechaty.github.io/wechaty/#Room+avatar>
