### ISSUE TITLE
scan方法会执行多次

### ISSUE THREAD

**Issue by fg607** [wechaty/wechaty#1933]
每次运行后scan方法执行了4次，会重复生成4次二维码

**Comment by huan** [comment]
The `scan` event will be fired with different `status` code.

You can find the `ScanStatus` enum from here:

https://github.com/wechaty/wechaty-puppet/blob/443c5705d3b348b0616172ad7da205d4612fa0d2/src/schemas/event.ts#L5-L12

See also: <https://wechaty.github.io/wechaty/#Wechaty+on>

**Comment by fg607** [comment]
@huan Before i have scanned the QR code,the scan event fired with different status  code 1(Cancel) and 4(Confirmed) in sequence，but with the same QR code . What's  the meaning of status code 1 and 4 ?  I'm so  confused about the code 1.Shuold i just show user the QR code in code 4 ?

**Comment by huan** [comment]
It depends on what puppet you are using.

I'm not sure what differences between the different implementation, so it will be better to read the related source code by yourself for your confirmation.

**Comment by fg607** [comment]
@huan Got it ! Thanks!
