### ISSUE TITLE
why can't find a user by weixinId

### ISSUE THREAD

**Issue by liangzhaoliang95** [wechaty/wechaty#1935]
why can't find a user by weixinId

**Comment by su-chang** [comment]
I think you should to have pre-knowledge about these two conceptions:

**WeChat ID**

- could see it in WeChat App
- named by the owner (If we do not set it, it will be same as `wxid`)
- only could be modified once time

**WXID**

- could not see it in WeChat App
- generate by the system (e.g.  `wxid_xxxxxxxxxxx`)

In Wecahty, we make `wxid` as the key of `Contact`.

```js
Contact {
  id: string, // wxid
  ...
  weixin: string // WeChat ID
}
```

**Solution**
Maybe `bot.Contact.findAll()` and `filter()` could help you to search contact by `WeChat ID`.
```js
function searchContactByWeChatID (wechatId) {
  return bot.Contact.findAll().filter(contact => contact.weixin === wechatId)
}
```

**Comment by liangzhaoliang95** [comment]
thank you
