### ISSUE TITLE
New version release notes for wechaty 0.38

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#1937]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: 0.32.5

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:0.6.0

- What is your node version? (run `node --version`)
Answer:10.16.0

- What os are you using
Answer: MacOS

## 2. Describe the bug
Give a clear and concise description of what the bug is.

The breaking change in `wechaty-puppet` should be release a new even version to match the `wechaty-puppet-padplus@latest` version. So does `wechaty`.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Now `wechaty@latest` is not match `wechaty-puppet-padplus@latest`.

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

`wechaty@latest` could match `wechaty-puppet-padplus@latest` and work all right.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Related PRs : https://github.com/wechaty/wechaty/pull/1936, https://github.com/wechaty/wechaty-puppet/pull/92

**Comment by su-chang** [comment]
Related issues : https://github.com/wechaty/wechaty-puppet-padplus/issues/192, https://github.com/wechaty/wechaty-puppet-padplus/issues/204

**Comment by huan** [comment]
## [v0.38](https://github.com/wechaty/wechaty/tree/v0.38) (2020-04-08)

[Full Changelog](https://github.com/wechaty/wechaty/compare/v0.30...v0.38)

**Implemented enhancements:**

- BREAKING CHANGE: Remove `MessageUserQueryFilter` [\#1929](https://github.com/wechaty/wechaty/issues/1929)
- Simplify the Accessory class logic [\#1924](https://github.com/wechaty/wechaty/issues/1924)
- Update Docker Base Image form Ubuntu:18 to Ubuntu:19 [\#1920](https://github.com/wechaty/wechaty/issues/1920)
- wechaty dependency modules deep cleaning [\#1917](https://github.com/wechaty/wechaty/issues/1917)
- FileBox version incompatible across wechaty wechaty-puppet and wechaty-puppet-x  [\#1914](https://github.com/wechaty/wechaty/issues/1914)
- Publish Wechaty Document Site to https://wechaty.js.org [\#1912](https://github.com/wechaty/wechaty/issues/1912)
- Support Encode & Decode QR Code functions from file-box@0.10 [\#1907](https://github.com/wechaty/wechaty/issues/1907)
- Design an new `Image` class for receive images with different sizes. [\#1871](https://github.com/wechaty/wechaty/issues/1871)
- Integrate Wechat with Matrix with the power of Wechaty [\#1737](https://github.com/wechaty/wechaty/issues/1737)

**Fixed bugs:**

- Can not create Image class. [\#1922](https://github.com/wechaty/wechaty/issues/1922)

**Closed issues:**

- 微信退出登录后，重新登录不了ipad [\#1839](https://github.com/wechaty/wechaty/issues/1839)
- 基于padpro协议不能发送微信小程序 [\#1837](https://github.com/wechaty/wechaty/issues/1837)

**Merged pull requests:**

- 0.38.0 [\#1936](https://github.com/wechaty/wechaty/pull/1936) ([su-chang](https://github.com/su-chang))
- Remove MessageUserQueryFilter [\#1931](https://github.com/wechaty/wechaty/pull/1931) ([huan](https://github.com/huan))
- \[Snyk\] Upgrade state-switch from 0.6.18 to 0.7.2 [\#1928](https://github.com/wechaty/wechaty/pull/1928) ([snyk-bot](https://github.com/snyk-bot))
- \[Snyk\] Upgrade brolog from 0.3.11 to 0.4.3 [\#1925](https://github.com/wechaty/wechaty/pull/1925) ([snyk-bot](https://github.com/snyk-bot))
- Image bug [\#1921](https://github.com/wechaty/wechaty/pull/1921) ([su-chang](https://github.com/su-chang))
- File box [\#1915](https://github.com/wechaty/wechaty/pull/1915) ([su-chang](https://github.com/su-chang))
- Support message.toImage\(\) method. [\#1913](https://github.com/wechaty/wechaty/pull/1913) ([su-chang](https://github.com/su-chang))
- Support delay to accept room invitation [\#1910](https://github.com/wechaty/wechaty/pull/1910) ([su-chang](https://github.com/su-chang))
