### ISSUE TITLE
在ready事件后获取  以及ready事件数据全部加载完成后的每一次心跳事件获取所有群都会固定缺失

### ISSUE THREAD

**Issue by windy-gf** [wechaty/wechaty#1945]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by JesseWeb** [comment]
Just like your WeChat App. You can’t load a non-spoken room until someone say something in that room.

**Comment by windy-gf** [comment]
> 但是有一个群我明明这天有说过话 还是没有获取到 反而一个将近一年没说过话的群都获取到了

**Comment by JesseWeb** [comment]
Due to the elusive rules of Wechat. The contributors still trying to catch more without any official protocol(there is no protocol exist). Hope we can evolve this project soon.
