### ISSUE TITLE
How to filter official account numbers

### ISSUE THREAD

**Issue by STDSuperman** [wechaty/wechaty#1951]
How to filter official account numbers

**Comment by su-chang** [comment]
```js
contact.type() : ContactType

export enum ContactType {
  Unknown = 0,
  Personal,
  Official,
}
```

**Comment by STDSuperman** [comment]
> ```js
> contact.type() : ContactType
> 
> export enum ContactType {
>   Unknown = 0,
>   Personal,
>   Official,
> }
> ```

thank you
