### ISSUE TITLE
node-pre-gyp WARN 

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty#1953]
![image](https://user-images.githubusercontent.com/1160703/80323745-cb29b400-885f-11ea-8b7e-d740aa3e9c4d.png)
总是出现这个，build grpc时也有一些编译红字
···
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v83-linux-x64-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.2 and node@14.0.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
···

**Comment by su-chang** [comment]
Please downgrade your node version to `v10.16.0` and then try it again.

**Comment by guoxiangke** [comment]
Thanks, Fixed by 
```
FROM node:10
```
in Dockerfile
