### ISSUE TITLE
friendship.contact() will load Contact only, contact.ready() is wanted.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#1954]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:0.39.14

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:0.7.15

- What is your node version? (run `node --version`)
Answer:10.16.0

- What os are you using
Answer:Mac OS 10.15.4 

## 2. Describe the bug
Give a clear and concise description of what the bug is.

I think it is better to add `contact.ready()` in `friendship.contact()` method, rather than let users to sync the contact in friendship event by themselves.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. start the bot
2. send a friend request to the bot
3. try to print `friendship.contact()`

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

No need to sync it by us, let wechaty do it.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

We need sync contact if we want to get the contact detail info not the only id.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Resolved.

**Comment by huan** [comment]
Please have a test on the newly published wechaty-puppet-hostie npm and make sure the bug has been fixed before we close this issue again.

**Comment by su-chang** [comment]
We discussed this issue based on `wechaty` and `wechaty-puppet-padplus`. The point of this issue: we can not load Contact payload. But it has contactId. This step is before `friendship.accept()`.

For `wechaty-puppet-hostie`, both problems existed on it.

I will test it after we merge this PR: https://github.com/wechaty/wechaty-puppet-hostie/pull/38.

**Comment by huan** [comment]
Great to see we have updated the hostie to fix this issue!

Please feel free to close this issue after you confirmed it has been fixed, thank you very much!

**Comment by su-chang** [comment]
Resolved!
