### ISSUE TITLE
mentionSelf question

### ISSUE THREAD

**Issue by sunshinearea** [wechaty/wechaty#1969]
[question]
I use wechaty API of .mentionSelf() && .self() to judge wheather the message is mention me,most of time is
worked correct,but sometimes  is return false when  the message is really mention for me,the way of mention is through input "@" word and automatic popup list  of wechat group,then  select some contact.

the following code:
![image](https://user-images.githubusercontent.com/15757462/81525309-db28b400-9386-11ea-98c9-c6e331eeccd1.png)

**Comment by huan** [comment]
This issue might exists. It's highly depends on what puppet protocol you use, and what Wechat client the user who mentioned you are using.

**Comment by sunshinearea** [comment]
I use wechaty-puppet-padplus,the Wechat client is on Mac or iOS,your means the client should on iPad?

**Comment by huan** [comment]
I can confirm the following setting can reproduce this issue:

1. Bot Puppet: padplus
1. User client: Macos WeChat
1. Steps: user mention bot in a room, mentionSelf not works.

Please confirm your environment with the details information like mine to reproduce this issue to help us make this problem clearer.

Thank you very much!

**Comment by sunshinearea** [comment]
ok!As mentioned above：
1.Bot Puppet: padplus
2.User client: Macos WeChat
3.Steps: user mention bot and a question in a room, mentionSelf not works.the message such as "@bot question",This is not inevitable in the same environment,I met this problem three times today.

**Comment by su-chang** [comment]
@huan @sunshinearea 
I‘m working on this issue, could you please provide some detail info for this issue? I can not reproduce this problem.

1. Bot Puppet: wechaty-puppet-padplus@0.6.3
2. User client: Macos WeChat@2.3.31 (13292)
3. Steps: user mention bot in a room, `mentionSelf()` works.

My Log:
```
10:24:39 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
10:24:39 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1589250277026,"FileName":"<msgsource>\n\t<atuserlist>wxid_orp7dihe2pm112</atuserlist>\n\t<silence>0</silence>\n\t<membercount>3</membercount>\n</msgsource>\n","NewMsgId":8539760895582207996,"FromMemberUserName":"Soul001001","msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":1,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"8539760895582207996","MsgSource":"<msgsource>\n\t<atuserlist>wxid_orp7dihe2pm112</atuserlist>\n\t<silence>0</silence>\n\t<membercount>3</membercount>\n</msgsource>\n","PushContent":"苏畅12在群聊中@了你","fromMemberNickName":"苏畅12","ImgBuf":"","FromMemberNickName":"苏畅12","fromMemberUserName":"Soul001001","Content":"Soul001001:\n@jessicaTu hai","FromUserName":"21529888566@chatroom","Uin":"289099750"}
10:24:39 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

10:24:39 SILL PuppetPadplus roomRawPayload(21529888566@chatroom)
10:24:39 SILL PuppetPadplus onPadplusMessageFriendshipEvent({id=8539760895582207996})
10:24:39 VERB Message static load(8539760895582207996)
10:24:39 SILL Accessory #4<Message> constructor()
10:24:39 VERB Message constructor(8539760895582207996) for class Message
10:24:39 VERB Message ready()
10:24:39 SILL PuppetPadplus messageRawPayload(8539760895582207996)
10:24:39 SILL PuppetPadplus messageRawPayloadParser()
10:24:39 SILL messageRawPayloadParser messageType 7
10:24:39 SILL Accessory #5<Room> constructor()
10:24:39 SILL Room constructor(21529888566@chatroom)
10:24:39 VERB Room ready()
10:24:39 SILL PuppetPadplus roomRawPayload(21529888566@chatroom)
10:24:39 SILL PuppetPadplus roomRawPayloadParser()
10:24:39 SILL PuppetPadplus roomMemberList(21529888566@chatroom)
10:24:39 SILL Accessory #6<Contact> constructor()
10:24:39 SILL Contact constructor(wxid_orp7dihe2pm112)
10:24:39 SILL Accessory #7<Contact> constructor()
10:24:39 SILL Contact constructor(wxid_atjcz7dvaxn422)
10:24:39 SILL Contact ready() @ Puppet#0<PuppetPadplus>(tu) with id="Soul001001"
10:24:39 SILL Contact ready() @ Puppet#0<PuppetPadplus>(tu) with id="wxid_orp7dihe2pm112"
10:24:39 SILL Contact ready() @ Puppet#0<PuppetPadplus>(tu) with id="wxid_atjcz7dvaxn422"
10:24:39 SILL Contact ready() @ Puppet#0<PuppetPadplus>(tu) with id="Soul001001"
10:24:39 SILL PuppetPadplus contactRawPayloadParser()
10:24:39 SILL PuppetPadplus contactRawPayloadParser()
10:24:39 SILL PuppetPadplus contactRawPayloadParser()
10:24:39 SILL Contact ready() @ Puppet#0<PuppetPadplus>(tu) with id="wxid_orp7dihe2pm112"
10:24:39 SILL Contact ready() isReady() true

    ============================================
    on message : {"domain":null,"_events":{},"_eventsCount":0,"id":"8539760895582207996","payload":{"id":"8539760895582207996","timestamp":1589250277.026,"type":7,"fromId":"Soul001001","mentionIdList":["wxid_orp7dihe2pm112"],"roomId":"21529888566@chatroom","text":"@jessicaTu hai","toId":"wxid_orp7dihe2pm112"}}
    ============================================

10:24:39 VERB Message mentionList()
10:24:39 SILL Contact ready() @ Puppet#0<PuppetPadplus>(tu) with id="wxid_orp7dihe2pm112"
10:24:39 SILL Contact ready() isReady() true

      The bot has been memtioned in the room: Room<Create Room 693>
```

**Comment by huan** [comment]
@su-chang thanks for looking into this.

My situation is that on my Macos client it does not work, however I know some friends that their Macos client works without any problem.

I'll post my Macos WeChat client version later

**Comment by sunshinearea** [comment]
@su-chang hello:
This is my situation :
1.Bot Puppet: wechaty-puppet-padplus@0.6.1
2.User client: Macos WeChat@Version. 2.3.31 (13331)

**Comment by su-chang** [comment]
@sunshinearea Could you please upgrade your WeChat to v2.4.1 (14470, _This is the new version for Mac OS_) in Mac OS, and have a test again. Waiting for your response.

Thank you very much.

**Comment by huan** [comment]
My MacOS WeChat Version 2.3.29 (13326)

**Comment by sunshinearea** [comment]
@su-chang I can upgrade my WeChat's version,but i can't ensure other client version that sends me the message to my wechaty bot in the group,how can this situation be resolved?

**Comment by su-chang** [comment]
Understand, you are right, I will collect some WeChat version info and try to fix it.

Thanks for your response.

**Comment by HolmanHuang** [comment]
@su-chang @huan @su-chang 
i got the similar situation, and after 2 hours debug,  i think the reason is
1. selfId is stored as the original WXID like  **wxid_t909c6jrfsxx**
2. the contact => contact.id may come like **wxid_t909c6jrfsxx** -- **success**
3. or, use the updated one like "**mywxid**" as example  --- **failed**

my solution is 
```
  public async mentionSelf (): Promise<boolean> {
    const mentionList = await this.mentionList() // mywxid or wxid_t909c6jrfsxx 
    const selfId = this.puppet.selfId()  // mywxid    
    if (mentionList.some(contact => contact.id === selfId) ) {
     return true;
     }
     const selfIdorg = this.puppet.selfIdorg()  // wxid_t909c6jrfsxx    
     if (mentionList.some(contact => contact.id === selfId) ) {
     return true;
     }
     return false;
  }
```
