### ISSUE TITLE
Wanted a middleware to manage OA account which is not start with 'gh_'

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#1974]
**Is your feature request related to a problem? Please describe.**

Some OA account which our user can not know all of them, and when we get some message from them, some mistake response message will make our bot crazy! And also take a high risk to our WeChat account.

**Describe the solution you'd like**

A smart wechaty middleware which could skip all of them messages which we do not want, and we could also add a white list for it.

**Describe alternatives you've considered**

We need a list like that: 
```
exceptid = ['newsapp', \
"weixin", \
"qqmail", \
"filehelper", \
"fmessage", \
"tmessage", \
"qmessage", \
"lbsapp", \
"qqsync", \
"floatbottle", \
"shakeapp", \
"medianote", \
"newsapp", \
"weibo", \
"weixinguanhaozhushou", \
"feedsapp", \
"qqsafe", \
"mphelper", \
"cmb4008205555", \
"meituanwx"]
```

the list is copy from [here](https://github.com/juguang2018/wequick/blob/0be069dce09ff51a6a9a08c555ead631c17afc05/demo/python/const.py)

And we could keep it open source, and let more and more contributor to expand it.

**Additional context**

[enhancement]

**Comment by lijiarui** [comment]
maybe we can add a function like this:

```
function checkOfficial (id: string):boolean {
  const exceptidList = [
    'newsapp',
    'weixin',
    'qqmail',
    'filehelper',
    'fmessage',
    'tmessage',
    'qmessage',
    'lbsapp',
    'qqsync',
    'floatbottle',
    'shakeapp',
    'medianote',
    'newsapp',
    'weibo',
    'weixinguanhaozhushou',
    'feedsapp',
    'qqsafe',
    'mphelper',
    'cmb4008205555',
    'meituanwx']

  if (/^gh_/.test(id) || exceptidList.indexOf(id) > -1) {
    return true
  }

  return false
}

```

**Comment by huan** [comment]
https://github.com/HalfdogStudio/wechat-user-bot/issues/10#issuecomment-172181796
https://github.com/EricCen/wechat-robot/blob/master/src/main/java/me/biezhi/wechat/Constant.java#L20

**Comment by lijiarui** [comment]
We can publish a npm package here: https://github.com/wechaty/wechaty-type

**Comment by huan** [comment]
Awesome! It's a great package and I believe that all puppet should dependence it for identifying the ID types.

BTW the WeChat system now allows the official account to customize their ID to any strings. So I believe we should try to find more robust way to identical the OA account other than depending the string features and the hard coded list.
