### ISSUE TITLE
Send card links that display different issues on different platforms

### ISSUE THREAD

**Issue by sunshinearea** [wechaty/wechaty#1987]
I used wechaty to send card links, but they were not displayed properly on MAC WeChat.

wechaty:0.38.4
Bot Puppet: padplus 0.6.1
User client: Macos WeChat（Version. 2.4.1 (14485)）、iOS Wechat(Version7.0.12)
Steps: 
1.Send card links that display different issues on different platforms
2.My urlLink params
link:{
                    description : 'xxxxxxx',
                    title       : 'xxxx',
                    url         : 'https://big-data.rxhui.com/#/home',
                    thumbnailUrl: 'https://rxhui-corpus.oss-cn-beijing.aliyuncs.com/fileupload/2020052517/576d2766133e4c35b70e7911402dfb99.png',
}

3.thumbnail can be displayed normally on iOS platform,but it cannot be displayed on the computer side
the screenshots:
iOS:
![image](https://user-images.githubusercontent.com/15757462/82993286-e9d3c400-a032-11ea-901c-d3b14e9142da.png)

MAC:
![image](https://user-images.githubusercontent.com/15757462/82994583-f8bb7600-a034-11ea-95c8-5d068f6c1b3a.png)

**Comment by sunshinearea** [comment]
I saw that there was also a problem with the card link of sending Github problem in the Wechaty Developers' Home group before, but it is normal now. Is there any configuration that has been modified? How do I set it up so that it can be displayed normally on both PC and mobile

**Comment by huan** [comment]
As far as I know, there's one possible reason for your issue: the image will have issues to display when your network is slow or can not connect to the image server.

Just FYI.

**Comment by sunshinearea** [comment]
I know what you mean, but the problem is not incidental, picture address is https://rxhui-corpus.oss-cn-beijing.aliyuncs.com/fileupload/2020052517/576d2766133e4c35b70e7911402dfb99.png, I've tested, the iOS devices, android devices and Windows WeChat client access is normal, only on the MAC client is never show success

**Comment by sunshinearea** [comment]
Is it related to my puppet?
