### ISSUE TITLE
微信安装

### ISSUE THREAD

**Issue by zmy17624559888** [wechaty/wechaty#1990]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]这是怎么安装的有详细加成没有？

**Comment by zmy17624559888** [comment]
详细的教程

**Comment by lijiarui** [comment]
See:

- http://github.com/wechaty/wechaty-getting-started
- http://wechaty.js.org/
