### ISSUE TITLE
To simplify the mention logic in message (@)

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1991]
We have a very long history of dealing with the `@` operations in the messages, see: #41 #153 #216 #362 #1511 #1569 #1661

Today there's a discussion in our contributor room starting from @jcai for this topic again, and @lijiarui has another suggestion to make this logic simple: do not care about that _magic charactors_.

After thinking on this suggestion, I feel there's a need to deal with the `@` as simple as possible because there almost no value from the restrictions to check those magic characters, and it always introduce trouble from different wechat clients (such as the mac, windows, android, and ios).

So let's make the code as simple as it could be: just check the `@` in the mentioned text, and never pay attention to those magic characters.

**Comment by jcai** [comment]
I had written some tests for `mentionList and mentionText`.

https://github.com/wechaty/scala-wechaty/blob/7eb5816e46e1ea87871198de3fee2e264d5fcd0d/wechaty/src/test/scala/wechaty/user/MessageTest.scala

**Comment by huan** [comment]
After reviewed the code, the `mentionIdList` is generated by the puppet provider, which is not able to control by Wechaty.

So what we should do is to keep this as a design principle when we develop/implement a puppet implementation.
