### ISSUE TITLE
How to get wechaty instance in on functions in typescript, Global.this? 

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty#2007]
Hi, with javascript version, we can get wechaty instance(bot) like this way.
![image](https://user-images.githubusercontent.com/1160703/85273231-e73c8100-b4af-11ea-9763-f3d4f51092ee.png)
@see https://github.com/wechaty/wechaty-getting-started/blob/b0e00a28993dc83824544d0f28058996186907b0/examples/advanced/busy-bot.js#L79

but how can I get the wechaty instance in the on('message','../on-message.ts') functions?
here is my way to walk around.
![image](https://user-images.githubusercontent.com/1160703/85273044-a0e72200-b4af-11ea-90c0-26a657097927.png)
![image](https://user-images.githubusercontent.com/1160703/85273077-ae9ca780-b4af-11ea-9f45-1461e338f18e.png)
========中文========
请教大家一个问题， wechaty，typescript中on-message 无法使用this获取wechaty实例，提示Global.this 但是又不会怎么搞？
需求图片：
![image](https://user-images.githubusercontent.com/1160703/85275268-adb94500-b4b2-11ea-9e8b-e26c73c1f993.png)

on-message函数定义：
![image](https://user-images.githubusercontent.com/1160703/85273887-c58fc980-b4b0-11ea-9a4f-4c61fbf64dd6.png)

**Comment by guoxiangke** [comment]
not work like this
![image](https://user-images.githubusercontent.com/1160703/85277918-c9264f00-b4b6-11ea-9db2-5adbd50080c7.png)

**Comment by guoxiangke** [comment]
搞定了！
```
// @see http://www.semlinker.com/ts-this-param-type/
async function onMessage(this: Wechaty, msg: Message) {
  // const wechaty: Wechaty = Wechaty.instance() // wrong!
  const wechaty: Wechaty = this
```

**Comment by huan** [comment]
@guoxiangke Hi, I have noticed that you are using the Hot Import function from the Wechaty.

Please notice that in the next version of Wechaty, this function has been removed to our Plugin system, instead of binding it with the Wechaty itself.

Please go to https://github.com/wechaty/wechaty-plugin-contrib#9-eventhothandler to learn the `EventHotHandler` plugin for Wechaty v0.40+.
