### ISSUE TITLE
(node:9941) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [Bus]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by archywillhe** [wechaty/wechaty#2016]
## 1. Versions
- What is your wechaty version?
Answer: 0.40.8

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: padplus

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.7.18

- What is your node version? (run `node --version`)
Answer: 13.5.0

- What os are you using
Answer: macOS 10.14.6 (18G5033)

## 2. problem 

Got this sometimes after node is restarted. Still trying to figure out what causes it and gain more info about it.

```
(node:9941) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [Bus]. Use emitter.setMaxListeners() to increase limit
```

**Comment by archywillhe** [comment]
discussion on SO: https://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected

maybe have to do with using `.on` instead of `.once` over `new WeChaty` for `onMessage` callbacks, etc.

**Comment by huan** [comment]
Maybe related to #2019 

BTW: This warning is just telling you that the Wechaty have more than 11 listeners for one event.

Sometimes we do need to have lots of listeners, especially when we are working with the RxJS & Redux, like [wechaty-redux](https://github.com/wechaty/wechaty-redux/) subsystem.

**Comment by archywillhe** [comment]
I see! I will `.setMaxListeners` to a higher number for now! `wechaty-redux` looks interesting :)
