### ISSUE TITLE
是否能在wechaty.instance(params)中添加flashstore的路径配置

### ISSUE THREAD

**Issue by sidny** [wechaty/wechaty#2018]
如果是在实体机安装，.wechaty（flash-store）的路径就在命令运行的目录下

如果是在docker环境下，没有把.wechaty mount出来的话，paas类环境进行更新应用时，会recreate 容器，于是.wechaty会丢失
，造成bot.Room.find({id})行为返回了空的对象，

是否能在wechaty.instance(params)中添加flashstore的路径配置

[enhancement]
```
// 初始化
const bot = new Wechaty({
  memory: new MemoryCard({ name : config.memorypath }),
  puppet: new PuppetPadplus({
    token: config.token,
    flashstore: { name: ".wechaty"} //添加类似memory-card的配置方式
  }),
  name: config.name
})

```

**Comment by huan** [comment]
It's a great question with the PaaS use case.

We will consider this situation and try to fix it in the future.

Before we fix it, I believe there are workarounds for this problem:

1. mount your volume for your container to the directory: `~/.wechaty` before start wechaty
1. link `~/.wechaty1` to your volume path in the container before start wechaty

I hope my workaround can solve your problem, and please feel free to let me know if you have more questions.

**Comment by sidny** [comment]
for other situation，ex：
workdir ：/app —— readonly for src
datadir ：/data —— writable for cache，logs ...
i think wechaty may have a config option for all storage path prefix
