### ISSUE TITLE
How to develop and debug WecHaty locally

### ISSUE THREAD

**Issue by zzzzzlucky** [wechaty/wechaty#2024]
I did it in the following steps:
1、download wechaty and wechaty-puppet-padplus from github
2、remove [devDependencies.wechaty-puppet] and [peerDependencies.wechaty-puppety] in   package.json of wechaty-puppet-padplus
3、cd wechaty-puppet-padplus && npm install
4、cd wechaty && npm install
5、ts-node index.ts
then error:
![image](https://user-images.githubusercontent.com/8832748/88132141-51605700-cc11-11ea-952f-31448c0c4fad.png)

my index.ts:
![image](https://user-images.githubusercontent.com/8832748/88132164-5c1aec00-cc11-11ea-800b-a64122be3087.png)

The term wechaty-puppet in wechaty differs from the version in the ipadplus
Thanks for your help:)

**Comment by windmemory** [comment]
From my personal experience, here is what I usually do:

- Clone `wechaty`, `wechaty-puppet` and `wechaty-puppet-x`(any puppet that you are trying to develop)
- Do `npm install` in each project folder
- Do `npm run dist` in each project folder
- Do `npm link` in `wechaty-puppet`
- Do `npm link wechaty-puppet` in `wechaty` and `wechaty-puppet-x`
- Do `npm run dist` in `wechaty` and `wechaty-puppet-x`
- Do `npm link` in `wechaty` and `wechaty-puppet-x`
- Create a `index.ts` file in another folder to do test, with some test code in it.
- Do `npm link wechaty` and `npm link wechaty-puppet-x` in the folder that has `index.ts`
- Do `ts-node index.ts`

Then the error should be gone.

The main reason that you see that error is that `wechaty` and `wechaty-puppet-x` are not using `wechaty-puppet` from the same folder and same file. To solve this, I came up with the solution above, which will link the `wechaty-puppet` from local folder. This works for me, you could give it a try.

Let me know if you still having issue with this, and also let me know if you came up with better solution for this issue.

**Comment by huan** [comment]
Related to https://github.com/wechaty/wechaty/issues/1930

**Comment by huan** [comment]
This problem should be fixed with the latest code with the Wechaty version above v0.50.7.

Please let me know if it still has any problem, thank you very much!

**Comment by huan** [comment]
Merge to #1930
