### ISSUE TITLE
@所有人。和@机器人。这个可以区分出来么

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [wechaty/wechaty#2025]
目前我在@所有人的时候。会触发@机器人的一些 操作。 想把这个区分出来，

**Comment by post707** [comment]
@zhihuifanqiechaodan 请教一下，代码里如何@所有人

**Comment by zhihuifanqiechaodan** [comment]
> @zhihuifanqiechaodan 请教一下，代码里如何@所有人

遍历获取群成员列表放到数组中然后发送...

**Comment by post707** [comment]
> > @zhihuifanqiechaodan 请教一下，代码里如何@所有人
> 
> 遍历获取群成员列表放到数组中然后发送...

那是@1 @2 @3 这样@群里所有人一遍吗？能不能跟原生的一样@所有人 这样

**Comment by zhihuifanqiechaodan** [comment]
> 
> 
> 
> 
> 
> 
> > > @zhihuifanqiechaodan 请教一下，代码里如何@所有人
> 
> > 
> 
> > 遍历获取群成员列表放到数组中然后发送...
> 
> 
> 
> 那是@1 @2 @3 这样@群里所有人一遍吗？能不能跟原生的一样@所有人 这样

目前依旧没提供这功能。

**Comment by SeasideLee** [comment]
微信里 @所有人 的时候，message.payload.mentionIdList 会是 [ 'notify@all' ]
