### ISSUE TITLE
join, room-join 不再起作用

### ISSUE THREAD

**Issue by henryhu712** [wechaty/wechaty#2029]
[bug]

room.on('join', ..)

bot.on('room-join', ...)

都不再起作用。用户加入群，没有收到事件消息。

**Comment by su-chang** [comment]
Please upgrade `wechaty-puppet-padplus@0.7.33`.

**Comment by henryhu712** [comment]
> Please upgrade `wechaty-puppet-padplus@0.7.33`.

How can I upgrade it ?

**Comment by henryhu712** [comment]
> Please upgrade `wechaty-puppet-padplus@0.7.33`.

Thank you. But, it does not work after I upgraded to padplus@0.7.33

**Comment by su-chang** [comment]
It seems that we need more details about this issue.

**Comment by why2lyj** [comment]
Same with  python-wechaty，and room-leave is not available in Python-wechaty as well

**Comment by henryhu712** [comment]
> Please upgrade `wechaty-puppet-padplus@0.7.33`.

Thank you. It works after upgrading.

**Comment by HarrisonQi** [comment]
Same with [java-wechaty](https://github.com/wechaty/java-wechaty), just room-join/leave not working.
