### ISSUE TITLE
Room ID is not permanent at all

### ISSUE THREAD

**Issue by dfang** [wechaty/wechaty#2030]
the [issue](https://github.com/wechaty/wechaty-getting-started/issues/136) should be posted here

**Comment by huan** [comment]
Could you please let me know what makes you believe that the Room ID should be permanent?

I do not think Wechaty can guarantee that the room id will not change between sessions, because it highly depends on what puppet provider (protocol) you are using.

**Comment by dfang** [comment]
[get](https://github.com/nodeWechat/wechat4u/issues/175). thank you.

but it should be permanent according to the name,  but there're limitations ......

**Comment by huan** [comment]
You are welcome!
