### ISSUE TITLE
await contact.alias() not changed after changing Alias on Phone

### ISSUE THREAD

**Issue by chixu** [wechaty/wechaty#2031]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.
## 1. Versions
- What is your wechaty version?
Answer: 0.45.16

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: puppeteer

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 0.23.1

- What is your node version? (run `node --version`)
Answer: v12.16.1

- What os are you using
Answer: Windows

## 2. Describe the bug
project: wechaty-getting-started
node ding-dong-bot.js
scan qrcode: ok
call loadAllContact: ok
```
async function loadAllContact() {
  const contactList = await bot.Contact.findAll()
  for (let i = 0; i < contactList.length; i++) {
    const contact = contactList[i]
    if (contact.type() === Contact.Type.Personal) {
      let alias = await contact.alias()
      log.info('Bot', `personal ${i}: ${contact.name()} : ${alias} : ${contact.id}`)
    }
  }
}
```
change alias(备注名) of one contact in my Phone
call loadAllContact again (can use setInterval)
the alias is not changed

## 3. To Reproduce

setInterval(loadAllContact, 10000);

The FAQ Link died =))) https://docs.chatie.io/faq

[bug]

**Comment by huan** [comment]
> The FAQ Link died =))) https://docs.chatie.io/faq

Could you please tell us where did you get this link from?

**Comment by chixu** [comment]
Issues -> New Issue
Wechaty Bug Report
under
## 0. Report Issue Guide
...
2...

**Comment by huan** [comment]
Oh, yes, it's in the Issue Templates.

Thank you very much for letting me know this!

**Comment by gclinux** [comment]
> 

Page not found
