### ISSUE TITLE
1. Introduce Yourself(who you are):

### ISSUE THREAD

**Issue by wang222** [wechaty/wechaty#2032]
1. Introduce Yourself(who you are):
   Allen
   
2. Explain the Problem You Want to Solve:(what you do):
   Create WeChat robots and manage groups
   
3. Are Your Bot Related with the Following Tasks? (YES/NO)   Gambling/   Adault & Sex
   NO
   
4. Your Email:
   990284817@qq.com
   
5. Your Wechat:
   13298401897
   
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)
	YES
   
7. I understand that the Wechaty Puppet Donut is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
	YES	 Allen

**Comment by huan** [comment]
Merge to #1941
