### ISSUE TITLE
How to get contacts list of the bot ?

### ISSUE THREAD

**Issue by 92hackers** [wechaty/wechaty#204]
title tells all.

**Comment by lijiarui** [comment]
`  const contactList = await Contact.findAll()`

learn more from the example: [contact-bot](https://github.com/wechaty/wechaty/blob/master/example/contact-bot.ts)

**Comment by 92hackers** [comment]
@lijiarui  thank you very much, but, to be honest,  such a useful method should be displayed in  project's  wiki, so we can not miss.

**Comment by lijiarui** [comment]
yep, you are right, I just added in the wiki:

what's more, wechaty can find contact by remark and name, learn more in the wiki:

https://github.com/wechaty/wechaty/wiki/API#contact-query-type

**Comment by 92hackers** [comment]
@lijiarui  thank you very much.
