### ISSUE TITLE
使用IPAD协议 在Windows系统CMD下生成的二维码  不能识别和扫描

### ISSUE THREAD

**Issue by Songbingjun** [wechaty/wechaty#2042]
![14)}I MPM5ANNCWSIO{K42E](https://user-images.githubusercontent.com/43177917/90467300-77144980-e146-11ea-8cb0-022d67506d89.png)

图大概就这样，CMD的字符集是utf-8

**Comment by Songbingjun** [comment]
呜呜呜有没有大佬啊

**Comment by huan** [comment]
Merge to #2055
