### ISSUE TITLE
Remove DEPRECATED methods from Wechaty@0.47.21

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2049]
Deprecated list:

 Before (Deprecated) | After
--- | --- |
WechatyOptions.profile | `name`
Wechaty.self() | `userSelf()`
Contact.stranger() | `friend()`
Contact.official() | `contact.type() === ContactType.Official`
Contact.personal() | `contact.type() === ContactType.Individual`
Contact.refresh() | `sync()`
Friendship.send() | `add()`
Message.content() | `text()`
Message.mentioned() | `mentionList()`
Message.file() | `toFileBox()`
RoomInvitation.roomTopic() | `topic()`
RoomInvitation.roomMemberCount() | `memberCount()`
RoomInvitation.roomMemberList() | `memberList()`
Room.refresh() | `sync()`
Room.qrcode() | `qrCode()`
Room.roomAlias() | `alias()`

That's all!

**Comment by shavingha** [comment]
wechatyName.memory-card.json 这个文件并没有生成，但是我还是可以自动登录，请问登录缓存信息放在什么地方的？
