### ISSUE TITLE
typo in Wiki

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#205]
https://github.com/wechaty/wechaty/wiki/API/_compare/ff5ffbb14f91cab6151a6df4137c7e354c5cc10b...1f93d8e3946d336a605965f065bf98d9d05a503b#diff-88333ba11114e014e87198d04680144dR469

**Comment by lijiarui** [comment]
done

**Comment by zixia** [comment]
Still, has an error in your code: 
https://github.com/wechaty/wechaty/wiki/API/_compare/1f93d8e3946d336a605965f065bf98d9d05a503b...b9e9d5a422688cbdbb6255fa9c34cf479cd3ca56#diff-88333ba11114e014e87198d04680144dL468

**The regex should not be put inside quotation marks.**

**Comment by lijiarui** [comment]
how about this one:   

https://github.com/wechaty/wechaty/wiki/API/_compare/b9e9d5a422688cbdbb6255fa9c34cf479cd3ca56...e69de85c14038633360c0bc485021c39178d3f4c

**Comment by zixia** [comment]
Ok

**Comment by zixia** [comment]
But there's still many similar mistakes not fixed.

ie:

> Room.find({ topic:"/^ding/i"} )

**Comment by lijiarui** [comment]
This is written by you.... but I fix it...

**Comment by zixia** [comment]
Just fix it.
