### ISSUE TITLE
bot.Friendship.search 判断结果是否已经是好友

### ISSUE THREAD

**Issue by dchaofei** [wechaty/wechaty#2054]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: 0.48.3

> Which puppet are you using for wechaty? (hostie/puppeteer/padchat/...)

Answer: hostie

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: 0.10.1

> What is your node version? (run `node --version`)

Answer: v12.16.1

> What os are you using

Answer: mac

## 2. Describe the bug

> Friendship.search() 返回的联系人不能用 friend() 判断是否是朋友.

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

如下代码:
```typescript
  const a = await bot.Friendship.search({weixin: "xxx"})
  if (!a) {
    return
  }
  if (!a.friend()) {
    await bot.Friendship.add(a, "hi")
    console.log("已经发送好友请求.")
  } else {
    console.log("已经是您的好友.")
  }
```

## 4. Expected behavior

> 预期第一次执行程序会输出：`已经发送好友请求.`
> 预期同意好友请求后，每次执行都输出：`已经是您的好友.`

## 5. Actual behavior

> 真实的结果，每次都会输出 `已经发送好友请求.`

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
17:54:21 VERB Friendship static search("{"weixin":"xxx"}")
17:54:21 VERB Puppet friendshipSearch("{"weixin":"xxx"}")
17:54:21 VERB PuppetHostie friendshipSearchWeixin(xxx)
17:54:21 VERB Contact load(xxx) init pool
17:54:21 SILL Contact constructor(dingchaofei123)
17:54:21 SILL Contact ready() @ Puppet#0<PuppetHostie>(ding-dong-bot) with id="xxx"
17:54:21 SILL Puppet contactPayload(xxx) cache MISS
17:54:21 VERB PuppetHostie contactRawPayload(xxx)
17:54:21 SILL Puppet contactPayload(xxx) cache SET
17:54:21 VERB Contact friend()
17:54:21 VERB Friendship static add(xxx, hi)
17:54:21 VERB PuppetHostie friendshipAdd(xxx, hi)
已经发送好友请求.


```

</details>

## 7. Additional context

> 是不是 hostie 服务端存了一份缓存？当好友同意申请时也没有清除？

**Comment by dchaofei** [comment]
这里说明我要实现的功能：我要实现用微信号加好友，当搜索出来的联系人已经是好友关系时就不做任何操作，否则执行添加好友逻辑

**Comment by dchaofei** [comment]
另外 Friendship.search() 的返回结果也奇怪。
搜索一个已存在的好友有的会返回 null, 有的会返回联系人信息，只不过 `friend()` 是 `false`。

**Comment by su-chang** [comment]
This issue should be transferred to repo `donut-test`. @huan help wanted.

And I will look into it next week.

**Comment by huan** [comment]
@su-chang I'd like to help but we can only transfer issue to other repo under the same org.

Please feel free to discuss under this issue, or create a new one in donut-tester repo and refer to this issue.

**Comment by dchaofei** [comment]
把好友删除了，使用 ` bot.Contact.find({weixin:"xxx"})` 依然能获取到，并且 `firend()` 为 true, 应该是同样的问题，也贴在这里
