### ISSUE TITLE
The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by wu1005690803** [wechaty/wechaty#2058]
我在使用 room.say(file) 时候碰到这样的提示， 我检查过文件都正常的，内容都是正常的

 InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

**Comment by su-chang** [comment]
Please upgrade `wechaty@0.48.1` and `wechaty-puppet-padplus@0.6.5`.

**Comment by wu1005690803** [comment]
我刚刚升级到 最新的版本，问题还是一样
  "dependencies": {
    "cross-env": "^7.0.2",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^0.48.5",
    "wechaty-plugin-contrib": "^0.14.2"
  },
  "devDependencies": {
    "@chatie/eslint-config": "^0.12.1",
    "@chatie/git-scripts": "^0.6.1",
    "@chatie/tsconfig": "^0.10.1",
    "check-node-version": "^4.0.3",
    "connect": "^3.7.0",
    "is-pr": "^1.1.0",
    "marked": "^1.1.0",
    "nodemon": "^2.0.3",
    "wechaty-puppet-mock": "^0.22.31",
    "wechaty-puppet-padplus": "^0.7.21",
    "wechaty-puppet-puppeteer": "^0.23.1",
    "wechaty-puppet-wechat4u": "^0.16.3"
  },

**Comment by su-chang** [comment]
> "wechaty-puppet-padplus": "^0.7.21",

The wrong version here.

Version `0.7.39` or `0.6.5` could resolve this problem.

**Comment by wu1005690803** [comment]
ok，谢谢了，已经正常使用
