### ISSUE TITLE
在使用FileBox 发送视频时候出现问题

### ISSUE THREAD

**Issue by wu1005690803** [wechaty/wechaty#2059]
我在wechaty 中使用 FileBox  发送 视频文件时候
提示 ：Cannot find ffmpeg，我在主机上 安装了 ffmpeg也是这样的问题

 Error: Cannot find ffmpeg
0|ding-dong-bot  |     at /home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:136:22
0|ding-dong-bot  |     at FfmpegCommand.proto._getFfmpegPath (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/capabilities.js:90:14)
0|ding-dong-bot  |     at FfmpegCommand.proto._spawnFfmpeg (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:132:10)
0|ding-dong-bot  |     at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/capabilities.js:517:10)
0|ding-dong-bot  |     at /home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/capabilities.js:568:14
0|ding-dong-bot  |     at nextTask (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:4576:27)
0|ding-dong-bot  |     at Object.waterfall (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:4587:9)
0|ding-dong-bot  |     at Object.awaitable [as waterfall] (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:208:32)
0|ding-dong-bot  |     at FfmpegCommand.proto._checkCapabilities (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/capabilities.js:565:11)
0|ding-dong-bot  |     at /home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:298:14
0|ding-dong-bot  |     at nextTask (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:4576:27)
0|ding-dong-bot  |     at Object.waterfall (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:4587:9)
0|ding-dong-bot  |     at Object.awaitable [as waterfall] (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:208:32)
0|ding-dong-bot  |     at FfmpegCommand.proto._prepare (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:295:11)
0|ding-dong-bot  |     at FfmpegCommand.proto.exec.proto.execute.proto.run (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/processor.js:431:10)
0|ding-dong-bot  |     at runCommand (/home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/recipes.js:401:12)
0|ding-dong-bot  |     at wrapper (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:268:20)
0|ding-dong-bot  |     at next (/home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:4582:24)
0|ding-dong-bot  |     at /home/work/wechaty-getting-started/node_modules/_async@3.2.0@async/dist/async.js:321:20
0|ding-dong-bot  |     at /home/work/wechaty-getting-started/node_modules/_fluent-ffmpeg@2.1.2@fluent-ffmpeg/lib/recipes.js:339:13
0|ding-dong-bot  |     at suppressedCallback (fs.js:211:5)
0|ding-dong-bot  |     at FSReqCallback.oncomplete (fs.js:155:23)

**Comment by xiebiaokmy** [comment]
设置环境变量了吗？ 前几天也是遇到上传视频的问题，说说步骤 1.找一个ffmpeg文件，2.环境变量在path后面添加一个路劲 值是你刚才的ffmpeg文件 的bin 文件夹的路劲

**Comment by wu1005690803** [comment]
好的 谢谢啦  已经可以使用了
