### ISSUE TITLE
监听入群时报错，求大佬 帮忙看看

### ISSUE THREAD

**Issue by xiebiaokmy** [wechaty/wechaty#2065]
报这个错  cannot get user_name from raw payload…… 虽然能正常拿到room, inviteeList, inviter 这三个参数，但是报一大堆错误 总是不好， 我看了源码好像是rawPayload.userName 不存在时会出现， 这个参数怎么传？ 目前我的wechaty版本和wechaty-puppet-padplus的版本分别是"wechaty": "^0.48.10", "wechaty-puppet-padplus": "^0.7.33" 是因为版本导致的吗？

**Comment by CavonCheng** [comment]
我也遇到这个问题，mark一下

**Comment by tomallv** [comment]
之前用这个版本的时候没有碰到这个问题：
"wechaty": "^0.46.4",
 "wechaty-puppet-padplus": "^0.6.5"

上周升级到如下版本的时候。也碰到了这个问题：
 "wechaty": "^0.48.10",
 "wechaty-puppet-padplus": "^0.6.6"

mark一下
