### ISSUE TITLE
enhance RoomMemberQueryFilter

### ISSUE THREAD

**Issue by treeguard** [wechaty/wechaty#2069]
**Is your feature request related to a problem? Please describe.**
The current RoomMemberQueryFilter doesn't support query by wxid (id of Contact), can we support this? 

**Describe the solution you'd like**
Add id as a string type in RoomMemberQueryFilter
**Describe alternatives you've considered**
1.  Find all contacts for the room and find out the matched id
2. Load the contact by id first and use Room.has function, however, if the contact is not a friend of the bot, I am not sure if we can load the contact by id

**Additional context**

[enhancement]

**Comment by AliBinBeshr** [comment]
i need to catch up someone scam

**Comment by AliBinBeshr** [comment]
scam i want try to say is criminal using account for selling product after tranfer money he\she block me on whats up how do i catch him\her ... please help!!
