### ISSUE TITLE
token for wechaty-puppet-padplus vs wechaty-puppet-hostie

### ISSUE THREAD

**Issue by Edward-Zhou** [wechaty/wechaty#2071]
Hi,

After checking #1986 , it metioned there are two ways to get **hostie token**.

Could you help to clearify the points below to make new members more clear about the token?

> How to get this Hostie Token?
> 
> If you have token before (like a padplus token), you can go to #1985; else
> If you have no token before, this post will tech you a very easy way to Create One Wechaty Hostie Token by yourself.

Referenced from #1986 

1. What is the difference between padplus token and hostie token? If possible, could you share us the request process about them?

2. For the difference between #1986 and #1985, docker run with different WECHATY_PUPPET. If we could create hostie token by ourself, whether we will need to apply for padplus token?

3. If Wechat account could not login through wechat web online, will it be able to use hostie token?

I am curious about the workflow about the wechaty, like when to register token, when to scran the qr code, it will help to understand and implement our own library with wechaty api.

**Comment by huan** [comment]
Hi Edward,

Thank you very much for asking this great question.

Quick answer for your questions:

> What is the difference between padplus token and hostie token? If possible, could you share us the request process about them?

A padplus token is for [wechaty-puppet-padplus](https://github.com/wechaty/wechaty-puppet-padplus), hostie token is for [wechaty-puppet-hostie](https://github.com/wechaty/wechaty-puppet-hostie)

> For the difference between #1986 and #1985, docker run with different WECHATY_PUPPET. If we could create hostie token by ourself, whether we will need to apply for padplus token?

The answer is Yes and No.

Hostie is a wrapper layer to other puppet protocols.

If you are using hostie with the [wechaty-puppet-puppeteer](https://github.com/wechaty/wechaty-puppet-puppeteer), then you will not need to apply for any padplus token

If you are using hostie with the [wechaty-puppet-padplus](https://github.com/wechaty/wechaty-puppet-padplus), then you will need to get a padplus token.

> If Wechat account could not login through wechat web online, will it be able to use hostie token?

Yes.

You can use Win32 Protocol or Pad Protocol if your WeChat account can not log in to Web Protocol.

I understand that the Wechaty documentation is not clear and friendly enough for our new developers, we need to make more improvements to our website at https://wechaty.js.org

**Comment by Edward-Zhou** [comment]
Thanks for the reponse, and after review the doc again. 

It's much clear now.

It seems I should not compare wechaty-puppet-padplus and wechaty-puppet-hostie.

For token, I should refer the doc 

Protocol | Puppet Provider | Environment Variable
-- | -- | --
Web | PuppetPuppeteer | export WECHATY_PUPPET=wechaty-puppet-puppeteer
iPad | PuppetPadplus | export WECHATY_PUPPET=wechaty-puppet-padplus
Mac | PuppetMacpro | export WECHATY_PUPPET=wechaty-puppet-macpro
Mock | PuppetMock | export WECHATY_PUPPET=wechaty-puppet-mock
Web | PuppetWechat4u | export WECHATY_PUPPET=wechaty-puppet-wechat4u
iPad | PuppetPadpro DEPRECATED | export WECHATY_PUPPET=wechaty-puppet-padpro
iPad | PuppetPadchat DEPRECATED | export WECHATY_PUPPET=wechaty-puppet-padchat

#[Switch Protocol(Puppet)](https://github.com/wechaty/wechaty#3-switch-protocolpuppet)

For wechaty-puppet-hostie, it's a wrapper layer for above tokens which could be used for multiple-language.

For whether I need to apply padplus token, it depends on which token I use for wechaty-puppet-hostie.

If there is no issue in my statement, I think we could close it now.

Thanks again.

**Comment by huan** [comment]
Great to know that there's no issue in your statement anymore.

If you feel the document should be improved, please feel free to send PR to improve it!
