### ISSUE TITLE
Token Server 是否开源

### ISSUE THREAD

**Issue by xiaopao2014** [wechaty/wechaty#2086]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
是否可以搭建自己的Token server

**Comment by huan** [comment]
Of course, you can!

Please refer to #1986 and make you a [Wechaty Puppet Service Provider](https://github.com/wechaty/puppet-service-providers)!
