### ISSUE TITLE
我在使用 room.has(contact)的时候，在Windows本地没有问题，但是在Centos服务器上遇到了问题

### ISSUE THREAD

**Issue by 0xtaosu** [wechaty/wechaty#2089]
我在使用 room.has(contact)的时候，在Windows本地没有问题，但是在Centos服务器上遇到了问题，

![image](https://user-images.githubusercontent.com/17952537/99613547-b490b780-2a52-11eb-9451-e76a063e199a.png)

btw ，判断说不在群里

![image](https://user-images.githubusercontent.com/17952537/99613575-c1151000-2a52-11eb-8195-735303469b12.png)

**Comment by taosue** [comment]
但是现在又好了
