### ISSUE TITLE
Can't login after scan the qrcode

### ISSUE THREAD

**Issue by YoHo-Wang** [wechaty/wechaty#2092]
Just got the token begin with "puppet_donut_*******". I tested with the code below. I can login at the first time(the message bar in my mobile wechat showes already login), but when I logged out. **I can't login anymore, no logs and no message bar shows after I scan the qrcode**, how can I resolve this issue? Thanks
```
const token = "puppet_donut_***********"

const bot = new Wechaty({
  puppet: 'wechaty-puppet-hostie',
  puppetOptions: {
    token,
  }
});

bot
  .on('scan', (qrcode, status) => {
    if (status === ScanStatus.Waiting) {
      QrcodeTerminal.generate(qrcode, {
        small: true
      })
    }
  })
  .on('login', async user => {
    console.log(`user: ${JSON.stringify(user)}`)
  })
  .on('message', async message => {
    console.log(`message: ${JSON.stringify(message)}`)
  })
  .start()
```

**Comment by lightlzm** [comment]
我也一样的问题，退出后一直无法在登录了，二维码也不见显示。

开了 WECHATY_LOG=silly，运行日志如下：

C:\Users\Administrator>node C:\nodejs\wechaty\index.js
16:57:50 SILL Puppet Config: WECHATY_LOG set level to silly
16:57:51 INFO Config registering process.on("unhandledRejection") for developmen
t/debug
16:57:51 VERB Config constructor()
16:57:51 VERB Wechaty constructor()
16:57:51 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"
logLevel":5,"prefixFilter":{}}}")
16:57:51 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":t
rue,"logLevel":5,"prefixFilter":{}}}")
16:57:51 VERB Wechaty on(scan, listener) registering... listenerCount: 0
16:57:51 VERB Wechaty on(login, listener) registering... listenerCount: 0
16:57:51 VERB Wechaty on(friendship, listener) registering... listenerCount: 0
16:57:51 VERB Wechaty on(message, listener) registering... listenerCount: 0
16:57:51 VERB Wechaty on(room-invite, listener) registering... listenerCount: 0
16:57:51 VERB Wechaty on(room-join, listener) registering... listenerCount: 0
16:57:51 VERB Wechaty <wechaty-puppet-hostie>() start() v0.51.4 is starting...
16:57:51 VERB Wechaty id: cki01966f00003wkgeuqpcful
16:57:51 SILL StateSwitch <Wechaty> on() is false
16:57:51 SILL StateSwitch <WechatyReady> off() is true
16:57:51 VERB StateSwitch <WechatyReady> off(true) <- (true)
16:57:51 SILL StateSwitch <Wechaty> on() is false
16:57:51 VERB StateSwitch <Wechaty> on(pending) <- (false)
16:57:51 VERB Wechaty initPuppet() wechaty-puppet-hostie
16:57:51 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOption
s: {"token":"puppet_donut_xxxxxxx"}})
16:57:51 VERB PuppetManager resolveName(wechaty-puppet-hostie)
16:57:51 VERB PuppetManager checkModule(wechaty-puppet-hostie)
16:57:51 SILL PuppetManager checkModule() wechaty-puppet-hostie installed versio
n 0.11.10 satisfied range *
16:57:51 VERB Puppet constructor({"token":"puppet_donut_xxxxxxxxxx"}) #0
16:57:51 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":t
rue,"logLevel":5,"prefixFilter":{}}}")
16:57:51 VERB Puppet constructor() watchdog timeout set to 60 seconds
16:57:51 VERB Puppet constructor() childClassPath=C:\nodejs\wechaty\node_modules
\wechaty-puppet-hostie\dist\src\client
16:57:51 VERB Puppet setMemory()
16:57:51 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>())
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCou
nt:0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0)
 registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0
) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:
0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCo
unt:0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCoun
t:0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCou
nt:0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCou
nt:0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0)
registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0)
 registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0)
registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0)
 registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCoun
t:0) registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0)
 registering...
16:57:51 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0)
 registering...
16:57:51 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetHostie>())
16:57:51 VERB PuppetHostie start()
16:57:51 SILL StateSwitch <PuppetHostie> on() is false
16:57:51 SILL StateSwitch <PuppetHostie> on() is false
16:57:51 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
16:57:51 VERB PuppetHostie startGrpcClient()
16:57:51 VERB PuppetHostie discoverHostieIp(puppet_donut_xxxxxxxxx)
16:57:52 VERB PuppetHostie startGrpcStream()
16:57:52 SILL StateSwitch <PuppetHostie> on() is pending
16:57:52 VERB StateSwitch <PuppetHostie> on(true) <- (pending)
16:57:52 VERB Wechaty on(heartbeat, listener) registering... listenerCount: 0
16:57:52 SILL StateSwitch <Wechaty> on() is pending
16:57:52 VERB StateSwitch <Wechaty> on(true) <- (pending)
16:57:52 VERB Wechaty <wechaty-puppet-hostie> stop() v0.51.4 is stopping ...
16:57:52 SILL StateSwitch <Wechaty> off() is false
16:57:52 SILL StateSwitch <WechatyReady> off() is true
16:57:52 VERB StateSwitch <WechatyReady> off(true) <- (true)
16:57:52 SILL StateSwitch <Wechaty> off() is false
16:57:52 VERB StateSwitch <Wechaty> off(pending) <- (false)
16:57:52 VERB PuppetHostie stop()
16:57:52 SILL StateSwitch <PuppetHostie> off() is false
16:57:52 SILL StateSwitch <PuppetHostie> off() is false
16:57:52 VERB StateSwitch <PuppetHostie> off(pending) <- (false)
16:57:52 VERB PuppetHostie stopGrpcStream()
16:57:52 VERB PuppetHostie startGrpcStream() eventStream.on(end)
16:57:52 VERB PuppetHostie stopGrpcClient()
16:57:52 SILL StateSwitch <PuppetHostie> off() is pending
16:57:52 VERB StateSwitch <PuppetHostie> off(true) <- (pending)
16:57:52 SILL StateSwitch <Wechaty> off() is pending
16:57:52 VERB StateSwitch <Wechaty> off(true) <- (pending)

C:\Users\Administrator>

**Comment by KochamCie** [comment]
Hi all, I got the same issue as well. 
One more thing, after I confirm login in my iPhone screen, it can kick out my Mac Wechat which means the QRCode is fine.

> "I can't login anymore, no logs and no message bar shows after I scan the qrcode"
I think we actually logon success from Wechat service perspective, 
@huan Could you please help to check why no logs ( suppose to log the 'login') and even no 'message' event logs.

Here's the bot creation I copy from a sample shared by juzibot.

// not assign attribute 'name' as I'm about to use two wechat account for testing separately.
const bot = new Wechaty({
  puppet: 'wechaty-puppet-hostie',
  puppetOptions: {
    token_which_expired_in_15_days,
  }
});

// dependencies
  "dependencies": {
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^0.51.10",
    "wechaty-puppet-hostie": "^0.10.8"
  },

if any kind of screenshot needed, please ping me, many thx.

**Comment by huan** [comment]
I guess this is a donut related bug.

Could you please try to use `wechaty-puppet-puppeteer` to log in your WeChat account?

If you can get any response after you scan the qr code, then the Wechaty is good, and then you should contact the donut service provider for support.

**Comment by KochamCie** [comment]
@huan 
Hi, thanks for your quick response and it took me a long time to install that puppeteer.

Yes , i got the 'To protect your account, logging in to WeChat via the web has been suspended ...' message after log in.

BTW, could you please share the contact point of donut service support or raise a ticket for us ? Coz I'm new here :)

**Comment by huan** [comment]
@KochamCie You are welcome!

Please go to <https://github.com/wechaty/puppet-services> to file puppet service-related issues.

**Comment by huan** [comment]
Please feel free to ask for support from our community at <https://gitter.im/wechaty/wechaty>
