### ISSUE TITLE
wxwork bot send miniprogram error: 'Can not send mini program without thumbKey.'

### ISSUE THREAD

**Issue by aslanTT** [wechaty/wechaty#2098]
use "wechaty-puppet-hostie" :"0.10.8",
       "wechaty": "^0.50.7",
       "wechaty-puppet": "0.32.2",

wxwork_puppet

![image](https://user-images.githubusercontent.com/1904655/100504972-9e4bcf80-31a7-11eb-9888-2678687e86ec.png)

**Comment by windmemory** [comment]
Currently the design of wxwork does not support a random given `thumbUrl` to send mini program messages. It only support forward mini programs, which means you have to send a mini program to the bot first, then the bot could save the payload of that mini program and use it else where.
