### ISSUE TITLE
wx.qq.com detect phantomjs and disabled it

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#21]
### Update 2016-9-1

Phantomjs work well now, without any modification at wechaty side. 

It seems like js code in wx upgraded again, and the accident that disable phantomjs is not the purpose (more like a compatible bug of checksum code run in phantomjs).

--------------------------

before fix, you can switch to chrome instead of phantomjs to use wechaty as usual.

```shell
$ WECHATY_HEAD=chrome node example/ding-dong-bot.js
```

detail:

> https://res.wx.qq.com/zh_CN/htmledition/v2/js/webwxApp2fd632.js
```javascript
    try {
        var p = angular.bootstrap.toString().replace(/\n"use strict";\n/, "")
          , h = m(p);
        "54c6b762ad3618c9ebfd4b439c8d4bda" !== h && ($.getScript("https://tajs.qq.com/stats?sId=54802481"),
        location.href = "https://wx.qq.com/?t=v2/fake")
    } catch (M) {}
    angular.bootstrap(document, ["webwxApp"])
```
> https://wx.qq.com/?t=v2/fake

### See Also

- 临时修复非官方客户端，无法登陆提示 https://github.com/geeeeeeeeek/electronic-wechat/pull/319
- https://github.com/zacyu/bilibili-helper/blob/3cc0e0d89a8279abadea6a6c8acf18877b5fa7bf/src/background.js#L961
- [PhantomJS change webpage content before evaluating](http://stackoverflow.com/a/24838718/1123955)

**Comment by JasLin** [comment]
```
$ WECHATY_HEAD=chrome node example/ding-dong-bot.js
```
not work too

**Comment by JasLin** [comment]
errors with:

```
/home/xxx/projects/learning/wechat/wechaty2/example/ding-dong-bot.js:35
.on('scan', ({url, code}) => {
             ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by JasLin** [comment]
run with chrome may need a GUI environment, can i just  change useragent of phantomjs to workaround this issue?

**Comment by zixia** [comment]
it seems u use node version under  v6.

what node version do u have? if under v6 pls upgrade to v6 and have another
try.

and yes, use chrome as head need `xvfb` under linux. pls see
bin/install-chrome-linux.sh to know how to use it.

please feel free to let me know if u need more help.

Zhuohuan LI - 發自我的小霸王學習機

**Comment by JasLin** [comment]
yes, i forgot to change node version back to v6.

**Comment by JasLin** [comment]
maybe we could use headless chrome instead of phantomjs

https://chromium.googlesource.com/chromium/src/+/master/headless/README.md

https://docs.google.com/presentation/d/1gqK9F4lGAY3TZudAtdcxzMQNEE7PcuQrGu83No3l0lw/edit#slide=id.g135a740781_0_0

**Comment by zixia** [comment]
change user agent maybe help, but i did not try yet.

if u can make it work, pull request is welcome. :)

**Comment by JasLin** [comment]
trying to change useragent of phantomjs  , it dose't work

````
const customPhantom = WebDriver.Capabilities.phantomjs()
    .setAlertBehavior('ignore')
    .set('phantomjs.binary.path', phantomjsExe)
    .set('phantomjs.cli.args', phantomjsArgs)
    .set('phantomjs.page.settings.userAgent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36')
```

**Comment by JasLin** [comment]
it' seems   ```bin/install-chrome-linux.sh```  is not work to  ```docker``` environment.

````
info Wechaty v0.3.9 initializing...
ERR! PuppetWebBrowser open() exception: Server terminated early with status 127
WARN PuppetWebBrowser dead() because Server terminated early with status 127
ERR! PuppetWeb initBrowser() exception: Server terminated early with status 127
ERR! PuppetWeb init exception: Server terminated early with status 127
ERR! Wechaty init() exception: Server terminated early with status 127
ERR! Bot Error: Server terminated early with status 127
ERR! Bot     at Error (native)
ERR! Bot     at /node_modules/.npminstall/selenium-webdriver/3.0.0-beta-2/selenium-webdriver/remote/index.js:243:22
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot From: Task: WebDriver.createSession()
...
```

**Comment by zixia** [comment]
yes, docker has issue after switched to  chrome. Will fix it later.

**Comment by zixia** [comment]
@JasLin docker worked. it based on `xvfb` & `chromium` solution. 

see details here: https://github.com/wechaty/wechaty/blob/d2bf393d1b2018fceab00664f7b6b220ecbfe79e/bin/xvfb-chromium

**Comment by zixia** [comment]
back to `phantomjs`

**Comment by zixia** [comment]
back to chrome because #28

**Comment by JasLin** [comment]
chrome is more stable:)

**Comment by zixia** [comment]
maybe is just another bug in inject code. 

phantomjs is better when you run wechaty on your desktop, like electron...
