### ISSUE TITLE
我在新版本中使用群消息时候，@不到人

### ISSUE THREAD

**Issue by shaohongwu** [wechaty/wechaty#2103]
"wechaty-puppet-mock": "^0.28.1",
    "wechaty-puppet-padplus": "^0.7.21",
    "wechaty-puppet-puppeteer": "^0.23.1",
    "wechaty-puppet-wechat4u": "^0.16.3"

如题，我在群里发消息
```
    const members = await room101.memberAll({ contactAlias: "目标" })
    if (members != null) {
      await room101.say(msg, ...members)
    }
```
在群里，有时候正常，有时候出现 {$@}

**Comment by huan** [comment]
Thanks for the reporting!

Related to #2097

**Comment by post707** [comment]
知道如何@all吗？
