### ISSUE TITLE
Room invitation document is incorrect

### ISSUE THREAD

**Issue by profthecopyright** [wechaty/wechaty#2105]
See pull request #2104

**Comment by huan** [comment]
Good catch, thank you very much for the fix!

> You've invited profthecopyright to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty Organization on GitHub, please accept it by visiting https://github.com/wechaty

And we also have a contributor-only WeChat room for better discussion. Please feel free to contact @lijiarui if you are interested to join!
