### ISSUE TITLE
[RFC] support wxwork tag group concept in Wechaty

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty#2108]
**Is your feature request related to a problem? Please describe.**
I would like to get tag information in Wechaty with a wxwork account, but the structure of wxwork tag is different from wechat.

Wechat:
```ts
['tag1', 'tag2', 'tag3']
```

Wxwork: 
```
[{
  groupName: 'tag group 1',
  tags: ['tag1', 'tag2'],
}, {
  groupName: 'tag group 2',
  tags: ['tag1', 'tag2'],
}]
```

And the problem is that in wxwork, different tags are allowed to have same name, as long as they are not in the same tag group.

**Describe the solution you'd like**
Seems like we need to adjust the current tag structure to support tag group concept, so we can align wxwork's tags with Wechaty.

I would design the class like below

```ts
class Tag {
  id: string,
  name: string,
  groupId?: string,

  // ... some other functions, same as the current design
}

class TagGroup {
  id: string,
  name: string,

  // ... some other functions, like add, update etc
}
```

Changes are:

- We need to add a name field into Tag, since tags are possible to have same name, so we can not use name as the id anymore.
- We need to add a new class called TagGroup with proper values and functions
- For wxwork, creating a tag needs to specify which group does this tag belong, we the Tag API needs some modification

**Describe alternatives you've considered**
Maybe we can just store the groupName as a property inside `Tag`, but in this way, if some tag group changes the name, we don't know whether this is a new tagGroup or an old one, we can not check by the name. If the Tag is using name as a relation to the TagGroup, the connection will be lost, and it will be hard to recover the relation.

**Additional context**

[enhancement]

Data structure of underlying layer wxwork tag
```ts
export enum LabelDataType {
  LABEL = 1,
  LABEL_GROUP = 2,
}

export enum LabelType {
  CORP_LABEL = 1,
  PERSONAL_LABEL = 2,
}

export interface LabelModel {
  id: number,
  name: string,
  data_type: LabelDataType,
  label_groupid: number,
  create_time: number,
  label_type: LabelType,
  sort_order: number,
}
```

**Comment by windmemory** [comment]
@huan Any thoughts on this issue?

**Comment by huan** [comment]
Let us think about it more this week and I hope we can have a discussion on its design next week

**Comment by windmemory** [comment]
When shall we start a discussion on this issue?

**Comment by huan** [comment]
Let's resume this discussion this week.

I always think the tag design from the WeCom is not right, however it seems we have to find a way to compatible with them because they are so HUGE!
