### ISSUE TITLE
Upgrade Node.js v12 -> v14 in Dockerfile

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2115]
Now we should follow the latest TLS version: v14

**Comment by leochen-g** [comment]
why when i use `FROM wechaty/onbuild:next`, the node version was also v12. I had cleaned all cache images. what shou i do ?

**Comment by huan** [comment]
Can you try the `wechaty/wechaty:next` and confirm the node version?

It should be 14, and the `onbuild:next` is based on it.

**Comment by leochen-g** [comment]
The `wechaty/wechaty:next` is good.I have copied the content of `onbuild:next`, and it's okay now.
