### ISSUE TITLE
support @all 

### ISSUE THREAD

**Issue by zpaimon** [wechaty/wechaty#2116]
["announcement@all"]

**Comment by paulhybryant** [comment]
+1, just ran into this.

**Comment by windmemory** [comment]
+1, this will help us easily identify an announcement instead of go over the whole mention list.

**Comment by windmemory** [comment]
@zpaimon Shall we add a new return type for `mention` method on `Message`? What do you think is the best design for this `@all` feature?

**Comment by paulhybryant** [comment]
I managed to do this by match @所有人 and @all with regex in mention_text
It does not cover all cases. For example, 群待办
