### ISSUE TITLE
Failed to connect to RPC server

### ISSUE THREAD

**Issue by luyomo** [wechaty/wechaty#2121]
Looks like that the api failed to connect the RPC server .
 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds... 

Is the server down? Or the token became invalid.
Because I posted one blog and I assumed that I could continue to use that token for development.

Hope your support.

**Comment by huan** [comment]
You can check whether your Puppet Service Token is valid by visiting the following API:

```sh
curl https://api.chatie.io/v0/hosties/__YOUR_TOKEN__
```

If you got a json with valid `ip` and `port` then your token is good.

Otherwise, your token is out of service.

**Comment by luyomo** [comment]
Thanks for your reply.
The response is 
{"ip":"0.0.0.0","port":0}

Looks it has been expired. 
How to extend the token since I have followed to publish one blog?

Of course I would like to do more open source as well.

BTW,
I failed to reach the Juzi.BOT. :)

**Comment by huan** [comment]
Yes, that means your token is our of service now.

Sad to know that you failed to contact with juzi bot, please feel free to contact @lijiarui on WeChat to join our contributors chat room, and get your new token from the wechaty contributor program!

**Comment by luyomo** [comment]
Huan

Thanks for your info. I tried to add lijiarui and messaged on the developer chat from last Friday. But no one replied to me so far.   Really need your help since I have a lot to try to implement with your wechaty.

**Comment by huan** [comment]
I'm sorry to hear about that your get no one reply to you so far.

I'd like to suggest that you can ping @lijiarui on WeChat and message the Juzi.BOT to see if you can reach them.

And also you can ask in our developer WeChat group, or in our Gitter room at https://gitter.im/wechaty/wechaty

**Comment by lijiarui** [comment]
@luyomo sorry for miss this issue, have you added my WeChat（ruirui_0914）? Kindly ping me on WeChat and send this issue to me.

And I will close this issue for now.
