### ISSUE TITLE
微信发送表情功能

### ISSUE THREAD

**Issue by 1334310385** [wechaty/wechaty#2126]
业务使用中希望能添加表情的发送
连天过程中表情是很重要的，希望能增加这个功能
谢谢

**Comment by huan** [comment]
Merge to #1513

**Comment by 1334310385** [comment]
没理解你的意思，是说还没做出来发送表情的功能吗？让我等，还是让我用wechat4u？

**Comment by InfTkm** [comment]
> 没理解你的意思，是说还没做出来发送表情的功能吗？让我等，还是让我用wechat4u？

huan意思这是一个重复的问题，两个问题合并一下，所以close了

**Comment by 1334310385** [comment]
显然我想要的答案是什么时候能有这个功能，或者有没有别的替代功能，而不是为什么close

**Comment by InfTkm** [comment]
> 显然我想要的答案是什么时候能有这个功能，或者有没有别的替代功能，而不是为什么close

根据那个issue的最新回复，现在阶段是等人写代码支持这个功能（因为是开源项目），所以没有一个准确时间
至于替代功能的话 你可以在那个issue里回复询问
