### ISSUE TITLE
exception when trying to add a Contact into a tag.

### ISSUE THREAD

**Issue by wenzai007** [wechaty/wechaty#2140]
while trying to use the sdk of add in tag.ts

```
await tag.add(contact);
```

**I got below exception, is this expected server error?? So Tecent does not allow this API?  Or I miss something?** 

00:12:59 ERR Tag add() exception: [tid:d8a97571] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d8a97571] wechat bad request error
(node:46652) UnhandledPromiseRejectionWarning: Error: add error : SubRequestCancelError: [tid:d8a97571] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d8a97571] wechat bad request error
    at WechatifiedTag.add (/Users/Knight/Working/github/padlocal-tagbased-bot/node_modules/wechaty/src/user/tag.ts:182:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by huan** [comment]
The tag function requires the puppet service to support it.

It seems that you are using the PadLocal puppet service, please contact the puppet service provider to check whether this feature is support or not.

**Comment by wenzai007** [comment]
@huan Thanks a lot for your quick reply! I will ask about that. A question, do we have a maintaining list for mapping of features enabled/notEnabled ---> puppet service provider ?    That would be very convinient.

**Comment by huan** [comment]
You are welcome.

We are trying to maintain a list for mapping of features, however, it's a lot of work to do.

You can read the following links for some basic tests feature list, and please help us to improve the wiki page if you feel there's anything missing.

https://github.com/wechaty/puppet-services/wiki/Basic-Test

**Comment by wenzai007** [comment]
thanks for the reference, I will wait for the reply from the puppet service provider firstly.

**Comment by padlocal** [comment]
PadLocal is supposed to support adding tag, we are analyzing your request and feedback soon

**Comment by padlocal** [comment]
@wenzai007 peer contact is not a friend with the bot.

**Comment by wenzai007** [comment]
@padlocal  Thanks a lot for your help!   Just a small tip, would it be possible to make the exception more clear so that the user will instantly get to know the reason of the exception?  :)

**Comment by padlocal** [comment]
@wenzai007 Ok, we will summarize the detailed error messages as we fixed emergent issues.

**Comment by leochen-g** [comment]
Same error happend

```
00:24:50 ERR [Request] [tid:5aef39b0], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:5aef39b0] wechat bad request error
00:24:50 ERR [AsyncBot] on error: VError: [tid:5aef39b0] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:5aef39b0] wechat bad request error
00:24:50 ERR Tag add() exception: [tid:5aef39b0] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:5aef39b0] wechat bad request error
Error: add error : SubRequestCancelError: [tid:5aef39b0] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:5aef39b0] wechat bad request error
at WechatifiedUserClass.add (file:///Users/**/node_modules/wechaty/src/user-modules/tag.ts:150:13)

```


Example

node: 16

wechaty: ^1.20.2

wechaty-puppet-padlocal" "^1.20.1"


```
const toContact = await bot.Contact.load(toUserId);
const tag = await bot.Tag.get("好友");
await tag.add(toContact);
```
