### ISSUE TITLE
添加群成员为好友

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#2142]
**Is your feature request related to a problem? Please describe.**
支持添加群内联系人为好友，可以便于针对群内不同用户进行针对性沟通。

**Describe the solution you'd like**
在任意群聊内，指定群成员添加为好友，并可附带一段好友验证消息。

**底层实现所需参数**
```
data: { 
  user_id: "78813xxxxx", // 传入user_id
  room_conversation_id: "R:1222121", //  用户所在群聊会话ID
  verify: "朋友推荐" // 验证消息
}
```

**接口设计**
```ts
// user/room.ts
public async addFriends (contact: Contact, hello: string): Promise<void>
```

```ts
const room = bot.Room.load('roomId')
room.addFriends(contact, 'hello')
```

**待讨论**
* 是否需要支持批量添加群成员的功能，可能会涉及到频率相关的问题
* 该方法基于哪个类进行实现
  * [x] Friendship
  * [ ] Contact
  * [ ] Room
* 方法命名
  * [ ] addMemberFriends()
  * [ ] memberFriends()

**Comment by huan** [comment]
Could you explain why you did not consider the following API in your request?

```ts
wechaty.Friendship.add(contact, 'hello')
```

**Comment by padlocal** [comment]
agree, because roomid is required while adding contact from room.

**Comment by su-chang** [comment]
出于以下几点考虑：
1. 添加群内成员为好友需要提供群ID，以联系人反查群ID相对复杂
2. `Friendship.add()` 方法一般配合 `Friendship.search()` 的结果来使用
3. 从添加群成员的使用场景考虑：
   * 接收到入群事件，直接通过当前room来调用`memberFriends()`方法
   * 接收到群成员消息，直接通过当前room来调用`memberFriends()`方法

**Comment by windmemory** [comment]
Maybe there is another alternative:

```ts
wechaty.Friendship.add(contact, 'hello', room);
```

The third parameter is optional.

**Comment by huan** [comment]
Yes, it will be better for us to keep all Friendship related operations encapsulating in the `Friendship` class.

I'd like to contribute a little more based on Yuan's version, by changing the second argument to an optional `options`.

```ts
interface FriendshipAddOptionsObj {
  room?: Room,
  contact?: Contact,
  hello?: string,
}

type FriendshipAddOptions = string | FriendshipAddOptionsObj

class Friendship {
  add (contact: Contact, options?: FriendshipAddOptions)
}
```

**Comment by su-chang** [comment]
`FriendshipAddOptionsObj`中的`contact`参数的作用是什么呢？

**Comment by huan** [comment]
You can safely ignore it for now, because it's `optional`.

And I believe it's not hard to guess the scenario in which it is required.

**Comment by su-chang** [comment]
This feature has supported in `wechaty@0.57.19`.
