### ISSUE TITLE
查询 一个好友是否在群时候发生问题

### ISSUE THREAD

**Issue by shaohongwu** [wechaty/wechaty#2144]
我目前使用的版本是
    node 版本：12.18.2
   服务器版本：centos 7
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^0.50.7",
    "wechaty-plugin-contrib": "^0.14.2"
我的代码
    const contact = await bot.Contact.find({ alias: contactName });
    const room101 = await bot.Room.load(roomId);
    await room101.sync();
    await room101.has(contact)
报错信息
   at /home/work/wechaty-getting-started/node_modules/wechaty/dist/src/user/room.js:836:42
   at Array.filter (<anonymous>)
   at WechatifiedRoom.has (/home/work/wechaty-getting-started/node_modules/wechaty/dist/src/user/room.js:836:14)

**Comment by huan** [comment]
Please post the full log message.
