### ISSUE TITLE
获取微信号错误

### ISSUE THREAD

**Issue by HG-Group** [wechaty/wechaty#2146]
WechatifiedContact {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 'wxid_g344rede8cws12',
    payload: {
      address: ' ',
      alias: '',
      avatar: 'http://wx.qlogo.cn/mmhead/ver_1/R4Fb8OKbkgJicsUqsibvPJlBgVxiaAb5hYXVpjBg119ljjibgXXqyonsA2I2k8bu3gQEXDJLAEs224ibQib9AbRIQMMQ2xsM7PQhvsTUwnP6KickAY/132',
      city: '',
      corporation: '',
      coworker: false,
      description: '',
      friend: false,
      gender: 0,
      id: 'wxid_g344rede8cws12',
      name: 'Isen',
      phone: [],
      province: '',
      signature: '',
      star: false,
      title: '',
      type: 1,
      weixin: ''
    },
    [Symbol(kCapture)]: false
  },

**Comment by huan** [comment]
Please fill the issue with our template so that other developers could understand your problem, thank you very much.

**Comment by Realzzz1874** [comment]
@huan I have the same problem today, I use `message.talker.weixin() ` to get ther contacts weixin but got `''`

**Comment by Realzzz1874** [comment]
> @huan I have the same problem today, I use `message.talker.weixin() ` to get ther contacts weixin but got `''`

get ther contacts ==> get the contacts
