### ISSUE TITLE
await message.mentionSelf() It always gets false

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [wechaty/wechaty#2149]
"wechaty": "^0.56.6"

await message.mentionSelf() It always gets false

**Comment by MashiroWang** [comment]
@zhihuifanqiechaodan +1
Is there any solution now?

**Comment by hookbin** [comment]
https://github.com/wechaty/wechaty/issues/1969#issuecomment-627088207
`
if(await msg.mentionSelf()) {...}
`
change to
`
// init account name on login
let loginUserName: string = ""
bot.on('login', (user: Contact) => { loginUserName = user.name()}

if(await msg.mentionSelf() || msg.text().includes(`@${loginUserName}`)){...}
`

**Comment by HolmanHuang** [comment]
i got same issute, it takes my for hours...

**Comment by huan** [comment]
It depends on what puppet you are using. See: https://wechaty.js.org/docs/puppet-providers/

And it might also related to #2247
