### ISSUE TITLE
why customer/list return empty list

### ISSUE THREAD

**Issue by zc10917** [wechaty/wechaty#2155]
I use juzimiaohui, and try to follow the doc https://docs.juzibot.com/customer/#%E8%8E%B7%E5%8F%96%E5%AE%A2%E6%88%B7%E5%88%97%E8%A1%A8

however this interface return empty list.
![image](https://user-images.githubusercontent.com/11190756/111630363-4061f700-882d-11eb-87e5-7ed9573ffb27.png)

I can not find out the reason, could you please help me out?

**Comment by huan** [comment]
Please contact the support from Juzi Miaohui.

I'll close this issue because it is not related to Wechaty.
