### ISSUE TITLE
Switch from grpc -> grpc-js

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2156]
We decided to use a pure JavaScript solution to get the maximum compatibility.

The codebase has been updated since `wechaty@0.59`

However, it might introduce BUGs, so please do not upgrade the Wechaty until the minor version is even, which means stable.

@wechaty/contributors @wechaty/juzi 

Link to:

- https://github.com/wechaty/grpc/issues/126
- https://github.com/wechaty/wechaty-puppet-service/issues/129

**Comment by huan** [comment]
## Update 7:00 pm Mar 19, 2021

Friday BOT switched to the latest Pure JS gRPC version: wechaty@0.59.3

**Comment by Codingxiaoshi** [comment]
我刚刚用 vue 测试了一下, 貌似有问题啊
```
 WAIT  Compiling...                                    下午6:10:51
98% after emitting CopyPlugin

 ERROR  Failed to compile with 4 errors                下午6:10:52
These dependencies were not found:

* console in ./node_modules/raven/lib/instrumentation/instrumentor.js
* dns in ./node_modules/@grpc/grpc-js/build/src/resolver-dns.js
* http2 in ./node_modules/@grpc/grpc-js/build/src/server.js
* module in ./node_modules/raven/lib/instrumentation/instrumentor.js

To install them, you can run: npm install --save console dns http2 module   
```
