### ISSUE TITLE
ERR PuppetService dirtyPayload() rejection: 2 UNKNOWN: Stream removed

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [wechaty/wechaty#2163]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: 0.56.6

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: puppet_wxwork

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: wechaty-puppet-service

> What is your node version? (run `node --version`)

Answer: v14.15.1

> What os are you using

Answer: mac os

## 2. Describe the bug

> 当我在onready生命钩子中获取群列表以及每个群的成员信息时发生了以下错误。尝试了重新安装包和重置juzi的token都没有办法修复以下问题

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

onReady 生命周期中获取群列表以及群成员信息

const chatbotRooms = await bot.Room.findAll()

chatbotRooms.forEach(async room => {
     const members = await room.memberAll()
});

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

16:01:18 ERR PuppetService dirtyPayload() rejection: 2 UNKNOWN: Stream removed
error in updateChatbotRooms Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 2,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'Stream removed'
}

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by huan** [comment]
In order to workaround your problem, you can try to rewrite your code from:

```ts
chatbotRooms.forEach(async room => {
   const members = await room.memberAll()
});
```

to:

```ts
for (const room of chatbotRooms) {
  const members = await room.memberAll()
  await room.wechaty.sleep(500)
}
```

If so, then you are running into https://github.com/wechaty/wechaty-puppet-service/issues/31

**Comment by zhihuifanqiechaodan** [comment]
> In order to workaround your problem, you can try to rewrite your code from:
> 
> ```ts
> chatbotRooms.forEach(async room => {
>    const members = await room.memberAll()
> });
> ```
> 
> to:
> 
> ```ts
> for (const room of chatbotRooms) {
>   const members = await room.memberAll()
>   await room.wechaty.sleep(500)
> }
> ```
> 
> If so, then you are running into [wechaty/wechaty-puppet-service#31](https://github.com/wechaty/wechaty-puppet-service/issues/31)

加入上面的代码进行尝试，10次中会有8次还是报上述的问题，有两次是没问题的。 并且我在获取微信全部联系人的时候还报出了以下错误
```
Error: 13 INTERNAL: no wxwork dao
    at Object.exports.createStatusError (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/cctvabu/renhejituan/chatbot_ale/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 13,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'no wxwork dao'
}
19:12:16 ERR Contact this.wechaty.puppet.contactFindAll() rejected: 13 INTERNAL: no wxwork dao
19:13:11 WARN Puppet dogReset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_READY)","timeout":60000}
```

**Comment by huan** [comment]
> 加入上面的代码进行尝试，10次中会有8次还是报上述的问题，有两次是没问题的。 

What if you increase the sleep time, say, `await room.wechaty.sleep(5000)`?

> Error: 13 INTERNAL: no wxwork dao

This is new to me, I'd like to suggest that you contact your puppet service provider.

**Comment by zhihuifanqiechaodan** [comment]
> > 加入上面的代码进行尝试，10次中会有8次还是报上述的问题，有两次是没问题的。
> 
> What if you increase the sleep time, say, `await room.wechaty.sleep(5000)`?
> 
> > Error: 13 INTERNAL: no wxwork dao
> 
> This is new to me, I'd like to suggest that you contact your puppet service provider.

Ok, let me keep trying and see
