### ISSUE TITLE
Room.read() and Contact.read() feature request

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty#2166]
**Is your feature request related to a problem? Please describe.**
I would like to suggest a feature that enable `Wechaty` to mark a message as read.

**Describe the solution you'd like**
Add a method on `Message` class called `read()`, which would mark the given message as read.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
N/A

[enhancement]

**Comment by windmemory** [comment]
Seems like the underlying api is mark a conversation to be read. So maybe we should add these two APIs:

`Room.read()`
`Contact.read()`

**Comment by binwan-dev** [comment]
conversationReadMark is unspport ?
![image](https://github.com/wechaty/wechaty/assets/45676208/5d7b98a0-e67f-4eba-9911-3d62841235ac)
