### ISSUE TITLE
Prepare to rename the nick/remark/display for contact/room

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#217]
Now we have three name type:
1. `nick`
1. `remark`
1. `display`

When we put the named together, they make us feel confusing, because it is not very clear which one is stands for what.

I think Wechaty should rename those names to the most understand names, instead of the names from the webwxApp code.

What's in my mind now, is that:
1. the name-string set by user his/her-self, should be called `name`(before is `nick`)
1. the name-string set by userself in a room, should be called `nick`(before is `display`). `nick` only belongs to the room.
1. the name-string set by others, should be called `alias` (before is `remark`)

If anyone has any suggestion/recommendation,  please let me know. Thanks.

**Comment by zixia** [comment]
@lijiarui How do you think about this?

**Comment by lijiarui** [comment]
I think it is good, maybe DC can give a good suggestion.

**Comment by zixia** [comment]
According to the reply of Rahim Nathwani from Google:

> In the English version of WeChat, those strings are:
> Name
> My Alias in Group
> Alias
> 
> So I suggest keeping it consistent with that, e.g.
> - bot_name
> - bot_alias
> - user_alias

and

> Perhaps I've misunderstood what the three terms in the GitHub issue mean, but it seems you want to distinguish on two dimensions:
> - name vs. alias
> - self or other (自己或其他人)

I want to keep the names more simple from 3 to 2: get rid of _nick_ , only keep _name_ & _alias_

1. the name-string set by user-self, should be called **name**
1. the name-string set by user-self in a room, should be called **room alias**. **room alias** only belongs to the room.
1. the name-string set by bot for others(original remark), should be called **alias**

If we follow the above new naming design, we will have the following changes for the current code base:

1. `Contact.remark()` will change to `Contact.alias()`
1. `Room.nick()` will change to `Room.alias()`
1. `Room.member()` query key will also need to change to the new name design

**Comment by zixia** [comment]
After a week, I believe that to use `alias` is a good decision. We will not have ~~remark~~ and ~~nick~~ anymore.

PR is welcome.

**Comment by lijiarui** [comment]
I thought it should be designed as follows:

####  `Room.alias()` should return contact's roomAlias
If the contact doesn't set its roomAlias in the room, it should return null.     
Because we can use `contact.name()` to get the contact's name.     
And we can use `contact.alias()` to get the contact's alias. 

#### `Room.member()` query key should consider on two dimensions:

* self-set: {name: string}
* other-set: {alias: string}

If one doesn't set query key, should use self-set by default,  it means`Room.member(string) = Room.member({name:string})`

**Comment by zixia** [comment]
Great.

It's a very clear design, LGTM.

**Comment by lijiarui** [comment]
Modify:

#### `Room.alias()` should return contact's roomAlias or name

If the contact doesn't set its roomAlias in the room, it should return name, not null

**Comment by zixia** [comment]
@lijiarui next u need to confirm your old bot code could run with the latest master code after ur PR.

esp. with the deprecated API.

After confirmation, please close this issue. 

Thanks.

**Comment by lijiarui** [comment]
@zixia I have tested my old project, it works well, but my project doesn't use `alias()`, but I have tested this function.  

If others find these function doesn't work, let me know.

Btw, this issue can be closed only by you, I don't have the permission.

**Comment by lijiarui** [comment]
@zixia  I think maybe we should keep three kind of name in the room.
besides `name` and `alias`, we should also add `display`

Then we can find the contact by name, alias, and display.

What's your concern?

**Comment by zixia** [comment]
please submit an new issue to talk about this.

and i don't understand what is "contact's version in a room"
