### ISSUE TITLE
登录成功之后监听到错误发生，服务一直重启，使用后续功能异常

### ISSUE THREAD

**Issue by brujie** [wechaty/wechaty#2170]
login success, user: Contact<userName>
logout user: Contact<userName>, reason : PuppetService stop()
login success, user: Contact<userName>
logout user: Contact<userName>, reason : PuppetService stop()
login success, user: Contact<userName>

**Comment by Genening** [comment]
the same issue
have you fix it？

**Comment by brujie** [comment]
时间很久了，我已经换其它方式了。



---原始邮件---
发件人: "ZHANG ***@***.***&gt;
发送时间: 2024年4月2日(周二) 凌晨3:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [wechaty/wechaty] 登录成功之后监听到错误发生，服务一直重启，使用后续功能异常 (#2170)




 
the same issue
 have you fix it？
