### ISSUE TITLE
发送的小程序卡片消息,打开提示加载小程序信息超时,无法启动

### ISSUE THREAD

**Issue by yuanbolin** [wechaty/wechaty#2174]
if (msg.text() === '小程序') {                        //padlocal
const miniProgram = new MiniProgram ({
appid : 'wx72946e501ff84a0d',
username : 'gh_63f457d623f5',
title : '涂色本',
description : '涂色本'
});
log.info('say:miniProgram:', msg.from(), miniProgram)
await msg.say(miniProgram);
}

我们通过用户发送消息，推送小程序卡片时，对方无法打开。
官方的示例，直接报错，无法成功推送过去；调整后，可以推送，但是对方无法打开
肯定官方帮忙看看~谢谢

**Comment by justsosoG** [comment]
解决了么，怎么解决的

**Comment by huan** [comment]
Merge to:

- #2064
