### ISSUE TITLE
Need a room listener for announcement updates

### ISSUE THREAD

**Issue by yangjiang3973** [wechaty/wechaty#2180]
**Is your feature request related to a problem? Please describe.**

I need to collect data from many room's announcement(群公告), but now there is no room listener for announcement changes.

So in order to get the latest announcement of a room, I need to listen to all messages and check if it is the one triggered by the update of announcement.

**Describe the solution you'd like**
Add a room listener for announcement's update.

For example:

```js
room.on('announce', (room, oldAnnounce, newAnnounce) => {
   console.log('the announcement was changed');
  })
``` 

**Describe alternatives you've considered**
If this is feasible but you do not have time to implement, maybe you can give me some hints and I will try to create a PR for this new feature.

Thanks!

**Comment by huan** [comment]
Thanks for the feature request! (related to #2116)

The implementation will heavily depend on the Wechaty Puppet Providers, I'm not sure whether we can get the `oldAnnouncement` when we modify it.

I'd like to suggest that you read the following posts before you prepare your PR:

1. [Introducing Wechaty Puppet Service (Providers), @huan, Jan 14, 2021](https://wechaty.js.org/2021/01/14/wechaty-puppet-service/)
2. https://wechaty.js.org/docs/puppet-providers/diy

**Comment by yangjiang3973** [comment]
@huan No problem, I will start reading the posts you suggested.

I feel the `oldAnnouncement` parameter is not really necessary, because I can always store all past announcements in database as a history. But the `listener` for room announcement is really needed.

By the way, right now is there any smart way to check new announcement?  My hacky solution is to listen to all messages and check if it mentions all members. If so, I call `await room.announce()` to get announcement again and update it in database.

**Comment by huan** [comment]
Thanks for working on this announcement new feature!

For now, there has no smart way to check new announcements, so I believe the `announce` event is a good way to archive that. (please also see the related discussion at #2116)
