### ISSUE TITLE
Wechaty主分支依赖的Wechaty-Puppet和Wechaty-Puppet目前的NPM版本不一致

### ISSUE THREAD

**Issue by 0x7a7a** [wechaty/wechaty#2183]
Wechaty主分支目前依赖的是`^0.35.1 `
而目前Wechaty-Puppet目前NPM上的版本是`0.34.3  `

我自己实现的Puppet继承自`0.34.3`版本(NPM能下载到的非next的最新版本),所以在实际使用的时候会出现报错
```typescript
const puppet = new CustomPuppet({
    token: 'token'
}) as Puppet
const bot = new Wechaty({ puppet })
```
会得到一个错误:
```shell
Type 'CustomPuppet' is not assignable to type 'Puppet'.
Property 'options' is protected but type 'Puppet' is not a class derived from 'Puppet'.
```
我想问下是因为Wechaty-Puppet版本不一致导致的问题吗?

**Comment by huan** [comment]
> 我想问下是因为Wechaty-Puppet版本不一致导致的问题吗?

The short answer is: YES.

I believe you are running into https://github.com/wechaty/wechaty/issues/2090 .

Please update your Puppet version to the same version that the Wechaty is using, and to see if it can solve your problem.

**Comment by 0x7a7a** [comment]
> Please update your Puppet version to the same version that the Wechaty is using, and to see if it can solve your problem.
但是目前npm上`wechaty-puppet`版本只有0.34.3,我是要使用`wechaty-puppet`的next版本么?还是等你们重新发布一个大于0.35版本的`wechaty-puppet`

**Comment by 0x7a7a** [comment]
我手动指定了`^0.35`版本,解决问题了.  
建议latest标签的版本可以升级到0.35以上,和`wechaty`所依赖的最低版本可以一致

**Comment by huan** [comment]
Glad to know that you have solved this issue, cheers!

I'd love to accept a PR to update the version to 0.35, please feel free to create one if you like to.

Thank you very much!

**Comment by 0x7a7a** [comment]
我需要研究下`wechaty-puppet`的发布机制,之后会提交一个pr试试
