### ISSUE TITLE
A 'declare' modifier cannot be used in an already ambient context.

### ISSUE THREAD

**Issue by xQuotes** [wechaty/wechaty#2184]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: 0.60.5

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: wechaty-puppet-wechat

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: ^0.28.1

> What is your node version? (run `node --version`)

Answer: v15.14.0

> What os are you using

Answer:

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. run '...'
2. ...
3. ...

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
node_modules/wechaty/src/io-peer/json-rpc-peer.d.ts:17:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

17   declare module 'json-rpc-peer' {
     ~~~~~~~

node_modules/wechaty/src/io-peer/json-rpc-peer.d.ts:66:5 - error TS2666: Exports and export assignments are not permitted in module augmentations.

66     export default Peer
       ~~~~~~


Found 2 errors.

error Command failed with exit code 2.
```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by huan** [comment]
According to <https://stackoverflow.com/a/17190172/1123955>, we try to remove the `declare` and please let me know if your issue solved.

**Comment by xQuotes** [comment]
tks

**Comment by huan** [comment]
You are welcome!
