### ISSUE TITLE
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('service server is invalid ... ', None, None)

### ISSUE THREAD

**Issue by 5118Python** [wechaty/wechaty#2188]
![image](https://user-images.githubusercontent.com/14151451/117931216-7f925d00-b331-11eb-9771-5609fa09aea3.png)

最近一直提示这个消息，没有办法正常登陆

**Comment by xiuxiu** [comment]
遇到了一样的问题
