### ISSUE TITLE
Adding Open Graph image metadata in the docusaurus site of wechaty.js.org

### ISSUE THREAD

**Issue by iamrajiv** [wechaty/wechaty#2190]
## 🚀 Feature

When we share https://wechaty.js.org over social media, it is good that the card they generate for the link has useful information.

#### Facebook:

![Screenshot 2021-05-23 at 6 54 01 PM](https://user-images.githubusercontent.com/42106787/119262307-5eb2ed00-bbf8-11eb-89c9-d84136470932.jpg)

#### LinkedIn:

![Screenshot 2021-05-23 at 6 53 28 PM](https://user-images.githubusercontent.com/42106787/119262309-61addd80-bbf8-11eb-845e-d7f54067e550.jpg)

#### Twitter:

![Screenshot 2021-05-23 at 6 53 37 PM](https://user-images.githubusercontent.com/42106787/119262313-66729180-bbf8-11eb-9202-90477f783351.jpg)

### References:

- Use https://developers.facebook.com/tools/debug/ to validate results for Facebook.
- Use https://www.linkedin.com/post-inspector/ to validate results for LinkedIn.
- Use https://cards-dev.twitter.com/validator to validate results for Twitter.

**Comment by iamrajiv** [comment]
@huan Please take a look.

**Comment by huan** [comment]
Thanks for raising this issue!

I agree with you that we should have a beautiful Open Graph Image in our metadata.

However, I feel this should be done by the Docusaurus system, and I believe that the Docusaurus should have already supported this.

Could you please have a check on Docusaurus to see if it supports it, and how can we add config in our site?

Thank you very much.

**Comment by iamrajiv** [comment]
Hi @huan, I have resolved this issue and created a PR on this. Do take a look.

**Comment by iamrajiv** [comment]
Hi @huan, I have resolved this issue and created a PR on this. Do take a look.
