### ISSUE TITLE
不兼容浏览器环境的watchdog库

### ISSUE THREAD

**Issue by ismanong** [wechaty/wechaty#2191]
您好！
项目通过Electron运行，通过渲染进程非node环境运行，
会出现这个错误 ：Uncaught TypeError: this.timer.unref is not a function

您依赖的库：https://github.com/huan/watchdog/issues/31

其他方面都运行健康

![image](https://user-images.githubusercontent.com/13862699/119586419-3e08b400-bdff-11eb-8476-403ee5cf6082.png)

**Comment by huan** [comment]
Thanks for the reporting!

Should be fixed with watchdog@0.8.21 and above.

See: https://github.com/huan/watchdog/issues/31
