### ISSUE TITLE
wxwork不能获取也不能发送小程序

### ISSUE THREAD

**Issue by xuwancheng** [wechaty/wechaty#2198]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 1. Versions

> What is your wechaty version?

Answer: 0.62.3

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: wxwork， 企业微信

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: wxwork

> What is your node version? (run `node --version`)

Answer: v14.12.0

> What os are you using

Answer: windows10

## 2. Describe the bug

> Bug1：在OnMessage回调函数中，打印msg内容，得到如下信息，没有小程序的信息, payload.text为空，
[{"_events":{},"_eventsCount":0,"id":"1000985","payload":{"filename":"","fromId":"7881302397907992","id":"1000985","mentionIdList":[],"roomId":"","text":"","timestamp":1623757181000,"toId":"1688850865025043","type":9}}]

Bug2: 我用donut的token却是可以获取到相应的小程序的信息的，然后我就分别用这个小程序的信息用donut和wxwork的分别发送，donut可以发送成功，但是wxwork的发送不成功，提示信息是：
Can not send mini program with wrong thumbKey, example: '{"key1":"xxx","key2":"xxx","key3":"xxx","size":1}'

## 3. To Reproduce

> wxwork无法发送小程序，提示wrong thumbKey， 该怎么获取到正确的thumbKey呢？

## 4. Expected behavior

> wxwork可以发送小程序

## 5. Actual behavior

> 确认一下，wxwork现在可否发送小程序？

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> PASTE YOUR FULL(DO NOT ONLY PROVIDE FRAGMENTS) LOG MESSAGES HERE

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by su-chang** [comment]
调用 `message.toMiniProgram()` 获取接收到的小程序详细信息。发送小程序需要先接收一次对应的小程序拿到参数后，即可发送。

**Comment by xuwancheng** [comment]
调用message.toMiniProgram()确实获取到了小程序的详细信息，请问一下，我在哪里可以找到企业微信的相关的资料呢（这个方法我没有找到），万分感谢！

**Comment by su-chang** [comment]
[wechaty接口文档](https://wechaty.js.org/docs/api/)，对于企微和个微都是通用的。目前部分接口没有在文档中同步，建议最好直接看wechaty对应源码，代码中每个方法都有详细的使用案例。

**Comment by xuwancheng** [comment]
好的，谢谢

**Comment by Hanhanhan11** [comment]
> [wechaty接口文档](https://wechaty.js.org/docs/api/)，对于企微和个微都是通用的。目前部分接口没有在文档中同步，建议最好直接看wechaty对应源码，代码中每个方法都有详细的使用案例。

Hi,你好，我跑了程序用企业微信扫描二维码 想成为机器人，没有成功，请问是这个wechaty接口不试用么？

**Comment by su-chang** [comment]
> Hi,你好，我跑了程序用企业微信扫描二维码 想成为机器人，没有成功，请问是这个wechaty接口不试用么？

你用的token是以 `puppet_wxwork` 开头的么？只有此类token才能支持企业微信登录。

**Comment by slq123** [comment]
const bot = new Wechaty({
puppet: 'wechaty-puppet-service',
puppetOptions: {
token: 'puppet_hostie_gdg_zhengzhou',

},
})
你好，是修改这里的token吗？token生成是要购买吗？

**Comment by Hanhanhan11** [comment]
> > Hi,你好，我跑了程序用企业微信扫描二维码 想成为机器人，没有成功，请问是这个wechaty接口不试用么？
> 
> 你用的token是以 `puppet_wxwork` 开头的么？只有此类token才能支持企业微信登录。

const bot = new Wechaty({
puppet: 'wechaty-puppet-service',
puppetOptions: {
token: 'puppet_hostie_gdg_zhengzhou',

},
})
老师，您好，请问此类token生成是需要购买的么？  是在上面的代码段里进行修改嘛？

**Comment by su-chang** [comment]
如果需要使用企业微信的话，token是需要购买的，免费的是个微微信（web版）。

对的，替换token即可。
