### ISSUE TITLE
build failed. info:error TS2416: Property 'set' in type 'MemoryCard' is not assignable to the...

### ISSUE THREAD

**Issue by Saraiby** [wechaty/wechaty#2199]
## 1. Versions

> What is your wechaty version?

Answer:0.62.3

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:WeChat4U

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:wechat4u@0.7.7

> What is your node version? (run `node --version`)

Answer:v14.16.0

> What os are you using

Answer:windows 10

## build error

```
node_modules/memory-card/dist/src/memory-card.d.ts:82:5 - error TS2416: Property 'set' in type 'MemoryCard' is not assignable to the same property in base type 'AsyncMapLike<any, any>'.
  Type '<T = any>(name: string, data: T) => Promise<this>' is not assignable to type 'AsyncifyMapFunction<any, any, (key: any, value: any) => Map<any, any>>'.
    Type 'Promise<this>' is not assignable to type 'Promise<AsyncMapLike<any, any>>'.
      Type 'this' is not assignable to type 'AsyncMapLike<any, any>'.
        Type 'MemoryCard' is missing the following properties from type 'AsyncMapLike<any, any>': [Symbol.iterator], [Symbol.toStringTag]

82     set<T = any>(name: string, data: T): Promise<this>;
```

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. nest g application test-wechaty
2. npm install 
3. npm i wechaty
4. nest build
5. error...

**Comment by Richardn2002** [comment]
Met the identical issue with puppet `wechaty-puppet-wechat`

**Comment by Richardn2002** [comment]
Possible fix: Add

```js
[Symbol.iterator]<T = any>(): AsyncIterableIterator<[string, T]>;
[Symbol.toStringTag]: Promise<string>;
```

before the line that generates the error. As it is unconventional to modify library codes, I'm not sure about all the side-effects of this fix. From my limited testing after the fix the error is eliminated and wechaty including memory cards is functioning well.

**Comment by huan** [comment]
Thanks for the reporting.

Could you please confirm that whether this problem is still existing with `wechaty@0.68.1`?

**Comment by Saraiby** [comment]
```wechaty@next``` is ok. thx.

**Comment by huan** [comment]
Thank you very much for the confirmation, appreciate it.
