### ISSUE TITLE
await bot.Contact.find({ alias }) & await bot.Contact.find({ name }) return null.

### ISSUE THREAD

**Issue by snow-sprite** [wechaty/wechaty#2200]
## 1. Versions

> What is your wechaty version?

Answer: "wechaty": "^0.60.10"

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:"wechaty-puppet-wechat": "^0.28.1"

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: "wechaty-puppet-wechat": "^0.28.1"

> What is your node version? (run `node --version`)

Answer: v12.19.0

> What os are you using

Answer: windows 10

## 2. Describe the bug

> Give a clear and concise description of what the bug is.
```
const tempFriend = (await bot.Contact.find({ alias })) || (await bot.Contact.find({ name }))
```
tempFriend is null.

**Comment by Richardn2002** [comment]
Load the contact list after the `ready` event of the bot. Example:

```js
async function onReady() {
    console.log(await bot.Contact.find({alias: your-friends-alias}));
}
bot.on('ready', onReady);
```

`wechaty-puppet-wechat` needs time to fully load the contact list.

**Comment by snow-sprite** [comment]
> Load the contact list after the `ready` event of the bot. Example:
> 
> ```js
> async function onReady() {
>     console.log(await bot.Contact.find({alias: your-friends-alias}));
> }
> bot.on('ready', onReady);
> ```
> 
> `wechaty-puppet-wechat` needs time to fully load the contact list.

thx, It's been solved.
