### ISSUE TITLE
当群聊天中有企业微信号，机器人就收不到这个群的消息了

### ISSUE THREAD

**Issue by lcl-101** [wechaty/wechaty#2205]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
当群聊天中有企业微信号，机器人就收不到这个群的消息了

**Comment by huan** [comment]
I believe this depends on what Puppet are you using.

For example, the [wechaty-puppet-wechat](https://wechaty.js.org/docs/puppet-providers/wechat/) can not receive messages from a mixed room, but the [wechaty-puppet-padlocal](https://wechaty.js.org/docs/puppet-providers/padlocal/) will work without any problem.
