### ISSUE TITLE
Room.member

### ISSUE THREAD

**Issue by 0kuang** [wechaty/wechaty#2209]
**Is your feature request related to a problem? Please describe.**
我想通过正则表达式匹配群里的某些用户

**Describe the solution you'd like**
为member，memberAll添加正则支持，或将memberList方法public，开发者可以更自由的实现功能。

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by huan** [comment]
I believe you can achieve this by the following code:

```ts
const jack = await room.member({ name: /Jack/i })
```

Please let me know if it works for you or not.

**Comment by WindStill** [comment]
> I believe you can achieve this by the following code:
> 
> ```ts
> const jack = await room.member({ name: /Jack/i })
> ```
> 
> Please let me know if it works for you or not.

Not work:

`const jack = await room.member({ name: /Jack/i })`
`const jack = await room.member(/Jack/i)`
`const jack = await room.memberAll({ name: /Jack/i })`
`const jack = await room.memberAll(/Jack/i)`

**Comment by huan** [comment]
@WindStill what's the output when you call `room.memberAll()`, does it get the member list? Does it contains the contact you want to search?

**Comment by WindStill** [comment]
> @WindStill what's the output when you call `room.memberAll()`, does it get the member list? Does it contains the contact you want to search?

比如群里成员的群昵称分别为：张三-软件、李四-硬件、王五-软件

关键字为『软件』的时候，期望room.memberAll('软件') 返回 『张三-软件、王五-软件』

但是以下4种方式，都返回空，匹配不到群昵称包含『软件』的成员：
```
room.member({ roomAlias: /软件/i })
room.member(/软件/i)
room.memberAll({ roomAlias: /软件/i })
room.memberAll(/软件/i)
```

只能通过完整的昵称来匹配。

**Comment by huan** [comment]
Thanks for the reporting.

Your statement is related to the below code:

https://github.com/wechaty/wechaty/blob/dcdcab2468f4a038d10b39360dc4771a5239fbb0/src/user-modules/room.ts#L989-L1000

The puppet code is at 

https://github.com/wechaty/puppet/blob/b5c101ccdc664907b62993b636e2b37eaa39436d/src/mixins/room-member-mixin.ts#L36-L125

Please feel free to take a look at the above code and help us to point the problem out.

Thank you very much.
