### ISSUE TITLE
Contact.findAll() return contactList includes oa account

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#222]
### Expected behavior
use function `Contact.findAll()` to get all the contact list.
It should return all my real contact, shouldn't include oa account

### Actual behavior
`Contact.findAll()` return the contactLIst includes oa account.

**Comment by zixia** [comment]
Wechat(webwxApp) always treat all contact(include OA account) as the same.

So the implementation of Wechaty in the current version, OA Account is also a Contact.

I'll close this issue for now. In the future, you can purpose a new design to separate the Contact type, and we can discuss based on that.
