### ISSUE TITLE
wechat banned my account when login via web wechat secondly😂

### ISSUE THREAD

**Issue by bruceeewong** [wechaty/wechaty#2221]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

拿小号在本地docker跑首页bot.js的示例，登录一次后退出，再次登录提示这个异常：

```
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
```

亲自打开wechat web试了下，依旧如此😂

难道是微信已经做了检测查封机制吗，还好是用的小号登录=。=，求解！

**Comment by mice2100** [comment]
用手机在同一个IP登陆几天再用web登陆

**Comment by huan** [comment]
You are running into https://github.com/wechaty/wechaty-puppet-wechat/pull/130

Using the latest version of wechaty should fix your problem.
