### ISSUE TITLE
二维码链接在浏览器中打开提示 “无法识别的二维码“ 怎么回事呢 

### ISSUE THREAD

**Issue by terryxuwen** [wechaty/wechaty#2224]
运行docker run -ti --rm --volume="$(pwd)":/bot wechaty/wechaty mybot.js
复制生成的二维码链接 到浏览器打开，浏览器里面的图片是奇怪的打着红叉叉的二维码图片，下放文字是 无法识别的二维码

mybot.js 的代码 就是https://wechaty.gitbook.io/wechaty/v/zh/ 提供的 6行 示范代码

**Comment by huan** [comment]
Please use the Wechaty official getting started: https://github.com/wechaty/wechaty-getting-started , which will always be the latest version and should work without any problem.
