### ISSUE TITLE
企业微信用户利用Wechaty成为机器人

### ISSUE THREAD

**Issue by Hanhanhan11** [wechaty/wechaty#2229]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
下载并运行了代码：https://github.com/wechaty/wechaty-getting-started， 然后用企业微信用户扫描生成的二维码，失败了，请问是这个不能用于企业微信用户成为机器人么？还是要使用 这个代码： https://github.com/wechaty/wechaty  呢？

**Comment by lijiarui** [comment]
Did you use correct token and puppet for wxwork?

See: https://wechaty.js.org/docs/examples/basic/starter-bot

**Comment by Hanhanhan11** [comment]
企业微信扫描提示要用微信扫描

**Comment by lijiarui** [comment]
Please give us the reproduce code here.

**Comment by slq123** [comment]
const bot = new Wechaty({
  puppet: 'wechaty-puppet-service',
  puppetOptions: {
    token: 'puppet_hostie_gdg_zhengzhou',
  
  },
})
你好，李老师，是修改这里的token吗？token生成是要购买吗？

**Comment by slq123** [comment]
const bot = new Wechaty({
puppet: 'wechaty-puppet-service',
puppetOptions: {
token: 'puppet_hostie_gdg_zhengzhou',

},
})
你好，李老师，是修改这里的token吗？token生成是要购买吗？

**Comment by slq123** [comment]
> Please give us the reproduce code here.
function onLogin (user) {
    log.info('StarterBot', '%s login', user)
    //每分钟的第30秒定时执行一次:
    schedule.scheduleJob('30 * * * * *',()=>{
       log.info('小助理开始工作啦！');
       console.log('scheduleCronstyle===========================================================:' + new Date());
       main()
    });

}
// 群发名单
const contactArr = [
  // '自己维护的群发名单'
  '三大开车手'
 ]
// 定时任务
const main = async() => {
  
   contactArr.forEach(async (v) => {
    const contact = await bot.Contact.find({
      alias: v
    })
    console.log('text==：'+ contact);
    const text = blessing(v)
    console.log('text=======大师傅师傅：'+ text);
    await contact.say(`${text}`)
  })


 }
 // 新年祝福语随机函数
function blessing(peo) {
  const arr = [
    `猪年到来踌躇满，志向高远可比天。新年到来运气变，霉运远离好运伴。万事顺利赚大钱，家庭美满笑开颜。健康平安在身边，幸福生活到永远。${peo}, 祝你猪年心想事成，快乐无边。`,
    `${peo}, 猪年祝你：工作舒心，薪水合心，被窝暖心，朋友知心，爱人同心，一切都顺心，永远都开心，事事都称心。`,
    `${peo}新年好，祝你：身体健康，万事如意，合家欢乐，生活美满，事业有成，珠玉满堂，多寿多富，财大气粗，攻无不克，战无不胜。`
  ]
  return arr[Math.floor(Math.random()*arr.length)]
}
exports.blessing = blessing

你好，李老师，机器人定时任务自动群发，没有发送出来？如何解决机器人定时任务自动对多个群群发呢？

**Comment by haydenzhourepo** [comment]
@lijiarui  hello, I am using wechaty with wechaty-puppet-wechat , my bot awalys auto logout after 1 day's normal running.  how can i persist the log in status. thx~.

**Comment by lijiarui** [comment]
Hi @haydenzhourepo 

This issue is talking about Wecom, which puppet is wechaty-puppet-service(Using wechaty-pippet-wxwork token). 

Please feel free to create a new issue talking about how to persist the log. (But do give more information)

**Comment by lijiarui** [comment]
@Hanhanhan11 Do you have any other problems using WeCom? 

Feel free to ask more questions and @su-chang would like to reply.

**Comment by zhiyuan081632** [comment]
> 企业微信扫描提示要用微信扫描

请问你的这个问题解决了吗？如何解决的？我也想用企业微信用户接入机器人自动回复。
