### ISSUE TITLE
Coverage not working with ESM & TAP: 'error from lcovParse: ' 'Failed to parse string'

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2242]
See the latest GitHub Actions: https://github.com/wechaty/wechaty/runs/3476470068?check_suite_focus=true#step:6:7

```sh
Run coverallsapp/github-action@master
Using lcov file: ./coverage/lcov.info
Error:  "2021-08-31T18:46:07.292Z"  'error from lcovParse: ' 'Failed to parse string'
Error:  "2021-08-31T18:46:07.293Z"  'input: ' ''
Error:  "2021-08-31T18:46:07.293Z"  'error from convertLcovToCoveralls'
Error: Failed to parse string
```

It fails with the empty input after we switched to ES Modules:

- #2232

It might be related to https://github.com/tapjs/node-tap/issues/545

**Comment by Prenuer** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>
