### ISSUE TITLE
npm audit find Command Injection     

### ISSUE THREAD

**Issue by flameleo11** [wechaty/wechaty#2243]
🚨 The issue tracker is not for questions 🚨

npm audit 

  "devDependencies": {
    "wechaty": "^0.69.34",
    "wechaty-puppet-wechat": "^0.28.4"
  }

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ npm-programmatic                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty > npm-programmatic                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1507                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 5 vulnerabilities (4 low, 1 critical) in 634 scanned packages
  run `npm audit fix` to fix 4 of them.
  1 vulnerability requires manual review. See the full report for details.

**Comment by flameleo11** [comment]
reinstall & test another version 

  "devDependencies": {
    "wechaty": "^0.68.1",
    "wechaty-puppet-wechat": "^0.28.4"
  }
}

stil cant fix these Command Injection   
if run npm audit fix, then start will throw a error



npm audit 
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev wechaty@0.69.34  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mem                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty > in-gfw > mem                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1084                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ npm-programmatic                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wechaty [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wechaty > npm-programmatic                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1507                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 2 vulnerabilities (1 low, 1 critical) in 617 scanned packages
  run `npm audit fix` to fix 1 of them.
  1 vulnerability requires manual review. See the full report for details.

**Comment by huan** [comment]
Thanks for your reporting!

We have removed the dependency of `npm-programmatic` for our future versions.
