### ISSUE TITLE
支持 Location 消息的相关操作

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#2250]
wechaty目前仅有 `Location` 的消息类型，但是没有对应的方法获取到具体消息内容。

### wechaty-puppet
增加 LocationPayload 数据结构

```ts
interface LocationPayload {
  address: string;
  latitude: number;
  longitude: number;
  name: string;
  precision: number; // 精度层级信息
}

messageLocation(): Promise<LocationPayload>
messageSendLocation(locationPayload: LocationPayload): Promise<void | string>
```

### wechaty
增加 toLocation() 方法，say() 方法支持 `Location` 类型

```ts
toLocation(): Promise<LocationPayload>
```

### Related PR Link
- [x] https://github.com/wechaty/wechaty/pull/2251
- [x] https://github.com/wechaty/wechaty-puppet/pull/150
- [x] https://github.com/wechaty/grpc/pull/153
- [x] https://github.com/wechaty/wechaty-puppet-service/pull/166
- [x] https://github.com/wechaty/wechaty-puppet-mock/pull/46

**Comment by huan** [comment]
Should we have the `altitude` information in the `Location`?

How to define `precision`? For example, the Android API has an `accuracy`, it the estimated horizontal accuracy of this location, radial, in meters.

**Comment by su-chang** [comment]
You are welcome.

For questions:
1. WxWork not support `altitude` now, let's add it when some puppet could support it.
2. Agree with use `accuracy` replace `precision`, for now, I have not found the convert method from `precision` to `accuracy`. Maybe we could get the `accuracy` in Android API and `precision` in WxWork with the same position.

**Comment by su-chang** [comment]
@huan ping

**Comment by huan** [comment]
## Accuracy

Let's use this term and define it as the same as Android and IOS:

- estimated horizontal accuracy of this location, radial, in meters.

See:

1. [Android Developers > Docs > Reference > Location > getAccuracy](https://developer.android.com/reference/android/location/Location#getAccuracy())
    > estimated horizontal accuracy of this location, radial, in meters.
2. [Stackoverflow](https://gis.stackexchange.com/q/25115)
    > Both iOS and Android can derive location from a combination of cell tower triangulation, visible wifi access points, and assisted GPS. The location APIs return a lat/long and an "accuracy" number in meters.

## To support 3D in the future

Currently, our design is 2D only, which means we lack the `altitude`.

We can add it in the future when we need it.

**Comment by huan** [comment]
All PRs have been merged, please feel free to keep improving them, and I'm looking forward to seeing the new functions to be implemented!

**Comment by su-chang** [comment]
I have to reopen this issue, and after these new PRs have been merged then we could close this issue.

**Comment by huan** [comment]
No problem, let's continue improving this feature based on this issue.

**Comment by huan** [comment]
All PRs have been merged.
