### ISSUE TITLE
Bug_Report: PadLocal longlink connection fail

### ISSUE THREAD

**Issue by Valerieeeee** [wechaty/wechaty#2260]
My chatbot collapses every now and then unpredictable haha. But generally won't take long to come back online.
It could be the network problem, could be whatever else.
So Could anyone please crack this? 

here:

![411632186912_ pic_hd](https://user-images.githubusercontent.com/77483278/134103381-f98276a8-63ed-42f9-acde-47b750f69682.jpg)

**Comment by huan** [comment]
LInk to https://github.com/padlocal/wechaty-puppet-padlocal/issues/98

**Comment by Valerieeeee** [comment]
> LInk to
> 
> * [VError: longlink fail to connect, host:120.241.21.110, port:80: longlink socket connect timeout padlocal/wechaty-puppet-padlocal#98](https://github.com/padlocal/wechaty-puppet-padlocal/issues/98)
> 
> BTW: It would be better and easy to read and search when pasting text log messages. @Valerieeeee

Roger, thanks!
