### ISSUE TITLE
can a good passerby help me.......

### ISSUE THREAD

**Issue by ffdrif** [wechaty/wechaty#2281]
🚨 The issue tracker is not for questions 🚨
Can someone help me to verify my new account in wechat? just search for wechat team then tap account and select help friend register then enter this number? 09562851625. THANKSSSSS
If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by huan** [comment]
This is not an issue, close it.

P.S. You can join the developers' home or visit our Gitter channel at https://gitter.im/wechaty/wechaty
