### ISSUE TITLE
Room&Contact.find() should throw exception when it get more than one value

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#229]
When I have two contacts with the same name, using function `find()`  will return one of the contacts randomly, which is not easy to debug.  

We should throw an exception when function `find()` return more than one value.

**Comment by zixia** [comment]
Agree. PR is welcome.

**Comment by zixia** [comment]
Instead of throw, I'm now considering to use a `log.warn()` instead.

Because sometimes be able to just using the first find result will be very convienence.

**Comment by lijiarui** [comment]
It's a good idea, I will change then.

**Comment by zixia** [comment]
We can set the level to warn or info. which one do you think is better?

**Comment by lijiarui** [comment]
I think warn is better, because it can cause more attention.
