### ISSUE TITLE
Cannot read property 'getRoomIds' of undefined

### ISSUE THREAD

**Issue by Jesn** [wechaty/wechaty#2294]
[question]

wechaty: v0.56

```
{ code: 13, details: "Cannot read property 'getRoomIds' of undefined" }
02:04:29 VERB PuppetServiceImpl roomList()
02:04:29 ERR PuppetServiceImpl grpcError() roomList() rejection: Cannot read property 'getRoomIds' of undefined
{ code: 13, details: "Cannot read property 'getRoomIds' of undefined" }
02:04:29 VERB PuppetServiceImpl roomList()
02:04:29 ERR PuppetServiceImpl grpcError() roomList() rejection: Cannot read property 'getRoomIds' of undefined
{ code: 13, details: "Cannot read property 'getRoomIds' of undefined" }
```

**Comment by huan** [comment]
It seems that you are using `wechaty@0.56` with an unmatched (very high) version of the `wechaty-puppet-service`.

`wechaty`, `wechaty-puppet`, and `wechaty-puppet-service` are decoupled but still highly dependent on each other, so you need to install the version at the same date range.

One of the solutions is to find a version of wechaty-puppet-service published near the `wechaty@v0.56` published.

## Find a version to match another within the same date range

For example, we can get the `wechaty@0.56` publish date from NPM at <https://www.npmjs.com/package/wechaty?activeTab=versions>

```
0.56.6 / 9 months ago
0.56.5 / 9 months ago
```

We can see it had been published after 9 months.

Then we can go to `wechaty-puppet-service` NPM version page at <https://www.npmjs.com/package/wechaty-puppet-service?activeTab=versions>, and search "9 month", then we can see:

```
0.15.2 / 8 months ago
0.14.8 / 9 months ago
0.14.7 / 9 months ago
```

Then we can say, the 0.14 or 0.15 (slightly newer version) should be able to work with `wechaty@0.56`.

## The LTS plan of Wechaty

We are planning of enabling Long-time Support (LTS) for Wechaty after v1.x is stabled, I hope with the LTS version the version mismatch that affects our users can be minimized.

Please feel free to let me know what you think, thank you very much.

**Comment by leochen-g** [comment]
如果使用的是js版web协议，以下配置可以运行0.x系列，无兼容问题，同时docker配置在项目中也可使用亲测：

```
"wechaty": "^0.68.1",
"wechaty-puppet": "^0.41.4",
"wechaty-puppet-wechat": "^0.28.4",
```

项目地址：[https://github.com/leochen-g/wechat-assistant-pro](https://github.com/leochen-g/wechat-assistant-pro)

**Comment by huan** [comment]
@Jesn If your version is ok, and you are using the PadLocal puppet, then there is a very high probability that you are running into

- https://github.com/padlocal/wechaty-puppet-padlocal/issues/115

**Comment by huan** [comment]
@Jesn Have you find the reason of this issue, could you please share what you found so that this information might help other developers who have the similar problems?

Thanks!
