### ISSUE TITLE
wechaty@1.x Urllink cannot be used directly

### ISSUE THREAD

**Issue by youmengme** [wechaty/wechaty#2301]
Dear @ Huan, hello. I try to use` wechaty@1.0.6 `Send 'urllink' message.

```typescript

import { UrlLink } from 'wechaty'

const url = new UrlLink({

...

})

```

However, the 'urllink' exported in the 'wechaty' package is an 'interface', and the 'new' keyword cannot be used. Can you tell me the correct way to use it?

**Comment by huan** [comment]
Use `wechaty.UrlLink.from('https://xxx')` instead.

All Wechaty User Modules (WUM) should be called from the `wechaty` instance like the above code demonstrated.

**Comment by Hzqi** [comment]
> Use `wechaty.UrlLink.from('https://xxx')` instead.
> 
> All Wechaty User Modules (WUM) should be called from the `wechaty` instance like the above code demonstrated.

emmmm, sincerely can you support a api doc for current version? Or update examples?

We follow the examples, then we got stuck, we found the api doc but it's old enough.

**Comment by huan** [comment]
Yes, the docs have not been updated to the v1.x yet.

Please feel free to send a PR to help us improve it so that the future new users will be benifited.
