### ISSUE TITLE
Can support a api to set remark for a room?

### ISSUE THREAD

**Issue by Hzqi** [wechaty/wechaty#2307]
Sometimes I want to set a remark for a room when my bot joined in , but I didn't find the apis. The api `room.alias(contact)` looks like just to return someone's alias in the room.

So, is it prossible to set remark for a room? Can I do in version of `1.0.6`, or may the future version? Like `room.remark([string])` to set the remark.

And, thank you.

**Comment by haibaiDS** [comment]
我今天找了半天没找到怎么修改群聊的备注，我也认为可以有这个功能~

**Comment by greper** [comment]
+1

**Comment by huan** [comment]
I'd like to accept a Pull Request to implemented this API.
