### ISSUE TITLE
Conflict with the typescript declaration of qrcode-terminal

### ISSUE THREAD

**Issue by System233** [wechaty/wechaty#2314]
When `wechaty` and `qrcode-terminal` are installed at the same time, the declarations of `qrcode-terminal` is overwritten by `wechaty`
![image](https://user-images.githubusercontent.com/20336040/143832175-73a4ee19-c578-4460-827e-4573e180284f.png)

now the type of  function `generate`  is any;

**Comment by huan** [comment]
It is caused by:

https://github.com/wechaty/wechaty/blob/main/src/typings.d.ts#L20

When we start using the `qrcode-terminal`, perhaps there's no `@types/qrcode-termal` yet.

A pr to remove this line will be welcome.
