### ISSUE TITLE
端口ip都是通的，本地启动后报错，“UNAVAILABLE: Network closed for unknown reason”docker上显示下面内容。

### ISSUE THREAD

**Issue by zywaiting** [wechaty/wechaty#2324]
01:04:35 INFO Io on(jsonrpc): [object Object]
01:04:35 VERB Io on(jsonrpc) send({"id":-9007199254736248,"jsonrpc":"2.0","result":8788})

**Comment by xuhai19901018** [comment]
服务端是用docker启动的？换个docker版本wechaty/wechaty:0.56

**Comment by zywaiting** [comment]
> 服务端是用docker启动的？换个docker版本wechaty/wechaty:0.56

token not found (save token to WECHATY_PUPPET_SERVICE_TOKEN env var or pass it to puppet options is required.). See: <https://github.com/wechaty/wechaty-puppet-service#1-wechaty_puppet_service_token> 
出现了这个问题，我看了一下下面的链接，不知道怎么解决，求帮助下
