### ISSUE TITLE
dead links in docs/docstring

### ISSUE THREAD

**Issue by TWT233** [wechaty/wechaty#2325]
some links are outdated since wiki changed:

https://github.com/wechaty/wechaty/blob/1c22c6bc7d6fc8fa4b921f7d0433d492ec3a2217/docs/index.md#L21

https://github.com/wechaty/wechaty/blob/1c22c6bc7d6fc8fa4b921f7d0433d492ec3a2217/src/wechaty/wechaty-base.ts#L94

https://github.com/wechaty/wechaty/blob/1c22c6bc7d6fc8fa4b921f7d0433d492ec3a2217/src/schemas/wechaty-events.ts#L101

all of the deadlinks(that I found) point to the FAQ

it seems that FAQ was not migrated to https://wechaty.js.org/ like [Puppet](https://github.com/wechaty/wechaty/wiki/Puppet), thus I altered the deadlinks to the available page with an incoming commit

**Comment by huan** [comment]
Thank you very much for your contribution!
