### ISSUE TITLE
[WhatsApp] Support more message related methods.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#2341]
**Is your feature request related to a problem? Please describe.**
When implementing the `puppet-whatsapp`, we found `Wechaty` maybe need more methods for making use it easily.

**Describe the solution you'd like**

**New Methods**
- message.removeConversation()

  > BTW, maybe we should need a new Class named `Conversation` or `Chat`, so that we could move `readMark()` and `removeConversation()` from `Message` class to `Conversation` class.

- message.toOrder()
- message.toPayment()

**New Type**
- Message.Type.Order
- Message.Type.Payment

**Additional context**

From now, I have no screenshots for above message type, will add them later.

[enhancement]

Related issue: https://github.com/wechaty/puppet-whatsapp/issues/23

**Comment by huan** [comment]
What is the `Payment`? We have a WIP `Money` WUC currently at https://github.com/wechaty/wechaty/blob/main/src/user-modules/money.ts
