### ISSUE TITLE
event "room-leave" cannot use room.say.

### ISSUE THREAD

**Issue by willin** [wechaty/wechaty#2350]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: 0.60.x

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: padlocal

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: 0.4.2

> What is your node version? (run `node --version`)

Answer: 16.13

> What os are you using

Answer: macOS 12

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

```ts
bot
  // add listeners
  .on('room-join', roomJoin)
  .on('room-leave', roomLeave)
```

## 3. To Reproduce

```ts
export default async function roomJoin(
  this: Wechaty,
  room: Room,
  inviteeList: Contact[],
  inviter: Contact
): Promise<void> {
  log.info(this.name(), 'Room Join');
  log.info(this.name(), room);
  log.info(this.name(), inviteeList);
  log.info(this.name(), inviter);
  await room.say('可以成功发送消息');
}


export default async function roomLeave(
  this: Wechaty,
  room: Room,
  leaverList: Contact[]
): Promise<void> {
  log.info(this.name(), 'Room Leave');
  log.info(this.name(), room);
  log.info(this.name(), leaverList);
  await room.say('无法成功发送消息');
}
```

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

can send msg on 'room-leave' event

**Comment by huan** [comment]
If the `leaver` is the bot, then that's expected behavior and should be very easy to understand:

When the bot is leaving a room, it is not a member of the room anymore, which means it can not say anything in that room, obviously.
