### ISSUE TITLE
web协议的现在还能登录吗?我一直登录失败呢

### ISSUE THREAD

**Issue by call6ack** [wechaty/wechaty#2352]
![图片](https://user-images.githubusercontent.com/97873180/150099861-fbf6159d-6e00-4d15-89cc-4186004efaa3.png)

**Comment by call6ack** [comment]
有没有大佬试一下

**Comment by aote777** [comment]
顶一下

**Comment by sumulige** [comment]
估计没戏了 
ipad协议不知道什么情况

**Comment by aote777** [comment]
> 估计没戏了 ipad协议不知道什么情况

我准备试试那个xp的协议 但是我没跑起来 报错了

**Comment by peychean** [comment]
确定已废弃，不能再使用。请更换为xp协议，但是xp协议支持的多为read类操作

**Comment by aote777** [comment]
收到

**Comment by zoudingyi** [comment]
web协议目前不能登录了 推荐使用padlocal 一直很稳定👍

**Comment by aote777** [comment]
> web协议目前不能登录了 推荐使用padlocal 一直很稳定👍

由于过于贫穷 所以没用这个

**Comment by DaGeger** [comment]
使用padlocal协议，提示我异地登录怎么办呢？然后马上限制登录了

**Comment by wxmbaci** [comment]
> 确定已废弃，不能再使用。请更换为xp协议，但是xp协议支持的多为read类操作

xp免费吗?

**Comment by peychean** [comment]
xp 是免费的，但是无法加群等操作
&nbsp;

若海 https://www.rehiy.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 上午10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechaty/wechaty] web协议的现在还能登录吗?我一直登录失败呢 (Issue #2352)





  
确定已废弃，不能再使用。请更换为xp协议，但是xp协议支持的多为read类操作
  
xp免费吗?
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huan** [comment]
Duplicated with 

- https://github.com/wechaty/puppet-wechat/issues/192

**Comment by ftune** [comment]
UOS不是也封了么。
我的微信因为用itchat被封了网页登录(https://wx.qq.com/)。
但是12月新出的网页文件传输助手(https://filehelper.weixin.qq.com)不限制。
我想问有没有哪个包可以调用web接口网页文件传输助手给自己的微信发消息。
我给自己的手机发消息没理由限制吧。
类似
```
itchat.auto_login(hotReload=True,fileHelper=True) 
itchat.send('hello filehelper','filehelper')
```

**Comment by huan** [comment]
@ftune I like your idea, it seems very promising to be useful and easy to be implemented!

PR is welcome to [Wechaty Puppet WeChat](https://github.com/wechaty/puppet-wechat)

**Comment by zhangtianyi252882824** [comment]
我的UOS还能用，但不适用我的功能，我要自动加群成员的功能，现在还没找到有哪个项目有这个接口
