### ISSUE TITLE
可以主动退出微信号吗？

### ISSUE THREAD

**Issue by gongzili456** [wechaty/wechaty#2354]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
翻阅 wechaty 的文档后，未发现主动退出微信号的方法，目前只能退出 wechaty 的 bot ，并不能退出 微信号 的登录状态。

**Comment by huan** [comment]
`wechaty.logout()` is designed to log the bot out of WeChat.

However, it will be depended on the implementation of underlying puppets.

I can confirm that the `wechaty-puppet-wechat` will satisfy this protocol, but not sure others.
