### ISSUE TITLE
About room name and get trigger by @the bot

### ISSUE THREAD

**Issue by fintie** [wechaty/wechaty#236]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

node: v7.4.0
npm: v4.0.5

  #### Wechaty Doctor

  1. Wechaty version: 0.7.18
  2. Linux x64 version 4.9.4-moby memory 444/1999 MB
  3. Docker: true
  4. Node version: v7.4.0
  5. Tcp IPC TEST: PASS

### Expected behavior

Can we trigger the bot without updating the room name to "wechaty"?
Can we trigger the bot only when the user @the bot name

Thanks a lot

**Comment by lijiarui** [comment]
You can trigger the bot without updating the room name to 'wechaty'.   
You also can trigger the bot only when the user @bot bot name.


For the first question:
> You can trigger the bot without updating the room name to 'wechaty'.  
Actually when the [events](https://github.com/wechaty/wechaty/wiki/API#event) happens, it would trigger the bot, it means if any event happens in a room, it will trigger the bot, includes `change room topic`, `invite friends into room`, `any member chat in the room`, and many other events. 


For the second question:
> You also can trigger the bot only when the user @bot bot name.
I use the following code let me know others @bot for your reference

```
  public isAtBot(): boolean {
    const regConfig = new RegExp('@' + this.botName)
    if (this.type !== MsgType.TEXT) return false
    if (regConfig.test(this.content)) {
      log.info('@bot Event')
      return true
    }
    return false
  }
```

**Comment by fintie** [comment]
Wow, thanks so much @lijiarui 
I will give a try now

**Comment by lijiarui** [comment]
So what's your question?  

By the way, I find you use `talk(msg)`,  but `talk()` is not wechaty API.

**Comment by fintie** [comment]
talk(msg) is coming from the example: tuling123-bot.ts

So currently, I put   

public isAtBot(): boolean {
    const regConfig = new RegExp('@' + this.botName)
    if (this.type !== MsgType.TEXT) return false
    if (regConfig.test(this.content)) {
      log.info('@bot Event')
      return true
    }
    return false
  }

into room.ts

What I would like to achieve is only trigger the bot's answer(auto response) only if the user in the room @the bot

From my current experiment, it will still reply all the message in the room. But the difference to original one is, before @the bot, there was not auto response


Thanks!

**Comment by fintie** [comment]
@zixia Thanks so much!

**Comment by zixia** [comment]
@fintie You are welcome.

**Comment by fintie** [comment]
@zixia I just had a try, now its working for 1-on-1 chatting only, not for room

Would you be able to have a look?

Thanks

**Comment by zixia** [comment]
@fintie Yes, it's expected. I made it work like that, in order to clear useless and confusing codes.

In order to develop your own feature, please read the API carefully and coding hard. 

I'll close this issue because here's not a support forum. You can join our developer community group on Wechat(QRCode in README) to discuss your requirement with other developers.

Good luck!

**Comment by fintie** [comment]
Thanks @zixia , I will try if I can set up the group chat as well. Cheers
