### ISSUE TITLE
About creating miniProgram/Url/Location without bot instance

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2372]
When reading the code, I saw this.
```
    // Huan(202110): it is ok to create a raw one without wechaty instance
    // guardWechatifyClass.call(this, UrlLink)
```
And I have to say I did not get it. Could you please explain it a bit more?
Say I have a URL like this in wechaty v0.40
```
const url = new UrlLink({
        title: urlContent.title,
        description: urlContent.summary,
        thumbnailUrl: urlContent.imageUrl,    // 缩略图
        url: urlContent.sourceUrl,
      });
```
How can I do this without wechaty instance in wechaty v1.0+? I'm aware I can use new `Bot.UrlLink()`

**Comment by huan** [comment]
We have all Wechaty User Module (WUM) binded with the Wechaty instance and should always use `wechatyInstance.UrlLink` to reference the correct WUM for using by the end user.

So there's no standard way to use UrlLink without a Wechaty instance by design now.

**Comment by hcfw007** [comment]
Actually I don't have such scenario currently, just feel confused about that comment in code while reading.
