### ISSUE TITLE
bot.stop() doesn't seem to stop the accumulation of message events

### ISSUE THREAD

**Issue by yzh1255245824** [wechaty/wechaty#2376]
When I use `await bot.stop()` to stop the bot service, it really won't respond to new messages.

But if a new message event arrives during the time it stops, when the bot login again, it will process these `message event` at one time. This means that I will send a lot of messages to one user at one time!

Does this mean that even if I stop the bot, it can still listen to the `message event`?

If so, how can I use `bot.logonoff()` for the situation that _**`when the bot is offline`**_ , it will directly `return`  without processing the received `message event`. Like this:
```javascript
bot.on("message", message);

async function message(msg) {
  if (bot.logonoff()) {
    console.log('Bot logined')
    //continue to do sth......
  } else {
    console.log('Bot not logined')
    return
  }
}
```

I will look forward to your reply.

**Comment by huan** [comment]
This behavior highly depends on the puppet provider implementation.

There are some use cases that require the bot to process as many messages as it can when it does not online. Think about the WeChat app on your PC/Mac: it can receive messages when it's offline/logged out, to keep your message timeline complete.

In your case, it's very easy to deal with: you can use `message.date()` or `message.age()` to check whether this message was sent in the past 60 seconds.

See:

- https://github.com/wechaty/wechaty/issues/1616

**Comment by yzh1255245824** [comment]
Ohhhh，I know how to do. Thank you!

**Comment by huan** [comment]
You are welcome!
