### ISSUE TITLE
How to send pictures？

### ISSUE THREAD

**Issue by lvhy** [wechaty/wechaty#238]
How to send pictures to room or contact

**Comment by zixia** [comment]
Duplicated with #4

**Comment by lvhy** [comment]
No direct call API ？

**Comment by zixia** [comment]
No(yet).

It's planed in [milestone v0.9](https://github.com/wechaty/wechaty/milestone/8)

**Comment by lvhy** [comment]
if I want to send pictures , what should I do?  thank you ^_^, Related documents?

**Comment by zixia** [comment]
I believe if you want to send pictures now, what you need to do is:
1. Read #4 in details
1. Send PR

:hand:
