### ISSUE TITLE
Return Type of Bot.on()

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2384]
Referring to the problem in this PR: #2375

I think I know what this is about. A few days ago they came to me and asked why this is not working in TS:
```
... // bot is a wechaty bot instance

bot.on(...).on(...).start()
```
TS will report type error because `bot.on()` will return a `TypedEventEmitter<WechatyEventListeners>` type instead of a `wechaty` type. So the demo in the homepage will not work in TS. That's why they want to change the demo. I have a better solution for this.

**Comment by huan** [comment]
Thanks for the information, I think this problem is related to my commits recently.

Could you please share your "better solution for this"?

I'm thinking about what's the best way to fix it.

**Comment by hcfw007** [comment]
We can change the return type of `wechaty.on()`, `wechaty.off()` and `wechaty.once()` like this:
```
interface WechatyEventEmitter {
  on   : AlterReturnType<TypedEventEmitter<WechatyEventListeners>['on'], WechatyImpl>
  off  : AlterReturnType<TypedEventEmitter<WechatyEventListeners>['off'], WechatyImpl>
  once : AlterReturnType<TypedEventEmitter<WechatyEventListeners>['once'], WechatyImpl>
}

type AlterReturnType<Func extends Function, ReturnType> =
  Func extends (...args: infer Args) => any ? (...args: Args) => ReturnType : never

```
This should solve the type issue.
If you are happy with, I'm glad to open a PR to solve this.

**Comment by huan** [comment]
Please go ahead to demonstrate this fix by creating the PR, thank you very much!

**Comment by huan** [comment]
Close this issue because the PR has been merged for it.
