### ISSUE TITLE
怎么调用扫一扫功能去识别群二维码图片加入群聊呢？

### ISSUE THREAD

**Issue by greper** [wechaty/wechaty#2386]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by huan** [comment]
I think currently we are not supporting this feature.

However, I believe it's a great feature and PR will be welcome.

P.S. The Windows Client has supported this feature in the most recent version, which I believe our [Puppett XP](http://wechaty.js.org/docs/puppet-providers/xp) will be very easy to implement.
