### ISSUE TITLE
Start puppet timeout

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2388]
https://github.com/wechaty/wechaty/blob/b3589083e00895d1de9b5e2ecb6f2b5631bc158a/src/wechaty-mixins/puppet-mixin.ts#L81-L109

As we talked before, we should use a bot-level retry method to handle situations when puppet-server is not ready yet. However since the start() procedure will not be interrupted by the timeout error. As I understood, the padlocal issue has been closed, this special handler for timeout should be removed.

**Comment by huan** [comment]
Of course, after I read the comment I think I have remembered something.

Let's confirm the fix has been published by the padlocal module, then we can go ahead to improve this workaround.

**Comment by hcfw007** [comment]
Any progress on this issue?

**Comment by huan** [comment]
I think we need to solve 

- https://github.com/wechaty/puppet-padlocal/issues/116

Before continue solving this issue.

**Comment by hcfw007** [comment]
Er, but that project is still using wechaty 0.x (main branch)

**Comment by huan** [comment]
Yes. But we can use a gateway to convert it to a v1.x puppet service.

Our Friday BOT is running with it for the past months.
