### ISSUE TITLE
Wechaty需要安装ix才能启动

### ISSUE THREAD

**Issue by lhr0909** [wechaty/wechaty#2389]
我其实不太想提issue，因为我本身是wechaty开发者，这些问题应该能克服。但是一年没有用项目，开发的难度越来越大了。

除了二次开发的复杂度非常大之外，我非常不希望我被wechaty提供的工具链绑架。可能是我是比较早期就进入nodejs生态，不希望library帮我考虑过多，或者做很多限制。这严重制约了生态的发展。

我的最小启动文件和package.json 需要另外安装`ix`才能正常使用ts-node启动 我估计是用了比较新的ts或者es规范 在`@chatie/tsconfig`加持下能正常使用吧。

另外文档希望用中文。While I am bilingual, I wish we have more proper (basic) Chinese material for developers.

wish this project the best, and I am moving onto building my own. Cheers and good luck

```typescript
import { WechatyBuilder, ScanStatus, log } from "wechaty";

const token = "puppet_donut_xxxxxx";

const bot = WechatyBuilder.build({
  puppet: "wechaty-puppet-service",
  puppetOptions: {
    token,
  },
});

bot.on("scan", (qrcode, status) => {
  if (status === ScanStatus.Waiting) {
    require("qrcode-terminal").generate(qrcode, {
      small: true,
    });
  }
});

bot.on("login", async (user) => {
  console.log(`user: ${JSON.stringify(user)}`);
});
bot.on("message", async (message) => {
  console.log(`message: ${JSON.stringify(message)}`);
});

bot
  .start()
  .then(() => log.info("StarterBot", "Starter Bot Started."))
  .catch((e) => log.error("StarterBot", e));

```

```json
{
  "name": "wechaty-puppet-wxwork-test",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Simon Liang",
  "license": "MIT",
  "dependencies": {
    "ix": "^4.5.2",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^1.18.1",
    "wechaty-puppet": "^1.18.3",
    "wechaty-puppet-service": "^1.18.2"
  },
  "devDependencies": {
    "ts-node": "^10.7.0",
    "typescript": "^4.6.2"
  }
}
```

**Comment by huan** [comment]
Thanks for the report, the missing `ix` problem should be fixed on Wechaty v1.19.8+ versions.

Your minimal code looks good. Please remember that we are always recommending using the Wechaty official getting started repo at https://github.com/wechaty/getting-started so that any newcomer can run Wechaty out-of-the-box.
