### ISSUE TITLE
FileBox save file with ZERO broken size

### ISSUE THREAD

**Issue by gqyang** [wechaty/wechaty#2397]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 1. Versions

> What is your wechaty version?

Answer: 1.18.1

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: wechaty-puppet-wechat

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: 1.18.1

> What is your node version? (run `node --version`)

Answer: v17.3.1

> What os are you using

Answer: CentOS Linux release 7.6.1810

## 2. Describe the bug

use filebox to save file to disk, but the file is 0 size. the file is empty.

the process was ok several days ago.

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. fileBox = await msg.toFileBox()
2. await fileBox.toFile(save_path + fileBox.name, true)
3. the file is 0 size

## 4. Expected behavior

> the file is not 0 size (1.3M should be)

**Comment by gqyang** [comment]
> Could you please confirm what message will trigger this problem:
> 
> 1. a outgoing message (sent by the bot)
> 2. a incoming message (send to the bot)
> 
> I guess there might be some bug when you call `toFileBox()` on a message sent from the bot itself.

Thx for your reply.

When the bot receives an attachment message, the bot saves the file to disk. That will trigger this problem.

The message from bot self will not trigger the save operation.  

I console.log the filebox object and find that the remote url is like this:

remoteUrl: 'https://file.wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetmedia?sender=@19aa7bb4f3d02573ee40a720775a38c31ac34fcc75546f7379d7fd4e34df59a5&mediaid=@crypt_da7a3586_9281d0fd1f08d5ca3cee23750074a9f3a0d9c3b7f55a485c7fb4ee4f2d4d78b6a645f8c9a08c6e941b4f18f6633c9205e9231ffc9e671855e45444efeed5eccd11260f877f6d6424264686540ea86ae9c4ce446f9ab8435d25486008a6734bfac7521a5434025fd1d9a0022787de214d295668055db4fecb9c166db50fb88ff5a3df22e475c2f86261cabd6e6a9f9c13de5001dbc823e665950685bcec5a137292cb264876cab258bd32499846c7e21503ce9efbcb2500ec0838d19b5d32e6beee3d1e4092b5424516a1ca5a6cae38fbe5ca1976c73b9f3d383b575d9e0caf4a&encryfilename=%E4%BA%BF%E6%AC%A7%E6%99%BA%E5%BA%93%EF%BC%9A%E4%B8%AD%E5%9B%BDAI%E6%95%99%E8%82%B2%E5%88%9B%E6%96%B0%E6%A6%9C%E5%8D%95%E4%BC%81%E4%B8%9A%E6%A1%88%E4%BE%8B%E5%88%86%E6%9E%90%E6%8A%A5%E5%91%8A%2Epdf&fromuser=57242504&pass_ticket=6SSRZfTl49Sao91idIb7nIyqXek23ElzVsOiNtMgtmk%253D&webwx_data_ticket=gSexOjXCQp6ntMNI%2B3qciCQQ',

When I clicked the url, I also got an empty file with zero size.

**Comment by huan** [comment]
That URL can not be visited directly because it requires session information, which will be lost when you click it.

**Comment by xiaogaozi** [comment]
Same issue here, and I found image and video could download normally, but other file types will cause this issue.

**Comment by gqyang** [comment]
> Same issue here, and I found image and video could download normally, but other file types will cause this issue.
> 
> BTW, I use wechaty-puppet-wechat v1.11.11.

thanks for your note. have you ever fixed the file download problem ?

**Comment by hex2tan** [comment]
I meet this same issue too.
Any idea to solve it? Optimize the implement  of FileBox.toFile() func?

**Comment by Lipingchang** [comment]
我也是 。。
发现 remote URL中 pass_ticket字段是undefined，是和这个有关系吗？

**Comment by Lipingchang** [comment]
我把这个字段改了下：fileBox.headers.Range = 'bytes=0-1'
就能下载了。。

**Comment by gqyang** [comment]
> 

谢谢您的建议；请问是在自己的代码逻辑里面修改就可以么？
