### ISSUE TITLE
企业微信 Token过期几天，再次续费后发不了图片，报 Error: 13 INTERNAL: no url

### ISSUE THREAD

**Issue by lightlizm** [wechaty/wechaty#2404]
"wechaty": "^0.62.3"
node.js :  v12

之前运行得好好的，续费后就发不了图片了

执行以下代码：
const room = await bot.Room.load(roomId) 
const fileBox = FileBox.fromUrl(url)  
const result = await **room.say(fileBox)**
调用 room.say就报下面的错误了

PS: 文字能发

 
(node:5048) UnhandledPromiseRejectionWarning: **Error: 13 INTERNAL: no url**
    at Object.callErrorFromStatus (C:\nodejs\wechaty-wxwork\node_modules\@grpc\g
rpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\nodejs\wechaty-wxwork\node_modules\@grpc\grpc-
js\build\src\client.js:179:52)
    at Object.onReceiveStatus (C:\nodejs\wechaty-wxwork\node_modules\@grpc\grpc-
js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (C:\nodejs\wechaty-wxwork\node_modules\@grpc\grpc-
js\build\src\client-interceptors.js:299:181)
    at C:\nodejs\wechaty-wxwork\node_modules\@grpc\grpc-js\build\src\call-stream
.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:5048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 6)

**Comment by zhaoyukoon** [comment]
想了解一下wechaty如何接入企业微信? 多谢

**Comment by xinxinyihao** [comment]
你好，请问你这个问题解决了没？
