### ISSUE TITLE
'UrlLink' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by nsioo** [wechaty/wechaty#2407]
🚨 The issue tracker is not for questions 🚨

node v18.0.0
npm 8.6.0
typescript:4.6.3

修改过很多版本，都报这个错误。框架式nestjs。

import {  Wechaty, Message, WechatyBuilder,  UrlLink   } from 'wechaty';
![image](https://user-images.githubusercontent.com/14137490/164625944-c118b213-7994-4cd3-ace1-a6ee8de5e9c9.png)
请问我做错了什么？

[问题]

src/modules/wechaty/wechaty.service.ts:123:37 - error TS2693: 'UrlLink' only refers to a type, but is being used as a value here.

123           let urlLink:UrlLink = new UrlLink({
                                        ~~~~~~~

Found 1 error(s).

**Comment by huan** [comment]
In Wechaty v1.x, you can not instantiate `UrlLink` directly.

Use `new wechaty.UrlLink({...})` instead.

**Comment by Marandi269** [comment]
> With Wechaty v1.x, you can not instantiate `UrlLink` directly. (`UrlLink` in your code is a `Interface` type instead of a JS value)
> 
> Use `new wechaty.UrlLink({...})` instead.

I have same problem, and I cannot find wechaty any where. Could you give me a short demo with import statements? Thank you! 🙏

**Comment by huan** [comment]
You can learn from the official getting started example at here: https://github.com/wechaty/getting-started/blob/main/examples/ding-dong-bot.ts
