### ISSUE TITLE
json-rpc-peer module declaration issue

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2411]
In the original json-rpc-peer declaration file (https://github.com/JsCommunity/json-rpc-peer/blob/master/index.d.ts), we can see that class `Peer` is exported as default export.
But in wechaty(https://github.com/wechaty/wechaty/blob/main/src/io-peer/json-rpc-peer.d.ts), the last line is missing.

Consider these lines: 
https://github.com/wechaty/wechaty/blob/4ed646d1fecdfca033f22749d0593bda3ae4872f/src/io-peer/io-peer.ts#L2
https://github.com/wechaty/wechaty/blob/4ed646d1fecdfca033f22749d0593bda3ae4872f/src/io-peer/io-peer.ts#L67

jsonRpcPeer was imported as defaulot (with no {})
So jsonRpcPeer should be the default export of json-rpc-peer, which is `Peer` class.
Trying to create an instance with `new jsonRpcPeer.Peer(onMessage)` will result in error (and it did, in my test).

**Comment by huan** [comment]
Thanks for testing and figuring it out!

I have tried to convert the upstream module to TypeScript natively before, and if it was in native TypeScript there will no this kind of issues.

The current typing definition in our repo might have bugs, so please feel free to create an PR to fix it. (With unit tests please.)

Thank you very much!
