### ISSUE TITLE
get the type of puppet in the plugin

### ISSUE THREAD

**Issue by leochen-g** [wechaty/wechaty#2412]
**Is your feature request related to a problem? Please describe.**

During the development of the plugin, I found that the method to be called needs to be judged according to different puppet types. But it seems that wechaty does not have this attribute at present, I hope it can support

**Describe the solution you'd like**
<img width="331" alt="image" src="https://user-images.githubusercontent.com/20028566/167128139-a332f7c8-1171-4653-b9b5-3205a29e2a4e.png">

**Describe alternatives you've considered**

Let the user enter the puppet type by himself. But it doesn't seem to be the best solution

**Comment by atorber** [comment]
**Use this feature requirement to supplement another related requirement.**

Although wechaty provides a set of standard Chatbot interface framework, different puppets have some differences in the implementation integrity and implementation methods of different functions, and developers have many problems in the use process.

So I wonder if wechaty can provide a list of methods currently supported by puppet or some response prompt interface. When puppet does not realize relevant functions, developers can get prompt information clearly. For example, puppet XP does not realize urllink sending function at present, so developers can get prompt when calling this method.

**Comment by atorber** [comment]
> During the development of the plugin, I found that the method to be called needs to be judged according to different puppet types.

The current issues are about puppet types. The question I raised is due to different puppet types, so I think it is a complete feature
So I think we really need a separate feature to implement?

**Comment by huan** [comment]
OK, I think we can keep those features together in this issue.

We can separate them when we feel its necessary in the future.
