### ISSUE TITLE
The SSL connection could not be established-WeChaty 0.68, C#SDK

### ISSUE THREAD

**Issue by jmc-123** [wechaty/wechaty#2413]
## 1. Versions

> What is your wechaty version?

Answer:wechaty  0.68

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:padlocal

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:wechaty-puppet-padlocal version: 0.4.2

> What is your node version? (run `node --version`)

Answer:no

> What os are you using

Answer: win10 home 21H1

## 2. Describe the bug

>fail: Wechaty.Module.Puppet.WechatyPuppet[0]
  StartGrpcClient() exception,Grpc Retry Surplus Count 3
  Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: 
  The SSL connection could not be established, see inner exception. IOException: Cannot determine the frame size or a corrupted frame was received.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
   ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
     at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

## 3. To Reproduce

1、下载dockertoolebox 18.02.0-ce.exe [Index of Docker Toolbox (daocloud.io)](https://get.daocloud.io/toolbox/)
2、下载完成后点击Docker Quickstart Terminal，出现小鲸鱼图标，安装完成。
3、在Docker Quickstart Terminal下输入：
export WECHATY_LOG="verbose"
export WECHATY_PUPPET="wechaty-puppet-padlocal"
export WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal"
export WECHATY_PUPPET_SERVICE_NO_SSL_UNSAFE_CLIENT=true
export WECHATY_PUPPET_SERVER_PORT="9001"
export WECHATY_TOKEN="token"

docker run  \
  --name wechaty_puppet_service_token_gateway \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_PADLOCAL_TOKEN \
  -e WECHATY_PUPPET_SERVER_PORT \
  -e WECHATY_TOKEN \
  -e WECHATY_PUPPET_SERVICE_NO_SSL_UNSAFE_CLIENT \
  -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
  wechaty/wechaty:0.68

出现WeChaty图标，在浏览器中打开Url，扫码登录微信。
4、运行控制台程序，出现上述报错。
5、下面是三个测试环境的对比图，前两台电脑运行正常。

电脑1 | 电脑2 | 实验室电脑
-- | -- | --
处理器：   Intel(R)   Core(TM) i7-8550U CPU @ 1.80GHz   1.99   GHz   机带 RAM：8.00 GB    系统类型：64 位操作系统, 基于 x64 的处理器 | 处理器：Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz   机带 RAM：12.0 GB   系统类型   64 位操作系统, 基于 x64 的处理器 | 处理器：   Pentium(R)   Dual-Core  CPU      E5800    @ 3.20GHz   3.20 GHz   机带RAM：4GB   系统类型：64位操作系统，基于x64的处理器
Win10系统，Wechaty 0.68，.net 5.0，docker 4.7.0.0 | Win10系统，WeChaty 0.68,.net 5.0，docker 4.7.0.0 | Win10系统，WeChaty 0.68,.net 5.0，docker ToolBox 18.02.0-ce
可运行 | 可运行 | 不可运行

**Comment by Jesn** [comment]
@jmc-123  issue go to -->   https://github.com/wechaty/dotnet-wechaty

**Comment by jmc-123** [comment]
@Jesn got it! Could you help to solve it ?  thx! https://github.com/wechaty/dotnet-wechaty/issues/42
