### ISSUE TITLE
新版wechat为什么二维码扫描登录后直接报这个错误！望大佬解答一下~十分感谢

### ISSUE THREAD

**Issue by wangji817** [wechaty/wechaty#2419]
ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (D:\work\wechatBot-from-pic\node_modules\_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat\dist\cjs\src\bridge.js:277:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (D:\work\wechatBot-from-pic\node_modules\_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat\dist\cjs\src\bridge.js:154:13)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (D:\work\wechatBot-from-pic\node_modules\_wechaty@1.20.2@wechaty\dist\cjs\src\wechaty-mixins\gerror-mixin.js:48:26)
    at PuppetWeChat.<anonymous> (D:\work\wechatBot-from-pic\node_modules\_wechaty@1.20.2@wechaty\dist\cjs\src\wechaty-mixins\puppet-mixin.js:181:34)
    at PuppetWeChat.emit (node:events:527:28)
    at PuppetWeChat.emit (D:\work\wechatBot-from-pic\node_modules\_wechaty-puppet@1.20.1@wechaty-puppet\dist\cjs\src\puppet\puppet-skeleton.js:133:22)
    at Bridge.<anonymous> (D:\work\wechatBot-from-pic\node_modules\_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat\dist\cjs\src\puppet-wechat.js:197:45)
    at Bridge.emit (node:events:527:28)
    at D:\work\wechatBot-from-pic\node_modules\_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat\dist\cjs\src\bridge.js:43:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (D:\\work\\wechatBot-from-pic\\node_modules\\_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat\\dist\\cjs\\src\\bridge.js:277:23)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.onLoad (D:\\work\\wechatBot-from-pic\\node_modules\\_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat\\dist\\cjs\\src\\bridge.js:154:13)'
}

**Comment by cwyl02** [comment]
hi @huan I can confirm this consistently happens to me as well on wsl Ubuntu, MacOS and Docker. I tried 2 different wechat accounts and seeing the same error.

**Comment by wangji817** [comment]
> 你好@huan我可以确认这一直发生在我身上`Ubuntu(wsl2)`，`MacOS`以及`Docker`。我尝试了 2 个不同的微信帐户并看到相同的错误。
> 
> 微信客户端版本：Android 8.0.18。账号使用微信后台，扫描美国二维码

我已经确认，是本人账号不支持网页版微信登录。无权限。

**Comment by Cuiyanjun** [comment]
请问解决了么？

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Rika321** [comment]
> hi @huan I can confirm this consistently happens to me as well on `Ubuntu(wsl2)`, `MacOS` and `Docker`. I tried 2 different wechat accounts and seeing the same error.
> 
> Wechat client version: Android 8.0.18. Account is using Weixin backend and scanned QRCode from the US

hi 老哥，我也是美国版微信遇到这个问题，请问你解决了吗？

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sir-ran** [comment]
> > 你好@huan我可以确认这一直发生在我身上`Ubuntu(wsl2)`，`MacOS`以及`Docker`。我尝试了 2 个不同的微信帐户并看到相同的错误。
> > 微信客户端版本：Android 8.0.18。账号使用微信后台，扫描美国二维码
> 
> 我已经确认，是本人账号不支持网页版微信登录。无权限。

我2个微信号都能登录网页版，也会报这个错误。
先正常扫码登录，然后退出重新扫描登录就会报这个异常。2个号都是这样。
MacOS
node: 16.0.0
npm: 7.10.0
wechaty: 1.20.2
wechaty-puppet-wechat: 1.18.4

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by isbiong100** [comment]
老哥后来怎么解决的？我测试环境是可以登录的，但是部署到docker就不行了

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hamlet626** [comment]
> 

Hello @Rika321 ,我也是美国微信这边遇到一些问题，可以一起交流下吗？老哥你那边问题有解决了吗，要不然加个微信？

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huan** [comment]
@dosubot According to the reply from @wangj817 : 

> 我已经确认，是本人账号不支持网页版微信登录。无权限。

He has confirmed it's an issue related to his WeChat account.

So, this issue is safe to be closed. Thank you very much!

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by linchen1987** [comment]
> > 你好@huan我可以确认这一直发生在我身上`Ubuntu(wsl2)`，`MacOS`以及`Docker`。我尝试了 2 个不同的微信帐户并看到相同的错误。
> > 微信客户端版本：Android 8.0.18。账号使用微信后台，扫描美国二维码
> 
> 我已经确认，是本人账号不支持网页版微信登录。无权限。

请问你是怎么确认账号不支持网页版微信登录的？ 我这边也报错，同样的错误

**Comment by wangji817** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huan** [comment]
This is the limitation from Tencent, not related to Wechaty.

anyone want to keep discussing please join the community discord https://discord.gg/7q8NBZbQzt for future information.
