### ISSUE TITLE
proxyWechaty(init) error: 503

### ISSUE THREAD

**Issue by sheldonzeng** [wechaty/wechaty#2428]
请问运行测试例子报503错误，是什么问题
```
wechaty:1.20.2
wechaty-puppet-wechat:1.18.1
wechaty-getting-started:1.18.7
node.js:v16.15.0
WECHATY_PUPPET=wechaty-puppet-wechat
```
----
```
wechaty-getting-started@1.18.7 start
cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

21:59:46 INFO StarterBot Starter Bot Started.
21:59:47 INFO StarterBot onScan: Waiting(2) - https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2F4aYj8PNFtQ%3D%3D
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▀ ▀  █▄▄▀█▄▄█ ▄▄▄▄▄ █
█ █   █ █   █▀▄▀▀ ▀ ▄▀█ █   █ █
█ █▄▄▄█ █▄█▀ ▄█ █ ▀▀ ██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ █ █ █▄▀▄▀▄█▄▄▄▄▄▄▄█
█ ▄▄ ▀█▄▀ █ ▄ █ ▄█▄ ▀█ ▀▀ ▄▄█ █
██▀ ▀▀ ▄█   ▄▄▀█▀▀█▀█ ▄▄█▀█▄▄▀█
█▄█  ██▄██▄▄▀ █▄▀▀▄█ █▄▀██▄ ▀▀█
█ █▀   ▄▄ ▀▄ █▄▀▀█▄▄▄▄ ▀  █▄ ▄█
█▄ ▀▄█▄▄▄████▄▄ ▄▄▀▄▄  █ ▄ ▀ ██
█▄█ ▄██▄█▄ █▀██▄▄▄▀▀█▀▀▀▄▀█ ███
██▄█▄██▄▄▀▀ ██▀▀█  ▀▀ ▄▄▄   ▀▀█
█ ▄▄▄▄▄ ██ █▀▀▀▀███ ▄ █▄█  █▄██
█ █   █ █▀██ █▀▀ ▄▄█▀  ▄  ▀▄▄ █
█ █▄▄▄█ █  ▄█ ▀▄█▀█ ▄ ██▄▀▀▄▀▄█
█▄▄▄▄▄▄▄█▄██▄███▄███▄▄▄██▄██▄██

21:59:52 INFO StarterBot onScan: Scanned(3)
21:59:53 INFO StarterBot onScan: Confirmed(4)
21:59:53 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:363
        throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
              ^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:363:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:363:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.onLoad (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:214:7)'
```
----

**Comment by sheldonzeng** [comment]
使用默认配置运行则报另外一个错误
```
> wechaty-getting-started@1.18.7 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

23:38:43 INFO StarterBot Starter Bot Started.
23:38:44 INFO StarterBot onScan: Waiting(2) - https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FAYIDDPLg7g%3D%3D
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▀▄▄█ ▄█▄▀█▀█ ▄▄▄▄▄ █
█ █   █ █▀███ ▀█▄█▀▀███ █   █ █
█ █▄▄▄█ █▄▄█▀▀▀▀▄▄ ▄▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█ █ █ ▀ █▄▄▄▄▄▄▄█
█▄ ▀▀▀ ▄▄█ █▄▀▄█▄█▄▀ ▀██▀ ▄▀▀██
█▀█▀▄ █▄▀ ▀▄█▀▄ ▄▀▄▄▀▀█ ▄▄▀████
█▄▄▄▀ █▄ ▄▄█▄▄██▄ ▀▀▀ ▄  ▀██▀ █
██ █ █▀▄█▀▄█ ▄▄▄▄ ▄██ █▄ ▀▄ █▀█
█   █ ▀▄▀▄▄ ▄▀ ▀█▀ ▀ ▀▀▀▀▀▄ ▀▀█
█ ▄▀ ▀▄▄▀▀█▀▄▀▄▀▄█▄█▄▄▀ ▀█▄██▄█
█▄███▄█▄▄ ▄██▄ ██▄    ▄▄▄ ▀▄▄▄█
█ ▄▄▄▄▄ █ ██ ▄█ ▄▄▄█  █▄█ ▄▄█▀█
█ █   █ █████▀ ▄▄ ▀▀ ▄ ▄▄▄ ▀▄▀█
█ █▄▄▄█ █▀█▀█▀   ▄█▀█▄  ▄   ▄▀█
█▄▄▄▄▄▄▄█▄▄██▄█▄██▄▄▄███▄██▄███

23:39:06 INFO StarterBot onScan: Scanned(3)
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (D:\MangHe\getting-started-main\node_modules\wechat4u\src\util\global.js:53:14)
    at D:\MangHe\getting-started-main\node_modules\wechat4u\src\core.js:179:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (D:\\MangHe\\getting-started-main\\node_modules\\wechat4u\\src\\util\\global.js:53:14)\n' +
    '    at D:\\MangHe\\getting-started-main\\node_modules\\wechat4u\\src\\core.js:179:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

```

**Comment by ZacharyLi1989** [comment]
也有这个问题...求解答

**Comment by williamhqs** [comment]
一样的问题 请问有解决方案吗？

**Comment by sir-ran** [comment]
也遇到了这个问题，但是我是主动退出那个微信然后再次扫码登录就会出现这个错误。
退出登录后直接重启扫码登录就可以。

**Comment by WangMingHua111** [comment]
> 请问运行测试例子报503错误，是什么问题
> 
> ```
> wechaty:1.20.2
> wechaty-puppet-wechat:1.18.1
> wechaty-getting-started:1.18.7
> node.js:v16.15.0
> WECHATY_PUPPET=wechaty-puppet-wechat
> ```
> 
> ```
> wechaty-getting-started@1.18.7 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts
> 
> 21:59:46 INFO StarterBot Starter Bot Started.
> 21:59:47 INFO StarterBot onScan: Waiting(2) - https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2F4aYj8PNFtQ%3D%3D
> ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
> █ ▄▄▄▄▄ █▄▀ ▀  █▄▄▀█▄▄█ ▄▄▄▄▄ █
> █ █   █ █   █▀▄▀▀ ▀ ▄▀█ █   █ █
> █ █▄▄▄█ █▄█▀ ▄█ █ ▀▀ ██ █▄▄▄█ █
> █▄▄▄▄▄▄▄█▄█ █ █ █▄▀▄▀▄█▄▄▄▄▄▄▄█
> █ ▄▄ ▀█▄▀ █ ▄ █ ▄█▄ ▀█ ▀▀ ▄▄█ █
> ██▀ ▀▀ ▄█   ▄▄▀█▀▀█▀█ ▄▄█▀█▄▄▀█
> █▄█  ██▄██▄▄▀ █▄▀▀▄█ █▄▀██▄ ▀▀█
> █ █▀   ▄▄ ▀▄ █▄▀▀█▄▄▄▄ ▀  █▄ ▄█
> █▄ ▀▄█▄▄▄████▄▄ ▄▄▀▄▄  █ ▄ ▀ ██
> █▄█ ▄██▄█▄ █▀██▄▄▄▀▀█▀▀▀▄▀█ ███
> ██▄█▄██▄▄▀▀ ██▀▀█  ▀▀ ▄▄▄   ▀▀█
> █ ▄▄▄▄▄ ██ █▀▀▀▀███ ▄ █▄█  █▄██
> █ █   █ █▀██ █▀▀ ▄▄█▀  ▄  ▀▄▄ █
> █ █▄▄▄█ █  ▄█ ▀▄█▀█ ▄ ██▄▀▀▄▀▄█
> █▄▄▄▄▄▄▄█▄██▄███▄███▄▄▄██▄██▄██
> 
> 21:59:52 INFO StarterBot onScan: Scanned(3)
> 21:59:53 INFO StarterBot onScan: Confirmed(4)
> 21:59:53 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
> file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:363
>         throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
>               ^
> GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
>     at Bridge.inject (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:363:15)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Bridge.onLoad (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:214:7) {
>   code: 2,
>   details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
>     '    at Bridge.inject (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:363:15)\n' +
>     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
>     '    at async Bridge.onLoad (file:///home/cehua/cdp/getting-started-main/node_modules/_wechaty-puppet-wechat@1.18.1@wechaty-puppet-wechat/src/bridge.ts:214:7)'
> ```

同样问题，用不了。

**Comment by jonnyzheng** [comment]
我也有这个问题，不知道怎么解决

**Comment by Zyx-A** [comment]
我这边的也遇到过类型的现象。确保本地 python-wechaty 代码没错，且确保作为中转代理的 wechaty 其他配置都没错的情况下，试试更换协议，也许能解决。
我就是使用 ding-dong.py 示例进行测试时，发现使用 wechaty-puppet-wechat 协议，无论是 wechaty 代理服务器自己的登陆，还是示例代码运行后的登陆，都扫码后提示报错。而更换 wechaty-puppet-wechat4u 协议后，两处不通的问题全都没有了。

**Comment by PeterChen1997** [comment]
> 

有用 感谢

**Comment by itooth** [comment]
> 我这边的也遇到过类型的现象。确保本地 python-wechaty 代码没错，且确保作为中转代理的 wechaty 其他配置都没错的情况下，试试更换协议，也许能解决。 我就是使用 ding-dong.py 示例进行测试时，发现使用 wechaty-puppet-wechat 协议，无论是 wechaty 代理服务器自己的登陆，还是示例代码运行后的登陆，都扫码后提示报错。而更换 wechaty-puppet-wechat4u 协议后，两处不通的问题全都没有了。

有用
