### ISSUE TITLE
企微群有加入群聊的事件时 会调dirtyPayloadContact 报错ERR_INVALID_CONTACT_ID

### ISSUE THREAD

**Issue by JessicaChim** [wechaty/wechaty#2431]
![image](https://user-images.githubusercontent.com/88080263/180935570-16872fd6-86a7-47c0-a140-4cb2b47e5eb6.png)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_ROOM_JOIN(19), payload:"{"inviteeIdList":["1688851146730811"],"inviterId":"1688851146730940","roomId":"R:10887079551159373","timestamp":1658815428189}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":4}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 SILL Contact constructor(R:10887079551159373)
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 SILL Puppet contactPayload(R:10887079551159373) cache MISS
14:03:47 VERB PuppetService contactRawPayload(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":2}"})
14:03:47 SILL Wechaty memoryCheck() free: 885 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB Contact ready() this.wechaty.puppet.contactPayload(R:10887079551159373) exception: 2 UNKNOWN: Error: ERR_INVALID_CONTACT_ID all ids should be number, R:10887079551159373 is not a number.
    at DataManager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:910:23)
    at Generator.next (<anonymous>)
    at C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:27:12)
    at DataManager.getContact (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:908:16)
    at DataManager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:901:40)
    at Generator.next (<anonymous>)
    at C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:31:71
    at new Promise (<anonymous>)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 SILL Puppet contactPayload(R:10887079551159373) cache MISS
14:03:47 VERB PuppetService contactRawPayload(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":2}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":4}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB Puppet dirtyPayload(RoomMember<4>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoomMember(R:10887079551159373)
14:03:47 VERB PuppetService roomMemberList(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":3}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 VERB Room ready()
14:03:47 VERB Puppet dirtyPayload(Room<3>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadRoom(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":4}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 VERB Contact ready() this.wechaty.puppet.contactPayload(R:10887079551159373) exception: 2 UNKNOWN: Error: ERR_INVALID_CONTACT_ID all ids should be number, R:10887079551159373 is not a number.
    at DataManager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:910:23)
    at Generator.next (<anonymous>)
    at C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:27:12)
    at DataManager.getContact (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:908:16)
    at DataManager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:901:40)
    at Generator.next (<anonymous>)
    at C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:31:71
    at new Promise (<anonymous>)
14:03:47 SILL Puppet contactPayload(R:10887079551159373) cache MISS
14:03:47 VERB PuppetService contactRawPayload(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":2}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":4}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)
14:03:47 SILL Puppet contactPayload(R:10887079551159373) cache MISS
14:03:47 VERB PuppetService contactRawPayload(R:10887079551159373)
14:03:47 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_DIRTY(27), payload:"{"payloadId":"R:10887079551159373","payloadType":2}"})
14:03:47 SILL Wechaty memoryCheck() free: 886 MB, require: 4 MB
14:03:47 SILL Contact ready() @ Puppet#0<PuppetService>(1073883076876826899) with id="R:10887079551159373"
14:03:47 VERB Puppet dirtyPayload(Contact<2>, R:10887079551159373)
14:03:47 VERB Puppet dirtyPayloadContact(R:10887079551159373)

这里的ID是roomid 但是调用了dirtyPayloadContact  这是为什么？怎么才可以不报错？

**Comment by xmsz** [comment]
+1

**Comment by juneyang** [comment]
+1

**Comment by su-chang** [comment]
Please replace `wechaty` module by `@juzi/wechaty` module, and then have a try again.

**Comment by xuwancheng** [comment]
该问题还是存在，那变也报了相同的问题，但是没有人解决
