### ISSUE TITLE
SyntaxError: The requested module 'wechaty' does not provide an export named 'UrlLink'

### ISSUE THREAD

**Issue by zhouted** [wechaty/wechaty#2449]
## 1. Versions
- What is your wechaty version?
Answer: 1.18.1

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: puppeteer

- What is your node version? (run `node --version`)
Answer: 16.17.1

- What os are you using
Answer: windows10

## 3. To Reproduce
````js
import { ScanStatus, WechatyBuilder, UrlLink, MediaMessage, log } from 'wechaty';
````
````shell
npm start
````
````conole
SyntaxError: The requested module 'wechaty' does not provide an export named 'UrlLink'
SyntaxError: The requested module 'wechaty' does not provide an export named 'MediaMessage'
````

**Comment by zaneon** [comment]
> const urlLink = new bot.UrlLink({})

**Comment by zaneon** [comment]
`const urlLink = new bot.UrlLink({})`

**Comment by zaneon** [comment]
`
const urlLink = new bot.UrlLink({})
`
