### ISSUE TITLE
Wechaty feature UrlLink is not a constructor

### ISSUE THREAD

**Issue by fengquanju** [wechaty/wechaty#2450]
I want to send the UrlLink message,so I write the :
const { WechatyBuilder,UrlLink } = require('wechaty');

and
async function onMessage(msg) {
const contact = msg.talker(); // 发消息人
  const content = msg.text().trim(); // 消息内容
  const room = msg.room(); // 是否是群消息
  const alias = await contact.alias() || await contact.name(); // 发消息人备注
  const isText = msg.type() === bot.Message.Type.Text;
  console.log("bot.Message.Type.Text",bot.Message.Type.Text)
  if (msg.text() === 'ding') {
    const urlLink = new UrlLink ({
      description : 'WeChat Bot SDK for Individual Account, Powered by TypeScript, Docker, and Love',
      thumbnailUrl: 'https://avatars0.githubusercontent.com/u/25162437?s=200&v=4',
      title       : 'Welcome to Wechaty',
      url         : 'https://github.com/chatie/wechaty',
    })
    msg.say(urlLink)
  }
}
but has the error message：
TypeError: UrlLink is not a constructor

**Comment by noodelskun** [comment]
try this
`const urlLink = new bot.UrlLink({})`
