### ISSUE TITLE
ts版不能发送小程序和网页链接吗?按照api文档操作显示类找不到买了服务不能用????求解释??

### ISSUE THREAD

**Issue by jackzhangrunze** [wechaty/wechaty#2451]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

版本
"wechaty": "^1.19.10",
    "wechaty-puppet": "^1.19.6",
    "wechaty-puppet-padlocal": "^1.11.18"

**Comment by zhaoeryu** [comment]
找到解决方法了吗？
