### ISSUE TITLE
docker部署，扫码登录后报503错误

### ISSUE THREAD

**Issue by isbiong100** [wechaty/wechaty#2454]
WECHATY Environment Variables: 5
WECHATY_TOKEN=“MY_TOCKEN”
WECHATY_DOCKER=1
WECHATY_PUPPET_SERVER_PORT=8080
WECHATY_LOG=verbose
WECHATY_PUPPET=wechaty-puppet-wechat

tarting Docker Container for Wechaty v1.20.2 with Node.js v16.15.0 

报错日志：
09:00:33 INFO IoClient [4] https://login.weixin.qq.com/l/wZ2a6cNrjA==
Online QR Code Image: https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FwZ2a6cNrjA%3D%3D
09:00:34 VERB PuppetWeChatBridge onLoad() page.url=https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=AS8SYJEE1ut7ltDHUltpn81k@qrticket_0&uuid=wZ2a6cNrjA==&lang=en_US&scan=1667898024
09:00:34 VERB PuppetWeChatBridge readyAngular()
09:00:34 VERB PuppetWeChatBridge inject()
09:00:34 VERB PuppetWeChatBridge inject() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env. stack: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///wechaty/node_modules/wechaty-puppet-wechat/src/bridge.ts:363:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///wechaty/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)
09:00:34 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env

端口是打开的，docker是没问题的，请问是怎么回事？

**Comment by ericcug** [comment]
你需要自己编译更新使用新版的wechaty-puppet-wechat，官方docker未包含支持uos的puppet。

**Comment by huan** [comment]
A PR request to upgrade the UOS support is welcome!

**Comment by ericcug** [comment]
> > 你需要自己编译更新使用新版的wechaty-puppet-wechat，官方docker未包含支持uos的puppet。
> 
> 请问有具体的方法吗？（虚心求教）

建议你搜索一下docker build 教程，clone仓库本地自己编译镜像。

**Comment by Shaun-Fong** [comment]
[最新Wechaty镜像](https://hub.docker.com/repository/docker/shaunfong/wechaty/general)，2023.7.1

**Comment by Shaun-Fong** [comment]
@huan You may want to check this [Fix Build In Workflow](https://github.com/Shaun-Fong/wechaty/blob/main/.github/workflows/docker.yml)

**Comment by huan** [comment]
Can you explain what you have done? Thanks.

**Comment by Shaun-Fong** [comment]
> Can you explain what you have done? Thanks.

I found that the publish step of the workflow did not execute correctly, I used a [publish action](https://github.com/marketplace/actions/docker-publish) from the marketplace instead (**network Socket timeout** in current publish action step).

**Comment by huan** [comment]
Could you please help us to send a PR to fix the main repo?

Thanks!
