### ISSUE TITLE
wechaty消息处理是否可以私有化部署？

### ISSUE THREAD

**Issue by lixijia2009** [wechaty/wechaty#2458]
我们的群消息含有非常隐私的数据，所以想了解：
1、我们在wechaty上发的消息，在wechaty是否会有留存？
2、wechaty平台是部署在自己的机房，还是托管在云端？如果托管在云端，是在哪个云？

**Comment by ericcug** [comment]
wechaty据我所知并没有提供托管服务，如果你使用托管建议咨询托管服务商。如果你很在意隐私，可以考虑使用puppet-xp [https://github.com/wechaty/puppet-xp](url) 自主部署，并且是免费的。
