### ISSUE TITLE
🔥🔥🔥 Introducing new puppet-service: wechaty-puppet-workpro

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2462]
Hello Wechaty community!

We are RPAChat, from Silcon Valley, developer of wechaty-puppet-wxwork(hereinafter called 'WxWork'). We focused on creating Robots from IM based on RPA technique. RPAChat is providing marketing cloud solution for well-known brands e.g. P&G, L’ORÉAL Paris, Swisse and POPMART.

![RPAChat](https://user-images.githubusercontent.com/13669999/209313637-cc938c6d-2144-4784-8ebd-3c638080ba43.jpg)

Now we are proud to announce our next-generation wecom puppet: wechaty-puppet-workpro(hereinafter called 'WorkPro').

It's been over two years since we published our first WxWork version. It has been well received, however there are some unsolvable problems due to basic structure:

- huge memory and cpu consumption
- react slowly when receiving wecom official broadcast
- takes a long time to sync messages when login

And WorkPro solves all above problems with a complete new design. It is absolutely incredible with great efficiency improvement. It also contains many great new features which are not completely supported by community version of wechaty currently. We are working on pushing these features now. Such as:

- Moment posting
- Quote messages
- Channel messages
- System messages
- Contact tagging
- Room announcement event*
- ...and much more

~Please note that room announce events will cause break down in current wechaty-puppet-service. See: https://github.com/wechaty/puppet-service/issues/216.~
***Please use the latest version of wechaty-puppet-service (>1.19.9) to prevent above issue.***

Besides the above room announcement event issue, workpro is compatible with current community wechaty version. Some of the latest features may be unusable, but you can still benefit from great efficiency improvement.

You can use [Wechaty getting-started project](https://github.com/wechaty/getting-started) to try WorkPro. (You'll need a token first.)

- Run via Github Codespace

    1. Click [Github Codespace](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=78732688) and then click ```Create Codespace```. Then wait for a while for the configuration service to install dependencies automatically.
    2. Set up environment variables. Currently we do not support TLS, see : <https://github.com/wechaty/puppet-service/issues/160>

        ```shell
        export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
        ```

    3. Edit ```examples/ding-dong-bot.ts``` which should be opended in editor already, replace line  73-76 to

        ```ts
        puppet: 'wechaty-puppet-service', // WorkPro is a puppet service, so you should put 'wechaty-puppet-service' instead of 'wechaty-puppet-workpro'
        puppetOptions: {
          token: 'xxx', // Put your token here, it should be something like 'puppet_workpro_xxxxxx'
        }
        ```

    4. Start the bot with ```npm start```. You should see the QRCode in the terminal.

- Run locally with ```git clone```

    1. Install dependencies. Make sure you have node 16 or above installed. Then run

        ```shell
        npm install cross-env -g
        npm install
        ```

    2. Set up environment variables. Currently we do not support TLS, see : <https://github.com/wechaty/puppet-service/issues/160>

        ```shell
        export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
        ```

    3. Edit ```examples/ding-dong-bot.ts``` which should be opended in editor already, replace line  73-76 to

        ```ts
        puppet: 'wechaty-puppet-service', // WorkPro is a puppet service, so you should put 'wechaty-puppet-service' instead of 'wechaty-puppet-workpro'
        puppetOptions: {
          token: 'xxx', // Put your token here, it should be something like 'puppet_workpro_xxxxxx'
        }
        ```

    4. Start the bot with ```npm start```. You should see the QRCode in the terminal.

For further information and 7-day free trial token application, please scan the following QRCode with wechat or wecom:
![Wechaty-GitHub-issue](https://user-images.githubusercontent.com/13669999/209300114-69281d6a-4ad3-44d4-80be-5215f1f06ac6.png)

Wish to talk to you soon.

RPAChat

**Comment by huan** [comment]
That's a fantastic new puppet; good job!

**Comment by JAi-Li** [comment]
![image](https://github.com/wechaty/wechaty/assets/45959826/05e4c1bc-2012-4a03-96d8-531042175a67)
If a user enters or exits the group chat, an error will be reported. How can I solve this problem

**Comment by zhongyufan** [comment]
> 

使用onError监听错误

**Comment by yalongwan** [comment]
客服没人答复啊
