### ISSUE TITLE
onMessage Repeat multiple times

### ISSUE THREAD

**Issue by lcm1475** [wechaty/wechaty#2473]
After I run npm run dev, I send three messages. When I finish the process and rerun npm run dev onMessage, the previous three messages will be output again. What method can I use to filter historical messages

**Comment by netcyabc** [comment]
我有个糙办法，msg.age()可以取得消息距当前系统时间的秒差，将此值大于一定值(几秒差不多就可以)的msg排除即可.

You can try to filter the messages whose 'msg.age()' are greater than a specific value.
