### ISSUE TITLE
[Feature Request]Wechaty should support messagePreview

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2479]
When receiving a mutil-media message, we may want to have a peek before we actually download the whole message.
e.g.
When receiving a file, we want to know its name and size to decided if we really need to download it or not.
When receiving a video, we want to just look at the thumbnail before we go through the whole video.

So introducing message.preview(), in my mind it looks like this:

```ts
async preview(): Promise<MessagePreviewObject> {}

interface MessagePreviewObject {
  fileMetadata?: FileMetadata | VideoMetadata | AudioMetadata,
}

interface FileMetadata {
  size?: number,
  name?: string,
}

interface VideoMetadata extends FileMetadata {
  duration?: number,
  height?: number,
  width?: number,
  thumbnail?: FileBox,
  thumbsize?: number,
  thumbwidth?: number,
  thumbheiht?: number,
}

interface AudioMetadata extends FileMetadata {
  duration?: number,
}
```

**Comment by huan** [comment]
@hcfw007 You can set the `size` in the FileBox serialization to archive this feature.

See:

https://github.com/huan/file-box/blob/fcae3be890801283ec2790fd57f91d643391517a/src/file-box.ts#L435-L448

**Comment by hcfw007** [comment]
> @hcfw007 You can set the `size` in the FileBox serialization to archive this feature.
> 
> See:
> 
> https://github.com/huan/file-box/blob/fcae3be890801283ec2790fd57f91d643391517a/src/file-box.ts#L435-L448

well, that will requires the puppet to download the file first in order to pack it into a filebox. With preview we can prevent the download process all alone if we don't want the file.

**Comment by huan** [comment]
> that will requires the puppet to download the file first in order to pack it into a filebox.

That's not true.

The download is not required, please read the code and you can figure it out by yourhelp.

**Comment by hcfw007** [comment]
> > that will requires the puppet to download the file first in order to pack it into a filebox.
> 
> That's not true.
> 
> The download is not required, please read the code and you can figure it out by yourself.

Our understand to download is different here. I meant download from IM to the puppet. e.g. when WorkPro recieves a file message, we need to download the file from wecom server to workpro server in order to create a filebox instance. However the metadata of size and filename dows not require such download.

**Comment by huan** [comment]
> we need to download the file from wecom server to workpro server in order to create a filebox instance.

I believe this can be lazy-loaded as well.

**Comment by hcfw007** [comment]
At current version? Could you explain a little more ?

**Comment by huan** [comment]
Thanks for asking! I’d love to explain and discuss on it.

it seems there are many improvements ideas & prs need to be discussed. Would you like to organize a community meeting for us, so that we can have a agenda for all of those and we can have a deep conversation and make it fast for decision? (Also welcome community developers/contributors to join)

It would be great if you can help us to organize it, please let me know that you think.

Thanks, and I hope you have a great day!

**Comment by hcfw007** [comment]
I have never organized such event before. Is there any conventions? e.g. do we have a live meeting or a text-based thread?

**Comment by hcfw007** [comment]
@huan Could you please explain how to lazy-load a media message with current version of wechaty when you have time?

**Comment by huan** [comment]
I’d love to explain them.

Could you please organize a meeting from https://calendly.com/huan/wechaty so that we can have a community meeting?

**Comment by hcfw007** [comment]
I also took the liberty to invite @su-chang and @windmemory to this meeting.

Is there a public bulletin board thing to post info about this meeting?

**Comment by huan** [comment]
Please create an new meeting entry at our Wechaty community meeting notes at https://bit.ly/2zpi2XG

**Comment by hcfw007** [comment]
After discussion in Wechaty Community Meeting (brief [here](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.si1xxj2xji7f))
We have dicided to implement lazy load with uuid-filebox.
TODO:
1. In wechaty-puppet-service server side, we can rewrite uuid loader so that when it cannot find the file in hard disk, it will search in cache to find the corresponding message and download the file and then pass it to client.
2. Use filebox metadata to pass metadata like duration, height and width.

Question:
Should we add a switch allowing bot to control whether auto-download media messages or not?
@huan @su-chang

**Comment by hcfw007** [comment]
@huan I now have an idea about how to implement this with WorkPro. In WorkPro I have full control of message caching and file downloading, so I can map the uuid with message and file.
But in regualr service run with wechaty-puppet-service, how do we achieve it? Especially for messages with mutiple files.

Example:
We have a image message, which contains a thumbnail and a HD image file.
Suppose messageImage(thumb) returns FileBox<uuid 'image-thumb'>, and messageImage(HD) returns FileBox<uuid 'HD'>. When bot calls filebox.toFile(), how do we download the corresponding file?
We need a cache mapping not only uuid to messageId, but also type of the file. This may also apply to MiniPrograms (thumb and icon) and other messages.
This seems a bit complicated. Is there a better way to do this?

CC @su-chang @windmemory
