### ISSUE TITLE
We might need a system level notification event

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2482]
We have events for some specific notifications, e.g. LOGOUT, ROOM_CREAT, etc.
However as we look deeper into an IM, we might find some less-important but still useful events that does not belong to any contact (so it cannot be put into message) or categorized into any exisiting event.
For example:
whatsapp: incoming call, battery change (some of whatsapp functionality relies on connection with phone, so if battery ran out, it may be effected)
wecom: system downgraded (sometimes the auth is partially invalid, some of the apis are effected, but the account is not logged out, you can send messages but you cannot post moment.)

Or is there a way to pass such event in current design?

**Comment by huan** [comment]
I’m curious about how did you fix it? It would be better to share the update under this issue before close it

**Comment by hcfw007** [comment]
This is not fixed. I closed it because I further introduced this in a new issue: https://github.com/wechaty/wechaty/issues/2529

So far what we did is implement new events in forked wechaty, and stop puppet-service from throwing errors in https://github.com/wechaty/puppet-service/pull/220
