### ISSUE TITLE
使用该功能，今天收到微信使用第三方插件提醒，你们有收到信息吗

### ISSUE THREAD

**Issue by jsl1992** [wechaty/wechaty#2488]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
今天收到了，微信使用第三方插件提醒
![44cc45ba9ea69f472d27179586d681d](https://user-images.githubusercontent.com/34052259/217536566-1ff56bed-ca50-4595-acc0-e9017cebab46.jpg)
想问下，腾讯是禁止使用第三方了吗

**Comment by thechen130** [comment]
+1，同样的问题，有解决办法吗

**Comment by Xavier9896** [comment]
一样的问题

**Comment by zhihuifanqiechaodan** [comment]
使用的收费版本还是免费版本。免费版本收到信息很正常。

**Comment by Xavier9896** [comment]
免费版本

**Comment by zhihuifanqiechaodan** [comment]
> 免费版本

用收费的吧，免费的还指望啥。

**Comment by thechen130** [comment]
> > 免费版本
> 
> 用收费的吧，免费的还指望啥。

收费版本如何使用，我是小白

**Comment by Xavier9896** [comment]
给开源项目微信群做关键字回复、定时消息等功能的，每个月200+的费用不值得

**Comment by zhihuifanqiechaodan** [comment]
> > > 免费版本
> > 
> > 
> > 用收费的吧，免费的还指望啥。
> 
> 收费版本如何使用，我是小白

看官网吧，介绍的很详细。

**Comment by zhihuifanqiechaodan** [comment]
> 给开源项目微信群做关键字回复、定时消息等功能的，每个月200+的费用不值得

免费的终究会有封禁的一天，目前只能通过不断的换号了。

**Comment by Lyq0055** [comment]
> 

联系不上padlocal的人员，想付费也不行啊

**Comment by wanguanyun** [comment]
连续两天 提示了两次 第二次还要要求好友辅助验证才能解封。 暂时不敢用了

**Comment by Xavier9896** [comment]
> 连续两天 提示了两次 第二次还要要求好友辅助验证才能解封。 暂时不敢用了

我在5、6天前停用了，昨天都依然收到了警告，本来就因为一些原因需要临时停用，所以近期暂时都没有重新使用的打算。
警告这出就更加不用了

**Comment by FLIER001** [comment]
开发者已经放弃wechaty项目了吗，收费的padpro也没人管了

**Comment by ringki** [comment]
看来不止我一个人，同问，还有啥解决方案嘛

**Comment by su-chang** [comment]
> 开发者已经放弃wechaty项目了吗，收费的padpro也没人管了

padpro这个项目应该很早之前就停用了，可以再次确认下用是是padlocal还是其他的puppet？

**Comment by ringki** [comment]
我有个大胆的猜测，之所以近期微信对“机器人”的监管变严了，或许是因为最近凭空出现了不少靠着“chatGpt”做智能机器人盈利的人，导致被微信针对了。导致我们就莫名躺枪了。。。

**Comment by zhihuifanqiechaodan** [comment]
> > 
> 
> 
> 
> 联系不上padlocal的人员，想付费也不行啊

可以联系我购买

**Comment by zhangdudu0** [comment]
搞不懂，开源了，一群人免费维护，就作者把钱全赚了？

**Comment by huanghonghao** [comment]
> 搞不懂，开源了，一群人免费维护，就作者把钱全赚了？

不完全开源，这个是服务收费的，你先到官网了解清楚。最核心的各平台通讯协议代码没放出来。

**Comment by nsnsqk** [comment]
> 搞不懂，开源了，一群人免费维护，就作者把钱全赚了？

这么给你解释吧： 开源的是接口定义，具体的方法实现和服务，都在各自puppet提供商那里

**Comment by nsnsqk** [comment]
> > > 
> > 
> > 
> > 联系不上padlocal的人员，想付费也不行啊
> 
> 可以联系我购买

从你这购买，便宜吗

**Comment by Rackar** [comment]
![image](https://user-images.githubusercontent.com/18388400/229250147-26cf6541-98dd-4a20-8a85-824ceb17c9de.png)

**Comment by RolloTomasiii** [comment]
> > > 
> > 
> > 
> > 联系不上padlocal的人员，想付费也不行啊
> 
> 可以联系我购买

怎么联系

**Comment by Xavier9896** [comment]
> > > > 
> > > 
> > > 
> > > 联系不上padlocal的人员，想付费也不行啊
> > 
> > 
> > 可以联系我购买
> 
> 怎么联系

这不他的主页就有联系方式吗？
https://github.com/zhihuifanqiechaodan
