### ISSUE TITLE
使用 wechaty-puppet-padlocal 这个puppet 二维码登陆失败

### ISSUE THREAD

**Issue by quboqin** [wechaty/wechaty#2492]
## 0. Report Issue Guide
使用 wechaty-puppet-padlocal 这个puppet 二维码登陆失败

```
0|wechat  | 02:11:11 ERR [Request] [tid:7f053c07], padlocal grpc request failed: 3, error: IOError: [tid:7f053c07] Exception while handling wechat request: longlink reset
0|wechat  | 02:11:11 ERR [PadLocalClient] error while syncing onpush: VError: [tid:7f053c07] request has been cancelled for reason: CLIENT_ERROR: [tid:7f053c07] Exception while handling wechat request: longlink reset
0|wechat  |     at Request._failAllPendingRequest (/root/wechat/node_modules/padlocal-client-ts/dist/Request.js:265:19)
0|wechat  |     at Request.error (/root/wechat/node_modules/padlocal-client-ts/dist/Request.js:275:14)
0|wechat  |     at Request.<anonymous> (/root/wechat/node_modules/padlocal-client-ts/dist/Request.js:159:30)
0|wechat  |     at Generator.throw (<anonymous>)
0|wechat  |     at rejected (/root/wechat/node_modules/padlocal-client-ts/dist/Request.js:6:65)
0|wechat  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|wechat  | 02:11:11 WARN [PadLocalClient]
```

在本地环境调试的时候没有问题, 但是部署在云端就会出现这个问题.经过自己反复尝试,似乎和部署的云服务器主机的外网IP地址有关,我换了不同的主机或IP地址,有时候就没有问题(都是用的Ubuntu 20.04, Nodejs的版本也是18,我确信不是版本的问题). 不知道大家是否遇到类似的问题?

**Comment by isbiong100** [comment]
pad版本建议用容器部署

**Comment by Linjovi** [comment]
同样的问题

**Comment by emilsong** [comment]
同样问题，困扰一个星期了，尝试了各种方法，换wx号，换服务器，换国内国外。。。。
跪求解决方案

00:29:12 INFO StarterBot Starter Bot Started.
00:29:12 INFO [PuppetPadlocal] start login with type: AutoLogin
00:29:13 INFO [PuppetPadlocal] start login with type: OneClickLogin
00:29:13 INFO [PuppetPadlocal] start login with type: QrLogin
00:29:13 ERR [Request] [tid:f850fe1b], padlocal grpc request failed: 3, error: IOError: [tid:f850fe1b] Exception while handling wechat request: longlink reset
00:29:13 ERR start client failed: VError: [tid:f850fe1b] request has been cancelled for reason: CLIENT_ERROR: [tid:f850fe1b] Exception while handling wechat request: longlink reset
    at Request._failAllPendingRequest (/opt/chat-padlocal/node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at Request.error (/opt/chat-padlocal/node_modules/padlocal-client-ts/dist/Request.js:275:14)
    at Request.<anonymous> (/opt/chat-padlocal/node_modules/padlocal-client-ts/dist/Request.js:159:30)
    at Generator.throw (<anonymous>)
    at rejected (/opt/chat-padlocal/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by emilsong** [comment]
升级服务器系统，升级nodejs版本到最新的18 问题解决了，困扰了1个星期。。。
