### ISSUE TITLE
Wechat bot to relay ChatGPT queries to desktop app

### ISSUE THREAD

**Issue by kevinwatson2** [wechaty/wechaty#2494]
I see a demand for a new feature that enables WeChaty to relay ChatGPT queries from WeChat to ChatGPT Desktop App (https://github.com/lencx/ChatGPT).  I do not have relevant knowledge or skills to implement it, but hope some gurus can help make it happen.  

Currently, Open AI does not provide ChatGPT service to queries initiated from China, but a ChatGPT Desktop App running in the US can relay the queries from WeChat if a messaging channel is established between WeChat and ChatGPT Desktop.  I imagine that a robot signing in to WeChat as group member can filter messages, and relay relevant messages or queries to ChatGPT Desktop and further to ChatGPT servers.  After ChatGPT Desktop receives the responses, it replicates the responses to the robot, which further relays and displays them in the corresponding WeChat group.  I am not sure if I have stated my idea clearly but please let me know if you have any questions or see anything infeasible.  

Thanks,
-Kevin

**Comment by zhihuifanqiechaodan** [comment]
i think it's a good idea and feature
