### ISSUE TITLE
怎么组装一个UrlLink或者小程序消息，官方的例子都过期了不能使用

### ISSUE THREAD

**Issue by jschenqiang** [wechaty/wechaty#2495]
类似这种的  
 const urlLink = new UrlLink ({
        description : 'WeChat Bot SDK for Individual Account, Powered by TypeScript, Docker, and Love',
        thumbnailUrl: 'https://avatars0.githubusercontent.com/u/25162437?s=200&v=4',
        title       : 'Welcome to Wechaty',
        url         : 'https://github.com/chatie/wechaty',
      })

**Comment by su-chang** [comment]
```ts
const bot = WechatyBuilder.build({
  puppet
})
const urlObj = bot.UrlLink(urlLink)
```

**Comment by stefan-ysh** [comment]
I can't see the cause of the problem in such a single lines of code,  I code like you and it works perfectly. Or it could be that you imported UrlLink in the wrong way. I hope you can give some more information, such as wechaty version, runtime terminal errors, etc. The follwing code is which works in my app.
### code
```js
    import { WechatyBuilder } from "wechaty"
    const bot = WechatyBuilder.build(YOUR_PUPPET_CONFIG)
    const linkPayload = new bot.UrlLink({
      description: 'WeChat Bot SDK for Individual Account, Powered by TypeScript, Docker, and Love',
      thumbnailUrl: 'https://avatars0.githubusercontent.com/u/25162437?s=200&v=4',
      title: 'Welcome to Wechaty',
      url: 'https://github.com/wechaty/wechaty'
    })
    return await room.say(linkPayload)
```
### wechaty version
```json
  "wechaty": "^1.18.1"
```
### demo
![image](https://user-images.githubusercontent.com/58702199/221594023-ac7ce04e-2d2d-40b7-b8e9-1d52f7e62c96.png)

**Comment by zhaoeryu** [comment]
我之前也遇到了这个问题，`1.x`和`0.x`版本的使用方式是有一些区别的

## 代码
```javascript
const bot = WechatyBuilder.build({
    name: botName,
    puppet: new PuppetPadlocal({token}),
})

const urlLink = new bot.UrlLink({
    description  : '',
    thumbnailUrl : '',
    title         : '',
    url           : '',
})
```

## 版本
```
"wechaty": "^1.20.2",
"wechaty-puppet": "^1.20.2",
```

**Comment by jschenqiang** [comment]
> 我之前也遇到了这个问题，`1.x`和`0.x`版本的使用方式是有一些区别的
> 
> ## 代码
> ```js
> const bot = WechatyBuilder.build({
>     name: botName,
>     puppet: new PuppetPadlocal({token}),
> })
> 
> const urlLink = new bot.UrlLink({
>     description  : '',
>     thumbnailUrl : '',
>     title         : '',
>     url           : '',
> })
> ```
> 
> ## 版本
> ```
> "wechaty": "^1.20.2",
> "wechaty-puppet": "^1.20.2",
> ```

多谢，小程序消息可以发出来了，点击又打不开，你遇到这种情况了吗？

**Comment by nsnsqk** [comment]
借楼 问一个，bot.$on('message'） 监听到的消息，能直接持久化到数据库吗，下次发送的时候，直接通过  message.say() 方法发出
有人实现了吗？？

**Comment by jschenqiang** [comment]
> 借楼 问一个，bot.$on('message'） 监听到的消息，能直接持久化到数据库吗，下次发送的时候，直接通过 message.say() 方法发出 有人实现了吗？？

你接收到消息后，自己重新定义实现，如果仅仅是回复的话，可以临时放到redis中
import { createClient } from 'redis';

const client = createClient({
    socket:{
        host:'localhost',
        port:6379,
    },
    password:'password',
    connectTimeout:5000,
    reconnectStrategy: retries => Math.min(retries * 50, 1000)
});

**Comment by nsnsqk** [comment]
我这场景是，定时消息发送，哪天发什么消息，隔多久发一次这种
        文本还好说，图片、小程序、视频类的，如果用wechaty 自己存入库，到时候再取出消息，组装成wechaty的消息体，进行发出，就比较复杂了（要搭建图片、视频文件服务器等）在寻求中直接把 bot.$on('message') 监听到的消息，直接入库保存的思路，不知道可不可行
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月21日 13:58
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [wechaty/wechaty] 怎么组装一个UrlLink或者小程序消息，官方的例子都过期了不能使用 (Issue #2495)
        
      
    
  


借楼 问一个，bot.$on('message'） 监听到的消息，能直接持久化到数据库吗，下次发送的时候，直接通过 message.say() 方法发出 有人实现了吗？？

你接收到消息后，自己重新定义实现，如果仅仅是回复的话，可以临时放到redis中
import { createClient } from 'redis';
const client = createClient({
socket:{
host:'localhost',
port:6379,
},
password:'password',
connectTimeout:5000,
reconnectStrategy: retries => Math.min(retries * 50, 1000)
});

**Comment by wwz223** [comment]
我发现发送的公众号文章信息没有来源，有人知道什么原因吗
<img width="725" alt="image" src="https://user-images.githubusercontent.com/36815297/233814834-c2f64cdf-cbc5-4344-8583-6bc7bfb87983.png">

**Comment by nsnsqk** [comment]
> 我这场景是，定时消息发送，哪天发什么消息，隔多久发一次这种 文本还好说，图片、小程序、视频类的，如果用wechaty 自己存入库，到时候再取出消息，组装成wechaty的消息体，进行发出，就比较复杂了（要搭建图片、视频文件服务器等）在寻求中直接把 bot.$on('message') 监听到的消息，直接入库保存的思路，不知道可不可行 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年3月21日 13:58 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [wechaty/wechaty] 怎么组装一个UrlLink或者小程序消息，官方的例子都过期了不能使用 (Issue #2495) 借楼 问一个，bot.$on('message'） 监听到的消息，能直接持久化到数据库吗，下次发送的时候，直接通过 message.say() 方法发出 有人实现了吗？？ 你接收到消息后，自己重新定义实现，如果仅仅是回复的话，可以临时放到redis中 import { createClient } from 'redis'; const client = createClient({ socket:{ host:'localhost', port:6379, }, password:'password', connectTimeout:5000, reconnectStrategy: retries => Math.min(retries * 50, 1000) }); —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

你实现了直接持久化message吗，兄dei。我也有定时消息的业务场景

**Comment by zhaoeryu** [comment]
> 

遇到过，我当时是因为有两个参数没有写正确

```
{
    ...
    "pagePath": "pages/loading/index.html"
    "username": "gh_600xxxxxxxx@app"
}
```
1、检查一下你的`pagePath`是否以`pages/`开头
2、`username`的值需要在结尾添加`@app`

祝你成功！

**Comment by 532777032** [comment]
> 类似这种的 const urlLink = new UrlLink ({ description : 'WeChat Bot SDK for Individual Account, Powered by TypeScript, Docker, and Love', thumbnailUrl: 'https://avatars0.githubusercontent.com/u/25162437?s=200&v=4', title : 'Welcome to Wechaty', url : 'https://github.com/chatie/wechaty', })

你后面可以了吗，我1.20.2版本也是卡这个问题，我是.js运行的，不是ts版本
