### ISSUE TITLE
为了你的帐号安全，请重新登录

### ISSUE THREAD

**Issue by TidyScript** [wechaty/wechaty#2496]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
error:Wechaty - INFO - receive <logout> event <EventLogoutPayload(contact_id='xxxxxx', data='为了你的帐号安全，请重新登录。')>

**Comment by haishen668** [comment]
我也有这个问题请问怎么解决啊

**Comment by aqpmzngldh** [comment]
> 我也有这个问题请问怎么解决啊

请问怎么解决的啊
