### ISSUE TITLE
你好，我是年费用户，新手，现在遇到：”为了你的帐号安全，请重新登录“，很崩溃

### ISSUE THREAD

**Issue by TidyScript** [wechaty/wechaty#2497]
如题，年费用户，如图
![image](https://user-images.githubusercontent.com/39083672/221125911-c26712c1-da63-44de-be5e-ba49997e8728.png)

已经在阿里云和腾讯云都试过，扫码过10秒附近，就提示：”为了你的帐号安全，请重新登录“。

**Comment by zhihuifanqiechaodan** [comment]
新注册的微信号还是老的微信号，新的话需要先养号，不然很容易风控

**Comment by TidyScript** [comment]
> 新注册的微信号还是老的微信号，新的话需要先养号，不然很容易风控

现在已经没问题了。当时新老微信号都出问题了。

**Comment by coderPeng3yang** [comment]
> 如题，年费用户，如图 ![image](http://user-images.githubusercontent.com/39083672/221125911-c26712c1-da63-44de-be5e-ba49997e8728.png)
> 
> 已经在阿里云和腾讯云都试过，扫码过10秒附近，就提示：”为了你的帐号安全，请重新登录“。

我也在服务器上是出来的二维码遇到这种问题,你最后怎么解决的呀

**Comment by aqpmzngldh** [comment]
> > 新注册的微信号还是老的微信号，新的话需要先养号，不然很容易风控
> 
> 现在已经没问题了。当时新老微信号都出问题了。

最后怎么解决的啊，教一下后人

**Comment by aqpmzngldh** [comment]
> > 如题，年费用户，如图 ![image](http://user-images.githubusercontent.com/39083672/221125911-c26712c1-da63-44de-be5e-ba49997e8728.png)
> > 已经在阿里云和腾讯云都试过，扫码过10秒附近，就提示：”为了你的帐号安全，请重新登录“。
> 
> 我也在服务器上是出来的二维码遇到这种问题,你最后怎么解决的呀

解决了没有啊，怎么搞的呀
