### ISSUE TITLE
发送消息出现异常 uncaughtException AssertionError

### ISSUE THREAD

**Issue by rookielz** [wechaty/wechaty#2503]
收到消息后，进行回复，调用message.say     控制台输出异常，但是实际上消息是发送成功的。异常如下：
```
uncaughtException AssertionError [ERR_ASSERTION]: 1204 == 0
    at Object.equal (/home/chatGPT/node_modules/wechat4u/lib/util/global.js:69:24)
    at /home/chatGPT/node_modules/wechat4u/lib/core.js:535:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (/home/chatGPT/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:631:9)
    at async WechatifiedUserClass.say (/home/chatGPT/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:300:23) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1204,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}

```

**Comment by lively-qcy** [comment]
我也遇到了这个问题，求解。
`WARN PuppetWechat4u contactRawPayload(AssertionError [ERR_ASSERTION]: 1205 == 0) wechat4u.batchGetContact() exception: undefined
uncaughtException AssertionError [ERR_ASSERTION]: 1205 == 0`

**Comment by myotsuki** [comment]
同样问题。。。

**Comment by myotsuki** [comment]
不知道原因，测试发现 把生成的`*.memory-card.json`文件删了，然后重新扫码登录就好了

**Comment by myotsuki** [comment]
哎。。。能用一时，后面还是一直报错。。。

**Comment by FinnWu** [comment]
> 

找到解决方案了吗

**Comment by 1999-xinz** [comment]
遇到同样问题了 uncaughtException AssertionError [ERR_ASSERTION]: 1204 == 0

**Comment by 1999-xinz** [comment]
> 遇到同样问题了 uncaughtException AssertionError [ERR_ASSERTION]: 1204 == 0

已解决，我的问题是我给自己的文件传输助手发消息是会报错的，也就是出现上面的问题；如果给群或其它人发消息是正常的(尴尬)。

**Comment by 1999-xinz** [comment]
> 用的什么puppet

我遇到的问题已解决(请忽略我的尴尬提问～); puppet使用的wechaty-puppet-wechat4u，我个人的搭建的项目主要使用微信web端登录个人账户进行的相关有趣操作。
