### ISSUE TITLE
About docs updates issue(关于文档更新的问题)

### ISSUE THREAD

**Issue by champkeh** [wechaty/wechaty#2507]
官方文档的API部分是不是不是最新版本，很多 类/方法/属性 在最新的wechaty@1.20.2里面都没有，比如`Wechaty`类不再导出，`bot.logonoff()`被废弃，文档上面都没有关于这些的说明。

请问在哪里可以看到最新的文档？还是说，需要查看ts的类型定义？

**Comment by hzb888** [comment]
加一。为什么官方不维护了。

**Comment by huan** [comment]
We are lacking of resources to build the latest version of the docs from the current maintainers, sorry for the confusing on the docs with the latest version of codes.

We’d like to accept PR to improve the docs, everyone is welcome to help the community to update the docs.
