### ISSUE TITLE
[linting] fix needed for new tslint rule: trailing-comma

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#251]
```shell
src/util-lib.ts[221, 26]: Missing trailing comma
```

**Comment by lijiarui** [comment]
@zixia please close this issue

**Comment by zixia** [comment]
You can close an issue by put `close #251` in your commit message.

Once your commit is merged, the referred issue will be closed automatically.

**Comment by lijiarui** [comment]
Thanks! I will try it next time! 

Could you please to help close the issue this time? because I just delete the branch I commited...

**Comment by zixia** [comment]
It's already closed.
