### ISSUE TITLE
query must provide at least one key. current query is empty.

### ISSUE THREAD

**Issue by coderzzp** [wechaty/wechaty#2511]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: 1.20.2

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:puppeteer

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:puppeteer

> What is your node version? (run `node --version`)

Answer:v18.15.0

> What os are you using

Answer:macos

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

when room-join trigger，there is an error：
![image](https://user-images.githubusercontent.com/24691802/229329068-5a415bc2-d216-448b-8040-9598af97d17d.png)
i print the inviteelist，but find its undifined
![image](https://user-images.githubusercontent.com/24691802/229329091-c03713bd-28bb-4dd0-b138-a2a5af7ac30e.png)
![image](https://user-images.githubusercontent.com/24691802/229329098-668bc0ee-4eca-4e3b-a4df-4871cb0a9578.png)

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. run '...'
2. ...
3. ...

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But the log message must be in plain text instead of screenshot.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> Make sure to copy/paste the full (instead of only fragments) log message in text format (instead of image/screenshot) at here

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by MEK-THEB** [comment]
same issue here with join event

**Comment by fyzhu** [comment]
this issue is not solved

**Comment by zhanghehe** [comment]
this issue is not solved
