### ISSUE TITLE
Does Wechaty support sending social circles

### ISSUE THREAD

**Issue by wwz223** [wechaty/wechaty#2514]
Wechaty 是否支持发送朋友圈

**Comment by nsnsqk** [comment]
不支持

**Comment by wwz223** [comment]
在issue中找到了使用方法
https://github.com/wechaty/wechaty/issues/2245

**Comment by nsnsqk** [comment]
> 在issue中找到了使用方法 #2245

哎，真有你的，厉害了啊。 我看这链接里，讨论的是还有视频号？
大佬们也不更新官网的api文档了。 让我等小白使用起来很费劲了

**Comment by wwz223** [comment]
文档api确实落后挺多，看起来朋友圈还支持评论点赞之类
我现在还有个问题没找到，怎么解析合并转发的消息

**Comment by hcfw007** [comment]
尽管wechaty层支持了，但具体能否发送还需要看puppet的实现。

**Comment by nsnsqk** [comment]
> 尽管wechaty层支持了，但具体能否发送还需要看puppet的实现。

如何才能催促一下puppet提供商，让他们跟上wechaty的步伐

**Comment by hcfw007** [comment]
去具体的puppet repo下面留言？。。。据我所知目前好像只有企微的puppet支持发朋友圈，个微好像没有

**Comment by nsnsqk** [comment]
> 去具体的puppet repo下面留言？。。。据我所知目前好像只有企微的puppet支持发朋友圈，个微好像没有

企微的话，只有你们句子在做吧

**Comment by hcfw007** [comment]
> > 去具体的puppet repo下面留言？。。。据我所知目前好像只有企微的puppet支持发朋友圈，个微好像没有
> 
> 企微的话，只有你们句子在做吧

是的，个微现在还在活跃的好像叫 padlocal 。但我不清楚他们有没有支持朋友圈。

**Comment by nsnsqk** [comment]
> 

是的，我在用个微的，他们不支持朋友圈，回复也是超级慢。 你们作为创始人团队，能统一在你们那维护，就太棒了。我调研了俩月了，个微需求也很大，很多的线下商家和个人客户，更喜欢用个人微信去管理客户群。 企微需要一定的成本（当然不止是那300块认证费）

**Comment by hcfw007** [comment]
个微封号政策比企微严格得多，说实话我觉得是风险很大的。。。我们不是创始人团队吧。。我也不太清楚角色到底是啥，应该只是主要的sponsor和参与者。

**Comment by nsnsqk** [comment]
lijiarui不是老板么，wechaty的创始人之一

可否加个wx沟通技术和业务
