### ISSUE TITLE
微信的视频号 消息类型，现在是0（未知类型）什么时候支持视频号的消息转发

### ISSUE THREAD

**Issue by nsnsqk** [wechaty/wechaty#2515]
有两个需求：
1 微信的视频号 消息类型，现在是0（未知类型）什么时候支持视频号的消息转发？
2 微信小程序不支持撤回，后续有排期开发小程序消息 的撤回操作吗 ？

**Comment by hcfw007** [comment]
这些都是依赖于具体puppet实现的，得看你用的是什么puppet。

**Comment by nsnsqk** [comment]
用的是padlocal

**Comment by hcfw007** [comment]
那去对应的repo发issue应该会更有效吧。我不是padplus的开发者不了解这个。
