### ISSUE TITLE
How to disable fetching offline messages after login

### ISSUE THREAD

**Issue by baiyidjp** [wechaty/wechaty#2517]
**Is your feature request related to a problem? Please describe.**
How to disable fetching offline messages after login

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by wjjmatthew** [comment]
Same request here. I have tried using msg.date() and msg.age() to filter out messages prior to login, but it doesn't seem to be reliable.
