### ISSUE TITLE
可能被腾讯官方封号,用于生产项目要谨慎....

### ISSUE THREAD

**Issue by jackzhangrunze** [wechaty/wechaty#2518]
腾讯的规则具体也没摸清楚,只发文字图片还好,发语音,网页就容易被封号,我们弄一些电商类项目,弄了一些H5付款,基本百分百被封...各位注意啊....

**Comment by jackzhangrunze** [comment]
腾讯官方应该不会支持这种群发机器人吧,官方文档写了严格进制群发机器人,感觉咱们自己玩玩就行[破涕为笑]
https://open.work.weixin.qq.com/help2/pc/14664?person_id=1&is_tencent=

**Comment by jackzhangrunze** [comment]
明白了 但是我有些惊讶,因为wechaty的官网赞助商里有腾讯的logo我还以为wechaty是受腾讯支持的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 下午5:30
收件人: ***@***.***&gt;; 
抄送: "Keep the faith ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechaty/wechaty] 可能被腾讯官方封号,用于生产项目要谨慎.... (Issue #2518)





 
这种肯定是难以避免的。。无非是看你多找些客服的成本高，还是买几个企微号成本高咯。。

**Comment by hcfw007** [comment]
大公司病，不同部门之间并不能互通有无得。据我所知腾讯游戏是使用了一些wechaty开发的产品做客服的，自家人也有可能干起来。。。

**Comment by jackzhangrunze** [comment]
那腾讯游戏是怎么防止不被封号呢....被封号就会损失客户啊,用新的号怎么让老客户加好友呢

**Comment by hcfw007** [comment]
他们也不能防止被封。好像是通过离职继承？我也不太了解。。
而且一般封号是1天、7天、30天、永封，可能被封1天还能继续用，被封7天就该考虑换新账号了。

**Comment by zhihuifanqiechaodan** [comment]
企业微信会稳定很多，即使被封了也能通过继承获取联系人信息继续维护等等，找个issues就先关了

**Comment by a515642** [comment]
有语音api吗？
