### ISSUE TITLE
我拉个微信群吧，方便沟通使用方法和新想法，看大群里好像没人说话

### ISSUE THREAD

**Issue by nsnsqk** [wechaty/wechaty#2519]
![3MHZ~KPIWDP51~OQPN`YEP2](https://user-images.githubusercontent.com/16953972/233745995-342baccf-d71a-46b6-8dcb-3e2ce657b486.jpg)

**Comment by Xr-TenderLIfe** [comment]
1667522649 能拉我一下嘛

**Comment by SolomonFly** [comment]
麻烦重新拉个二维码，过期了
