### ISSUE TITLE
New puppet for WXKF (微信客服)

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2521]
@huan Hi there.

I just wrote a new puppet for WXKF (微信客服，Wechat Customer Service), based on Tencent official API. You can check it out here. https://github.com/juzibot/wechaty-puppet-wxkf.
In order to handle callbacks, it also comes with a manager-service, WXKF-Manager, you can find it here: https://github.com/juzibot/wxkf-manager.

Please tell me your opinions of these projects, and should I transfer them to Wechaty Org in github. Thanks.

**Comment by huan** [comment]
Hi @hcfw007 ,

Thank you very much for your contribution! I think it is very valuable to implement a puppet for WXKF so that the bot developed by Wechaty can be running on the WXKF API with the same API.

I will check it when I got time and get back to you.

Cheers!

**Comment by hcfw007** [comment]
I also wrote a blog to introduce this puppet in Chinese. https://github.com/wechaty/jekyll/pull/159
