### ISSUE TITLE
[FEAT] New event: ROOM_ANNOUNCE

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2524]
Room Announcement is a feature that most IMs have, and there is no appropriate event for it in Wecahty so far. A possible work around is to generate a text message when Room Announcement changes, however the best pratice I blieve is to make a new event: Room announce.

The event listener will be somethign like:

```ts
export type RoomAnnounceEventListener = (room: RoomInterface, newAnnouncement: string, oldAnnouncement?: string)
  => void | Promise<void>
```

**Comment by hcfw007** [comment]
https://github.com/wechaty/puppet/pull/214

**Comment by huan** [comment]
Can we check on related PRs? @hcfw007 

Thank you very much!
