### ISSUE TITLE
TypeError: UrlLink is not a constructor

### ISSUE THREAD

**Issue by littlezyx** [wechaty/wechaty#2528]
"wechaty": "^1.19.10",
"wechaty-puppet": "^1.19.6",
"wechaty-puppet-padlocal": "^1.11.18"

发送链接消息失败，以上是我使用的wechaty版本，使用js开发，引用如下
const {
	UrlLink
} = require("wechaty");

const urlLink = new UrlLink({
	      description: 'Wechaty is a Bot SDK for Wechat Individual Account which can help you create a bot in 6 lines of javascript, with cross-platform support including Linux, Windows, Darwin(OSX/Mac) and Docker.',
	      thumbnailUrl: 'https://camo.githubusercontent.com/f310a2097d4aa79d6db2962fa42bb3bb2f6d43df/68747470733a2f2f6368617469652e696f2f776563686174792f696d616765732f776563686174792d6c6f676f2d656e2e706e67',
	      title: 'Wechaty',
	      url: 'https://github.com/wechaty/wechaty',
	    });
await toContact.say(urlLink)

报错 TypeError: UrlLink is not a constructor
请问该如何正确发送链接消息？ 还有小程序也是如此

**Comment by hcfw007** [comment]
在wechaty 1.x版本中，应该使用 new bot.UrlLink和 new bot.MiniProgram 来创建对应的实例
