### ISSUE TITLE
Whatsapp Contact.find returns error

### ISSUE THREAD

**Issue by kaihungc1993** [wechaty/wechaty#2532]
## 1. Versions

> What is your wechaty version?
Answer: 1.18.1

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)
Answer: wechaty-puppet-whatsapp

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: 1.19.0

> What is your node version? (run `node --version`)
Answer: 16.13.0

> What os are you using
Answer: Windows

## 2. Describe the bug
I'm trying to find contact by name using this line of code: `match = await bot.Contact.find({ name:'xx'} )`
It used to work, but somehow it hasn't been working lately.

Specifically, I'm getting
```
01:34:26 ERR Config ###########################
01:34:26 ERR Config Wechaty unhandledRejection: ERR_CONTACT_NOT_FOUND: please check contact id: 104084371677224@lid again. [object Promise]
01:34:26 ERR Config ###########################
```
I looked into the code and find the issue in `node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js` line 196.
``` 
/*2. Cache not found*/
log.warn("Kai2", contactId)
const rawPayload = await this.contactRawPayload(contactId);
```
The contactId fails the if statement `!isContactId(id)`. 

I also observe that in the `onReady()` function, I have several `contactOrRoomId` that is neither Contact nor Room. So there are logs showing 
`01:34:29 WARN LoginEventHandler Unknown contact type: {"id":"server":"lid","user":"117334396125372","_serialized":"117334396125372@lid"},"number":"117334396125372","isBusiness":false,"isEnterprise":false,"type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false}
`
There are some contacts with avatar and I checked where are these contacts. They seem to be "Contacts on WhatsApp", which they are listed when you start a new chat ([link](https://mobiletrans.wondershare.com/whatsapp-tips/delete-whatsapp-contact.html?gclid=Cj0KCQjwr82iBhCuARIsAO0EAZyhys5qmrc-JDu_KIc6WI3dWnIBrpI2F04oJJPp5EpoXFW7tGyu1YwaAkUCEALw_wcB)).  They are not  registered through phone number, in which case the "server" will be "c.us". For example, a user with phone number 13148176*** will have payload like this:
`contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"13148176***","_serialized":"13148176***@c.us"},"number":"13148176***","isBusiness":false,"isEnterprise":false,
"name":"Name","shortName":"Name","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false}) result({"friend":true,"gender":0,"id":"13148176***@c.us","name":"
Name","phone":["13148176***"],"type":1,"weixin":"13148176***"})
`
Note that a single user can have both phone number contact and whatsapp contact. 

Last but not least, if I search through id `match = await bot.Contact.find({ id:'16692499432@c.us'} )`, it will not show the ERR_CONTACT_NOT_FOUND error.

I suspect that these whasapp contact with server:lid and contactId ending in @lid will fail the if above if statement `!isContactId(id)`. 
Are these scenario tested? What might be a workaround?

## 3. To Reproduce
async function onLogin (user: Contact) {
  log.info('StarterBot', '%s login', user)
  // match = await bot.Contact.find({ id:'16692499432@c.us'} )  // this works
  match = await bot.Contact.find({ name:'Chloe'} )
  if (match != null){
    log.info("Registered match name = ", match.name())
  }
  else {
    log.warn("Cannot find registered match name: ", match_name)
  }
}

## 4. Expected behavior
`match = await bot.Contact.find({ name:'xx'} )` should return me the desired contact without any error.

## 5. Actual behavior
```
01:34:26 ERR Config ###########################
01:34:26 ERR Config Wechaty unhandledRejection: ERR_CONTACT_NOT_FOUND: please check contact id: 104084371677224@lid again. [object Promise]
01:34:26 ERR Config ###########################
```
And the return Promise fails.

## 6. Full Output Logs

02:15:52 VERB PuppetWhatsapp onStart()
02:15:52 VERB Manager start()
02:15:52 VERB WhatsAppManager initWhatsAppClient()
02:15:52 VERB WhatsAppManager initWhatsAppEvents()
02:15:52 VERB StateSwitch <PuppetServiceMixin> stable(inactive, noCross=false)
02:15:52 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ... done
02:15:52 SILL StateSwitch <PuppetServiceMixin> active() is pending
02:15:52 VERB StateSwitch <PuppetServiceMixin> active(true) <- (pending)
02:15:52 VERB ServiceCtl<PuppetServiceMixin> start() ... done
02:15:52 VERB PuppetWatchdogAgent start() "heartbeat" event listener added
02:15:52 VERB PuppetWatchdogAgent start() "reset" event listener added
02:15:52 VERB WechatyPuppetMixin start() starting puppet ... done
02:15:52 VERB ServiceCtl<Wechaty> start() super.start() ... done
02:15:52 VERB ServiceCtl<Wechaty> start() this.onStart() ...
02:15:52 VERB Wechaty onStart()
02:15:52 VERB Wechaty <wechaty-puppet-whatsapp>(ding-dong-bot) onStart() v1.20.2 is starting...
02:15:52 VERB Wechaty id: 806bcc64-2e1c-40cb-89a3-2d59ac738fd7
02:15:52 VERB Wechaty onStart() ... done
02:15:52 VERB ServiceCtl<Wechaty> start() this.onStart() ... done
02:15:52 SILL StateSwitch <Wechaty> active() is pending
02:15:52 VERB StateSwitch <Wechaty> active(true) <- (pending)
02:15:52 VERB ServiceCtl<Wechaty> start() ... done
02:15:52 INFO StarterBot Starter Bot Started.
02:16:10 INFO LoginEventHandler onAuthenticated()
02:16:10 INFO WhatsAppManager initWhatsAppEvents: "authenticated", value: undefined
02:16:11 VERB LoginEventHandler onWhatsAppReady()
02:16:11 INFO WhatsAppManager initWhatsAppEvents: "ready", value: undefined
02:16:11 VERB WhatsAppManager start() whatsapp.initialize() done.
02:16:11 VERB LoginEventHandler onLogin()
02:16:11 INFO LoginEventHandler WhatsApp Client Info: {"pushname":"{MY NAME}","wid":{"server":"c.us","user":"1{MY NUMBER}","_serialized":"1{MY NUMBER}@c.us"},"me":{"server":"c.us","user":"1{MY NUMBER}","_serialized":"1
{MY NUMBER}@c.us"},"platform":"android"}
02:16:11 VERB Manager initCache(1{MY NUMBER}@c.us)
02:16:11 VERB CacheManager initCache() inited Messages: 1455 cacheDir="C:\Users\{MY NAME}hu\.wechaty\puppet-whatsapp\flash-store-v0.12\1{MY NUMBER}@c.us"
02:16:13 VERB PuppetWhatsapp onLogin(1{MY NUMBER}@c.us)
02:16:13 INFO PuppetWhatsapp LOGIN, 1{MY NUMBER}@c.us
02:16:13 VERB PuppetLoginMixin login(1{MY NUMBER}@c.us)
02:16:13 SILL Contact find({"id":"1{MY NUMBER}@c.us"})
02:16:13 SILL PuppetLoginMixin get currentUserId()
02:16:13 VERB PoolifyMixin get pool() init pool
02:16:13 SILL Contact constructor(1{MY NUMBER}@c.us)
02:16:13 SILL Contact ready() @ Puppet<PuppetWhatsapp>(ding-dong-bot) with id="1{MY NUMBER}@c.us"
02:16:13 SILL PuppetContactMixin contactPayload(1{MY NUMBER}@c.us) cache MISS
02:16:13 WARN {MY NAME}2 1{MY NUMBER}@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(1{MY NUMBER}@c.us)
02:16:13 INFO LoginEventHandler onLogin(1{MY NUMBER}@c.us})
02:16:13 VERB LoginEventHandler onReady()
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"1{MY NUMBER}","_serialized":"1{MY NUMBER}@c.us"},"number":"1{MY NUMBER}","isBusiness":false,"isEnterprise":false,
"type":"in","isMe":true,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false}) result({"friend":false,"gender":0,"id":"1{MY NUMBER}@c.us","name":"{MY NAME}","phone":["1{MY NUMBER}"],"
type":1,"weixin":"1{MY NUMBER}"})
02:16:13 SILL PuppetContactMixin contactPayload(1{MY NUMBER}@c.us) cache SET
02:16:13 SILL PuppetLoginMixin get currentUserId()
02:16:13 INFO StarterBot Contact<{MY NAME}> login
02:16:13 SILL Contact find({"name":"Chloe"})
02:16:13 VERB Contact findAll({"name":"Chloe"})
02:16:13 VERB PuppetContactMixin contactSearch(query={"name":"Chloe"}, )
02:16:13 VERB MIXIN_CONTACT contactList()
02:16:13 WARN PuppetContactMixin contactSearch() searchIdList.length = 61
02:16:13 VERB PuppetContactMixin contactQueryFilterFactory({"name":"Chloe"})
02:16:13 SILL PuppetContactMixin contactPayload(104084371677224@lid) cache MISS
02:16:13 VERB MIXIN_CONTACT contactRawPayload(104084371677224@lid)
02:16:13 SILL PuppetContactMixin contactPayload(104840336298195@lid) cache MISS
02:16:13 WARN {MY NAME}2 104840336298195@lid
02:16:13 VERB MIXIN_CONTACT contactRawPayload(104840336298195@lid)
02:16:13 SILL PuppetContactMixin contactPayload(109710795604061@lid) cache MISS
02:16:13 WARN {MY NAME}2 109710795604061@lid
02:16:13 VERB MIXIN_CONTACT contactRawPayload(109710795604061@lid)
2:16:13 SILL PuppetContactMixin contactPayload(111733674909726@lid) cache MISS
02:16:13 WARN {MY NAME}2 111733674909726@lid
02:16:13 VERB MIXIN_CONTACT contactRawPayload(111733674909726@lid)
02:16:13 SILL PuppetContactMixin contactPayload(117334396125372@lid) cache MISS
02:16:13 WARN {MY NAME}2 117334396125372@lid
02:16:13 VERB MIXIN_CONTACT contactRawPayload(117334396125372@lid)
02:16:13 WARN {MY NAME}1 1{MY NUMBER}@c.us
02:16:13 SILL PuppetContactMixin contactPayload(12017379358@c.us) cache MISS
02:16:13 WARN {MY NAME}2 12017379358@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(12017379358@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(12062580417@c.us) cache MISS
02:16:13 WARN {MY NAME}2 12062580417@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(12062580417@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(12108751841@c.us) cache MISS
02:16:13 WARN {MY NAME}2 12108751841@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(12108751841@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(12164014718@c.us) cache MISS
02:16:13 WARN {MY NAME}2 12164014718@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(12164014718@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(123862863839472@lid) cache MISS
02:16:13 WARN {MY NAME}2 123862863839472@lid
02:16:13 VERB MIXIN_CONTACT contactRawPayload(123862863839472@lid)
02:16:13 SILL PuppetContactMixin contactPayload(12546614279@c.us) cache MISS
02:16:13 WARN {MY NAME}2 12546614279@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(12546614279@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(13125269592@c.us) cache MISS
02:16:13 WARN {MY NAME}2 13125269592@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(13125269592@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(13148176904@c.us) cache MISS
02:16:13 WARN {MY NAME}2 13148176904@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(13148176904@c.us)
02:16:13 SILL PuppetContactMixin contactPayload(14153091417@c.us) cache MISS
02:16:13 WARN {MY NAME}2 14153091417@c.us
02:16:13 VERB MIXIN_CONTACT contactRawPayload(14153091417@c.us)
02:16:13 WARN {MY NAME} ***** 150345397330135@lid
02:16:13 SILL PuppetContactMixin contactPayload(150345397330135@lid) cache MISS
02:16:13 WARN {MY NAME}2 150345397330135@lid
02:16:13 VERB MIXIN_CONTACT contactRawPayload(150345397330135@lid)
02:16:13 WARN {MY NAME}: this error
02:16:13 WARN {MY NAME}: this error
02:16:13 WARN {MY NAME}: this error
02:16:13 WARN {MY NAME}: this error
02:16:13 WARN {MY NAME}: this error
02:16:13 WARN {MY NAME}: this error
02:16:13 WARN {MY NAME}: this error
02:16:13 ERR Config ###########################
02:16:13 ERR Config Wechaty unhandledRejection: ERR_CONTACT_NOT_FOUND: please check contact id: 104084371677224@lid again. [object Promise]
02:16:13 ERR Config ###########################
02:16:13 ERR Config process.on(unhandledRejection) promise.catch(please check contact id: 104084371677224@lid again.)
Config [ERR_CONTACT_NOT_FOUND: please check contact id: 104084371677224@lid again.] {
  code: 4001,
  details: undefined
}
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"12017379358","_serialized":"12017379358@c.us"},"number":"12017379358","isBusiness":false,"isEnterprise":false,
"pushname":"George Cartagena","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}) result({"avatar":" url ","friend":false,"gender":0,"id":"12017379358@c.us","name":"George Cartagena","phone":["12017379358"],"type":1,"weixin":"12
017379358"})
02:16:13 SILL PuppetContactMixin contactPayload(12017379358@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"12062580417","_serialized":"12062580417@c.us"},"number":"12062580417","isBusiness":false,"isEnterprise":false,
"name":"Autodesk Diane","shortName":"Autodesk Diane","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false}) result({"friend":true,"gender":0,"id":"1206
2580417@c.us","name":"Autodesk Diane","phone":["12062580417"],"type":1,"weixin":"12062580417"})
02:16:13 SILL PuppetContactMixin contactPayload(12062580417@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"12108751841","_serialized":"12108751841@c.us"},"number":"12108751841","isBusiness":false,"isEnterprise":false,
"name":"Jeremy","shortName":"Jeremy","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false,"avatar":"url"}) result({"avatar":" url ","friend":true,"gender":0,"id":"12108751841@c.us","name":"Jeremy","phone":["12108751841"],"type":1,"weixin":"121087518
41"})
02:16:13 SILL PuppetContactMixin contactPayload(12108751841@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"12164014718","_serialized":"12164014718@c.us"},"number":"12164014718","isBusiness":false,"isEnterprise":false,
"name":"Jonathan King","shortName":"Jonathan","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false,"avatar":" url "}) result({"avatar":" url ","friend":true,"gender":0,"id":"12164014718@c.us","name":"Jonathan King","phone":["12164014718"],"type":1,"we
ixin":"12164014718"})
02:16:13 SILL PuppetContactMixin contactPayload(12164014718@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"12546614279","_serialized":"12546614279@c.us"},"number":"12546614279","isBusiness":false,"isEnterprise":false,
"name":"Cynthia","shortName":"Cynthia","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false,"avatar":" url "}) result({"avatar":" url ","friend":true,"gender":0,"id":"12546614279@c.us","name":"Cynthia","phone":["12546614279"],"type":1,"weixin":"1254
6614279"})
02:16:13 SILL PuppetContactMixin contactPayload(12546614279@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"13125269592","_serialized":"13125269592@c.us"},"number":"13125269592","isBusiness":false,"isEnterprise":false,
"name":"Melissa Sugar","shortName":"Melissa","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false}) result({"friend":true,"gender":0,"id":"13125269592@
c.us","name":"Melissa Sugar","phone":["13125269592"],"type":1,"weixin":"13125269592"})
02:16:13 SILL PuppetContactMixin contactPayload(13125269592@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"13148176904","_serialized":"13148176904@c.us"},"number":"13148176904","isBusiness":false,"isEnterprise":false,
"name":"Ana","shortName":"Ana","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false}) result({"friend":true,"gender":0,"id":"13148176904@c.us","name":"
Ana","phone":["13148176904"],"type":1,"weixin":"13148176904"})
02:16:13 SILL PuppetContactMixin contactPayload(13148176904@c.us) cache SET
02:16:13 VERB MIXIN_CONTACT contactRawPayloadParser whatsAppPayload({"id":{"server":"c.us","user":"14153091417","_serialized":"14153091417@c.us"},"number":"14153091417","isBusiness":false,"isEnterprise":false,
"name":"咔咔","shortName":"咔咔","type":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":true,"isBlocked":false}) result({"friend":true,"gender":0,"id":"14153091417@c.us","name"
:"咔咔","phone":["14153091417"],"type":1,"weixin":"14153091417"})
02:16:13 SILL PuppetContactMixin contactPayload(14153091417@c.us) cache SET
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"104840336298195","_serialized":"104840336298195@lid"},"number":"104840336298195","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"150345397330135","_serialized":"150345397330135@lid"},"number":"150345397330135","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"180659326865580","_serialized":"180659326865580@lid"},"number":"180659326865580","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"191418136023282","_serialized":"191418136023282@lid"},"number":"191418136023282","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"197375356317832","_serialized":"197375356317832@lid"},"number":"197375356317832","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"202366141915242","_serialized":"202366141915242@lid"},"number":"202366141915242","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"58106864218269","_serialized":"58106864218269@lid"},"number":"58106864218269","isBusiness":false,"isEnterprise":false,"type":
"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"87084824019160","_serialized":"87084824019160@lid"},"number":"87084824019160","isBusiness":false,"isEnterprise":false,"type":
"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:13 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"33526548316328","_serialized":"33526548316328@lid"},"number":"33526548316328","isBusiness":false,"isEnterprise":false,"type":
"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false,"avatar":" url "}
02:16:16 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"117334396125372","_serialized":"117334396125372@lid"},"number":"117334396125372","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false}
02:16:16 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"156221097152755","_serialized":"156221097152755@lid"},"number":"156221097152755","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false}
02:16:16 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"160099385516258","_serialized":"160099385516258@lid"},"number":"160099385516258","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false}
02:16:16 WARN LoginEventHandler Unknown contact type: {"id":{"server":"lid","user":"175509644271664","_serialized":"175509644271664@lid"},"number":"175509644271664","isBusiness":false,"isEnterprise":false,"typ
e":"in","isMe":false,"isUser":true,"isGroup":false,"isWAContact":true,"isMyContact":false,"isBlocked":false}
02:16:16 INFO LoginEventHandler onReady() all contacts and rooms are ready, friendCount: 13 contactCount: 14 roomCount: 0
02:16:16 VERB PuppetWhatsapp onReady()
02:16:16 INFO PuppetWhatsapp READY
02:16:16 SILL WechatyPuppetMixin __setupPuppetEvents() puppet.on(ready)
02:16:16 SILL StateSwitch <WechatyReady> active() is false
02:16:16 VERB StateSwitch <WechatyReady> active(true) <- (false)
02:16:16 SILL ScheduleManager addScheduledTask()

**Comment by kaihungc1993** [comment]
感謝回覆，這樣我看看能否暫時關掉name的報錯

我的理解是這些Contact 並不是從通訊錄中導入的，而是從通訊錄中的號碼找到有在使用whatsapp的用戶，另外獨立存成一個聯絡人。具體如我上面說的，在whatsapp app中，點開new chat，就可以看到有一欄 Contact on Whatsapp App ([link](https://mobiletrans.wondershare.com/whatsapp-tips/delete-whatsapp-contact.html?gclid=Cj0KCQjwr82iBhCuARIsAO0EAZyhys5qmrc-JDu_KIc6WI3dWnIBrpI2F04oJJPp5EpoXFW7tGyu1YwaAkUCEALw_wcB))

{
  "id": {
    "server": "lid",
    "user": "160099385516258",
    "_serialized": "160099385516258@lid"
  },
  "number": "160099385516258",
  "isBusiness": false,
  "isEnterprise": false,
  "type": "in",
  "isMe": false,
  "isUser": true,
  "isGroup": false,
  "isWAContact": true,  // 這應該是說他是whatsapp APP上的聯繫人
  "isMyContact": false, // 不在通讯录中的联系人
  "isBlocked": false
}

**Comment by su-chang** [comment]
> "isWAContact": true, // 這應該是說他是whatsapp APP上的聯繫人

是的，isWAContact 表明当前账号注册过 WhatsApp

**Comment by shihyihong** [comment]
我使用Whatsapp Contact.findall() 也遇到 `ERR_CONTACT_NOT_FOUND: please check contact id:`
有什麼方式work around嗎

**Comment by shihyihong** [comment]
這是 wechaty-puppet-whatsapp 的bug嗎

**Comment by kaihungc1993** [comment]
Thank you. I already closed the ticket.
