### ISSUE TITLE
After a period of inactivity, it will automatically exit

### ISSUE THREAD

**Issue by BlackBerry009** [wechaty/wechaty#2536]
## 0. Report Issue Guide
I found the same issue here , someone says it need real-name authentication. I've tried it but it doesn't work for me
https://github.com/wechaty/wechaty/issues/2320

## 1. Versions

wechaty: 1.20.2
wechaty-puppet-wechat: 1.18.4
node: 18.12.1
os: mac

## 2.Log

> GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (/node_modules/.pnpm/wechaty-puppet@1.20.2/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///Users/xxx/Desktop/ChatGPT-wechat-bot/node_modules/.pnpm/watchdog@0.9.2/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)

**Comment by chimeElm** [comment]
uncaughtException AssertionError [ERR_ASSERTION]: 3 == 0
    at Object.equal (/root/wxMonitor/node_modules/wechat4u/lib/util/global.js:69:24)
    at /root/wxMonitor/node_modules/wechat4u/lib/core.js:444:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 3 == 0\n' +
    '    at Object.equal (/root/wxMonitor/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /root/wxMonitor/node_modules/wechat4u/lib/core.js:444:24\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
12:34:52 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (/root/wxMonitor/node_modules/wechaty-puppet/dist/cjs/src/agents/watchdog-agent.js:48:39)
    at Watchdog.emit (node:events:513:28)
    at Timeout._onTimeout (/root/wxMonitor/node_modules/watchdog/dist/cjs/src/watchdog.js:84:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (/root/wxMonitor/node_modules/wechaty-puppet/dist/cjs/src/agents/watchdog-agent.js:48:39)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Timeout._onTimeout (/root/wxMonitor/node_modules/watchdog/dist/cjs/src/watchdog.js:84:18)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

I meet the same problem

**Comment by nsnsqk** [comment]
> ```
> uncaughtException AssertionError [ERR_ASSERTION]: 3 == 0
>     at Object.equal (/root/wxMonitor/node_modules/wechat4u/lib/util/global.js:69:24)
>     at /root/wxMonitor/node_modules/wechat4u/lib/core.js:444:24
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   code: 2,
>   details: 'AssertionError [ERR_ASSERTION]: 3 == 0\n' +
>     '    at Object.equal (/root/wxMonitor/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
>     '    at /root/wxMonitor/node_modules/wechat4u/lib/core.js:444:24\n' +
>     '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
> }
> 12:34:52 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
> uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
>     at Watchdog.reset (/root/wxMonitor/node_modules/wechaty-puppet/dist/cjs/src/agents/watchdog-agent.js:48:39)
>     at Watchdog.emit (node:events:513:28)
>     at Timeout._onTimeout (/root/wxMonitor/node_modules/watchdog/dist/cjs/src/watchdog.js:84:18)
>     at listOnTimeout (node:internal/timers:559:17)
>     at processTimers (node:internal/timers:502:7) {
>   code: 2,
>   details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
>     '    at Watchdog.reset (/root/wxMonitor/node_modules/wechaty-puppet/dist/cjs/src/agents/watchdog-agent.js:48:39)\n' +
>     '    at Watchdog.emit (node:events:513:28)\n' +
>     '    at Timeout._onTimeout (/root/wxMonitor/node_modules/watchdog/dist/cjs/src/watchdog.js:84:18)\n' +
>     '    at listOnTimeout (node:internal/timers:559:17)\n' +
>     '    at processTimers (node:internal/timers:502:7)'
> }
> ```
> 
> I meet the same problem

你们这是用的哪个提供商？

**Comment by dustookk** [comment]
experiencing the same issue. It crashes every two days.

**Comment by 532777032** [comment]
[解决提示axiosError的问题（其实也是wechaty超时重连的问题）](https://mp.weixin.qq.com/s/vTVYk52xHvld_s3Vm72L8A)
