### ISSUE TITLE
PuppetWeChatBridge start() exception: Error: 

### ISSUE THREAD

**Issue by mehouse** [wechaty/wechaty#2537]
system in aws
服务器是亚马逊云的服务器
通过 cat /proc/version 获得系统版本如下
Linux version 6.1.25-37.47.amzn2023.x86_64 (mockbuild@ip-10-0-36-105) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.39-6.amzn2023.0.5) #1 SMP PREEMPT_DYNAMIC Mon Apr 24 23:20:16 UTC 2023

启动 bot 的时候报错
12:11:29 ERR PuppetWeChatBridge start() exception: Error: Failed to launch the browser process!
/www/wwwroot/campus-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

**Comment by Lyq0055** [comment]
请问解决了吗
