### ISSUE TITLE
再拉一遍微信群吧，之前的码过期了

### ISSUE THREAD

**Issue by nsnsqk** [wechaty/wechaty#2540]
![fa90355470f82dfbf9d8f8ef3585592](https://github.com/wechaty/wechaty/assets/16953972/9ae5703b-24d5-434c-9603-8c3a9b699014)

**Comment by ricochoi712** [comment]
二维码过期了,请问我可以加入吗?

**Comment by MEK-THEB** [comment]
二维码过期了, 请问可以更新一下二维码嘛？感谢！

**Comment by Da1Zh0nggu0** [comment]
可以再更新一下吗。求入群。小白问题比较多。
