### ISSUE TITLE
https://wechaty.js.org/  官方网站无法打开，报503错误，现在还能用吗？

### ISSUE THREAD

**Issue by lban2049** [wechaty/wechaty#2541]
如标题

**Comment by MEK-THEB** [comment]
same issue here

**Comment by Hayao41** [comment]
same issue +1

**Comment by Da1Zh0nggu0** [comment]
same issue+1 

After conducting research for a period of time, we are about to enter development、、、
waiting for answer online     
QAQ

**Comment by Hayao41** [comment]
Oh, it restarts working now guys! Enjoy it again🚀!

**Comment by huan** [comment]
The reason is that the server has been restarted automatically, but the web server has not started automatically.

Thanks for reporting anyway!
