### ISSUE TITLE
room或contact的findAll() 方法，早已退了的群或者早已删除的好友，还是能获取到

### ISSUE THREAD

**Issue by nsnsqk** [wechaty/wechaty#2546]
room或contact的findAll() 方法，早已退了的群或者早已删除的好友，还是能获取到

各位有什么办法清理掉这些脏数据吗？ 是不是wechaty有本地缓存，我是用的padlocal

**Comment by MEK-THEB** [comment]
Yea, same issues here with padlocal.

**Comment by hcfw007** [comment]
contact和room的findAll原本就是返回所有数据库中有的联系人和群，需要根据isFriend和has(bot)来区分是不是好友、是否在群众。

**Comment by nsnsqk** [comment]
> contact和room的findAll原本就是返回所有数据库中有的联系人和群，需要根据isFriend和has(bot)来区分是不是好友、是否在群众。

请问，你这里说的“数据库”是指谁的数据库，微信的吗？

**Comment by hcfw007** [comment]
puppet实现的库
