### ISSUE TITLE
啥时候能支持音乐在线播放,使用UrlLink的时候并不能播放只是一个连接,还是说有这种实现方法我并没有发现(When can support music online playback, when using UrlLink can not play just a connection, or there is such an implementation method I have not found)

### ISSUE THREAD

**Issue by coderPeng3yang** [wechaty/wechaty#2554]
![微信图片_20230630104700](https://github.com/wechaty/wechaty/assets/88971513/0c1179e2-7a5b-4020-b73b-b95d5d01ca05)

**Comment by hcfw007** [comment]
没有这个功能，据我所知也没有计划支持。这个应该bot自身去解析url内容再去播放音乐吧。

**Comment by coderPeng3yang** [comment]
> 没有这个功能，据我所知也没有计划支持。这个应该bot自身去解析url内容再去播放音乐吧。

我尝试了一下拿到了这个信息转发出去是可以转发出去,但似乎仅支持转发出去才行,当我把拦截的text复制下来发送出去并不能成功的发送出一样的音乐,你说的bot自身解析是一个怎么样的方法呢,能说一下嘛,或者有demo吗,我尝试了挺多种,没有想到好办法,困扰了我好久,感谢你

**Comment by MEK-THEB** [comment]
同样希望增加此功能. 楼主所指的message type是music, 而目前WeChaty只支持url类型.

**Comment by hcfw007** [comment]
哦哦，那是我理解错了。是一种特殊的消息类型是吧。那应该还是有可能能支持的。首先需要有一个底层能收到、解析、发送这种消息。

**Comment by coderPeng3yang** [comment]
> 

是否能帮我看看怎么小改一下,我看了源码,但是似乎有一些没看懂,也不知道未来会不会上这个特性

**Comment by coderPeng3yang** [comment]
> 哦哦，那是我理解错了。是一种特殊的消息类型是吧。那应该还是有可能能支持的。首先需要有一个底层能收到、解析、发送这种消息。
对的,我去看了一下源码似乎自己改一下源码,自己技术不够但是看上去好像结构不是很复杂,但是自己技术不是很足,所以可以帮我看看吗

**Comment by coderPeng3yang** [comment]
@hcfw007 > 哦哦，那是我理解错了。是一种特殊的消息类型是吧。那应该还是有可能能支持的。首先需要有一个底层能收到、解析、发送这种消息。

对的,我去看了一下源码似乎自己改一下源码,自己技术不够但是看上去好像结构不是很复杂,但是自己技术不是很足,所以可以帮我看看吗,感谢

**Comment by coderPeng3yang** [comment]
@MEK-THEB > 同样希望增加此功能. 楼主所指的message type是music, 而目前WeChaty只支持url类型.
你用的哪个傀儡

**Comment by hcfw007** [comment]
这个应该不是只修改wechaty的就可以做到的，需要有一个对应的Puppet支持这类消息才行。

**Comment by coderPeng3yang** [comment]
@hcfw007 > 这个应该不是只修改wechaty的就可以做到的，需要有一个对应的Puppet支持这类消息才行。
我用的是padlocal那个但是研究了好一会不知道哪一步出问题了，在他那边提了isuee似乎没人回答，所以只能到这里看看能不能获取帮助
