### ISSUE TITLE
有谁能帮我解决支持微信可以在线播放的音乐,似乎这也是一个链接,可以拦截message转发出去但是就是不能自主发送(Who can help me solve the problem of supporting wechat can play music online, it seems that this is also a link, you can intercept message forward, but it is not automatically sent)

### ISSUE THREAD

**Issue by coderPeng3yang** [wechaty/wechaty#2556]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
![微信图片_20230630104700](https://github.com/wechaty/wechaty/assets/88971513/bea6c124-40b1-4eac-82a5-2bf056db695a)

**Comment by jackwang111222** [comment]
我有，加moxi3620
