### ISSUE TITLE
frienship重复触发

### ISSUE THREAD

**Issue by code-farmer-i** [wechaty/wechaty#2557]
当node服务重启时，之前处理过的好友请求会再次触发frienship事件，这是正常的吗

**Comment by zhihuifanqiechaodan** [comment]
> 当node服务重启时，之前处理过的好友请求会再次触发frienship事件，这是正常的吗

用的什么puppet

**Comment by code-farmer-i** [comment]
> > 当node服务重启时，之前处理过的好友请求会再次触发frienship事件，这是正常的吗
> 
> 用的什么puppet

wechaty-puppet-wechat
我的需求是自动通过好友请求后并推送一条消息，现在还发现在friendship.accept之后contact数据有延时，得setTimeout几秒后才能查询到刚刚通过的好友

**Comment by zhihuifanqiechaodan** [comment]
> 

我认为延迟几秒后发送消息给当前通过的好友是可以接受的，毕竟服务器同步和缓存数据到你从新load加载联系人是需要一定时间的。

**Comment by Qyokizzzz** [comment]
哥们 我加好友报错
const contact = await bot.Friendship.search({ phone: '15088888888' })
await bot.Friendship.add(contact, { hello: 'xxx' })
你知道怎么搞吗

**Comment by zhihuifanqiechaodan** [comment]
> 哥们 我加好友报错 const contact = await bot.Friendship.search({ phone: '15088888888' }) await bot.Friendship.add(contact, { hello: 'xxx' }) 你知道怎么搞吗

等我今天晚上尝试一波看看，到时候给你反馈

**Comment by Qyokizzzz** [comment]
> > 哥们 我加好友报错 const contact = await bot.Friendship.search({ phone: '15088888888' }) await bot.Friendship.add(contact, { hello: 'xxx' }) 你知道怎么搞吗
> 
> 等我今天晚上尝试一波看看，到时候给你反馈

ok，感谢

**Comment by zhihuifanqiechaodan** [comment]
> > > 哥们 我加好友报错 const contact = await bot.Friendship.search({ phone: '15088888888' }) await bot.Friendship.add(contact, { hello: 'xxx' }) 你知道怎么搞吗
> > 
> > 
> > 等我今天晚上尝试一波看看，到时候给你反馈
> 
> ok，感谢

你使用的什么puppet? 使用企业微信token这个功能是没有问题的。 个人微信的话需要明日在看看

**Comment by Qyokizzzz** [comment]
> > > > 哥们 我加好友报错 const contact = await bot.Friendship.search({ phone: '15088888888' }) await bot.Friendship.add(contact, { hello: 'xxx' }) 你知道怎么搞吗
> > > 
> > > 
> > > 等我今天晚上尝试一波看看，到时候给你反馈
> > 
> > 
> > ok，感谢
> 
> 你使用的什么puppet? 使用企业微信token这个功能是没有问题的。 个人微信的话需要明日在看看

默认的puppet

**Comment by zhihuifanqiechaodan** [comment]
> > > > > 哥们 我加好友报错 const contact = await bot.Friendship.search({ phone: '15088888888' }) await bot.Friendship.add(contact, { hello: 'xxx' }) 你知道怎么搞吗
> > > > 
> > > > 
> > > > 等我今天晚上尝试一波看看，到时候给你反馈
> > > 
> > > 
> > > ok，感谢
> > 
> > 
> > 你使用的什么puppet? 使用企业微信token这个功能是没有问题的。 个人微信的话需要明日在看看
> 
> 默认的puppet

默认的话应该免费版本，用的网页的协议，这个puppet的功能有缺陷，很多功能用不了的

**Comment by zhihuifanqiechaodan** [comment]
> > 
> 
> 
> 
> 多谢，问题解决了

是代码问题还是源码问题

**Comment by Qyokizzzz** [comment]
> > > 
> > 
> > 
> > 多谢，问题解决了
> 
> 是代码问题还是源码问题

代码问题，换了paimon
