### ISSUE TITLE
Wechaty official website tutorials are out of date (https://wechaty.js.org/)

### ISSUE THREAD

**Issue by zhangtianrun** [wechaty/wechaty#2567]
I am a total beginner to Wechaty and chatbot application development. I was trying to understand how the bot works by following the tutorials on the official website [https:wechaty.js.org/](url) and noticed that the tutorials are out of date

Things that are out of date:
1. Video tutorial [https:www.youtube.com/watch?v=LHT49Q_x5D8&ab_channel=SouvikBiswas](url)
       - package.json file: versions of the dependencies
       - Importing Wechaty instead of WechatyBuilder from 'wechaty' (some functions are deprecated)
       - returns error `ERR DingDongBot TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined`

2. Installation page: don't have the necessary command `npm install qrcode-terminal`

3. API page
      - some of the APIs are deprecated and replaced 
      - new packages updated since 2022 are not shown on the API list

4. Running "Getting started" ding dong bot locally
        - live demo code embedded on the webpage is no longer functional
        - Importing Wechaty instead of WechatyBuilder from 'wechaty' (some functions are deprecated)
        - generates QR codes that are not functioning/doesn't generate QR codes with WhatsApp puppet

5. Usage with docker page: code not functioning and returns error 

6. At the Getting-started repo, npm install returns errors and the demo bot can't be used: [https://github.com/wechaty/getting-started/issues/294](url) and [https:github.com/wechaty/getting-started/issues/262](url)
my progress: I copied the latest version of the code of ding dong bot from the test folder and updated the dependencies, but an error pops after the bot starts
`21:22:43 ERR WhatsAppManager start() whatsapp.initialize() rejection: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'GK') `

Overall, I think it's time to renew the basic tutorials. We can start from updating the video tutorial of building the demo ding dong bot.

**Comment by lijiarui** [comment]
Good job! Could you update the video tutorial of building the demo ding dong bot first?
