### ISSUE TITLE
UrlLink无法正常发送。提示Wechaty Puppet Unsupported API Error.

### ISSUE THREAD

**Issue by jcdomt** [wechaty/wechaty#2568]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 1. Versions

> What is your wechaty version?

Answer:1.19.10

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:puppeteer

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:puppeteer

> What is your node version? (run `node --version`)

Answer:16.16.0

> What os are you using

Answer:Windows 11 Insider

## 2. Describe the bug

```javascript
var data = result.data
const link = new bot.UrlLink({
	description : data.artist, 
	thumbnailUrl: data.pic, 
	title : data.name,
	url : data.url
});
message.say(link)
```
该段代码处于 axios 的 then 函数里

运行后报错

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. run 'npm start'
2. 使用 axios 获取接口data
3. 构造 UrlLink
4. 使用message.say发送（room.say也尝试过了）

## 4. Expected behavior

> UrlLink可以正产发送

## 5. Actual behavior

>提示say(UrlLinkInterface)是不支持的接口

## 6. Full Output Logs

```
Error: Wechaty Puppet Unsupported API Error. Learn More At https://github.com/wechaty/wechaty-puppet/wiki/Compatibility
    at Object.throwUnsupportedError (C:\code\i\node_modules\wechaty-puppet\src\throw-unsupported-error.ts:4:9)
    at PuppetWeChat.messageSendUrl (C:\code\i\node_modules\wechaty-puppet-wechat\src\puppet-wechat.ts:382:12)
    at C:\code\i\node_modules\wechaty\src\sayable\deliver-sayable.ts:65:26
    at WechatifiedUserClass.say (C:\code\i\node_modules\wechaty\src\user-modules\contact.ts:338:87)
    at WechatyImpl.say (C:\code\i\node_modules\wechaty\src\wechaty\wechaty-base.ts:275:28)
    at C:\code\i\main.ts:83:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
	```

**Comment by zaneon** [comment]
这不是写的很清楚了，puppet不支持

**Comment by zhihuifanqiechaodan** [comment]
选用puppet的时候请查看对应支持的功能，免费版的更可能功能受限
