### ISSUE TITLE
请问wechaty可以发送音乐卡片嘛，好像没看到文档有写，能实现嘛？

### ISSUE THREAD

**Issue by Yang474985795** [wechaty/wechaty#2569]
下图这样，有人知道嘛

![WechatIMG1486](https://github.com/wechaty/wechaty/assets/35017057/a82f0e43-9878-4526-88bd-3ac31c29414a)

**Comment by zhihuifanqiechaodan** [comment]
> 下图这样，有人知道嘛
> 
> 
> 
> ![WechatIMG1486](https://github.com/wechaty/wechaty/assets/35017057/a82f0e43-9878-4526-88bd-3ac31c29414a)
> 
> 

不支持的

**Comment by jackwang111222** [comment]
可以的，需要改一点源码，需要的话加我 moxi3620

![WechatIMG2347](https://github.com/wechaty/wechaty/assets/139688710/ef7f8b92-3bec-4f6d-873c-1a639448adfd)

**Comment by coderPeng3yang** [comment]
帮大家问了楼上的需要300块,我只需280加我codermie

**Comment by nsnsqk** [comment]
> 帮大家问了楼上的需要300块,我只需280加我codermie

666，哈哈，内卷是吧

**Comment by MEK-THEB** [comment]
same issue here and wanted to send music message.
