### ISSUE TITLE
14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by littlezyx** [wechaty/wechaty#2571]
"wechaty": "^1.20.2",
"wechaty-puppet": "^1.19.6",
"wechaty-puppet-padlocal": "^1.11.18"
版本如上，本地调试没问题，部署到腾讯云的windows服务器刚开始运行没问题，过一段时间就报错
14 UNAVAILABLE: No connection established
![image](https://github.com/wechaty/wechaty/assets/19370936/8757c03e-56b9-4d32-a3bb-09938a3d521d)

**Comment by zhihuifanqiechaodan** [comment]
> "wechaty": "^1.20.2",
> 
> "wechaty-puppet": "^1.19.6",
> 
> "wechaty-puppet-padlocal": "^1.11.18"
> 
> 版本如上，本地调试没问题，部署到腾讯云的windows服务器刚开始运行没问题，过一段时间就报错
> 
> 14 UNAVAILABLE: No connection established
> 
> ![image](https://github.com/wechaty/wechaty/assets/19370936/8757c03e-56b9-4d32-a3bb-09938a3d521d)
> 
> 
> 
> 

目前还有这个问题嘛
