### ISSUE TITLE
`msg.age()` doesn't give real age of the messages.

### ISSUE THREAD

**Issue by shiyishiaa** [wechaty/wechaty#2575]
Every 10 seconds, I send a message from my WeChat to the bot. I expect the `age` of `message` to be 0 every time the console prints. The `timestamp` in `payload` seems to be the value display above the series messages (like 22:42 in the below image) rather than the real timestamp when the message is sent.

[Related Codesnap]
```Javascript
        console.log(`${msg.age()} seconds ago: `, content)
```
[Console Output]
```
-1 seconds ago 1
17 seconds ago 2
31 seconds ago 3
```
[Real Messages]
![image](https://github.com/wechaty/wechaty/assets/39306140/a632e833-2ab8-4fd6-b047-be0408237c84)

**Comment by zhihuifanqiechaodan** [comment]
what do you want to do, if you want get the send message time, you can try this
`
const messageTimestamp = new Date().getTime() - message.age() * 1000
`

**Comment by shiyishiaa** [comment]
> what do you want to do, if you want get the send message time, you can try this `const messageTimestamp = new Date().getTime() - message.age() * 1000`

Nope. This does not return the actual exact time that the message is sent. As I mentioned in the post, it returns the time the first message was sent in the series.

 Let me explain in text.
Given that I send 3 messages to Mike: 
__________________________Hi------------------message A, sent at 10:00:00;
__________________________Mike---------------message B, sent at 10:00:12;
__________________________How are you?-----message C, sent at 10:00:25.

Automatically WeChat will merge these three messages together:
___________10:00___________
___________________________Hi
___________________________Mike
___________________________How are you?

When I want to acquire the exact live time of message C, I will use `msg.age()` method.
When I want to acquire the exact sent time of message C, I will use `new Date(msg.payload.timestamp)` method.

The problem is that all the `timestamp`s I acquired via the above two methods are 10:00:00 rather than 10:00:25.

**Comment by zhihuifanqiechaodan** [comment]
ok this is problem! but i think this problem depends on the puppet you use, when i use padlocal and service puppet, not has this , you can try change puppet you use

**Comment by zhihuifanqiechaodan** [comment]
<img width="1110" alt="image" src="https://github.com/wechaty/wechaty/assets/39149607/c6133ba3-8a06-4e76-8fb5-95ef6e722106">
padloacl puppet

**Comment by shiyishiaa** [comment]
> ok this is problem! but i think this problem depends on the puppet you use, when i use padlocal and service puppet, not has this , you can try change puppet you use

Thanks for your kind suggestion! :)
