### ISSUE TITLE
The usage of LRU cache and Pool cache

### ISSUE THREAD

**Issue by hcfw007** [wechaty/wechaty#2577]
Recently we paid lots of effort on reducing the meory usage of wechaty bots, and I have some questions of the usage of LRU cache.

When we load a poolified instance (e.g. room or contact), we will save the payload in the LRU cache and also create a wechatified isntance in the pool. However I failed to find any case when we clear the instance in the pool while keeping the payload in the LRU cache. That is to say, we don't actually need the LRU cache.

Please tell me if I missed anything, or we should clear the instances in the pool manually.

**Comment by hcfw007** [comment]
Scenario:
- Load new contact
  The payload will be fetched from the puppet, saved in LRU, and we create a new instance with that payload. When we call methods or get properties from the contact, it will use the instance in the pool directly.
- Renew contact payload
  The puppet will recive a dirty event. The contact LRU cached is cleared and and re-fetched, however the contact instance will also have the payload refreshed from the call, there is no point to use the cache to transfet the payload.

If we delete the instance from the pool, the LRU cache will be useful. When we load the contact, it will get the payload from the LRU cache. However wechaty seems never trims the pool.

**Comment by hcfw007** [comment]
The flashstore cache in wechaty-puppet-service is useful because it will store the cache in the hard drive. When we restart the system, we don't need to fetch cached payloads from remote server. However as far as I know quick-LRU is a memory cache.

**Comment by nsnsqk** [comment]
社区太不活跃了，我都快要坚持不住了。

**Comment by huan** [comment]
> When we load a poolified instance (e.g. room or contact), we will save the payload in the LRU cache and also create a wechatified isntance in the pool. However I failed to find any case when we clear the instance in the pool while keeping the payload in the LRU cache. That is to say, we don't actually need the LRU cache.

@hcfw007 When the Puppet instance and the Wechaty instance are running in the same process, your statements are true.

However, the design of the puppet system is to support the distributed system; that's why it will always keep the LRU to prevent performance issues.

For your requirement, I remember I have put some environment variables to control the LRU cache size in the Puppet system; you can set them to fit your need (0, or some small number) as you need in your system.

I hope this explanation helps. Feel free to let me know if you have more questions.

**Comment by hcfw007** [comment]
> However, the design of the puppet system is to support the distributed system; that's why it will always keep the LRU to prevent performance issues.

By distributted system, you mean with puppet-service, or running in one machine on two different processes? Is there an example for this kind of pratice?

**Comment by hcfw007** [comment]
> 社区太不活跃了，我都快要坚持不住了。

活跃的开发者确实不是特别多，但如果仅限typescript和企业微信的puppet，大部分问题我们还是能解决的。
