### ISSUE TITLE
获取服务器列表的时候返回都是空，导致服务无法访问

### ISSUE THREAD

**Issue by boboli611** [wechaty/wechaty#2582]
<img width="792" alt="image" src="https://github.com/wechaty/wechaty/assets/8155912/24ff1df6-1c5e-4b85-9bb1-3edd0a43836c">

**Comment by boboli611** [comment]
3天内出现两次了，麻烦看看这个问题吧，每次都持续很久导致业务瘫痪

**Comment by logiccao** [comment]
mark
