### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by UI-ceiling** [wechaty/wechaty#2590]
提供的在线环境情况 与我本地环境相同  
所以我觉得是不是有什么必要的环境没有写在文档中

![image](https://github.com/wechaty/wechaty/assets/87213312/ef14b0ec-5d13-4af3-b8d2-86ef05cc1fff)

![image](https://github.com/wechaty/wechaty/assets/87213312/20ba8ff1-35fb-4ec4-b35c-697b4a95d0d1)

![image](https://github.com/wechaty/wechaty/assets/87213312/bf37bc21-2740-41dc-b7e5-f183a31779af)

**Comment by UI-ceiling** [comment]
我尝试了之前的代码版本   问题依然存在

**Comment by TommySherlock** [comment]
devDependencies的依赖里加这两项试试
    "@swc/core": "1.3.83",
    "ts-node": "10.8.1"

**Comment by UI-ceiling** [comment]
> devDependencies的依赖里加这两项试试 "@swc/core": "1.3.83", "ts-node": "10.8.1"

问题依然存在，解决方法是手动替换node_models下的@swc依赖

**Comment by CauseMyLove** [comment]
> > devDependencies的依赖里加这两项试试 "@swc/core": "1.3.83", "ts-node": "10.8.1"
> 
> 问题依然存在，解决方法是手动替换node_models下的@swc依赖
换成什么呢？

**Comment by CauseMyLove** [comment]
我是把ts-node降到10.8.1就可以了

**Comment by UI-ceiling** [comment]
> > > devDependencies的依赖里加这两项试试 "@swc/core": "1.3.83", "ts-node": "10.8.1"
> > 
> > 
> > 问题依然存在，解决方法是手动替换node_models下的@swc依赖
> > 换成什么呢？

@chatie下的@swc文件夹
