### ISSUE TITLE
是否有支持心跳检测的单独api？用以及时感知机器人是否正常 或者网络是否正常

### ISSUE THREAD

**Issue by luoyuwowo** [wechaty/wechaty#2591]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by luoyuwowo** [comment]
如果机器人掉线后 重新上线能否获取到历史数据？

**Comment by gnipbao** [comment]
gRPC Helth check https://github.com/wechaty/puppet-service#grpc-health-checking-protocol
