### ISSUE TITLE
需要二狗机器人代码的找我vx：codermie

### ISSUE THREAD

**Issue by coderPeng3yang** [wechaty/wechaty#2625]
需要二狗机器人代码的找我vx：codermie

**Comment by stefan-ysh** [comment]
Please don't post ads here. This is a place where we only can talk about Wechaty. I will report it to the repository admins.

**Comment by huan** [comment]
@stefan-ysh, thank you very much for helping our community activities be healthy.

@coderPeng3yang Please join our Discord community if you want to provide any developing services to the community.

The GitHub issue is for bug reports, feature requests, etc.

Thanks for understanding, this issue will be closed.
