### ISSUE TITLE
Wechaty is imported as a type in typescript.

### ISSUE THREAD

**Issue by liuhq** [wechaty/wechaty#2648]
## 1. Versions

> What is your wechaty version?

Answer: 1.20.2

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: _

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: _

> What is your node version? (run `node --version`)

Answer: 20.11.1

> What os are you using

Answer: Windows

## 2. Describe the bug

![image](https://github.com/wechaty/wechaty/assets/48037182/490cd6b5-9a95-477d-a31f-95c3846c4ba6)

![image](https://github.com/wechaty/wechaty/assets/48037182/41588f87-fa84-4bcb-9ccf-b1c8cdb43502)

![image](https://github.com/wechaty/wechaty/assets/48037182/beeec593-0086-47af-a680-24147bcdfbce)

as above, after `import { Wechaty } from 'wechaty'`, the `Wechaty` is imported as a type and I can't instantiate it. But the package source code shows that it is indeed exported as a type. or did I use it uncorrectly?

**Comment by Zeng95** [comment]
The [building the bot](https://wechaty.js.org/docs/getting-started/running-locally#building-the-bot) section of the [beginner-friendly tutorial](https://wechaty.js.org/docs/getting-started/running-locally) needs updates.

The recommended way to instantiate Wechaty is by using [`WechatyBuilder.build()`](https://github.com/wechaty/getting-started/blob/afa6aa144c5758102089a677b1b72e2ed699adcb/examples/ding-dong-bot.ts#L51).


```js
import { WechatyBuilder } from 'wechaty'

// Initializing bot
const bot = WechatyBuilder.build();

// Handle events of bot
bot.on('scan', onScan);
bot.on('login', onLogin);
bot.on('logout', onLogout);
bot.on('message', onMessage);

// Start bot
bot.start();
```

**Comment by huan** [comment]
I’d love to accept a PR for fixing that.

**Comment by liuhq** [comment]
> The [building the bot](https://wechaty.js.org/docs/getting-started/running-locally#building-the-bot) section of the [beginner-friendly tutorial](https://wechaty.js.org/docs/getting-started/running-locally) needs updates.
> 
> The recommended way to instantiate Wechaty is by using [WechatyBuilder.build()](https://github.com/wechaty/getting-started/blob/afa6aa144c5758102089a677b1b72e2ed699adcb/examples/ding-dong-bot.ts#L51).
> 
> ```js
> import { WechatyBuilder } from 'wechaty'
> 
> // Initializing bot
> const bot = WechatyBuilder.build();
> 
> // Handle events of bot
> bot.on('scan', onScan);
> bot.on('login', onLogin);
> bot.on('logout', onLogout);
> bot.on('message', onMessage);
> 
> // Start bot
> bot.start();
> ```

Tkx! It works fine.

**Comment by huan** [comment]
BTW: this kind of problems could be very easy to be solved by talking with our Friday BOT @ GPTs - https://chat.openai.com/g/g-s4mx1ODQy-friday-bot

Please check it out if you have a ChatGPT Plus subscription.

Or, welcome to join our Discord community https://discord.gg/7q8NBZbQzt and you can talk with Friday BOT over there as well.
