### ISSUE TITLE
wechaty是不更新了吗

### ISSUE THREAD

**Issue by lovecodeyou** [wechaty/wechaty#2652]
我怎么看 npm上的包版本已经两年多没更新过【https://www.npmjs.com/package/wechaty】

**Comment by huan** [comment]
Welcome to Wechaty! We're glad you're here. Here's how to help us keep things organized:

- **Found a bug?** First, see if anyone else has reported it. If not, go ahead and tell us about it. Please include what happened, how to make it happen again, and any pictures if you have them.
- **Have a new idea?** Great! Check if someone else has already thought of it. If not, let us know what you're thinking and why it's a good idea.
- **Got questions?** For questions, please don't use GitHub. Instead, try talking to our Friday BOT for answers:
  1. If you have ChatGPT Plus, use this link: https://chat.openai.com/g/g-s4mx1ODQy-friday-bot
  2. Or join our Discord community and ask Friday BOT there: https://discord.gg/7q8NBZbQzt

Thanks for helping Wechaty! We're excited to see what you do.
