### ISSUE TITLE
bot.room.findAll()只能获取10个微信群，并且每次都是随机的10个群，无法获取所有的

### ISSUE THREAD

**Issue by CYscared** [wechaty/wechaty#2670]
bot.room.find(roomName)查不到微信群，后来发现bot.room.findAll()只能获取10个微信群的列表数据，而且每次返回的还都不一样。就算多次调用把需要的群id复制出来，使用bot.room.load(id)，返回的内容虽然不是undefined，而是有对象数据。但是也无法获取memberAll()数据。有什么办法可以让findAll()查到所有吗。

"wechaty-puppet-wechat": "^1.18.4",
"wechaty-puppet-wechat4u": "^1.14.14"
使用这2个方式，bot.room.findAll()测试都只能得到length=10的数据，每次得到的微信群也都是随机的。所以bot.room.find('哈哈群')才会大部分都是undefined，偶尔出现查询到这个群

**Comment by huan** [comment]
@CYscared See https://discord.com/channels/916984413944967180/917009119595081729/1228967624768225322

You need to try the `ready` event.
