### ISSUE TITLE
 wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。

### ISSUE THREAD

**Issue by chickenWing-ape** [wechaty/wechaty#2694]
request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:7c51947b] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。

这种怎么处理呢。现在点击完确认登陆之后就会报错，然后再次循环。

**Comment by missile-xuan** [comment]
相同的问题 
"wechaty": "^1.20.2",
"wechaty-puppet-padlocal": "^1.20.1"

**Comment by tanwei0857** [comment]
@huan 您好，这个怎么处理是怎么样个情况呢？

**Comment by Lyq0055** [comment]
解决了吗

**Comment by huan** [comment]
Merget to https://github.com/wechaty/puppet-padlocal/issues/302

**Comment by Sakchai686868** [comment]
解决了吗？我这里一直都是报错的
