### ISSUE TITLE
重新扫码padlocal两三天了还没有人修复嘛，wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面,登录不了咯，

### ISSUE THREAD

**Issue by coderPeng3yang** [wechaty/wechaty#2696]
重新扫码padlocal两三天了还没有人修复嘛，wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面,登录不了咯，

**Comment by Lyq0055** [comment]
解决了吗

**Comment by coderPeng3yang** [comment]
> 解决了吗

没解决 @huan

**Comment by huan** [comment]
Merge to https://github.com/wechaty/puppet-padlocal/issues/302
