### ISSUE TITLE
重新扫码padlocal两三天了还没有人修复嘛，wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面,登录不了咯，

### ISSUE THREAD

**Issue by coderPeng3yang** [wechaty/wechaty#2699]
重新扫码padlocal六天了还没有人修复嘛，wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面,登录不了咯， @huan

**Comment by hedibin** [comment]
解决了，我也遇到这种情况了，更新依赖没用啊

**Comment by hedibin** [comment]
你解决了嘛？我也遇到这种情况，更新了依赖也没用啊

**Comment by chenzhiqiang0518** [comment]
需要对接个微，可以找我，已解决问题

**Comment by sy5415** [comment]
> 需要对接个微，可以找我，已解决问题

sonyi007     有偿

**Comment by allforone** [comment]
> 需要对接个微，可以找我，已解决问题

v ：  huadongchaofei

**Comment by huan** [comment]
Merge to https://github.com/wechaty/puppet-padlocal/issues/302

**Comment by qushixiaoming** [comment]
> 需要对接个微，可以找我，已解决问题

v:wzy1349065374

**Comment by MonarchMan** [comment]
> 需要对接个微，可以找我，已解决问题

v: Mythology-1

**Comment by szwhl** [comment]
> 需要对接个微，可以找我，已解决问题

怎么解决的啊

**Comment by 233312-ship-it** [comment]
解决不了呢

**Comment by 233312-ship-it** [comment]
> 需要对接个微，可以找我，已解决问题

v: xiu1548279875
