### ISSUE TITLE
为什么使用bot.Contact.findAll()方法查找到的联系人名称都是空呢

### ISSUE THREAD

**Issue by littlemonOvO** [wechaty/wechaty#2701]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
文件传输助手() 头像: FileBox#Buffer<wechaty-contact-avatar-文件传输助手.jpg> 是否为公众号: false
微信团队() 头像: FileBox#Buffer<wechaty-contact-avatar-微信团队.jpg> 是否为公众号: true
只有这样的联系人可以找出正确信息

**Comment by littlemonOvO** [comment]
查找方法：
const findAllConcact = async () => {
    const contactList = await bot.Contact.findAll()
    console.log(`总共有 ${contactList.length} 个联系人`)

    for (const contact of contactList) {
      const name = contact.name() // 联系人昵称
      const alias = await contact.alias() // 联系人备注名
      const avatar = await contact.avatar() // 联系人头像 URL
      const isOfficial = contact.type() === bot.Contact.Type.Official // 是否为公众号联系人
      console.log(`${name}(${alias}) 头像: ${avatar} 是否为公众号: ${isOfficial}`)
    }
}

**Comment by coderPeng3yang** [comment]
> 查找方法： const findAllConcact = async () => { const contactList = await bot.Contact.findAll() console.log(`总共有 ${contactList.length} 个联系人`)
> 
> ```
> for (const contact of contactList) {
>   const name = contact.name() // 联系人昵称
>   const alias = await contact.alias() // 联系人备注名
>   const avatar = await contact.avatar() // 联系人头像 URL
>   const isOfficial = contact.type() === bot.Contact.Type.Official // 是否为公众号联系人
>   console.log(`${name}(${alias}) 头像: ${avatar} 是否为公众号: ${isOfficial}`)
> }
> ```
> 
> }

你用的是什么协议ipad还是pc还是web

**Comment by littlemonOvO** [comment]
import { WechatyBuilder, ScanStatus } from 'wechaty';
import qrTerm from 'qrcode-terminal';
import schedule from 'node-schedule';

const bot = WechatyBuilder.build();


默认协议，没有改过

**Comment by littlemonOvO** [comment]
> > 查找方法： const findAllConcact = async () => { const contactList = await bot.Contact.findAll() console.log(`总共有 ${contactList.length} 个联系人`)
> > ```
> > for (const contact of contactList) {
> >   const name = contact.name() // 联系人昵称
> >   const alias = await contact.alias() // 联系人备注名
> >   const avatar = await contact.avatar() // 联系人头像 URL
> >   const isOfficial = contact.type() === bot.Contact.Type.Official // 是否为公众号联系人
> >   console.log(`${name}(${alias}) 头像: ${avatar} 是否为公众号: ${isOfficial}`)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> 你用的是什么协议ipad还是pc还是web

```
import { WechatyBuilder, ScanStatus } from 'wechaty';
import qrTerm from 'qrcode-terminal';
import schedule from 'node-schedule';

const bot = WechatyBuilder.build();

bot
    .on('logout', onLogout)
    .on('login', onLogin)
    .on('scan', onScan)
    .on('error', onError)
    .start()
    .catch(async (e) => {
        console.error('Bot start() fail:', e);
        await bot.stop();
        process.exit(-1);
    });
```
没有改过协议，应该是ipad

**Comment by littlemonOvO** [comment]
只能找到最近联系过的联系人

**Comment by coderPeng3yang** [comment]
> > > 查找方法： const findAllConcact = async () => { const contactList = await bot.Contact.findAll() console.log(`总共有 ${contactList.length} 个联系人`)
> > > ```
> > > for (const contact of contactList) {
> > >   const name = contact.name() // 联系人昵称
> > >   const alias = await contact.alias() // 联系人备注名
> > >   const avatar = await contact.avatar() // 联系人头像 URL
> > >   const isOfficial = contact.type() === bot.Contact.Type.Official // 是否为公众号联系人
> > >   console.log(`${name}(${alias}) 头像: ${avatar} 是否为公众号: ${isOfficial}`)
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > 
> > 
> > 你用的是什么协议ipad还是pc还是web
> 
> ```
> import { WechatyBuilder, ScanStatus } from 'wechaty';
> import qrTerm from 'qrcode-terminal';
> import schedule from 'node-schedule';
> 
> const bot = WechatyBuilder.build();
> 
> bot
>     .on('logout', onLogout)
>     .on('login', onLogin)
>     .on('scan', onScan)
>     .on('error', onError)
>     .start()
>     .catch(async (e) => {
>         console.error('Bot start() fail:', e);
>         await bot.stop();
>         process.exit(-1);
>     });
> ```
> 
> 没有改过协议，应该是ipad

你扫码是手机登录得ipad是吧，目前看ipad协议已经用不了了，你怎么用的
