### ISSUE TITLE
【wechaty问题交流微信群】一起讨论，吐槽，解决wechaty中遇到的坑

### ISSUE THREAD

**Issue by suxiaobei1024** [wechaty/wechaty#2707]
加我vx:   pixes6688
一起交流问题， 
备注: wechaty-xxx

**Comment by huan** [comment]
@suxiaobei1024 Thanks for creating a community for Wechaty developers.

However, it should not be posted in Issues because this topic is unrelated to Issue.

Feel free to discuss at our Wechaty Discord Server at https://discord.gg/7q8NBZbQzt
