### ISSUE TITLE
how i can use multiple robot in a same project and non-interference each other?

### ISSUE THREAD

**Issue by songyu719** [wechaty/wechaty#271]
how i can use multiple robot  in a same project  and non-interference each other? 

i tried  like this 

 var wechat= new Wechaty() ;

but it's not working !  the last one will be active !  

can you give me some help?

**Comment by zixia** [comment]
Currently, Wechaty can only have one instance, so you have to use the singleton method to initiate Wechaty:

```ts
const bot = Wechaty.instance()
```

The reason we only can have one instance is a little bit complicated. Hope we can get rid of this limitation in the future release.

If you need multiple Wechaty ChatBot, I suggest you to run multiple Node.js instance to do that.

**Comment by songyu719** [comment]
Before you answer me  i tryied this solution  but there is new trouble  when i killed the child process the chrome window still there  how to close it ? by the way i read all the issues about "how to send image"  i still don't know  how to do it , can you show me the code ? thanks  The great author

**Comment by zixia** [comment]
1. When you send kill signal to Wechaty, Wechaty is possible to not close chromedriver as normal. If you could provide a piece of runnable code to reproduce this problem, I can have a look into it.
1. send image is planning to be supported in the next [Milestone v0.9](https://github.com/wechaty/wechaty/milestone/8)

**Comment by songyu719** [comment]
`const {Wechaty,Contact} = require('wechaty')

var loginuser="";
var wechat= new Wechaty() ;


wechat.on('scan', (url, code) => {

  console.log(url)
});


wechat.on('login',user => {

    console.log(`User ${user} logined`);

    loginuser=user;

});

wechat.on('message',  message => {


    var room =message.room();


    if(room){

        if(message=="10086"){
            console.log(message);

            room.say("自动回复:这是中国移动的电话号码")
        }

        if(message=="exit"){

            process.exit();
        }

    }

    console.log(`消息内容: ${message}`+
        "       发送者："+message.from()
    );


});
wechat.init();


`
  process.exit() is working chrome window still there

**Comment by lijiarui** [comment]
@songyu719 I guess you don't mind chrome window still there or not, what you care about is when you run multiple Node.js instances, all the instances start the same wechat account.

If I guess， then I suggest you could try the following code:
```
var wechat= new Wechaty({profile:'test1'})
```

You can set one instance's `profile` is `test1` and another is `test2`, then when you run 2 instances, you can use multiple robots and they won't interfere with each other.

**Comment by zixia** [comment]
@songyu719 I think you can add a `wechaty.quit()` before `process.exit()`, this  could help you to close the chromedriver and chrome browser.

```ts
    if(message=="exit"){

        wechaty.quit().then(() => process.exit())
    }
```

**Comment by songyu719** [comment]
@zixia 

Error: current not match target
    at StateMonitor.current (/Users/Terry/wechat/node_modules/wechaty/dist/src/state-monitor.js:52:27)
    at Wechaty.<anonymous> (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:193:24)
    at Generator.next (<anonymous>)
    at /Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:7:71
    at __awaiter (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at Wechaty.quit (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:191:16)
    at Wechaty.wechat.on.message (/Users/Terry/wechat/myrobot.js:42:20)
    at emitOne (events.js:96:13)
    at Wechaty.emit (events.js:188:7)
    at PuppetWeb.puppet.on (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:172:31)

still not working

**Comment by songyu719** [comment]
@lijiarui 

think you   i will try it   can you give me your other  contact information like QQ or wechat   i can tell you more details of my project 。 i  hope you can help me  please !

**Comment by zixia** [comment]
@songyu719 There might be a bug or misusing in the program. Please provide your full code and full log output for analyse, Thanks.

**Comment by songyu719** [comment]
```
const {Wechaty,Contact} = require('wechaty')

var loginuser="";
var wechat=  Wechaty.instance() ;


wechat.on('scan', (url, code) => {

  console.log(url)
});


wechat.on('login',user => {

    console.log(`User ${user} logined`);

    loginuser=user;

});

wechat.on('message',  message => {


    var room =message.room();


    if(room){

        if(message=="10086"){
            console.log(message);

            room.say("自动回复:这是中国移动的电话号码")
        }


        if(message=="大100"){

            room.say(message.from()+"您已成功下注100块")
        }

        if(message=="exit"){
            wechat.quit().then(() => process.exit()).catch((e)=>{

                console.log(e)
            })

        }

    }

    console.log(`消息内容: ${message}`+
        "       发送者："+message.from()
    );






});
wechat.init();




```




this instance running by 


```
 var workerProcess = child_process.fork('myrobot.js', [1]);


    workerProcess.on("message",(m)=>{

        console.log("this message from child process:"+m)

    })


    workerProcess.send("i'm your father")

    workerProcess.on('close', function (code) {
        console.log('子进程已退出，退出码 '+code);
    });


```




Console log 


INFO Wechaty v0.7.17 initializing...
https://login.weixin.qq.com/qrcode/YdAJkJ-_OA==
https://login.weixin.qq.com/qrcode/YdAJkJ-_OA==
User 宋潇宇 logined
WARN StateMonitor Wechaty:current(standby,false) current is different with target. call state.target(standby) first.
消息内容: exit       发送者：宋潇宇
Error: current not match target
    at StateMonitor.current (/Users/Terry/wechat/node_modules/wechaty/dist/src/state-monitor.js:52:27)
    at Wechaty.<anonymous> (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:193:24)
    at Generator.next (<anonymous>)
    at /Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:7:71
    at __awaiter (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:3:12)
    at Wechaty.quit (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:191:16)
    at Wechaty.wechat.on.message (/Users/Terry/wechat/myrobot.js:42:20)
    at emitOne (events.js:96:13)
    at Wechaty.emit (events.js:188:7)
    at PuppetWeb.puppet.on (/Users/Terry/wechat/node_modules/wechaty/dist/src/wechaty.js:172:31)

**Comment by zixia** [comment]
Thanks for the details of the code & log.

Could you please try the latest master code of v0.7.34 ? I believe this version should fix this issue.

**Comment by songyu719** [comment]
@zixia  cool it work !  when we can use the "send image" feature ?

**Comment by zixia** [comment]
Great to hear that!

As I mentioned earlier: "send image" is planning to be supported in the next [Milestone v0.9](https://github.com/wechaty/wechaty/milestone/8).

Please let me know if you have any future questions/sugestions, Cheer!

**Comment by songyu719** [comment]
ok !  to be honest  you are very great !  now you can close this issues

**Comment by zixia** [comment]
Thanks! 

To be honest too, I'd like to hear you praise Wechaty instead of me! ;-)

**Comment by lijiarui** [comment]
@songyu719 Glad to help you.

My wechat is:  ruirui_0914

You also can join our wechat room `Wecchaty Developer's Home` by scan the qrcode in readme and sent 'wechaty' to the bot. You can talk with a lot of developers there.
