### ISSUE TITLE
Anyone as a solution to solve problem about cannot get room uniqueId?

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#274]
I'm using wechaty to manage my room, anyone can send keyword then the bot can invite the contact in the room.

But we cannot get the unique roomId for all of my rooms, so some contact invites the bot into a room and changes the room name as the bot managed on purpose.

For example:

The bot is managing a room called `robot room`, anyone sends `robot` to the bot, the bot can invite the contact to the room, then one of the contacts invite the bot to his room called `robot room`  too. Then,  the bot always invites a contact to his room by mistake.

It confused me.

Because the bot cannot leave the room automatically, and we cannot get a unique roomId to identify the room,  the bot has thousands of friend and I cannot detect this by myself.

Now, I'm trying to detect a bot-room-join event, then change the `room-topic` by bot automatically, but it cannot resolve the issue fundamentally.

Related discuss can find in #90 and #201 

Anyone have some good ideas?

**Comment by zixia** [comment]
According to FAQ Q2: 
https://github.com/wechaty/wechaty/wiki/FAQ#2-how-to-get-the-permanent-id-for-a-room

I think that's the only way to do it when we are using PuppetWeb. 

After we supported PuppetAndroid/PuppetIos, there might be other ways.
