### ISSUE TITLE
how i can save avatar without await keywords?

### ISSUE THREAD

**Issue by songyu719** [wechaty/wechaty#278]
```
    wechat.on('login',user => {

            const avatarFileName = `public/headimg/${user.name()}.jpg`
           user.avatar().then((data)=>{

               const avatarWriteStream = fs.createWriteStream(avatarFileName)
               data.pipe(avatarWriteStream)


           })

```
when i try to save avatar like this   but the image is empty !  i'm a new player of node.js   i don't  know  how to use await keywords  . can you tell me how to save avatar without await keywords?

sorry for ask the stupid question!

**Comment by zixia** [comment]
Could you save avatar file with the await keyword successfully?

I believe if you can do it with await, you could do it by this code.

**Comment by zixia** [comment]
Hope you are doing well. 

I'll close this issue for now, if you still experiencing this issue, please feel free to let me know the details.
