### ISSUE TITLE
wechaty 0.7.21 works but 0.7.24 failed with Argument of type 'string | Promise<boolean>' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by xinbenlv** [wechaty/wechaty#282]
21:44:17 zzn@zzn-curie ❯ ~ ❯ ws ❯ haoshiyou-bot ▶ master + ▶ $npm i wechaty@0.7.24
haoshiyou-bot@1.0.1 /usr/local/google/home/zzn/ws/haoshiyou-bot
└─┬ wechaty@0.7.24
  └── ws@2.0.3

21:44:22 zzn@zzn-curie ❯ ~ ❯ ws ❯ haoshiyou-bot ▶ master + ▶ $ ▶docker run --env CLOUDINARY_SECRET=$CLOUDINARY_SECRET -ti --volume="$(pwd)":/bot --rm zixia/wechaty main.ts

 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  ____                            _   _
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/
  ____ _           _   ____        _
 / ___| |__   __ _| |_| __ )  ___ | |_ ___
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/

Starting Wechaty ... v0.7.35

Working directory: /bot
Please make sure you had installed all the NPM modules which is depended by your bot script.
Executing ts-node main.ts

/wechaty/node_modules/ts-node/src/index.ts:319
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
main.ts (140,58): Argument of type 'string | Promise<boolean>' is not assignable to parameter of type 'string'.
  Type 'Promise<boolean>' is not assignable to type 'string'. (2345)
    at getOutput (/wechaty/node_modules/ts-node/src/index.ts:319:17)
    at /wechaty/node_modules/ts-node/src/index.ts:350:18
    at Object.compile (/wechaty/node_modules/ts-node/src/index.ts:509:17)
    at Module.m._compile (/wechaty/node_modules/ts-node/src/index.ts:413:44)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/wechaty/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
  ____  _   _  ____   ____  _____ ____   ___  ____ _____
 | __ )| | | |/ ___| |  _ \| ____|  _ \ / _ \|  _ \_   _|
 |  _ \| | | | |  _  | |_) |  _| | |_) | | | | |_) || |
 | |_) | |_| | |_| | |  _ <| |___|  __/| |_| |  _ < | |
 |____/ \___/ \____| |_| \_\_____|_|    \___/|_| \_\|_|

Press ENTER to continue ...

### 1. source code of main.ts

import {Wechaty, Room, Contact, Message, FriendRequest, MsgType} from "wechaty";
import {HsyBotLogger, HsyGroupEnum} from "./datastore";
import { createWriteStream }  from 'fs';
import { Logger, LoggerConfig } from "log4ts";
import ConsoleAppender from "log4ts/build/appenders/ConsoleAppender";
import BasicLayout from "log4ts/build/layouts/BasicLayout";
import {LogLevel} from "log4ts/build/LogLevel";
import {LoopbackQuerier} from "./loopback-querier";
import {HsyUser} from "./loopbacksdk/models/HsyUser";
import {HsyUtil} from "./hsy-util";

const bot = Wechaty.instance();
const cloudinary = require('cloudinary');
const newComerSize = 200;
const groupDownSizeTarget = 465;
const groupDownSizeTriggerThreshold = 480;
let appender = new ConsoleAppender();
let layout = new BasicLayout();
appender.setLayout(layout);
let config = new LoggerConfig(appender);
config.setLevel(LogLevel.ALL);
Logger.setConfig(config);

const logger = Logger.getLogger(`main`);
if (process.env.CLOUDINARY_SECRET !== undefined && process.env.CLOUDINARY_SECRET.length > 0) {
  cloudinary.config({
    cloud_name: 'xinbenlv',
    api_key: '999284541119412',
    api_secret: process.env.CLOUDINARY_SECRET
  });

} else {
  logger.error('Need to specify cloudinary secret by export CLOUDINARY_SECRET="some_secret" .');
  process.exit();
}

const hsyCannotUnderstandMsg = `小助手没听懂你说啥意思哈，回复【加群】了解怎样加入租房群。`;
const hsyGreetingsMsg =
    `你好，谢谢你加我们群，请问你要在哪个区域找房子或者室友？\n` +
    `我们是按照区域分群的。我拉你入群：\n` +
    `  【南湾西】包含Palo Alto，Stanford, Mountain View，Sunnyvale，Cupertino一带；\n` +
    `  【南湾东】包含San Jose，Santa Clara，Milpitas一带；\n` +
    `  【东湾】湾东边Milpitas以北，包括Fremont，Hayward，Berkeley等；\n` +
    `  【中半岛】Redwood以北，San Francisco以南；\n` +
    `  【三番】旧金山(San Francisco)城里，含South San Francisco；\n`+
    `  【西雅图】我们新开设了西雅图好室友群，服务大西雅图地区；\n`+
    `  【短租】如果你希望在旧金山湾区任意地方内进行3个月以内短租（出租和求租），请加短租群；\n`+
    `请回复要加哪个群，例如： 南湾西\n` +
    `另外如果你在我们群里找到了室友或者房子，欢迎加入我们的【好室友】"老友群"，闲聊~，` +
    `详情请私信群主周载南(wechat:xinbenlv)或者入口群里的管理员们`;

const hysAlreadyAddedMsg = `已邀请，请点击加入[湾区好室友]系列租房群。`;

const hsyGroupNickNameMsg = `

提醒一下小伙伴记得按照要求修改群昵称哦，格式为“求/招-区域-时间-全真名”，
例如 "求-SV-3月-王小明"表示你是王小明，求租3月在Sunnyvale附近的房子。
请大家把昵称改为如下格式：“招/求/-地点-时间-真全名”，例如:

“招-mtv-5/1-王小明”表示你是王小明，招租房客，房子地点在 Mountain View，时间5月1日开始。
“求-pa-4/12-韩梅梅”表示你是韩梅梅，求租房子，房子地点在 Palo Alto，时间4月1日开始。
“介-李雷”表示你是李雷，在群里目前没有需求，仅为了介绍朋友进群。“介”这类可以不写时间地点。

本群中对地点常用缩写约定如下：
  SF-San Francisco,
  PA-Palo Alto,
  MTV-Mountain View,
  SV-Sunnyvale,
  FMNT-Fremont,
  SJ-San Jose,
  MPTS-Milpitas,
  SEA - Seattle
  KIR - Kirkland

好室友系列租房群会自动定期清理没有修改群昵称的群友，以及最早的群友以便给新人腾位置。
`;

const hsyGroupClearMsg =
    `亲爱的各位好室友租房群的群友们，现在群快满了，清理一批群友给新朋友们腾位置。\n` +
    `我们主要清理两类朋友：\n` +
    `  1. 没有按照改群昵称的朋友，如果你的群昵称不是以'招'、'求'、'介'开头，那么你可能会被优先清理；\n` +
    `  2. 如果你的入群时间比较长，那么我们会请你优先离群，把空位流动起来（可以重新回来）；\n` +
    `若仍有需求，欢迎私信好室友小助手（微信号：haoshiyou-admin）重新加群哈~\n`;

bot
    .on('scan', async (url, code) => {
      await HsyBotLogger.logDebug(`Please scan the QR code for URL ${url}.`);
      let loginUrl = url.replace('qrcode', 'l');
      require('qrcode-terminal').generate(loginUrl);
    })

    .on('login', async user => {
      await logger.info(`${user} logged in`);
    })

    .on('logout', async user => {
      await logger.info(`${user} logged out.`);
    })

    .on('friend', async (contact, request:FriendRequest) => {
      await HsyBotLogger.logFriendRequest(request);
      if (request) {  // 1. request to be friend from new contact
        await request.accept();
        await contact.say(hsyGreetingsMsg);
      } else {        // 2. confirm friend ship
        await logger.info('new friend ship confirmed with ' + contact);
      }
    })

    .on('message', async (m) => {
      await HsyBotLogger.logRawChatMsg(m);
      if (m.self()) {
        return; // Early return for talking to myself.
      }
      logger.debug(`Got a msg type: ${m.type()}`);
      await maybeAddToHsyGroups(m);
      await extractPostingMessage(m);
    })

    .init()
    .then(async _ => await logger.info(`HsyBot is terminated`))
    .catch(e => logger.error(e));

let maybeDownsizeKeyRoom = async function(keyroom: Room, c:Contact) {
  if (/老友/.test(keyroom.topic())) return;
  if (keyroom.memberList().length >= groupDownSizeTriggerThreshold) { // triggering
    await keyroom.say(hsyGroupClearMsg);
    let potentialRotationList = [];
    let noGroupNickNames = [];
    let cList:Contact[] = keyroom.memberList();
    let shouldRemoveSize = cList.length - groupDownSizeTarget;
    let shouldRemoveList = [];
    for (let i = 0; i < keyroom.memberList().length - newComerSize/* never newComer */; i++) {
      let c:Contact = cList[i];
      if (c.self()) continue; // never does anything with haoshiyou-admin itself.
      let groupNickName = getGroupNickNameFromContact(c);
      if (/^(管|介|群主)-/.test(groupNickName) || /管理员/.test(c.remark())) {
        logger.info(`略过管理员 ${c.name()}, 群里叫做 ${getGroupNickNameFromContact(c)}，备注${c.remark()}`);
        // pass, never remove
      } else if (/^(招|求)租/.test(groupNickName)) {
        // good format, but need to rotate
        potentialRotationList.push(c);
      } else {
        noGroupNickNames.push(c);
      }
      if (noGroupNickNames.length >= shouldRemoveSize) {
        shouldRemoveList = noGroupNickNames;
        break;
      } else if (noGroupNickNames.length + potentialRotationList.length >= shouldRemoveSize) {
        shouldRemoveList = noGroupNickNames
            .concat(potentialRotationList.slice(0,
                shouldRemoveSize - noGroupNickNames.length));
        break;
      }
    }
    if (shouldRemoveList.length > 0) {
      await c.say(`群里有点儿满，我先清一下人哦`);
    }
    await Promise.all(shouldRemoveList.map(async (c:Contact) => {
      await HsyBotLogger.logDebug(`Deleting contact ${c.name()} from group ${keyroom.topic()}`);
      let msg = (`亲 ~ 你在${keyroom.topic()}里面`) +
          (/^(招|求)租/.test(getGroupNickNameFromContact(c)) ?
          `待得比较久了，如果你已经在群里找到室友或者房子，恭喜你！`  +
          `请联系群主 周载南（微信号xinbenlv）加入"老友群"，` :
          `没有按照规则修改群昵称，`) +
          `这里我先把你挪出本群哈，随时加我（小助手，微信号haoshiyou-admin）重新入群。`;
      await c.say(msg);
      await keyroom.del(c);
    }));
  } else {
    logger.info(`Group Size of ${keyroom.topic()} is ` +
        `still good (${keyroom.memberList().length}).`)
  }
};

let maybeAddToHsyGroups = async function(m:Message) {
  const contact = m.from();
  const content = m.content();
  const room = m.room();
  let groupType:HsyGroupEnum;
  // only to me or entry group
  if (isTalkingToMePrivately(m) || /好室友.*入口群/.test(m.room().topic())) {
    logger.debug(`${contact.name()}(weixin:${contact.weixin()}) sent a message ` +
        `type: ${m.type()} ` +
        `content: ${m.content()}`);
    let groupToAdd = null;
    if (/加群/.test(content)) {
      await m.say(hsyGreetingsMsg);
      return;
    } else if (/南湾西|Mountain View|mtv|sv|Sunnyvale|Palo Alto|Stanford|Facebook|Google|Menlo Park/.test(content)) {
      groupToAdd = "南湾西";
      groupType = HsyGroupEnum.SouthBayEast;
    } else if (/南湾东|Milpitas|San Jose|Santa Clara|SJ|Campbell|Los Gatos/.test(content)) {
      groupToAdd = "南湾东";
      groupType = HsyGroupEnum.SouthBayWest;
    } else if (/东湾|奥克兰|伯克利|Berkeley|Fremont|Hayward|Newark/.test(content)) {
      groupToAdd = "东湾";
      groupType = HsyGroupEnum.EastBay;
    } else if (/(中)半岛|Redwood|San Carlos|San Mateo|Burlingame|Millbrae|San Bruno/.test(content)) {
      groupToAdd = "中半岛";
      groupType = HsyGroupEnum.MidPeninsula;
    } else if (/旧金山|三番|San Francisco|Uber|AirBnb/.test(content)) {
      groupToAdd = "三番";
      groupType = HsyGroupEnum.SanFrancisco;
    } else if (/西雅图/.test(content)) {
      groupToAdd = "西雅图";
      groupType = HsyGroupEnum.Seattle;
    } else if (/短租/.test(content)) {
      groupToAdd = "短租";
      groupType = HsyGroupEnum.ShortTerm;
    } else if (/测试/.test(content)) {
      groupToAdd = "测试";
      groupType = HsyGroupEnum.TestGroup;
    } else if (/老友/.test(content)) {
      groupToAdd = "老友";
      groupType = HsyGroupEnum.OldFriends;
    }
    if (groupToAdd == null) { // found no valid group
      await m.say(hsyCannotUnderstandMsg);
    } else {
      await logger.info(`Start to add ${contact} to room ${groupToAdd}.`);
      await HsyBotLogger.logBotAddToGroupEvent(contact, groupType);
      await m.say(`好的，你要加${groupToAdd}的群对吧，我这就拉你进群。`);
      let typeRegEx = new RegExp(`好室友.*` + groupToAdd);
      let keyroom = await Room.find({topic: typeRegEx});
      if (keyroom) {
        await maybeDownsizeKeyRoom(keyroom, contact);
        await keyroom.add(contact);
        await contact.say(hysAlreadyAddedMsg);
        await contact.say(hsyGroupNickNameMsg);
      } else {
        await m.say(`囧...加群失败，请联系群主周载南(微信号:xinbenlv)。`);
        logger.info(`Can't find group ${groupToAdd}`);
      }
    }
  }

};

let isTalkingToMePrivately = function(m:Message) {
  return m.rawObj['MMIsChatRoom'] == false;
};

let extractPostingMessage = async function(m:Message) {
  if (isTalkingToMePrivately(m) || /好室友/.test(m.room().topic())) {
    let userId = maybeCreateUser(m);
    if (m.type() == MsgType.IMAGE) {
      logger.info(`${m.from().name()} sent an image.`);
      let publicId = await saveImgFileFromMsg(m);
      logger.info(
          `Uploaded image ${publicId} to cloudinary, now update the database, in group` +
          `${getHsyGroupEnum(m.room())}`);
      await HsyBotLogger.logListingImage(m, getHsyGroupEnum(m.room()), publicId);
    } else {
      logger.info(`${m.from().name()} say: ${m.content()}`);
      if (m.content().length >= 80 &&
          /租|rent|roomate|小区|公寓|lease/.test(m.content())) {
        HsyBotLogger.logListing(m, getHsyGroupEnum(m.room()));
      }
    }
  }
};

let getGroupNickNameFromContact = function(c:Contact) {
  return c['rawObj']['DisplayName'];
};

let getHsyGroupEnum = function(room) {
  let topic = room.topic();
  if (!/好室友/.test(topic)) return HsyGroupEnum.None;
  else if (/旧金山/.test(topic)) {
    return HsyGroupEnum.SanFrancisco;
  } else if (/中半岛/.test(topic)) {
    return HsyGroupEnum.MidPeninsula;
  } else if (/南湾西/.test(topic)) {
    return HsyGroupEnum.SouthBayEast;
  } else if (/南湾东/.test(topic)) {
    return HsyGroupEnum.SouthBayEast;
  } else if (/东湾/.test(topic)) {
    return HsyGroupEnum.EastBay;
  } else if (/老友/.test(topic)) {
    return HsyGroupEnum.OldFriends;
  } else if (/西雅图/.test(topic)) {
    return HsyGroupEnum.Seattle;
  }
  return HsyGroupEnum.None;
};
let savePic = async function(filename:string, picStream:NodeJS.ReadableStream):Promise<string> {
  logger.debug('IMAGE local filename: ' + filename);
  const fileStream = createWriteStream(filename);
  let stream = await picStream;
  // TODO(xinbenlv): this might cause the error of following
  //   unhandledRejection: Error: not a media message [object Promise]
  return new Promise<string>( /* executor */ function(resolve, reject) {
    stream.pipe(fileStream)
        .on('close', () => {
          logger.debug('finish readyStream()');
          cloudinary.uploader.upload(filename, function(result, error) {
            if (error) {
              logger.warn(`There is an error in saveMediaFile upload of cloudinary`);
              logger.warn(error);
              reject(error);
            } else {
              logger.info(`Uploaded an image:` + JSON.stringify(result));
              resolve(result.public_id);
            }
          });
        });
  }).then(publicId => {
    logger.debug(`The PublicId result is ${publicId}`);
    return publicId;
  });
};
let saveImgFileFromMsg = async function(message: Message):Promise<any> {
  const filename = 'tmp/img/' + message.filename();
  return await savePic(filename, await message.readyStream());
};

let maybeCreateUser = async function(m:Message):Promise<string/*userId*/> {
  logger.debug(`Maybe create an user`);
  let c = m.from();
  let uid = HsyUtil.getUserIdFromName(c.name());
  let q = new LoopbackQuerier();
  let user = await q.getHsyUserByUid(uid);
  if (!c.weixin()) {
    c = await c.refresh();
  }
  logger.debug(`Got user of uid:${uid}: ${JSON.stringify(user)}`);
  if (user === null || user === undefined) {
    user = new HsyUser();
    user.id = uid;
    user.name = c.name();
    user.created = new Date();
    user.weixin = c.weixin();
    logger.debug(`User of uid:${uid} does not exist, creating a user...`);
  } else {
    logger.debug(`User of uid:${uid} already existed`);
  }
  // TODO(zzn): avatar is currently empty file
  // user.avatarId = await savePic('tmp/img/' + c.name() + '.jpg', await c.avatar());
  user.lastUpdated = new Date();
  await q.setHsyUser(user);
  logger.debug(`User of uid:${uid} created/updated: ${JSON.stringify(user)}`);
  return uid;
};

### 2. directory structor of /bot

total 841184
-rw-r-----   1 180524 5000      1994 Feb 10 04:16 Readme.md
-rw-r-----   1 180524 5000      4843 Feb 11 22:54 datastore.ts
-rw-r-----   1 180524 5000       121 Feb 11 22:54 hsy-util.ts
-rw-r--r--   1 180524 root 860448202 Feb 24 05:28 log.json
-rw-r-----   1 180524 5000      2780 Feb 24 05:26 loopback-querier.ts
drwxr-x---   5 180524 5000      4096 Feb  1 16:46 loopbacksdk
-rw-r-----   1 180524 5000     14670 Feb 24 05:26 main.ts
drwxr-x--- 192 180524 5000      4096 Feb 24 05:44 node_modules
-rw-r-----   1 180524 5000      1390 Feb 24 05:26 package.json
-rw-r--r--   1 180524 5000    778093 Feb 24 03:55 potential-posting.json
drwxr-x---   3 180524 5000      4096 Feb 10 04:25 tmp
-rw-r-----   1 180524 5000       142 Jan 21 05:11 tsconfig.json
-rw-r--r--   1 180524 root     40245 Feb 10 06:32 yarn.lock

### 3. package.json

{
  "dependencies": {
    "@purest/providers": "^1.0.0",
    "@types/express": "^4.0.34",
    "bluebird": "^3.4.7",
    "chromedriver": "^2.27.2",
    "cloudinary": "^1.6.0",
    "express": "^4.14.0",
    "jsonfile": "^2.4.0",
    "log4ts": "^0.4.2",
    "purest": "^3.0.1",
    "qrcode-terminal": "^0.11.0",
    "request": "^2.79.0",
    "uuid": "^3.0.1",
    "wechaty": "^0.7.3"
  },
  "scripts": {
    "docker": "docker run -ti --volume=\"$(pwd)\":/bot --rm zixia/wechaty main.ts",
    "preinstall-chromedriver": "npm install",
    "install-chromedriver": "node node_modules/chromedriver/install.js",
    "pretest_e2e": "npm run install-chromedriver",
    "test_e2e": "node release/test/rune2e.js"
  },
  "name": "haoshiyou-bot",
  "description": "[![Powered by Wechaty](https://img.shields.io/badge/Powered%20By-Wechaty-green.svg)](https://github.com/wechaty/wechaty)",
  "version": "1.0.1",
  "main": "main.js",
  "devDependencies": {},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/xinbenlv/haoshiyou-bot.git"
  },
  "keywords": [
    "haoshiyou",
    "haoshiyou.org",
    "chatbot",
    "wechaty",
    "wechat",
    "rent",
    "house",
    "roommate"
  ],
  "author": "Zainan Victor Zhou",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/xinbenlv/haoshiyou-bot/issues"
  },
  "homepage": "https://github.com/xinbenlv/haoshiyou-bot#readme"
}

### 4. directory structor inside /bot/node_modules

@purest		    bcrypt-pbkdf     component-emitter	  engine.io-client	    glob	       is-property	    mime	      path-is-absolute	  send		     tunnel-agent
@request	    benchmark	     component-inherit	  engine.io-parser	    graceful-fs        is-typedarray	    mime-db	      path-to-regexp	  serve-static	     tweetnacl
@types		    better-assert    concat-map		  escape-html		    graceful-readlink  isarray		    mime-types	      pause-stream	  setprototypeof     type-is
accepts		    blob	     content-disposition  escape-string-regexp	    har-validator      isstream		    minimatch	      pinkie		  sntp		     ultron
adm-zip		    bluebird	     content-type	  etag			    has-ansi	       jodid25519	    minimist	      pinkie-promise	  socket.io	     unpipe
after		    body-parser      cookie		  event-stream		    has-binary	       jsbn		    mkdirp	      proxy-addr	  socket.io-adapter  utils-merge
ansi-regex	    boom	     cookie-signature	  express		    has-cors	       json-schema	    moment	      ps-tree		  socket.io-client   uuid
ansi-styles	    brace-expansion  cryptiles		  extend		    hawk	       json-stringify-safe  ms		      punycode		  socket.io-parser   vary
array-flatten	    brolog	     dashdash		  extsprintf		    hoek	       json3		    negotiator	      purest		  split		     verror
arraybuffer.slice   bytes	     debug		  finalhandler		    http-errors        jsonfile		    oauth-sign	      q			  sshpk		     wechaty
asn1		    callsite	     deep-copy		  forever-agent		    http-signature     jsonpointer	    object-component  qrcode-terminal	  statuses	     wrappy
assert-plus	    caseless	     delayed-stream	  form-data		    iconv-lite	       jsprim		    on-finished       qs		  stream-combiner    ws
asynckit	    chalk	     depd		  forwarded		    indexof	       kew		    once	      range-parser	  stringstream	     wtf-8
aws-sign2	    chromedriver     destroy		  fresh			    inflight	       lodash		    options	      raw-body		  strip-ansi	     xml2js
aws4		    ci-info	     duplexer		  from			    inherits	       log4ts		    os-tmpdir	      request		  supports-color     xmlbuilder
backo2		    cloudinary	     ecc-jsbn		  fs.realpath		    ipaddr.js	       map-stream	    parsejson	      retry-promise	  through	     xmlhttprequest-ssl
balanced-match	    combined-stream  ee-first		  generate-function	    is-ci	       media-typer	    parseqs	      rimraf		  tmp		     xtend
base64-arraybuffer  commander	     encodeurl		  generate-object-property  is-docker	       merge-descriptors    parseuri	      sax		  to-array	     yeast
base64id	    component-bind   engine.io		  getpass		    is-my-json-valid   methods		    parseurl	      selenium-webdriver  tough-cookie

#### Wechaty Doctor

  1. Wechaty version: 0.7.35
  2. Linux x64 version 3.13.0-106-generic memory 1436/32176 MB
  3. Docker: true
  4. Node version: v7.6.0
  5. Tcp IPC TEST: PASS

  ____        _               _ _             ___ ____ ____  _   _ _____
 / ___| _   _| |__  _ __ ___ (_) |_    __ _  |_ _/ ___/ ___|| | | | ____|
 \___ \| | | | '_ \| '_ ` _ \| | __|  / _` |  | |\___ \___ \| | | |  _|
  ___) | |_| | |_) | | | | | | | |_  | (_| |  | | ___) |__) | |_| | |___
 |____/ \__,_|_.__/|_| |_| |_|_|\__|  \__,_| |___|____/____/ \___/|_____|

_____________________________________________________________
####### please paste all the above diagnose messages #######

Wechaty Issue https://github.com/wechaty/wechaty/issues

Press ENTER to continue ...

 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  _____      _ _     _
 | ____|_  _(_) |_  / |
 |  _| \ \/ / | __| | |
 | |___ >  <| | |_  | |
 |_____/_/\_\_|\__| |_|

**Comment by zixia** [comment]
It's a little bit difficult to read because of you are mixing the logs with your words...

**Comment by zixia** [comment]
@xinbenlv How about this issue, did you solved it?
