### ISSUE TITLE
[New Feature] FriendRequest class and event

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#33]
according to #14 

## WxApp

```typescript
class contactFactory {
  verifyUser({
      UserName: string
      , Opcode: confFactory.VERIFYUSER_OPCODE_VERIFYOK
      , Scene: confFactory.ADDSCENE_PF_WEB
      , Ticket: Ticket
      , VerifyContent: string
  })
}

type RecommendInfo = {
  UserName: string
  NickName: string
  Content:     string // request message
  Ticket:         string // a pass token
  VerifyFlag:  number
}

interface Message = {
  RecommendInfo: RecommendInfo
}
```

## Wechaty Class `FriendRequest`

1. send request to other
2. receive request from other(in `friend` event)

```typescript
class FriendRequest {
  private info: RecommentInfo
  private hello: string
  private ticket: string

  private contact: Contact

  constructor(): FriendRequest

  send(contact: string|Contact, hello?: string): Promise<any> // 1. send friend request to other
  receive(info?: RecommendInfo): FriendRequest    // 2. receive request from other

  accept(): Promise<any>
}

Interface Wechaty {
  on('friend', (contact: Contact, request: FriendRequest) => void): void
}
```

### Add Friend / Send Friend Request

accept friend requirest interface should be like this:

```javascript
const sender : Contact = message.get('from')
const fr = new FriendRequest()
fr.send(sender, 'hello~')
```

### Event: Friend Request

1. Receive New Friend Request
2. Confirmation of FriendShip

friend request is a message from `SP_CONTACT_RECOMMEND_HELPER: "fmessage"`, with type `Message.Type.VERIFYMSG`

in `PuppetWeb.onServerMessage()`:

```typescript
if (message.MsgType === MSGTYPE_VERIFYMSG) {
  const request = new FriendRequest()
  request.receive(message.RecommendInfo)
  emit('friend', request.contact, request)
}

// Be Accepted: I've accepted your friend request. Now let's chat!
// Accept: You have added ${NickName} as your WeChat contact. Start chatting!
case Message.Type.SYS:
if (/^You have added (.+) as your WeChat contact. Start chatting!$/.test(m.get('content'))) {
const request = new FriendRequest()
  const contact = Contact.load(m.get('from'))
  request.confirm(contact)

  this.emit('friend', contact)
}
```

then we can:
```typescript
wechaty.on('friend', (contact, request) => {
  if (request) { // 1. we got new request
    if (/secret/.test(request.hello)) {
      request.accept()
    }
  } else { // 2. we got new friend
    console.log('got new friend: ' + contact)
  }
})
```

**Comment by zixia** [comment]
all done. :)

**Comment by JasLin** [comment]
great job,

```
const sender : Contact = message.get('from')
const fr = new FriendRequest()
fr.send(sender, 'hello~')
```
so, now  we can add friend in rooms ,just instance an Contact from room.memberList?

and ,has any idea to add friend with a  giving  wechat number?

**Comment by JasLin** [comment]
may be we should puppet the android version wechat , ```puppetAndroid``` :)

**Comment by zixia** [comment]
@JasLin wow... you caught me...

how do you think? we could use webdriver/appium to puppet the wechat app in android/ios, through the emulator. and the emulator can run inside docker, so there will be no difficaulty to use(even the environment will be more complex than now).

but I'm afraid recently I have no time to start this. if you are familar with the emulator, you are definitely welcome to have a try with PuppetAndroid!

**Comment by JasLin** [comment]
@zixia it could be very complex , forget it , just a joke :)

**Comment by zixia** [comment]
@JasLin I think maybe it's not that complex...

i.e. inject code to wechat as root, to skip the emulator check function in wechat? 

I don't know exactly, hope somebody will come someday, get it done. then everything will work like a charm. ;-) (I believe somebody is already do that: run wechaty inside emulator)

**Comment by JasLin** [comment]
@zixia yes, somebody is already do that:)
for andoird , it could use [AccessibilityService](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html) to simulate click action.

**Comment by JasLin** [comment]
@zixia look like this :  https://github.com/waylife/RedEnvelopeAssistant/blob/master/RedEnvelopeAssistant/src/com/nearucenterplaza/redenvelopeassistant/service/WechatAccService.java#L82
