### ISSUE TITLE
Trying to connect with dashbot.io

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#371]
[dashbot.io](https://www.dashbot.io/) is a fantastic bot analytics platform, it can provide abundant metrics to help you better monitor your data. You can increase user engagement, acquisition, and monetization through analytics, bot specific metrics, funnel analysis and live transcripts and other functions.

Now, I'm trying to communicate with their founder DennisYang and trying to integrate with wechaty.

We can send data with generic type, but we want to integrate more.

Here is the raw message Json example to see whether we can store more.

```shell
{
    "MsgId": "1159549798484970886", 
    "FromUserName": "@@f47ccb7762cf4dc7352508fb03b79b44cedd3d1e16152e7f1bae3d4cf7996eb2", 
    "ToUserName": "@56c8d702f12e05ae64872e7c2a92073486b57623bf04941cef47bf2e8452ca7d", 
    "MsgType": 1, 
    "Content": "@c8e11ab44ea04b92c98885453eeef1a5:<br/>@wuli舞哩客服 @小桔同学 你们好", 
    "Status": 3, 
    "ImgStatus": 1, 
    "CreateTime": 1489758397, 
    "VoiceLength": 0, 
    "PlayLength": 0, 
    "FileName": "", 
    "FileSize": "", 
    "MediaId": "", 
    "Url": "", 
    "AppMsgType": 0, 
    "StatusNotifyCode": 0, 
    "StatusNotifyUserName": "", 
    "RecommendInfo": {
        "UserName": "", 
        "NickName": "", 
        "QQNum": 0, 
        "Province": "", 
        "City": "", 
        "Content": "", 
        "Signature": "", 
        "Alias": "", 
        "Scene": 0, 
        "VerifyFlag": 0, 
        "AttrStatus": 0, 
        "Sex": 0, 
        "Ticket": "", 
        "OpCode": 0
    }, 
    "ForwardFlag": 0, 
    "AppInfo": {
        "AppID": "", 
        "Type": 0
    }, 
    "HasProductId": 0, 
    "Ticket": "", 
    "ImgHeight": 0, 
    "ImgWidth": 0, 
    "SubMsgType": 0, 
    "NewMsgId": 1159549798484971000, 
    "OriContent": "", 
    "MMPeerUserName": "@@f47ccb7762cf4dc7352508fb03b79b44cedd3d1e16152e7f1bae3d4cf7996eb2", 
    "MMDigest": "22acb030-ff09-11e6-8a73-cff62d9268c5:@wuli舞哩客服 @小桔同学 你们好", 
    "MMIsSend": false, 
    "MMIsChatRoom": true, 
    "MMUnread": true, 
    "LocalID": "1159549798484970886", 
    "ClientMsgId": "1159549798484970886", 
    "MMActualContent": "@wuli舞哩客服 @小桔同学 你们好", 
    "MMActualSender": "@c8e11ab44ea04b92c98885453eeef1a5", 
    "MMDigestTime": "21:46", 
    "MMDisplayTime": 1489758397, 
    "MMTime": "21:46"
}
```

**Comment by lijiarui** [comment]
Now I'm using dashbot with generic like the following function:
```
public outgoing() {
    request({
        uri: 'https://tracker.dashbot.io/track?platform=generic&v=0.8.2-rest&type=incoming&apiKey=' + this.DASHBOT_API_KEY_GENERIC,
        qs: {
            type: 'outgoing',
            platform: 'generic',
            apiKey: this.DASHBOT_API_KEY_GENERIC,
            v: this.version,
        },
        method: 'POST',
        json: {
            text: this.message,
            userId: this.contact.name(),
        },
    })
  }

  public incoming() {
    request({
        uri: 'https://tracker.dashbot.io/track?platform=generic&v=0.8.2-rest&type=incoming&apiKey=' + this.DASHBOT_API_KEY_GENERIC,
        qs: {
            type: 'incoming',
            platform: 'generic',
            apiKey: this.DASHBOT_API_KEY_GENERIC,
            v: this.version,
        },
        method: 'POST',
        json: {
            text: this.message,
            userId: this.contact.name(),
        },
    })
  }
```

**Comment by dcsan** [comment]
FYI I've chatted with Dennis (as in Tennis :) quite a lot. I had problems with dashbot being blocked from our (china/AWS) servers. One idea is that maybe they were hosted on digitalOcean (I'm not sure though), which sometimes the whole IP block gets censored.

Other than that it's a great service!

So you don't have any problem now sending events to dashbot?

FYI analytics for Bots is a big topic in the US. Another company is:
botanalytics.co

**Comment by lijiarui** [comment]
Because my bot is hosted on digitalOcean too, so I don't have too many problems when sending events to dashbot. And I just begin to use dashbot these days, so I'm not very sure.

By the way, I have several bots, some on aliyun and some on digitalOcean. For now, there isn't any difference between them.

And I found https://bot-metrics.com/ is also good too.

**Comment by dcsan** [comment]
About the userId problem and getting a unique ID

https://github.com/Chatie/wechaty/blob/master/src/contact.ts#L27-L41

instead of:

            userId: this.contact.name(),

it looks like Contact class has access to the wechatID - can't we use that?
https://github.com/Chatie/wechaty/blob/master/src/contact.ts#L97

**Comment by lijiarui** [comment]
About the uniqueID, my solution on my bot is to set alias for each contact
```ts
await contact.alias(uuid())
``` 
and use alias(we called remark before, see #217 ) to find the contact. 
```ts
Contact.find({alias: 'a0023550-14a8-11e7-95fa-71e801e1855d' })
```

Btw, wechaty do has function `contact.weixin()` to get contact's wechatID, because sometimes we can get wechatID in contact's rawObj from webwx, but cannot always get some person's wechatID each time for some reason, I haven't found the real reason, so using `contact.weixin()` is not a good solution.

**Comment by dcsan** [comment]
so alias remains consistent between sessions and devices, since it is stored server side by wechat, correct? ie you set it thru the wechaty/web client but then it shows up on your phone too?

the wechat ID is not available about 10% of the time? I think its only for users that joined wechat directly from QQ in the old days, when this was possible.

otherwise this is a bit ugly and it makes it hard to know who you are talking to, if a real human was to take over the chat.

we could do something like

`contact.safeId()`

that would create a user alias *only if* the wechat ID doesn't exist?

```typescript
  public static async safeId(): string {

    return this.obj.weixin || 
               this.obj.alias || 
               this.obj.alias( uuid() )   // this would set a uuid so safe to call next time
}
```

**Comment by dcsan** [comment]
in our app at least we often have a live teacher take from the bot and chat to people
we also want to be able to see the userName so we can associate users from the official account into the bot chat. So in this way we would want to keep the original name visible. Maybe you dont need this for a fully automated bot ...

**Comment by dcsan** [comment]
125428 unread messages 🤣 🤣 🤣 
you have some catching up to do @lijiarui 

do you find this slows down wechaty on login?
I know on native clients it fetches all those messages, even in rooms you have muted.

I had a bot and found that the "get list of rooms" function was taking a long time - I think because it was syncing a lot of unread messages to the web client even in chromedriver. But not sure... 
Does the web client only request messages when you want to view them?

**Comment by lijiarui** [comment]
Yes, alias remains consistent between sessions and devices, even if you reload wechat or relog in wechat on the different phone.

And I set alias through wechaty/web client and then it shows up on my phone.

The wechat ID is not available all the time, but I don't know the exact number, I guess only the new users can get wechat ID, because I can get my wechat ID by wechaty, but @zixia cannot get his wechat ID by wechaty.

**Comment by lijiarui** [comment]
> otherwise this is a bit ugly and it makes it hard to know who you are talking to, if a real human was to take over the chat.

I really agree with this, and it confused me a lot when take over. So I suggest whether dashbot can show  both uniqueId and username, then it will easy to recognize.

![1111](https://cloud.githubusercontent.com/assets/6419514/24487881/963e82c4-1545-11e7-81f6-d54ab1c1dd3f.jpeg)

**Comment by lijiarui** [comment]
But I do not entirely agree with your solution:
```
public static async safeId(): string {

    return this.obj.weixin || 
               this.obj.alias || 
               this.obj.alias( uuid() )   // this would set a uuid so safe to call next time
}
```
because we cannot set contacts's alias by wechaty by default. It should let developer to decide, or if someone uses wechaty and dashbot, and then he saw his contact `李佳芮` has changed to `a0023550-14a8-11e7-95fa-71e801e1855d`, he will shouted...... 

maybe
```
public static async safeId(): string {

    return this.obj.weixin || 
               this.obj.alias || 
               this.obj.id   // contactId as we talked
}
```

but I'm not sure it should be obj.id(somethin like @cd7d467d7464e8ff6b0acd29364654f3666df5d04551f6082bfc875f90a6afd2) or obj.name (something like 李佳芮)

As you have said, usually names are almost unique.... Although my bot has two contact with the same name....

**Comment by lijiarui** [comment]
> do you find this slows down wechaty on login?

About a great amount of message, it never slows down wechaty on login. But it indeed slow down my android device... Receiving message on server is quite faster then the device, so if I can connect dashbot, I can leave out my device completely.

> I had a bot and found that the "get list of rooms" function was taking a long time - I think because it was syncing a lot of unread messages to the web client even in chromedriver. But not sure...
Does the web client only request messages when you want to view them?

Yes, `get list of rooms` does take some time, but not that long. I have more than 500 hundred groups and it won't take me too long time to get all. Actually, server always faster than web or phone.... I thought the time is cost on render front-end show, maybe.

**Comment by lijiarui** [comment]
Here is the contact rawObj data, maybe you can find something interesting
```
Contact {
  id: '@4c32c97337cbb325442c304d6a44e374',
  rawObj:
   { Alias: 'ruirui_0914',
     AppAccountFlag: 0,
     AttrStatus: 2147584103,
     ChatRoomId: 0,
     City: '海淀',
     ContactFlag: 3,
     DisplayName: '',
     EncryChatRoomId: '',
     HeadImgUrl: '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=648035215&username=@4c32c97337cbb325442c304d6a44e374&skey=@crypt_ee003aea_5265cdd0c2676aab3df86b0249ae90f7',
     HideInputBarFlag: 0,
     IsOwner: 0,
     KeyWord: 'qq5',
     MMOrderSymbol: '~',
     MemberCount: 0,
     MemberList: [],
     NickName: '李佳芮',
     OwnerUin: 0,
     PYInitial: 'LJR',
     PYQuanPin: 'lijiarui',
     Province: '北京',
     RemarkName: '22acb030-ff09-11e6-8a73-cff62d9268c5',
     RemarkPYInitial: '22ACB030FF0911E68A73CFF62D9268C5',
     RemarkPYQuanPin: '22acb030ff0911e68a73cff62d9268c5',
     Sex: 2,
     Signature: '出洞计划  |  向前一步',
     SnsFlag: 49,
     StarFriend: 0,
     Statues: 0,
     Uin: 0,
     UniFriend: 0,
     UserName: '@4c32c97337cbb325442c304d6a44e374',
     VerifyFlag: 0,
     _h: 50,
     _index: 16,
     _offsetTop: 696,
     stranger: false },
  obj:
   { id: '@4c32c97337cbb325442c304d6a44e374',
     uin: 0,
     weixin: 'ruirui_0914',
     name: '李佳芮',
     alias: '22acb030-ff09-11e6-8a73-cff62d9268c5',
     sex: 2,
     province: '北京',
     city: '海淀',
     signature: '出洞计划  |  向前一步',
     address: 'ruirui_0914',
     star: false,
     stranger: false,
     avatar: '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=648035215&username=@4c32c97337cbb325442c304d6a44e374&skey=@crypt_ee003aea_5265cdd0c2676aab3df86b0249ae90f7' } }
```

**Comment by dcsan** [comment]
>> because we cannot set contacts's alias by wechaty by default. It should let developer to decide, or if someone uses wechaty and dashbot, and then he saw his contact 李佳芮 has changed to a0023550-14a8-11e7-95fa-71e801e1855d, he will shouted......

yes, agreed.

**Comment by lijiarui** [comment]
> Also using names is risky since the user can change it. We would lose their info, in future this does expose the fact someone could change their name, and impersonate someone to get at content inside our bot app. So, not a good way forward.

yes, maybe this is the most important reason why we cannot user name.....
but it is better than contactId?

So maybe the best implement as follows?
```
public static async safeId(): string {
    return this.obj.weixin || 
               this.obj.alias || 
               this.obj.name  
}
```

**Comment by lijiarui** [comment]
Here is the rawObj message for Dennis Yang

### message rawObj JSON

``` json
{
    "MsgId": "1159549798484970886",
    "FromUserName": "@@f47ccb7762cf4dc7352508fb03b79b44cedd3d1e16152e7f1bae3d4cf7996eb2",  because this message is 
    "ToUserName": "@56c8d702f12e05ae64872e7c2a92073486b57623bf04941cef47bf2e8452ca7d", 
    "MsgType": 1, 
    "Content": "@c8e11ab44ea04b92c98885453eeef1a5:<br/>@wuli舞哩客服 @小桔同学 你们好", 
    "Status": 3, 
    "ImgStatus": 1, 
    "CreateTime": 1489758397, 
    "VoiceLength": 0, 
    "PlayLength": 0, 
    "FileName": "", 
    "FileSize": "", 
    "MediaId": "", 
    "Url": "", 
    "AppMsgType": 0, 
    "StatusNotifyCode": 0, 
    "StatusNotifyUserName": "", 
    "RecommendInfo": {
        "UserName": "", 
        "NickName": "", 
        "QQNum": 0, 
        "Province": "", 
        "City": "", 
        "Content": "", 
        "Signature": "", 
        "Alias": "", 
        "Scene": 0, 
        "VerifyFlag": 0, 
        "AttrStatus": 0, 
        "Sex": 0, 
        "Ticket": "", 
        "OpCode": 0
    }, 
    "ForwardFlag": 0, 
    "AppInfo": {
        "AppID": "", 
        "Type": 0
    }, 
    "HasProductId": 0, 
    "Ticket": "", 
    "ImgHeight": 0, 
    "ImgWidth": 0, 
    "SubMsgType": 0, 
    "NewMsgId": 1159549798484971000, 
    "OriContent": "", 
    "MMPeerUserName": "@@f47ccb7762cf4dc7352508fb03b79b44cedd3d1e16152e7f1bae3d4cf7996eb2", 
    "MMDigest": "22acb030-ff09-11e6-8a73-cff62d9268c5:@wuli舞哩客服 @小桔同学 你们好", 
    "MMIsSend": false, 
    "MMIsChatRoom": true, 
    "MMUnread": true, 
    "LocalID": "1159549798484970886", 
    "ClientMsgId": "1159549798484970886", 
    "MMActualContent": "@wuli舞哩客服 @小桔同学 你们好", 
    "MMActualSender": "@c8e11ab44ea04b92c98885453eeef1a5", 
    "MMDigestTime": "21:46", 
    "MMDisplayTime": 1489758397, 
    "MMTime": "21:46"
}
```

### Some known annotation:

- **MsgId**  
messageId, nothing special

- **FromUserName** 
roomId(because the message is sent in group) roomId begin with `@@`,

- **ToUserName**
bot's contact name'

- **MsgType** 
message type, full list of rich content please click [here](https://github.com/Chatie/wechaty/wiki/API#messagetype-msgtype "here")

- **Content**
message content, it maybe rich content, and Content has @id prefix added by wx

- **CreateTime**
send time

- **VoiceLength** 
something to descript voiceLength, it shows in angular2: `ng-style="{'width':40 + 7*message.VoiceLength/1000}`

- **FileName** 
if one send file via wechaty, it will return fileName, something like `test.pdf`

- **AppMsgType**  
MsgType == MSGTYPE_APP && message.AppMsgType == CONF.APPMSGTYPE_ATTACH

- **MMIsChatRoom**
check whether message is form room, return boolean

- **MMActualContent**
message content

- **MMActualContent**
 the real message sender's id (the contact's contactID who send this message)

### useful code in [message.ts](https://github.com/Chatie/wechaty/blob/master/src/message.ts) to explain rawObj

``` ts
export type MsgRawObj = {
  MsgId:            string,

  MMActualSender:   string, // getUserContact(message.MMActualSender,message.MMPeerUserName).isContact()
  MMPeerUserName:   string, // message.MsgType == CONF.MSGTYPE_TEXT && message.MMPeerUserName == 'newsapp'
  ToUserName:       string,
  MMActualContent:  string, // Content has @id prefix added by wx

  MMDigest:         string,
  MMDisplayTime:    number,  // Javascript timestamp of milliseconds

  /**
   * MsgType == MSGTYPE_APP && message.AppMsgType == CONF.APPMSGTYPE_URL
   * class="cover" mm-src="{{getMsgImg(message.MsgId,'slave')}}"
   */
  Url:              string,
  MMAppMsgDesc:     string,  // class="desc" ng-bind="message.MMAppMsgDesc"

  /**
   * Attachment
   *
   * MsgType == MSGTYPE_APP && message.AppMsgType == CONF.APPMSGTYPE_ATTACH
   */
  FileName:         string,  // FileName: '钢甲互联项目BP1108.pdf',
  FileSize:         number,  // FileSize: '2845701',
  MediaId:          string,  // MediaId: '@crypt_b1a45e3f_c21dceb3ac01349...

  MMAppMsgFileExt:      string,  // doc, docx ... 'undefined'?
  MMAppMsgFileSize:     string,  // '2.7MB',
  MMAppMsgDownloadUrl:  string,  // 'https://file.wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetmedia?sender=@4f549c2dafd5ad731afa4d857bf03c10&mediaid=@crypt_b1a45e3f
                                 // <a download ng-if="message.MMFileStatus == CONF.MM_SEND_FILE_STATUS_SUCCESS
                                 // && (massage.MMStatus == CONF.MSG_SEND_STATUS_SUCC || massage.MMStatus === undefined)
                                 // " href="{{message.MMAppMsgDownloadUrl}}">下载</a>
  MMUploadProgress: number,  // < 100

  /**
   * 模板消息
   * MSGTYPE_APP && message.AppMsgType == CONF.APPMSGTYPE_READER_TYPE
   *  item.url
   *  item.title
   *  item.pub_time
   *  item.cover
   *  item.digest
   */
  MMCategory:       any[],  //  item in message.MMCategory

  /**
   * Type
   *
   * MsgType == CONF.MSGTYPE_VOICE : ng-style="{'width':40 + 7*message.VoiceLength/1000}
   */
  MsgType:          number,
  AppMsgType:       AppMsgType,  // message.MsgType == CONF.MSGTYPE_APP && message.AppMsgType == CONF.APPMSGTYPE_URL
                                 // message.MsgType == CONF.MSGTYPE_TEXT && message.SubMsgType != CONF.MSGTYPE_LOCATION

  SubMsgType:       MsgType, // "msgType":"{{message.MsgType}}","subType":{{message.SubMsgType||0}},"msgId":"{{message.MsgId}}"

  /**
   * Status-es
   */
  Status:           string,
  MMStatus:         number,  // img ng-show="message.MMStatus == 1" class="ico_loading"
                             // ng-click="resendMsg(message)" ng-show="message.MMStatus == 5" title="重新发送"
  MMFileStatus:     number,  // <p class="loading" ng-show="message.MMStatus == 1 || message.MMFileStatus == CONF.MM_SEND_FILE_STATUS_FAIL">
                             // CONF.MM_SEND_FILE_STATUS_QUEUED, MM_SEND_FILE_STATUS_SENDING

  /**
   * Location
   */
  MMLocationUrl:    string,  // ng-if="message.MsgType == CONF.MSGTYPE_TEXT && message.SubMsgType == CONF.MSGTYPE_LOCATION"
                             // <a href="{{message.MMLocationUrl}}" target="_blank">
                             // 'http://apis.map.qq.com/uri/v1/geocoder?coord=40.075041,116.338994'
  MMLocationDesc:   string,  // MMLocationDesc: '北京市昌平区回龙观龙腾苑(五区)内(龙腾街南)',

  /**
   * MsgType == CONF.MSGTYPE_EMOTICON
   *
   * getMsgImg(message.MsgId,'big',message)
   */

  /**
   * Image
   *
   *  getMsgImg(message.MsgId,'slave')
   */
  MMImgStyle:       string,  // ng-style="message.MMImgStyle"
  MMPreviewSrc:     string,  // message.MMPreviewSrc || message.MMThumbSrc || getMsgImg(message.MsgId,'slave')
  MMThumbSrc:       string,

  /**
   * Friend Request & ShareCard ?
   *
   * MsgType == CONF.MSGTYPE_SHARECARD" ng-click="showProfile($event,message.RecommendInfo.UserName)
   * MsgType == CONF.MSGTYPE_VERIFYMSG
   */
  RecommendInfo?:   RecommendInfo,
}

```

**Comment by zixia** [comment]
Is there any progress/milestones update for the dashbot.io integration?

**Comment by sinned** [comment]
Yes! We added conversationId to our Generic implementation now:
https://www.dashbot.io/docs/generic/rest

When we launch the wechat integration, it will use the same JSON payload as Generic, with platform=wechat in the API call instead.

Does that make sense?

**Comment by zixia** [comment]
Awesome! Do you have any examples on dashbot website? I'd like to have a try.

Cheers!

**Comment by zixia** [comment]
See: https://github.com/Chatie/blog/issues/52
