### ISSUE TITLE
[Upgrade to v0.5] Convert code base to Typescript from Javascript

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#40]
It's in my mind for months. 
- [x] rename `.js` to `.ts`
- [x] setup `tsconfig.json`
- [x] fix `tsc` error
- [x] fix `tslint` error
- [x] run `examples/*-bot.ts` & fix
- [x] hacking `ava` to support run `typescript` natively by adding a `--ext ts` arg
- [x] run `tests/**/*.spec.ts` & fix

Typescript will benefit us as the following:
1. ~~enable circular dependency between modules~~
2. better async coding style: `async`/`await` (now we use `co` module)
3. strong type definition/checking for data structure
4. auto completion/static syntax check with vscode ide
5. static variable with initializing inside class
6. public/private setting for methods/member variables
7. other benefits...

after converted, there will be different if you:
1. use the master code base directly. solution: use `ts-node` instead of `node`, and write your code with `typescript`.
2. study typescript and setup typescript environment.

there will be no different if you:
- use npm module to `require('wechaty')`. you can use javascript as before because typescript will be compiled to javascript before publish.

The lastest javascript version is: [v0.4.0](https://github.com/wechaty/wechaty/releases/tag/v0.4.0)

### Reference

1. [The Future of Declaration Files](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)
2. [What's new in TypeScript](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript)
3. [export default can lead to problems](https://basarat.gitbooks.io/typescript/content/docs/tips/defaultIsBad.html)

**Comment by Samurais** [comment]
A nice slide about TypeScript
http://git.oschina.net/rockq/node-party/blob/master/archieves/5th/Angular_TypeScript.pdf

**Comment by zixia** [comment]
https://github.com/wechaty/wechaty/commit/b54bfbafbe0f64f80b1f9937635278319d84a66a
https://github.com/wechaty/wechaty/commit/dec557b8b79b967e76c884419d178e929b17f162
https://github.com/wechaty/wechaty/commit/12d491d170dccebeb108bb6fdae0f59b353cb795
https://github.com/wechaty/wechaty/commit/3917e703c7a330b5a9427c87810cd29cd2af50cf
https://github.com/wechaty/wechaty/commit/aa98e45a55fe1c623af6360d3ccd2e27daefb4b4
https://github.com/wechaty/wechaty/commit/5787f6dad515cbb304b19e0414b99fe734657e2c
https://github.com/wechaty/wechaty/commit/195d11eefd6befaf4c79e595687dd0a6717509ab

**Comment by zixia** [comment]
almost last step: tsc with `@types` https://github.com/Microsoft/TypeScript/issues/11491

**Comment by zixia** [comment]
this is caused by a bug of typescript : https://github.com/Microsoft/TypeScript/issues/11103 , could be fixed by add `--moduleResolution node`

**Comment by zixia** [comment]
stucked with a strange behaviour of ts-node : https://github.com/TypeStrong/ts-node/issues/216

**Comment by zixia** [comment]
unit tests need to convert, too...

**Comment by zixia** [comment]
Could Typescript save us from circular denpendence module undefined problem? https://github.com/Microsoft/TypeScript/issues/11576

**Comment by zixia** [comment]
<img width="646" alt="screen shot 2016-10-25 at 00 17 03" src="https://cloud.githubusercontent.com/assets/1361891/19656832/2173fe2c-9a54-11e6-932c-58a627356925.png">

cheers!

**Comment by zixia** [comment]
all done!

**Comment by zixia** [comment]
today, all tests passed in CI , and with docker!

cheers!

**Comment by zixia** [comment]
Due to [export default can lead to problems](https://basarat.gitbooks.io/typescript/content/docs/tips/defaultIsBad.html), delete all the `export default` in wechaty.

so from now, we must use `import { Wechaty } from 'wechaty'` instead of `import Wechaty from 'wechaty'`.

**Comment by zixia** [comment]
Prepare send TypeScript Support Pull Request to AVA:
https://github.com/avajs/ava/issues/1109
