### ISSUE TITLE
[puppet] Android Puppet will let us do more than Web Puppet

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#400]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=43928763)](https://www.bountysource.com/issues/43928763-puppet-android-puppet-will-let-us-do-more-than-web-puppet?utm_source=43928763&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Wechat Web version has many limitations, including:

1. can not delete contact
1. can not set alias in a room
1. can not open Red Envelopes(红包)
1. can not open Room Invitation(群邀请)
1. can not add Contact by Wechat Id
1. can not post/read Moments(朋友圈)
1. etc...

Currently, Wechaty is using PuppetWeb to control Wechat, which is based on Wechat Web. So Wechaty is not able to do those jobs.

If we want to do those jobs in the future, then we need to consider to add a PuppetAndroid to Wechaty.

### See Also

* [Wiki:Puppet](https://github.com/Chatie/wechaty/wiki/Puppet)
* [微信App通信协议案例学习参考指南 @h4dex](https://blog.chatie.io/wechat-protocol-reference-guide/)

Any suggestion / discusstion / contribution is welcome.

**Comment by jy03078959** [comment]
When will the plan begin?

**Comment by zixia** [comment]
The plan is still in TBD stage.

PuppetAndroid will be complicated and need a lot working on it. Hope there will be someone who is familiar with Android platform to kick off this plan.

**Comment by jy03078959** [comment]
thanks ,i see

**Comment by heekah7** [comment]
Please let me know if you needed help.

**Comment by zixia** [comment]
@heekah7 We still have not got any progress on it.

You may have a look at this repository: https://github.com/lijiarui/xposed-wechat , which is a demo that uses Xposed to control Wechat app, but I have no time to look at it yet.

If you want to help, the best way is to provide a run-able repository that demo your control.

**Comment by imWildCat** [comment]
Recently I found a brilliant Android library to hook WeChat: https://github.com/Gh0u1L5/WechatSpellbook

In addition, there is also a great way to use Xposed without rooting the system:
https://github.com/android-hacker/VirtualXposed 
It works similar to a mini virtual machine on Android.

Best regards.
