### ISSUE TITLE
webdrive login always occur error, for one success login always cost 4-5 log trys

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#42]
running the same code , the error below appears:

![image](https://cloud.githubusercontent.com/assets/6419514/19228457/100fae22-8ef8-11e6-9c81-b19a902ca6f9.png)

trying to log in will cost 4-5 times log error  each time, then can login successfully

I opened LOG, run the code with WECHATY_LOG=silly, log as follows and stop:
![image](https://cloud.githubusercontent.com/assets/6419514/19229467/60ea466a-8f00-11e6-907b-eef36ea8d427.png)

![image](https://cloud.githubusercontent.com/assets/6419514/19229736/71c1441e-8f02-11e6-8270-79ffd1988fe4.png)

**Comment by zixia** [comment]
Wechaty sometimes hang because there's something strange happened between browser and wx.qq.com. 

and i know there indeed have bug inside the watchdog, that's why i'm planing to rewrite part of those code.

but it should not happen much.

have there any other guys ran into this same issue?

**Comment by lijiarui** [comment]
when the bot log out ,the log seems like this:


INFO Bot wuli舞哩 logouted
WARN PuppetWebBrowser execute() exception: no such session
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6)
WARN PuppetWebBrowser dead() because deadEx() found dead browser coz 1+1 = no such session
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
WARN PuppetWebBrowser quit() exception: no such session
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
WARN PuppetWebBrowser driver.quit() exception: no such session
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
WARN PuppetWebEvent onBrowserDead() will not init browser because browser.targetState(close) !== open

**Comment by zixia** [comment]
this is most because chrome window crashed. (or is closed by you)

`uppetWebBrowser execute() exception: no such session` means browser session had gone, so wechaty have to re-birth it.

**Comment by zixia** [comment]
it seems no more availble information for this question, so I'll close it.

please feel free to re-open this issue if you could re-produce this problem, and provide more useful information.
