### ISSUE TITLE
element_wrong----contact.get('name') got room name not contact name

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#43]
when I use Message Event as follows:

> .on('message', m => {
>   m.ready()
>   .then(msg => {
>     const contact  = m.from()
> 

the event happens in the chatroom

 I use Class Contact function as follows:

> contact.get('name')

refer your document:
https://github.com/wechaty/wechaty#class-contact

but I got the room name not the contact name.

I print contact, the log as follows:

> Contact {
>   id: '@@c728bd50281d791a174968892264afb04abb9d845e00c1e919274ccaff6bcb41',
>   obj: 
>    { id: '@@c728bd50281d791a174968892264afb04abb9d845e00c1e919274ccaff6bcb41',
>      uin: 0,
>      weixin: '',
**      name: 'test1',**

while, when i use the same function not in room, all the things works well
I print contact, the log as follows:

> Contact {
>   id: '@3ed374e169fd41e4f809bc1784967f80',
>   obj: 
>    { id: '@3ed374e169fd41e4f809bc1784967f80',
>      uin: 0,
>      weixin: 'ruirui_0914',
>      name: '芮芮',

I guess the element you define in the Contact when in a room may wrong.

thanks

**Comment by lijiarui** [comment]
when msgType=10000 means the message type is sys, sender.name is the room name

**Comment by zixia** [comment]
so it should makes sense because a sys message could send from `room`?

**Comment by lijiarui** [comment]
because a sys message send from room, so contact.name got the room topic. it seems make sence...

but if a sys message send from room, contact.name = SYS seems more easy to understand
