### ISSUE TITLE
function sendMessage error

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#44]
hi，

I use function sendMessage after accept friend request,
when the new friend request and the bot not in the same network, the program stopped and has error.

while if the new friend request and the bot are in the same network, it can work well

error log as follows:

> WARN PuppetWebBrowser execute() exception: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver 
> WARN PuppetWebBridge execute() exception: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
> WARN PuppetWebBridge proxyWechaty() exception: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
> ERR PuppetWebBridge send() exception: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
> ERR PuppetWeb send() exception: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
> ERR Wechaty send() exception: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
> /Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/promise.js:2291
>         throw error;
>         ^
> 
> WebDriverError: unknown error: r.isBrandContact is not a function
>   (Session info: chrome=53.0.2785.143)
>   (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64)
>     at WebDriverError (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
>     at Object.checkLegacyResponse (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
>     at parseHttpResponse (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/http.js:398:13)
>     at doSend.then.response (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/http.js:330:11)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> From: Task: WebDriver.executeScript()
>     at Driver.schedule (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
>     at Driver.executeScript (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:563:16)
>     at Browser.execute (/Users/lijiarui/git/wechaty/src/puppet-web/browser.js:437:38)
>     at Bridge.execute (/Users/lijiarui/git/wechaty/src/puppet-web/bridge.js:346:32)
>     at execute.then.then (/Users/lijiarui/git/wechaty/src/puppet-web/bridge.js:332:19)
>     at ManagedPromise.invokeCallback_ (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/promise.js:1303:14)
>     at TaskQueue.execute_ (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/promise.js:2731:14)
>     at TaskQueue.executeNext_ (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/promise.js:2714:21)
>     at asyncRun (/Users/lijiarui/git/wechaty/node_modules/selenium-webdriver/lib/promise.js:2584:27)

before use sendMessage,  the log shows, the parameter isn't null

> INFO Bot sendMessage(Class Wechaty(web), {content: hi，我是桔子蜜，最好用的微信群助手，回复1，加入测试1群，回复2，加入测试2群, to: @323bce54d6559e43a712796d14340d68, room: null})

**Comment by zixia** [comment]
sendMessage is not a api. it just a demo in example, and it had already deprecated.

please use `Room.say()` / `Message.say()` / `this.say()` instead.

**Comment by zixia** [comment]
another tip: 

after `request.accept()`, the `request.contact` might not ready(yet).

you can try to check if contact data is full loaded. if not, wait 3s and call `contact.ready()`, then check & try again.

**Comment by lijiarui** [comment]
thanks! 

After I use bot.send and use message.ready(), it works well
because I use sendMessage you gave in the example, which  doesn't ready（）, so the bug occurred.

but when I test the bot.send, i found the doc you gave may revise:


```
Message.get(prop): String|Contact|Room|Date

Get prop from a message.

Supported prop list:

id :String
from :Contact
to :Contact
content :String
room :Room
date :Date
```

from :Contact
to :Contact

should change to:

from :String
to :String

because， when I use message.set('to', contact), bug occurred but I use   message.set('to', contact.id) all works well.

**Comment by zixia** [comment]
yes, the doc is out dated.

I suggest you to use the new `say()` methods:

1. `Message.say(content: string)`
1. `Room.say(content: string, replyTo: Contact)`

instead of `Wechaty.send()`

and when you have to create a Message manualy, better to use

1. `Message.from(contact: Contact)`
1. `Message.to(contact: Contact)`
1. `Message.content(content: string)`

instead of `Message.set(...)`, because they work better.
