### ISSUE TITLE
Suggest give an api to get url

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#45]
hi
I want to get url in Message, I print message and find url in Message.rawOby.Url. But i can't use m.rawObj.Url to get Url

than  I use (m.rawObj as any).Url to get Url

I suggest you can give an api for us to get Url if you have time.

thanks!

**Comment by zixia** [comment]
added by https://github.com/wechaty/wechaty/commit/71f0594535ad837d8c5369924e057d82942459b5

**Comment by zixia** [comment]
there still no plan to create a api for this, because this is for a specific type message. maybe in the future.

future suggestion is very welcome. thanks.
