### ISSUE TITLE
test/fix Watchdog with browser dead & timeout conditions

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#47]
- [x] browser be killed during init
- [x] browser be killed after init
- [ ] WechatyBro injection fail
- [ ] WechatyBro init() fail
- [ ] WechatyBro heartbeat lost
- [ ] Wx App died during scan/login(not fire events any more)
- [ ] Wx App died after scan/login(not fire events any more)

etc...

**Comment by sjdy521** [comment]
关注了很久，有个问题一直不明白，这个项目是一定要在浏览器里运行吗？一定要开浏览器？为什么不设计成独立运行的微信程序


发自网易邮箱大师
On 10/15/2016 11:02, Zhuohuan LI wrote:

[ ] browser be killed during init
[ ] browser be killed after init
[ ] WechatyBro injection fail
[ ] WechatyBro init() fail
[ ] WechatyBro heartbeat lost
[ ] Wx App died during scan/login(not fire events any more)
[ ] Wx App died after scan/login(not fire events any more)
etc...

**Comment by sjdy521** [comment]
我同时也关注了类似的其他项目，有java的，有python的，等等


之所以保持关注，主要有几点：
1. 关注别的项目的更新情况 随时掌握腾讯官方的改动
2. 关注别的项目的issue 了解用户的使用需求
3. 关注别的项目的软件框架，代码风格，函数封装形式等，作为一个非开发出身的产品工程师，这方面没有从事专业的训练 比较弱:-)
4. 尤其关注nodejs项目，因为在我看来，模拟web微信的功能 基于javascript是最为理想的语言，尤其是phantomjs的应用 、“hack in browser”这种技术 我也一直很想学习 但是很不幸的我一开始选择了perl语言相对比较冷门，要重新移植到javascript上是比较耗费精力的 实在没动力


发自网易邮箱大师
在2016年10月16日 00:05，Zhuohuan LI 写道:

@sjdy521 wechaty是一定在浏览器里面运行的，一定要开浏览器。

没有设计成独立运行程序的原因，是因为我最初写wechaty的目的之一，是为了学习基于 WebDriver 的自动化测试技术。我有在README里面说明的。：）

我看你一直是Perl全栈，可以说说关注Wechaty的原因吗？:P

**Comment by zixia** [comment]
了解了。有没有你觉得很不错的值得关注的其它类似项目，没有被我收集到 README 出面的？

如果有的话可以帮我列一下吗，谢谢啦。

**Comment by sjdy521** [comment]
目前了解到的情况看没有其他更不错的了


发自网易邮箱大师
在2016年10月16日 09:29，Zhuohuan LI 写道:

了解了。有没有你觉得很不错的值得关注的其它类似项目，没有被我收集到 README 出面的？

如果有的话可以帮我列一下吗，谢谢啦。

**Comment by zixia** [comment]
https://github.com/wechaty/wechaty/commit/c106d6488ebeb716676d1c1901f996c3d7d361a7

**Comment by zixia** [comment]
postponed, coz not the priority.
