### ISSUE TITLE
How to Install & Run Wechaty in Linux Server

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#48]
Steps:
	
1.install nvm：

```
curl https://raw.githubusercontent.com/creationix/nvm/v0.11.1/install.sh | bash
```

2.install node
```
nvm install 6
nvm alias default 6
```

3.install git and clone repo

```
sudo apt-get install git
git clone https://github.com/wechaty/wechaty.git
```

4.install google chrome for debian
```
sudo apt-get update
sudo apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb
sudo apt-get install -f
```

5.wechaty operation：
```
cd wechaty
npm install
cd script
bash xvfb.sh
export DISPLAY=':99.0'
```

6.run wechaty：

go back wechaty directory

```
cd example
npm run ts-node example/ding-dong-bot.ts
```

then run wechaty successfuly:

![image](https://cloud.githubusercontent.com/assets/6419514/19425573/97f384e4-9466-11e6-8550-f2771d78439e.png)

**Comment by zixia** [comment]
what's ur DISPLAY env variable?

**Comment by lijiarui** [comment]
is this one?

> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "/root/.nvm/v6.8.1/bin/node" "/root/.nvm/v6.8.1/bin/npm" "run" "ts-node" "example/ding-dong-bot.ts"
> npm ERR! node v6.8.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! wechaty@0.4.0 ts-node: `ts-node "example/ding-dong-bot.ts"`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the wechaty@0.4.0 ts-node script 'ts-node "example/ding-dong-bot.ts"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the wechaty package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node "example/ding-dong-bot.ts"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs wechaty
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls wechaty
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/git/wechaty/example/npm-debug.log

**Comment by lijiarui** [comment]
the variable as follows

```
Set DISPLAY to :99.0
Xvfb started
to set env, run $ export DISPLAY=':99.0'
Xvfb ready
```

then i run

```
export DISPLAY=':99.0'
```

thanks!

**Comment by zixia** [comment]
good job.

1. I believe the step 7(Install ChromeDriver) is not necessary, because it will be installed by `npm install`.
2. if u change step 5(git clone) from `git@github.com:wechaty/wechaty.git` to `https://github.com/wechaty/wechaty.git`, then the step 4(Generating a new SSH key and adding it to the ssh-agent) will be not necessary, too.

can u confirm?

**Comment by lijiarui** [comment]
thanks ！
I tried as you told, it does work!
and then I update the install intro ！

**Comment by plantvsbirds** [comment]
is it possible to put all these into a npm run command? like `npm run install-linux`. that would be sweet.

**Comment by zixia** [comment]
@lijiarui great. you should link this issue in README in order to help others.
@plantvsbirds I agree. pull request is welcome. :)
