### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript src/puppet-web/event.ts (120,12): Type 'PuppetWeb' is not assignable to type 'void'. (2322)

### ISSUE THREAD

**Issue by NNorLand** [wechaty/wechaty#51]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/liujiaan/.nvm/versions/node/v6.7.0/bin/node',
1 verbose cli   '/Users/liujiaan/.nvm/versions/node/v6.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle wechaty@0.4.0~predemo: wechaty@0.4.0
6 silly lifecycle wechaty@0.4.0~predemo: no script for predemo, continuing
7 info lifecycle wechaty@0.4.0~demo: wechaty@0.4.0
8 verbose lifecycle wechaty@0.4.0~demo: unsafe-perm in lifecycle true
9 verbose lifecycle wechaty@0.4.0~demo: PATH: /Users/liujiaan/.nvm/versions/node/v6.7.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/liujiaan/wechaty/node_modules/.bin:/Users/liujiaan/.nvm/versions/node/v6.7.0/bin:/Users/liujiaan/.nvm/versions/node/v6.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/aria2/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
10 verbose lifecycle wechaty@0.4.0~demo: CWD: /Users/liujiaan/wechaty
11 silly lifecycle wechaty@0.4.0~demo: Args: [ '-c', 'ts-node example/ding-dong-bot.ts' ]
12 silly lifecycle wechaty@0.4.0~demo: Returned: code: 1  signal: null
13 info lifecycle wechaty@0.4.0~demo: Failed to exec demo script
14 verbose stack Error: wechaty@0.4.0 demo: `ts-node example/ding-dong-bot.ts`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/liujiaan/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/liujiaan/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid wechaty@0.4.0
16 verbose cwd /Users/liujiaan/wechaty
17 error Darwin 16.0.0
18 error argv "/Users/liujiaan/.nvm/versions/node/v6.7.0/bin/node" "/Users/liujiaan/.nvm/versions/node/v6.7.0/bin/npm" "run" "demo"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error wechaty@0.4.0 demo: `ts-node example/ding-dong-bot.ts`
22 error Exit status 1
23 error Failed at the wechaty@0.4.0 demo script 'ts-node example/ding-dong-bot.ts'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wechaty package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ts-node example/ding-dong-bot.ts
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs wechaty
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls wechaty
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

是我环境有问题吗?刚运行成功了,但是想要再运行api-ai-bot.ts的时候,不知怎么就不行了.重新clone也不行

**Comment by zixia** [comment]
please feel free to re-open this if the issue still there.
