### ISSUE TITLE
在room中通过room.topic()获取不到room的topic

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#55]
当我使用在room中使用 room.topic() 时， 遇见了和#54 同样的bug

#### Wechaty Doctor

1. Wechaty version: #git[dda941b fix #54]
2. Darwin x64 version 15.6.0 memory 4 GB
3. Docker: false

**Comment by zixia** [comment]
can not understand. please provide the detail.

**Comment by zixia** [comment]
please feel free to re-open this issue if you can provide **Steps to reproduce the behavior**. thanks.

**Comment by lijiarui** [comment]
#### Wechaty Doctor

1. Wechaty version: #git[cd7c7dd log for #55]
2. Darwin x64 version 15.6.0 memory 38/4096 MB
3. Docker: false


when I try to get the topic of msgRoom as follows

```
.on('message', m => {
  m.ready()
  .then(msg => {

    const msgRoom = m.room()
    const msgRoomTopic = msgRoom.topic
    console.log(msgRoomTopic)  
    ....
```

then, I can't run wechaty, error log as follows:

> lijiaruideMacBook-Air:orangiss lijiarui$ WCHATY_LOG=silly npm run ts-node orangiss/juzimi.ts
> 
> > wechaty@0.4.0 ts-node /Users/lijiarui/git/wechaty
> > ts-node "orangiss/juzimi.ts"
> 
> 
> /Users/lijiarui/git/wechaty/node_modules/ts-node/src/index.ts:308
>           throw new TSError(diagnosticList)
>                 ^
> TSError: ⨯ Unable to compile TypeScript
> orangiss/juzimi.ts (204,26): Object is possibly 'null'. (2531)
> orangiss/juzimi.ts: Emit skipped
>     at getOutput (/Users/lijiarui/git/wechaty/node_modules/ts-node/src/index.ts:308:17)
>     at /Users/lijiarui/git/wechaty/node_modules/ts-node/src/index.ts:334:18
>     at Object.compile (/Users/lijiarui/git/wechaty/node_modules/ts-node/src/index.ts:488:17)
>     at Module.m._compile (/Users/lijiarui/git/wechaty/node_modules/ts-node/src/index.ts:392:44)
>     at Module._extensions..js (module.js:550:10)
>     at Object.require.extensions.(anonymous function) [as .ts] (/Users/lijiarui/git/wechaty/node_modules/ts-node/src/index.ts:395:12)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Function.Module.runMain (module.js:575:10)
> 
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ts-node" "orangiss/juzimi.ts"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE
> npm ERR! wechaty@0.4.0 ts-node: `ts-node "orangiss/juzimi.ts"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the wechaty@0.4.0 ts-node script 'ts-node "orangiss/juzimi.ts"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the wechaty package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node "orangiss/juzimi.ts"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs wechaty
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls wechaty
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/lijiarui/git/wechaty/orangiss/npm-debug.log


then, I change the code as follows:


```
.on('message', m => {
  m.ready()
  .then(msg => {

    const msgRoom = m.room()
    const msgRoomTopic = (msgRoom as any).topic
    console.log(msgRoomTopic)  
    ....
```

all works well!
