### ISSUE TITLE
Can not start: Runtime.executionContextCreated has invalid 'cont ext'

### ISSUE THREAD

**Issue by zixia** [wechaty/wechaty#56]
yesterday I can not start wechaty under win32 in sudden.

the log is: `WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'cont ext': {"auxData":{"frameId" isDefault":true} ...`

after hours digging, I found out that I was using a out dated `chromedriver`, which can not work any more after I upgrade chrome to v54.

https://github.com/SeleniumHQ/selenium/issues/2614#issuecomment-255293479

**Comment by faminram** [comment]
I am still unable to run tests in chrome though I have the latest chrome drivers. please read the comments here: SeleniumHQ/selenium#2614 (comment)

**Comment by zixia** [comment]
@faminram sorry I have no idea of that after look your issue.

my issue was solved after I deleted the old driver, and specific the node_modules/... driver inside my code. 

you can have a look inside my commit, that solve my issue perfectly.

good luck.
