### ISSUE TITLE
Run wechaty occurs chromedriver is still running and the solution

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#62]
#### Wechaty Doctor

1. Wechaty version: #git[93d1728 doc]
2. Darwin x64 version 15.6.0 memory 146/4096 MB
3. Docker: false

### Expected behavior

run wechaty

### Actual behavior

error log as follows:

> ERR PuppetWeb initBrowser() exception: The previously configured ChromeDriver service is still running. You must shut it down before you may adjust its configuration.
> ERR PuppetWebEvent onBrowserDead() exception: The previously configured ChromeDriver service is still running. You must shut it down before you may adjust its configuration.

### Steps to reproduce the behavior (and fixes, if any)

execute npm install

lijiaruideAir:example lijiarui$ npm install
wechaty@0.4.0 /Users/lijiarui/git/wechaty
├── brolog@0.3.10 
├── typescript@2.0.3 
└── wechat-qrcode@0.1.0  extraneous

├─┬ phantomjs-prebuilt@2.1.13 
│ └── es6-promise@4.0.5 
└── wechat-qrcode@0.1.0  extraneous

and close some program then fix the error

**Comment by zixia** [comment]
this problem is related to https://github.com/wechaty/wechaty/commit/09099fc9f7f20fd3913a005e5d0f72cc4827c2f4#diff-cf58bef97838a4ef74380372d2cb9129L226

**Comment by lijiarui** [comment]
You said "only need under win32 with cygwin"
But I run wechaty under macOs and occur the error..

**Comment by zixia** [comment]
can you provide the way to reproduce the problem? 

or I'll close this issue in 3 days.
