### ISSUE TITLE
在 electron 中使用，打包后，无法启动 wechaty

### ISSUE THREAD

**Issue by cmzz** [wechaty/wechaty#637]
正在开发一个 electron 的项目木，使用到 wechaty.

run dev 可以正常运行，但是， 使用 electron-builder 打包 app 后， wechty 的登录窗口无法打开。

![image](https://user-images.githubusercontent.com/6111715/27966729-ed8072f6-6372-11e7-8245-f4e6eb3ea592.png)

弹出授权框，确定之后并没有打开 chrome 窗口。

求助。谢谢。

**Comment by zixia** [comment]
It will be very interesting when we integrate Wechaty with Electron on Desktop.

We have an electron demo project at here: https://github.com/Chatie/wechaty-electron

However:

1. I'm not sure it will run properly because I have not pay attention at Electron for months, for I'm busying on ML & APP side recently.
1. When I use Wechaty under Electron I mainly using PhantomJS as WECHATY_HEAD, but it seems PhantomJS HEAD had some problems. (Read more at #633 #60 )

So please let me know when you have any new progress, and I'd like to help you in the future when I have time for Electron.

Good luck!

**Comment by cmzz** [comment]
现在我将 head 设置为 phantomjs， 可以运行，暂时未发现重大问题。

我将继续探索在 wechay 在 electron 中的应用，有问题再来报告。另 还有一个比较恼人的问题：无法唯一标记群用户。希望@zixia 能继续去找找解决方案...

非常感谢。

**Comment by zixia** [comment]
@cmzz Amazing, it's a surprise for me that PhantomJS works out-of-box. You are so lucky!

Please let me know if you have any issue with PhantomJS. If it works perfect, I'd like to switch the default HEAD from Chrome to PhantomJS for Wechaty, because it will be easier to setup.

**Comment by cmzz** [comment]
@zixia Ok。

目前正在小范围内测，待到公测没问题后再来反馈😆

**Comment by RamboWu** [comment]
@cmzz @zixia ，我也正在使用electron想做一个定制版的微信，刚刚注意到了wechaty，为什么wechaty每次运行的时候 都会打开chrome浏览器？我可以纯粹使用 http接口加上自己的ui去做一个定制版的微信么？而不是通过 借助 chrome。

**Comment by Zhou-Bill** [comment]
有同样需求 @RamboWu

**Comment by zixia** [comment]
Wechaty is using puppeteer today which is using `headless` mode by default.

Please feel free to share your new progress with us, thanks!

**Comment by shenlanzifa** [comment]
我遇到的同样的问题，执行start的时候出现了错误。
代码为：
```
   bot.start()
        .catch(e => {
            log.error('bot start error:' + e.message)
            bot.stop()
          //  process.exit(-1)
        })
```
日志中显示的错误为：
 bot start error:Failed to launch chrome! spawn E:\NodeProject\webchattest\dist\win-unpacked\resources\app.asar\node_modules\puppeteer\.local-chromium\win64-555668\chrome-win32\chrome.exe ENOENT
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by shenlanzifa** [comment]
我也遇到了这样的问题，使用electron-builder打包之后，wechaty无法启动
wechaty版本为0.14.1  electron 2.0.1

调用start函数的代码为：
```
   bot.start()
        .catch(e => {
            log.error('bot start error:' + e.message)
            bot.stop()
          //  process.exit(-1)
        })
```
日志中显示的错误为
 bot start error:Failed to launch chrome! spawn E:\NodeProject\webchattest\dist\win-unpacked\resources\app.asar\node_modules\puppeteer\.local-chromium\win64-555668\chrome-win32\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by zixia** [comment]
@shenlanzifa Can you run Wechaty basic demo(6 lines bot) under your environment with your current installation?

**Comment by shenlanzifa** [comment]
@zixia 在没有和electron一起用的时候，是可以的。下面的是执行test.js之后的输出
```
E:\NodeProject\webchattest  (webchattest@1.0.0)
$ node test.js
11:12:58 INFO Wechaty v0.14.1 starting...
(node:6676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: rxjs.interval is not a function
(node:6676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Scan QR Code to login: 408
https://login.weixin.qq.com/qrcode/oba_ph2cAQ==
```
test.js的内容：
```
const { Wechaty } = require('wechaty') // import { Wechaty } from 'wechaty'

Wechaty.instance() // Singleton
    .on('scan', (url, code) => console.log(`Scan QR Code to login: ${code}\n${url}`))
    .on('login', user => console.log(`User ${user} logined`))
    .on('message', message => console.log(`Message: ${message}`))
    .start().catch(e => {
       console.log('start error:' + e.message)
    })
```

在和electron一起使用的时候，在vscode下调试的时候是可以的，不过使用electron-builder打包之后再运行程序就会有错误。

**Comment by shenlanzifa** [comment]
@zixia  这是我集成electron时的测试代码：
```
const { app } = require('electron')
const { Wechaty } = require('wechaty')
let log4js = require('log4js')
let logconf = require('./log4js.json')
log4js.configure(logconf)
let log = log4js.getLogger('log_date')

let window;
app.on('ready', () => {
    log.info('start......')
    const { Wechaty } = require('wechaty') // import { Wechaty } from 'wechaty'

    Wechaty.instance() // Singleton
        .on('scan', (url, code) => console.log(`Scan QR Code to login: ${code}\n${url}`))
        .on('login', user => console.log(`User ${user} logined`))
        .on('message', message => console.log(`Message: ${message}`))
        .start().catch(e => {
            log.info('start error:' + e.message)
        })

})
app.on('window-all-closed', () => {
    app.quit()
})
```
使用electron-builder打包之后，运行程序，就会报错 ` start error:Failed to launch chrome!`

**Comment by zixia** [comment]
@shenlanzifa If you can run wechaty with the electron when developing, but can not run it after build, then it seems related to the build process, for example, it does not install the puppeteer right.

We have a repository at https://github.com/Chatie/wechaty-electron which is doing the job of packing the wechaty with the electron.

Could you send a PR to this repository which can reproduce your problem? (or provide a repository with the description in detail)

If so, I could be able to have a look for you into it.

**Comment by shenlanzifa** [comment]
@zixia 我先试一下wechaty-electron，看是否还有问题。非常感谢。。。

**Comment by zixia** [comment]
Good luck, it's a very old project ...

**Comment by travelk** [comment]
> @zixia我先试一下wechaty电子，看是否还有问题。非常感谢...

我也遇到了这个问题了 你解决了么

**Comment by travelk** [comment]
@shenlanzifa

**Comment by travelk** [comment]
打包的时候把asar关闭就可以了

**Comment by LittleCCB** [comment]
@shenlanzifa 请问问题有进展吗？

**Comment by LittleCCB** [comment]
我解决了electron打包后wechaty不能启动的问题
可以参考我的仓库 https://github.com/LittleCCB/wx-bot-client

原理是通过重写wechaty-wechat包中puppeteer的启动方式实现
