### ISSUE TITLE
Can't get the demo running..

### ISSUE THREAD

**Issue by sleedata** [wechaty/wechaty#65]
### Run `npm run doctor` and paste the output here
1. Wechaty version: #git[24bf66a code clean]
2. Linux x64 version 4.4.19-29.55.amzn1.x86_64 memory 682/995 MB
3. Docker: true
### Expected behavior

Please help.

When I ran npm run demo, I got the following errors:
error Linux 4.4.19-29.55.amzn1.x86_64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "demo"
19 error node v6.9.1
20 error npm v3.10.9
21 error code ELIFECYCLE
22 error wechaty@0.5.0 demo: `ts-node example/ding-dong-bot.ts`
22 error Exit status 255
23 error Failed at the wechaty@0.5.0 demo script 'ts-node example/ding-dong-bot.ts'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wechaty package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error ts-node example/ding-dong-bot.ts
23 error You can get information on how to open an issue for this project with:
23 error npm bugs wechaty
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls wechaty
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by zixia** [comment]
It seems you are use wechaty inside docker.

docker is great, but will need you extra setup, if you are not use the official wechaty docker image.

first question: had you run `npm install`?

if not, please read README first, it will be helpful and save your time.

**Comment by sleedata** [comment]
Yes, i did npm install. I install from GitHub.

**Comment by zixia** [comment]
hi, @sleedata , as you are using docker, could you have a try to use wechaty docker?

```shell
docker run -t -i --rm zixia/wechaty run demo
```

that should be run without problem.

then you can have a look of Dockerfile of wechaty.

also, see issue #66 for how to use wechaty docker(in pre-alpha stage).

please let me know what you think, thanks.

**Comment by zixia** [comment]
@sleedata please feel free to re-open this issue if you still experience any problem with the wechaty demo.
