### ISSUE TITLE
在cloud9中运行wechaty报错

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#67]
steps:

1.click the button you gave in readme to open in cloud9

2.install node in cloud9:

```
curl https://raw.githubusercontent.com/creationix/nvm/v0.11.1/install.sh | bash
nvm install 6
sudo apt-get update
```

3.run wechaty:

```
npm install
npm run demo
```

encounter following error message：

> INFO Wechaty v#git[461dc84 code clean] initializing...
> WARN PuppetWebBrowserDriver getChromeDriver() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64), retry ttl: 2
> WARN PuppetWebBrowserDriver getChromeDriver() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64), retry ttl: 1
> WARN PuppetWebBrowserDriver getChromeDriver() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64), retry ttl: 0
> ERR PuppetWebBrowserDriver getChromeDriver() exception: WebDriverError: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
>     at WebDriverError (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/error.js:27:5)
>     at Object.checkLegacyResponse (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/error.js:505:15)
>     at parseHttpResponse (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/http.js:398:13)
>     at doSend.then.response (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/http.js:330:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> From: Task: WebDriver.createSession()
>     at Function.createSession (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
>     at Driver (/home/ubuntu/workspace/node_modules/selenium-webdriver/chrome.js:716:38)
>     at Builder.build (/home/ubuntu/workspace/node_modules/selenium-webdriver/index.js:554:16)
>     at BrowserDriver.<anonymous> (/home/ubuntu/workspace/src/puppet-web/browser-driver.ts:125:24)
>     at throw (native)
>     at rejected (/home/ubuntu/workspace/src/puppet-web/browser-driver.ts:5:62)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7), retry ttl: -1
> ERR PuppetWebBrowser init() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
> WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
> ERR PuppetWeb initBrowser() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR PuppetWeb init() exception: WebDriverError: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
>     at WebDriverError (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/error.js:27:5)
>     at Object.checkLegacyResponse (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/error.js:505:15)
>     at parseHttpResponse (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/http.js:398:13)
>     at doSend.then.response (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/http.js:330:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> From: Task: WebDriver.createSession()
>     at Function.createSession (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
>     at Driver (/home/ubuntu/workspace/node_modules/selenium-webdriver/chrome.js:716:38)
>     at Builder.build (/home/ubuntu/workspace/node_modules/selenium-webdriver/index.js:554:16)
>     at BrowserDriver.<anonymous> (/home/ubuntu/workspace/src/puppet-web/browser-driver.ts:125:24)
>     at throw (native)
>     at rejected (/home/ubuntu/workspace/src/puppet-web/browser-driver.ts:5:62)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> WARN PuppetWeb quit() without a bridge
> WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
> WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
> ERR Wechaty init() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR Bot init() fail: WebDriverError: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> WARN PuppetWeb quit() without a bridge
> 
> npm ERR! Linux 4.2.0-c9
> npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/npm" "run" "demo"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! wechaty@0.5.0 demo: `ts-node example/ding-dong-bot.ts`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the wechaty@0.5.0 demo script 'ts-node example/ding-dong-bot.ts'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the wechaty package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node example/ding-dong-bot.ts
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs wechaty
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls wechaty
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/workspace/npm-debug.log
> 

then I tried following steps to install:

1.I thought maybe I didn't install google-chrome, then I test as follows:

```
lijiarui:~/workspace (master) $ google-chrome --version
bash: google-chrome: command not found
```

then , I run your script: "install-chrome-linux.sh "

```
lijiarui:~/workspace/script (master) $ bash install-chrome-linux.sh 
...
Building dependency tree       
Reading state information... Done
E: Unable to locate package google-chrome-stable
install-chrome-linux.sh: line 12: google-chrome: command not found
```

It seems I failed to install chrome, then I tried following steps to install chrome:

```
sudo apt-get update
sudo apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb
sudo apt-get install -f
```

It seems success:

```
lijiarui:~/workspace/script (master) $ google-chrome --version
Google Chrome 54.0.2840.71 
```

then " npm run demo"

occurs the same  I have showed above...

2.I guess maybe  I should set headless right for Xvfb
then I run your script "xvfb.sh " 

```
lijiarui:~/workspace/script (master) $ bash xvfb.sh 
...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Xvfb installed
export DISPLAY=:99.0
Xvfb started

export DISPLAY=:99.0
Xvfb ready.
lijiarui:~/workspace/script (master) $ export DISPLAY=:99.0
```

then " npm run demo"

occurs the same  I have showed above...

At last  I open the log to run demo , error log as follows:

> SILL StateMonitor constructor(Wechaty, standby)
> VERB Wechaty contructor()
> VERB Wechaty on(login, function)
> VERB Wechaty on(logout, function)
> VERB Wechaty on(error, function)
> VERB Wechaty on(scan, function)
> VERB Wechaty on(message, function)
> INFO Wechaty v#git[461dc84 code clean] initializing...
> VERB Wechaty puppet: web
> VERB Wechaty head: chrome
> VERB Wechaty profile: demo.wechaty.json
> VERB Wechaty uuid: 9720caa0-ddd2-4828-8f54-c112c95f0de2
> SILL StateMonitor Wechaty.state.current() is standby
> SILL StateMonitor constructor(Puppet, dead)
> VERB PuppetWeb init() with head:chrome, profile:demo.wechaty.json
> VERB StateMonitor Puppet.state.target(live) from dead
> VERB StateMonitor Puppet.state.current(live,false) from (dead,true)
> VERB UtilLib getPort(18788)
> VERB UtilLib getPort(18788) return: 19103
> VERB PuppetWeb init() getPort 19103
> VERB PuppetWeb initServer()
> SILL StateMonitor Puppet.state.target() is live
> VERB PuppetWebServer init() on port 19103
> VERB PuppetWebServer createHttpsServer() listen on port 19103
> VERB PuppetWeb initServer() done
> VERB PuppetWeb initBrowser()
> SILL StateMonitor constructor(Browser, close)
> VERB PuppetWebBrowser constructor() with head(chrome) sessionFile(demo.wechaty.json)
> VERB PuppetWebBrowserDriver constructor(chrome)
> VERB PuppetWebBrowserCookie constructor(BrowserDriver, demo.wechaty.json)
> SILL StateMonitor Puppet.state.target() is live
> VERB StateMonitor Browser.state.target(open) from close
> VERB StateMonitor Browser.state.current(open,false) from (close,true)
> VERB PuppetWebBrowserDriver init() for head: chrome
> VERB PuppetWebBrowserDriver getChromeDriver()
> VERB PuppetWebBrowserDriver getChromeDriver() wechaty in docker confirmed(should not show this in CI)
> VERB PuppetWebBrowserDriver getChromeDriver() with ttl: 2
> SILL PuppetWebBrowserDriver valid()
> WARN PuppetWebBrowserDriver getChromeDriver() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64), retry ttl: 2
> VERB PuppetWebBrowserDriver getChromeDriver() with ttl: 1
> SILL PuppetWebBrowserDriver valid()
> WARN PuppetWebBrowserDriver getChromeDriver() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64), retry ttl: 1
> VERB PuppetWebBrowserDriver getChromeDriver() with ttl: 0
> SILL PuppetWebBrowserDriver valid()
> WARN PuppetWebBrowserDriver getChromeDriver() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64), retry ttl: 0
> ERR PuppetWebBrowserDriver getChromeDriver() exception: WebDriverError: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
>     at WebDriverError (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
>     at Object.checkLegacyResponse (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
>     at parseHttpResponse (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/http.js:398:13)
>     at doSend.then.response (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/http.js:330:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> From: Task: WebDriver.createSession()
>     at Function.createSession (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
>     at Driver (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/chrome.js:716:38)
>     at Builder.build (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/index.js:554:16)
>     at BrowserDriver.<anonymous> (/home/ubuntu/workspace/wechaty/src/puppet-web/browser-driver.ts:125:24)
>     at throw (native)
>     at rejected (/home/ubuntu/workspace/wechaty/src/puppet-web/browser-driver.ts:5:62)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7), retry ttl: -1
> ERR PuppetWebBrowser init() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> VERB StateMonitor Browser.state.current(close,true) from (open,false)
> VERB PuppetWebBrowser quit()
> SILL StateMonitor Browser.state.current() is close
> SILL StateMonitor Browser.state.inprocess() is false
> VERB StateMonitor Browser.state.current(close,false) from (close,true)
> WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
> WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
> VERB StateMonitor Browser.state.current(close,true) from (close,false)
> ERR PuppetWeb initBrowser() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR PuppetWeb init() exception: WebDriverError: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
>     at WebDriverError (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
>     at Object.checkLegacyResponse (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
>     at parseHttpResponse (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/http.js:398:13)
>     at doSend.then.response (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/http.js:330:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> From: Task: WebDriver.createSession()
>     at Function.createSession (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
>     at Driver (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/chrome.js:716:38)
>     at Builder.build (/home/ubuntu/workspace/wechaty/node_modules/selenium-webdriver/index.js:554:16)
>     at BrowserDriver.<anonymous> (/home/ubuntu/workspace/wechaty/src/puppet-web/browser-driver.ts:125:24)
>     at throw (native)
>     at rejected (/home/ubuntu/workspace/wechaty/src/puppet-web/browser-driver.ts:5:62)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> VERB PuppetWeb quit()
> SILL StateMonitor Puppet.state.current() is live
> SILL PuppetWebWatchdog onFeed: 60000, POISON:[PuppetWeb.quit()]
> SILL StateMonitor Puppet.state.current() is live
> SILL PuppetWebWatchdog clearWatchDogTimer() nothing to clear
> SILL PuppetWebWatchdog setWatchDogTimer(60000, POISON:[PuppetWeb.quit()])
> SILL PuppetWebWatchdog monitorScan(POISON)
> SILL PuppetWebWatchdog autoSaveSession()
> SILL PuppetWebWatchdog memoryCheck() free: 4209 MB, require: 16 MB
> SILL PuppetWebWatchdog clearWatchDogTimer() [60] seconds left
> VERB StateMonitor Puppet.state.current(dead,false) from (live,false)
> WARN PuppetWeb quit() without a bridge
> VERB PuppetWebServer quit()
> VERB PuppetWebServer closing socketServer
> VERB PuppetWebServer closing httpsServer
> VERB PuppetWeb quit() server.quit() this.server = null
> VERB PuppetWebBrowser quit()
> SILL StateMonitor Browser.state.current() is close
> SILL StateMonitor Browser.state.inprocess() is false
> VERB StateMonitor Browser.state.current(close,false) from (close,true)
> WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefined
> WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of undefined
> VERB StateMonitor Browser.state.current(close,true) from (close,false)
> VERB PuppetWeb quit() server.quit() this.browser = null
> VERB StateMonitor Puppet.state.current(dead,true) from (dead,false)
> VERB PuppetWeb quit() done
> VERB StateMonitor Puppet.state.current(dead,true) from (dead,true)
> ERR Wechaty init() exception: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR Bot init() fail: WebDriverError: unknown error: no chrome binary at /wechaty/bin/xvfb-chromium
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> VERB Wechaty quit()
> VERB StateMonitor Wechaty.state.current(standby,true) from (standby,true)
> VERB PuppetWeb quit()
> SILL StateMonitor Puppet.state.current() is dead
> SILL StateMonitor Puppet.state.inprocess() is false
> SILL PuppetWebWatchdog onFeed: 60000, POISON:[PuppetWeb.quit()]
> SILL StateMonitor Puppet.state.current() is dead
> SILL StateMonitor Puppet.state.inprocess() is false
> SILL PuppetWebWatchdog clearWatchDogTimer() nothing to clear
> SILL PuppetWebWatchdog setWatchDogTimer(60000, POISON:[PuppetWeb.quit()])
> SILL PuppetWebWatchdog monitorScan(POISON)
> SILL PuppetWebWatchdog autoSaveSession()
> SILL PuppetWebWatchdog memoryCheck() free: 4208 MB, require: 16 MB
> SILL PuppetWebWatchdog clearWatchDogTimer() [60] seconds left
> VERB StateMonitor Puppet.state.current(dead,false) from (dead,true)
> WARN PuppetWeb quit() without a bridge
> VERB PuppetWebServer quit()
> 
> npm ERR! Linux 4.2.0-c9
> npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/npm" "run" "ts-node" "example/ding-dong-bot.ts"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! wechaty@0.5.0 ts-node: `ts-node "example/ding-dong-bot.ts"`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the wechaty@0.5.0 ts-node script 'ts-node "example/ding-dong-bot.ts"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the wechaty package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node "example/ding-dong-bot.ts"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs wechaty
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls wechaty
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/workspace/wechaty/script/npm-debug.log
> 

Need your help badly....
Thanks..

**Comment by lijiarui** [comment]
Thanks, I can run several times, then ,occur another error:

log as follows:


> INFO Wechaty v#git[2a71d33 fix #67 not run in `docker mode` in cloud9 ide] initializing...
> ERR PuppetWebBrowser open() exception: unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed
>   (Session info: chrome=54.0.2840.71)
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR PuppetWebBrowser init() exception: unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed
>   (Session info: chrome=54.0.2840.71)
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR PuppetWeb initBrowser() exception: unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed
>   (Session info: chrome=54.0.2840.71)
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR PuppetWeb init() exception: WebDriverError: unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed
>   (Session info: chrome=54.0.2840.71)
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
>     at WebDriverError (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/error.js:27:5)
>     at Object.checkLegacyResponse (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/error.js:505:15)
>     at parseHttpResponse (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/http.js:398:13)
>     at doSend.then.response (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/http.js:330:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
> From: Task: WebDriver.navigate().to(https://wx.qq.com)
>     at Driver.schedule (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
>     at Navigation.to (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/webdriver.js:1042:25)
>     at Driver.get (/home/ubuntu/workspace/node_modules/selenium-webdriver/lib/webdriver.js:832:28)
>     at BrowserDriver.get (/home/ubuntu/workspace/src/puppet-web/browser-driver.ts:279:52)
>     at Browser.<anonymous> (/home/ubuntu/workspace/src/puppet-web/browser.ts:100:25)
>     at next (native)
>     at /home/ubuntu/workspace/src/puppet-web/browser.ts:7:65
>     at __awaiter (/home/ubuntu/workspace/src/puppet-web/browser.ts:3:12)
>     at Browser.open (/home/ubuntu/workspace/src/puppet-web/browser.ts:74:16)
>     at Browser.<anonymous> (/home/ubuntu/workspace/src/puppet-web/browser.ts:71:18)
> WARN PuppetWeb quit() without a bridge
> WARN PuppetWebBrowser quit() exception: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
> WARN PuppetWebBrowser driver.quit() exception: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
> ERR Wechaty init() exception: unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed
>   (Session info: chrome=54.0.2840.71)
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> ERR Bot init() fail: WebDriverError: unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed
>   (Session info: chrome=54.0.2840.71)
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.2.0-c9 x86_64)
> WARN PuppetWeb quit() without a bridge
> 
> npm ERR! Linux 4.2.0-c9
> npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/npm" "run" "ts-node" "example/ding-dong-bot.ts"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! wechaty@0.5.0 ts-node: `ts-node "example/ding-dong-bot.ts"`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the wechaty@0.5.0 ts-node script 'ts-node "example/ding-dong-bot.ts"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the wechaty package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node "example/ding-dong-bot.ts"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs wechaty
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls wechaty
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by zixia** [comment]
This is mostly like caused by `shm` size not enough, it's an `out of memory` error. you can see here:
https://github.com/elgalu/docker-selenium/issues/20#issuecomment-132967581

It's not recommended to run wechaty inside cloud9 anymore because the following 2 reasons:
1. the TOS of cloud9 ide is not permitted any bot to run on IDE9. wechaty is a bot, so wechaty is not permitted run on IDE9.
1. the SHM size of cloud9 has only 64MB:  
        ```shell
        zixia:~/workspace (master) $ df -h
        Filesystem                Size  Used Avail Use% Mounted on
        shm                        64M  512K   64M   1% /dev/shm
        ```

Use wechaty docker(see #66) when possible instead, it will run better than any other choice.

**Comment by maxostreet** [comment]
用 aws lambda好了，免费的。

**Comment by zixia** [comment]
@maxostreet interesting! how to do that, could you please post a brief introduction or some useful links? thanks!
