### ISSUE TITLE
wechaty with electron

### ISSUE THREAD

**Issue by ghost** [wechaty/wechaty#673]
这几天抽时间看了下electron，因为electron 有自带的chrome内核，并封装了executeJavaScript方法。所以有个想法：使用webview 连接微信网页端，并inject wechaty-bro.js ，使用electron  ipcMain 和ipcRenderer 通信机制代替express 和socket（测试可行），这样的话，就不需要每次弹出一个浏览器页面。也无需担心chromedriver 找不到的问题了。

**Comment by zixia** [comment]
Yes, that's the idea!

But I have no time to implement it. If you are interested in it, I'd like to encourage you to do that, and then I believe we could have a new Puppet: **PuppetElectron**

**Comment by iRabbit** [comment]
@zixia   I will try  to  do that!

**Comment by zixia** [comment]
Hello, is there any progress about the electron puppet? :)

**Comment by iRabbit** [comment]
@zixia  前段时间事情比较多。PuppetElectron 已经开始，国庆假期期间差不多可以提上来。

**Comment by zixia** [comment]
Hi, @iRabbit!

Thanks for the update, and great to hear about your new progress, it will be a very exciting new puppet for us.

Looking forward to your branding new PupetElectron!

**Comment by iRabbit** [comment]
@zixia  最近项目更新比较频繁，puppet-electron 的开发一直再进行，但是总觉得有些问题难以处理。master分支使用puppeteer 之后，这边也跟着改了许多地方，但是仍然存在不少问题。最大的一个问题是 electron 无法使用ts-node  启动，需要先把ts 编译成js才能进行调试。有没有好一点的方法？ ts 用的比较少，也造成了很多麻烦。 我还考虑到一个问题，就是，electron 本身npm包也不小，且需要下载。集成之后，是否真的需要把electron 和puppeteer 都安装上呢？显然这是不合适的。能否考虑一种方式，让这个驱动可选。 或者将 puppet 做成一个插件的接口？？在创建wechaty的时候，传入参数。

puppetElectron 开发的过程中，参考了很多您的代码。虽然目前还没有成果，但是学到了很多东西。我希望尽快能提交一份测试通过的代码。

**Comment by zixia** [comment]
Hi @iRabbit !

It's fantastic that hear from you again, and I'm glad hearing that you are working on the PuppetElectron!

I fully agree with you that we should design a pluggable architecture for both PuppetElectron and PuppetPuppeteer. Currently we are only using the Puppeteer, but in theory, you could have a look inside `PuppetWebBridge`, and replace the puppeteer inside the `PuppetWebBridge` to the electron, which I believe is the most effective way to get your work done.

After you get your code worked, we can discuss more about how to make it switchable/configurable to use both of them at the same time.

**Comment by zhanghuabin** [comment]
Hi, @iRabbit 

Any update?

**Comment by GuoYingxu** [comment]
@zhanghuabin  https://github.com/GuoYingxu/wechaty/tree/wechaty-electron  
尚有很多问题，可以参考下

**Comment by zhanghuabin** [comment]
@zixia @GuoYingxu 
各位，我听传闻微信网页版可能会被腾讯弃用，那现在这条下钩子的路就废了吧？
但是只要pc/mac版不废，至少还有机会。

**Comment by GuoYingxu** [comment]
@zhanghuabin 我也看到这个消息了，至于什么时候执行，会不会执行，现在还不知道。办法总比困难多。hack pc客户端难度是比较大的。我猜大概是因为有了web版，所以才选了一种简单的方式。如果web没了，一定会出现新的解决方法。我关注wechaty，更多的是关注技术本身，和解决问题的思路。
如果web版要封了，一定还会涌现出更多的解决方案，对技术本身而言，也不是一件坏事～～

**Comment by zixia** [comment]
I have to say I can not agree @GuoYingxu anymore! ;-)

**Comment by WuQic** [comment]
http://news.163.com/17/1128/08/D4AJDF26000187VE.html

**Comment by Zhou-Bill** [comment]
@GuoYingxu  我想用electron 给wechaty 做界面，但发现你的好像并不适用

**Comment by zixia** [comment]
Is there anyone have any progress to update?

Thanks!

**Comment by LittleCCB** [comment]
我解决了electron打包后wechaty不能启动的问题
这是我的仓库 https://github.com/LittleCCB/wx-bot-client

原理是通过重写wechaty-wechat包中puppeteer的启动方式实现
