### ISSUE TITLE
Just have a try as example of tuling bot. But method message.self() seems work improper.  

### ISSUE THREAD

**Issue by kyle-yu** [wechaty/wechaty#68]
In src/message.ts I suppose  method message.self() denotes that it checks whether message is sent by self. But it seems compare between message-id and user-id.

code segment as below:
  public self(): boolean {
    const userId = Config.puppetInstance()
                        .userId

    const fromId = this.obj.id

I do like your contribution and just wonder whether the method is as my expectation or not.

**Comment by zixia** [comment]
hi @kyle-yu , 

thanks for your review, and you are right, `fromId` should get from `this.obj.from`.

it's a mistake made by me, just fixed in the master.

please feel free to let me know if there's other mistakes made by me, appreciated it.
