### ISSUE TITLE
contactFind(function (c) { return /.*/.test(c) }) rejected: javascript error: Unexpected token

### ISSUE THREAD

**Issue by JasLin** [wechaty/wechaty#98]
the following exception raise today suddenly

### Actual behavior

```javascript
WARN PuppetWeb contactFind(function (c) { return /.*/.test(c) }) rejected: javascript error: Unexpected token (
JavaScript stack:
SyntaxError: Unexpected token (
    at contactFindAsync (<anonymous>:783:20)
    at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
    at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
    at executeAsyncScript (<anonymous>:329:26)
    at <anonymous>:345:29
    at callFunction (<anonymous>:237:33)
    at <anonymous>:247:23
    at <anonymous>:248:3
  (Session info: chrome=54.0.2840.90)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-45-generic x86_64)
ERR Contact findAll() rejected: javascript error: Unexpected token (
JavaScript stack:
SyntaxError: Unexpected token (
    at contactFindAsync (<anonymous>:783:20)
    at eval (eval at executeAsyncScript (:329:5), <anonymous>:6:16)
    at eval (eval at executeAsyncScript (:329:5), <anonymous>:11:8)
    at executeAsyncScript (<anonymous>:329:26)
    at <anonymous>:345:29
    at callFunction (<anonymous>:237:33)
    at <anonymous>:247:23
    at <anonymous>:248:3
  (Session info: chrome=54.0.2840.90)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-45-generic x86_64)
```

### Steps to reproduce the behavior (and fixes, if any)

it seems function string for eval not work correctly

exceute those functionfilter in chrome:
```javascript
eval ('function (c) { return /.*/.test(c) }')
eval("function (c) { return c === 'jas' }")
```
will raise this error

```javascript
VM456:1 Uncaught SyntaxError: Unexpected token (
    at <anonymous>:1:1
```

**Comment by zixia** [comment]
my bad. this bug is added by me for #60 at https://github.com/wechaty/wechaty/commit/ca733287dfccfcbb38c47bfca3f1513a082d3698

**Comment by zixia** [comment]
should fixed. please confirm.

**Comment by JasLin** [comment]
anonymous function exception had been fix. but add an syntax error:)

**Comment by zixia** [comment]
good catch!

my English is always too poor...

once upon a time, I typo 'guy' to a 'gay' in a qmail mail list...

**Comment by JasLin** [comment]
haha , hi gays...:)

**Comment by JasLin** [comment]
@zixia can u pls push a docker image for me?

**Comment by zixia** [comment]
Sure, no problem.

BTW: Wechaty will build the zixia/wechaty:latest automaticly if the latest commit pass all the CI tests.

For example, after I merged your PR, the CI will start testing. If the test passed, you will see a green `✔` , that means Docker Image `zixia/wechaty:latest` will be updated.

Now we are testing at here: https://circleci.com/gh/wechaty/wechaty/797

**Comment by JasLin** [comment]
great, thanks. i will use the latest  image:)

**Comment by zixia** [comment]
I suggest you use the latest image only if you are very sure that version is ok for you. 

And can you see this page: https://hub.docker.com/r/zixia/wechaty/builds/ ? Please make sure the commit you want is:

1. passed the CI
2. triggered the Docker Hub, and build successfully.

I can see it's building now:

| Status | Actions | Tag | Created | Last Updated |
| ------- |  ------- | ---- | -------- | --------------- |
| Building | Cancel | latest | 2 minutes ago | 2 minutes ago |
| Building | Cancel | 0.6.22 | 2 minutes ago | 2 minutes ago |

**Comment by JasLin** [comment]
thks, i'll check this next time:)
