### ISSUE TITLE
chromedriver error

### ISSUE THREAD

**Issue by z8313568** [wechaty/wechaty#99]
ubuntu 安装 chromedriver了。
运行node mybot.js出现下面错误

npm install --save wechaty

ubuntu@VM-20-53-ubuntu:~$ uname -a
Linux VM-20-53-ubuntu 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@VM-20-53-ubuntu:~$ node -v
v6.9.0

ubuntu@VM-20-53-ubuntu:~$ npm -v
3.10.8

ubuntu@VM-20-53-ubuntu:~$ chromedriver -v
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)

ubuntu@VM-20-53-ubuntu:~$ node mybot.js
INFO Wechaty v0.6.20 initializing...
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/home/ubuntu/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:125:35)
    at next (native)
    at fulfilled (/home/ubuntu/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
ERR PuppetWebBrowser quit() this.driver.quit() exception unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-86-generic x86_64)
ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/home/ubuntu/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:125:35)
    at next (native)
    at fulfilled (/home/ubuntu/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERR Wechaty init() exception: initChromeDriver() got invalid driver
(node:32114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: initChromeDriver() got invalid driver

**Comment by zixia** [comment]
Your should upgrade your chromedriver to 2.24 or above first. 

Please reopen this issue, or submit a new issue if you still have the problem after upgrading.

Duplicated with #77

**Comment by kinginsun** [comment]
Mac上使用 2.9最新版的chromedriver出现下面错误：

INFO Wechaty v0.6.63 initializing...
WARN BrowserDriver valid() fail: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63545.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64)
WARN BrowserDriver valid() fail: two = WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63545.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64) ?
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
WARN BrowserDriver valid() fail: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63557.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64)
WARN BrowserDriver valid() fail: two = WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63557.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64) ?
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
WARN BrowserDriver valid() fail: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63569.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64)
WARN BrowserDriver valid() fail: two = WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63569.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64) ?
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
WARN BrowserDriver valid() fail: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63581.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64)
WARN BrowserDriver valid() fail: two = WebDriverError: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"63581.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64) ?
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/Users/randyz/Documents/wechat_robot/wechaty2/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:119:35)
    at next (native)
    at fulfilled (/Users/randyz/Documents/wechat_robot/wechaty2/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
WARN PuppetWebBrowser quit() exception: browser number: 2
WARN PuppetWebBrowser driver.quit() exception: browser number: 2
ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/Users/randyz/Documents/wechat_robot/wechaty2/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:119:35)
    at next (native)
    at fulfilled (/Users/randyz/Documents/wechat_robot/wechaty2/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERR Wechaty init() exception: initChromeDriver() got invalid driver
(node:63536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: initChromeDriver() got invalid driver

**Comment by zixia** [comment]
@kinginsun Please submit a new issue and provide more details by following the template.

Also, I suggest u use docker if possible.

Thanks.

**Comment by zixia** [comment]
BTW: the last version of chromedriver is not 2.9.

Should be 2.26 according https://sites.google.com/a/chromium.org/chromedriver/

**Comment by git4sun** [comment]
I downloaded the chrome driver. It is an executable file. Where should I put it?

**Comment by zixia** [comment]
Put it into one of the directories in your $PATH, and make sure there's no other version of chromedriver in your $PATH.

**Comment by lijiarui** [comment]
add in [FAQ](https://github.com/wechaty/wechaty/wiki/FAQ#3-where-should-i-put-chrome-driver-if-i-downloaded-manually)
